// lib/dailyData.ts

export const RECYCLING_CATEGORIES = [
  {
    emoji: "🗑️",
    nameEn: "General Trash",
    nameKo: "일반쓰레기",
    bagColor: "White designated bag",
    bagColorKo: "흰색 종량제 봉투",
    descEn: "Food-contaminated waste, diapers, cigarette butts, broken items that don't fit other categories. Must use official designated bags (종량제 봉투) bought from any convenience store.",
    descKo: "음식물 묻은 쓰레기, 기저귀, 담배꽁초 등. 반드시 편의점에서 구입한 종량제 봉투 사용.",
    tipsEn: ["Buy 종량제 봉투 at any GS25, CU, 7-Eleven, E-Mart 24", "Available in 5L, 10L, 20L, 50L sizes", "Can be expensive — reducing general waste saves money"],
    tipsKo: ["GS25, CU, 세븐일레븐, 이마트24 등 편의점에서 구입", "5L, 10L, 20L, 50L 등 다양한 크기", "비쌀 수 있음 — 일반쓰레기 줄이면 절약"],
    how: "Tie securely and leave in the designated trash collection spot for your building.",
    howKo: "잘 묶어 건물의 지정된 쓰레기 배출 장소에 두세요.",
  },
  {
    emoji: "🍌",
    nameEn: "Food Waste",
    nameKo: "음식물쓰레기",
    bagColor: "Yellow/translucent food waste bag",
    bagColorKo: "노란색/투명 음식물쓰레기 봉투",
    descEn: "All food scraps: vegetable peels, leftovers, coffee grounds. Separate from general trash. In apartment buildings, use the designated food waste bin.",
    descKo: "모든 음식물: 채소 껍질, 음식 찌꺼기, 커피 찌꺼기. 일반쓰레기와 분리. 아파트는 지정된 음식물 쓰레기통 이용.",
    tipsEn: ["Do NOT include hard shells (shellfish, walnut, peach pit)", "Do NOT include bones, tea bags, or toothpicks", "It's turned into animal feed or compost — drain moisture first"],
    tipsKo: ["조개껍데기, 호두 껍데기, 복숭아씨 등 딱딱한 껍질은 불가", "뼈, 티백, 이쑤시개 불가", "사료나 퇴비로 재활용 — 수분 제거 후 배출"],
    how: "Use food waste bags (음식물쓰레기 봉투) or community bins. In some buildings, you swipe a card to open the food waste bin.",
    howKo: "음식물쓰레기 봉투 또는 공동 음식물 쓰레기통 이용. 일부 건물에서는 카드 태그 방식 사용.",
  },
  {
    emoji: "📦",
    nameEn: "Recyclables",
    nameKo: "재활용",
    bagColor: "Any clear bag (transparent)",
    bagColorKo: "투명한 봉투",
    descEn: "Paper, cardboard, plastic, glass, cans, metal. Sort into separate bags or bins at your building's recycling area.",
    descKo: "종이, 박스, 플라스틱, 유리, 캔, 금속. 건물 재활용 공간에서 항목별로 분리 배출.",
    tipsEn: ["Remove food residue before recycling", "Flatten cardboard boxes", "Remove caps from bottles", "Separate paper from other recyclables"],
    tipsKo: ["재활용 전 음식물 제거", "박스는 납작하게 접기", "병뚜껑 제거", "종이류와 다른 재활용품 분리"],
    how: "Place in the color-coded bins at your building's recycling station. Most buildings have this in the underground parking or side of building.",
    howKo: "건물 재활용 공간의 색깔별 분리수거함에 배출. 대부분 지하주차장 또는 건물 옆에 있음.",
  },
  {
    emoji: "🪴",
    nameEn: "Large Items / Bulky Waste",
    nameKo: "대형폐기물",
    bagColor: "Special sticker required",
    bagColorKo: "대형폐기물 스티커 필요",
    descEn: "Furniture, appliances, mattresses, large electronics. Cannot be left with regular trash — must purchase a disposal sticker.",
    descKo: "가구, 가전, 매트리스, 대형 전자제품 등. 일반쓰레기와 함께 버릴 수 없음 — 스티커 구입 필요.",
    tipsEn: ["Buy a disposal sticker (대형폐기물 스티커) from your local district office (구청) or dong community center (동 주민센터)", "Cost varies by item size: ₩3,000–₩30,000", "Attach sticker visibly and place outside on designated collection day"],
    tipsKo: ["구청 또는 동 주민센터에서 대형폐기물 스티커 구입", "물품 크기에 따라 3,000~30,000원", "스티커 잘 보이게 붙이고 지정 수거일에 배출"],
    how: "Reserve collection online at your district's website (gu.go.kr) or visit in person.",
    howKo: "각 구청 홈페이지에서 온라인 예약 또는 방문 신청.",
  },
];

export const PHONE_PLANS = [
  {
    carrier: "SKT",
    carrierKo: "SK텔레콤",
    plan: "Foreigner Pre-Paid SIM",
    planKo: "외국인 선불 유심",
    priceKRW: 33000,
    data: "1.5GB + unlimited LTE (throttled after)",
    dataKo: "1.5GB + 속도 제한 LTE 무제한",
    calls: "300 min",
    callsKo: "300분",
    contractRequired: false,
    arcRequired: false,
    descEn: "Available at airports, SKT stores, convenience stores. Good for short-term visitors and new arrivals without ARC.",
    descKo: "공항, SKT 매장, 편의점에서 구입 가능. ARC 없는 단기 방문자에 적합.",
  },
  {
    carrier: "KT",
    carrierKo: "KT",
    plan: "LTE Data SIM (Foreigner)",
    planKo: "외국인 LTE 데이터 유심",
    priceKRW: 30000,
    data: "2GB/month unlimited (throttled after 2GB)",
    dataKo: "월 2GB 무제한 (2GB 초과 시 속도 제한)",
    calls: "Unlimited (domestic)",
    callsKo: "국내 무제한",
    contractRequired: false,
    arcRequired: true,
    descEn: "Requires ARC. Good monthly value. KT has solid nationwide coverage.",
    descKo: "ARC 필요. 월정액 성능 좋음. KT 전국 커버리지 우수.",
  },
  {
    carrier: "LG U+",
    carrierKo: "LG 유플러스",
    plan: "Monthly Foreigner Plan",
    planKo: "외국인 월정액 요금제",
    priceKRW: 38000,
    data: "5GB + unlimited (throttled)",
    dataKo: "5GB + 속도 제한 무제한",
    calls: "Unlimited domestic",
    callsKo: "국내 무제한",
    contractRequired: false,
    arcRequired: true,
    descEn: "More data than competitors. Requires ARC. Good choice if you stream a lot.",
    descKo: "타사 대비 데이터 많음. ARC 필요. 스트리밍 많이 하는 경우 추천.",
  },
  {
    carrier: "MVNO (알뜰폰)",
    carrierKo: "알뜰폰",
    plan: "Budget MVNO Plans",
    planKo: "알뜰폰 요금제",
    priceKRW: 10000,
    data: "1-3GB (varies by plan)",
    dataKo: "1-3GB (요금제별 상이)",
    calls: "50-100 min or unlimited (plan-dependent)",
    callsKo: "50-100분 또는 무제한 (요금제 따라)",
    contractRequired: false,
    arcRequired: true,
    descEn: "MVNO carriers (Hellovision, U+알뜰폰, etc.) piggyback on major networks at 1/3 the price. Great for budget-conscious residents.",
    descKo: "알뜰폰 사업자(헬로비전 등)는 대형 통신사 망 이용, 요금은 1/3 수준. 절약 원하는 거주자에게 좋음.",
  },
];

export const ESSENTIAL_APPS = [
  {
    category: "Navigation",
    categoryKo: "지도/내비",
    apps: [
      { name: "Naver Maps (네이버 지도)", descEn: "The best navigation in Korea. Google Maps is unreliable here — Naver Maps knows every alley, every restaurant, real-time transit.", descKo: "한국 최고의 지도 앱. 구글맵은 여기서 부정확. 골목길, 실시간 대중교통 완벽 지원.", platform: "iOS + Android" },
      { name: "Kakao Metro (카카오 지하철)", descEn: "Subway route planner with real-time train tracking. Shows transfer routes and estimated arrival.", descKo: "실시간 지하철 위치와 환승 경로 안내. 도착 예정 시간 표시.", platform: "iOS + Android" },
      { name: "T Map", descEn: "Best driving navigation app in Korea. Integrates with car GPS systems. Good for road trips.", descKo: "한국 최고의 자동차 내비. 차량 GPS와 연동 가능. 장거리 이동에 좋음.", platform: "iOS + Android" },
    ],
  },
  {
    category: "Food & Delivery",
    categoryKo: "음식/배달",
    apps: [
      { name: "Baemin (배달의민족)", descEn: "The #1 food delivery app. Every Korean restaurant delivers. Requires Korean phone number. Some UI now in English.", descKo: "배달 앱 1위. 거의 모든 음식점이 배달 됨. 한국 전화번호 필요.", platform: "iOS + Android" },
      { name: "Coupang Eats (쿠팡이츠)", descEn: "Faster than Baemin (often 30 min). Smaller restaurant selection but excellent for quick orders.", descKo: "배민보다 빠름 (보통 30분). 음식점 수는 적으나 빠른 배달에 최적.", platform: "iOS + Android" },
      { name: "Coupang (쿠팡)", descEn: "Amazon equivalent in Korea. Next-day or same-day delivery for almost everything. Rocket delivery is extraordinary.", descKo: "한국의 아마존. 거의 모든 물건 당일/익일 배달. 로켓배송 체험 필수.", platform: "iOS + Android" },
    ],
  },
  {
    category: "Communication",
    categoryKo: "소통",
    apps: [
      { name: "KakaoTalk (카카오톡)", descEn: "THE messaging app in Korea. Everyone uses it. You need this. Download it before you even land.", descKo: "한국의 국민 메신저. 모두가 사용. 입국 전에 미리 설치할 것.", platform: "iOS + Android" },
      { name: "Papago", descEn: "Naver's translation app. Superior to Google Translate for Korean. Camera translation is excellent for reading menus, signs, contracts.", descKo: "네이버 번역 앱. 한국어는 구글 번역보다 우수. 카메라 번역으로 메뉴, 간판, 계약서 번역 가능.", platform: "iOS + Android" },
      { name: "Naver Dictionary (네이버 사전)", descEn: "Deep Korean-English dictionary with example sentences, conjugations, and pronunciation.", descKo: "예문, 활용형, 발음까지 제공하는 심층 한-영 사전.", platform: "iOS + Android" },
    ],
  },
  {
    category: "Banking & Finance",
    categoryKo: "금융",
    apps: [
      { name: "Toss (토스)", descEn: "Korea's fintech super-app. Easy money transfers, credit score checking, spending analysis. Works with most Korean bank accounts.", descKo: "한국 핀테크 슈퍼앱. 간편 송금, 신용점수 확인, 지출 분석. 대부분의 한국 은행 계좌 연동 가능.", platform: "iOS + Android" },
      { name: "Your bank's app", descEn: "Hana, Shinhan, KB each have apps. Hana and Shinhan have decent English support.", descKo: "하나, 신한, KB 앱 각각 제공. 하나, 신한 영어 지원 양호.", platform: "iOS + Android" },
    ],
  },
  {
    category: "Health",
    categoryKo: "건강",
    apps: [
      { name: "Goodoc (굿닥)", descEn: "Find English-speaking doctors and clinics. Book appointments directly from the app. Filter by specialty and language.", descKo: "영어 가능 병원 찾기. 앱에서 바로 예약. 전문과목, 언어별 필터 가능.", platform: "iOS + Android" },
      { name: "NaverMap → pharmacy", descEn: "Search '약국' on Naver Maps to find open pharmacies near you with real-time hours.", descKo: "네이버 지도에서 '약국' 검색으로 근처 약국 실시간 영업 시간 확인.", platform: "iOS + Android" },
    ],
  },
  {
    category: "Shopping & Lifestyle",
    categoryKo: "쇼핑/생활",
    apps: [
      { name: "당근 (Daangn)", descEn: "Korea's Craigslist/Facebook Marketplace. Buy/sell second-hand items locally. Great for finding furniture when you first arrive.", descKo: "한국의 중고거래 플랫폼. 동네에서 중고 물건 사고팔기. 처음 입국 시 가구 구하기 좋음.", platform: "iOS + Android" },
      { name: "Naver Shopping", descEn: "Price comparison across all Korean online shops. Best way to find the cheapest price for any product.", descKo: "국내 모든 온라인 쇼핑몰 가격 비교. 최저가 찾기 최적.", platform: "Web + App" },
    ],
  },
];

export const DELIVERY_GUIDE = [
  { service: "Coupang Rocket (로켓배송)", emoji: "🚀", descEn: "Order before midnight, get it next morning. Often same-day for orders before 2pm. Extraordinary service. Sign up for Coupang Rocket Wow membership (₩4,990/month) for free shipping.", descKo: "자정 전 주문 시 다음날 아침 배달. 오후 2시 전 주문 시 당일 배달도 가능. 로켓와우 멤버십(월 4,990원)으로 무료배송." },
  { service: "Baemin (배달의민족)", emoji: "🍕", descEn: "30-60 min food delivery. Download the app, set your address, and browse. Most restaurants have photos. Minimum orders apply (usually ₩15,000-20,000).", descKo: "30-60분 음식 배달. 앱 설치, 주소 설정 후 주문. 대부분 사진 있음. 최소 주문 금액 있음 (보통 15,000-20,000원)." },
  { service: "Address issues", emoji: "📍", descEn: "Your delivery address in Korea should be in Korean format. When setting up apps, use your building's Korean address (찾기 with Naver Maps or ask your landlord). English addresses rarely work.", descKo: "배달 주소는 한국어 형식으로 입력. 건물의 한국어 주소 사용 (네이버 지도 또는 집주인에게 확인). 영어 주소는 잘 안 됨." },
  { service: "Delivery to the door", emoji: "🏠", descEn: "Most delivery people will call/text when they arrive (in Korean). Having a basic phrase ready helps: '문 앞에 놔주세요' (leave at the door) is useful.", descKo: "대부분 배달 기사가 도착 시 전화/문자 (한국어). 기본 문구 준비 도움: '문 앞에 놔주세요' (문 앞에 두고 가기)." },
];

export const DRIVERS_LICENSE = {
  conversionEn: "If your home country has a reciprocal agreement with Korea, you can convert your existing license without a test. Countries include: USA, Canada, UK, Australia, Germany, France, and 100+ others.",
  conversionKo: "본국과 한국 간 상호 인정 협정이 있는 경우 시험 없이 면허 변환 가능. 미국, 캐나다, 영국, 호주, 독일, 프랑스 등 100개국 이상.",
  conversionSteps: [
    { stepEn: "Visit a Driver's License Examination Office (운전면허시험장)", stepKo: "운전면허시험장 방문" },
    { stepEn: "Bring: ARC, passport, your home country license + Korean translation (from a notary or Naver), 1 passport photo, ₩10,000 fee", stepKo: "ARC, 여권, 본국 면허증 + 한국어 번역본 (공증 또는 네이버), 여권 사진 1매, 수수료 10,000원 지참" },
    { stepEn: "Take an eye test on-site (quick, about 5 minutes)", stepKo: "현장 시력 검사 (빠름, 약 5분)" },
    { stepEn: "If your country requires it: take a short road safety quiz (25 questions, easy, in English)", stepKo: "일부 국가의 경우: 교통안전 퀴즈 (25문제, 쉬움, 영어 가능)" },
    { stepEn: "Receive your Korean license same day (or next day)", stepKo: "당일 (또는 다음날) 한국 면허 수령" },
  ],
  newTestEn: "If your country doesn't have an agreement, you'll need to take the full Korean driving test (written + practical). Visit Kakao Navi's website or the Road Traffic Authority (도로교통공단) site for study materials in English.",
  newTestKo: "협정 미체결 국가 국민은 한국 면허 시험(필기+실기) 응시 필요. 카카오내비 웹사이트 또는 도로교통공단 사이트에서 영어 공부자료 확인 가능.",
};
