// lib/dailyData.ts

export const RECYCLING_CATEGORIES = [
  {
    emoji: "🗑️",
    nameEn: "General Trash",
    nameKo: "일반쓰레기",
    nameJa: "一般ゴミ",
    nameZhCN: "一般垃圾",
    nameZhTW: "一般垃圾",
    namePt: "Lixo Comum",
    nameEs: "Basura General",
    bagColor: "White designated bag",
    bagColorKo: "흰색 종량제 봉투",
    bagColorJa: "白色指定袋（종량제 봉투）",
    bagColorZhCN: "白色指定袋（종량제 봉투）",
    bagColorZhTW: "白色指定袋（종량제 봉투）",
    bagColorPt: "Saco branco designado (종량제 봉투)",
    bagColorEs: "Bolsa blanca designada (종량제 봉투)",
    descEn: "Food-contaminated waste, diapers, cigarette butts, broken items that don't fit other categories. Must use official designated bags (종량제 봉투) bought from any convenience store.",
    descKo: "음식물 묻은 쓰레기, 기저귀, 담배꽁초 등. 반드시 편의점에서 구입한 종량제 봉투 사용.",
    descJa: "食べ物が付着したゴミ、おむつ、タバコの吸い殻など、他のカテゴリに当てはまらないもの。コンビニで購入できる公式指定袋（종량제 봉투）の使用が必須。",
    descZhCN: "沾有食物的废弃物、尿布、烟蒂等不属于其他类别的垃圾。必须使用在便利店购买的官方指定袋（종량제 봉투）。",
    descZhTW: "沾有食物的廢棄物、尿布、菸蒂等不屬於其他類別的垃圾。必須使用在便利商店購買的官方指定袋（종량제 봉투）。",
    descPt: "Resíduos contaminados com comida, fraldas, bitucas de cigarro e itens que não se encaixam em outras categorias. Deve-se usar os sacos designados oficiais (종량제 봉투), vendidos em qualquer conveniência.",
    descEs: "Residuos contaminados con comida, pañales, colillas de cigarrillos y artículos que no encajan en otras categorías. Se deben usar las bolsas designadas oficiales (종량제 봉투), vendidas en cualquier tienda de conveniencia.",
    tipsEn: ["Buy 종량제 봉투 at any GS25, CU, 7-Eleven, E-Mart 24", "Available in 5L, 10L, 20L, 50L sizes", "Can be expensive — reducing general waste saves money"],
    tipsKo: ["GS25, CU, 세븐일레븐, 이마트24 등 편의점에서 구입", "5L, 10L, 20L, 50L 등 다양한 크기", "비쌀 수 있음 — 일반쓰레기 줄이면 절약"],
    tipsJa: ["GS25、CU、7-Eleven、E-Mart 24など任意のコンビニで購入", "5L、10L、20L、50Lサイズあり", "高価なので一般ゴミを減らすと節約になる"],
    tipsZhCN: ["在任意GS25、CU、7-Eleven、E-Mart 24便利店购买", "有5L、10L、20L、50L多种规格", "价格较贵——减少一般垃圾可省钱"],
    tipsZhTW: ["在任何GS25、CU、7-Eleven、E-Mart 24便利商店購買", "有5L、10L、20L、50L多種規格", "價格較貴——減少一般垃圾可省錢"],
    tipsPt: ["Compre o 종량제 봉투 em qualquer GS25, CU, 7-Eleven, E-Mart 24", "Disponível nos tamanhos 5L, 10L, 20L, 50L", "Pode ser caro — reduzir o lixo comum economiza dinheiro"],
    tipsEs: ["Compra la 종량제 봉투 en cualquier GS25, CU, 7-Eleven, E-Mart 24", "Disponible en tamaños 5L, 10L, 20L, 50L", "Puede ser costosa — reducir la basura general ahorra dinero"],
    how: "Tie securely and leave in the designated trash collection spot for your building.",
    howKo: "잘 묶어 건물의 지정된 쓰레기 배출 장소에 두세요.",
    howJa: "しっかり結んで、建物の指定されたゴミ収集場所に置いてください。",
    howZhCN: "扎紧袋口，放在楼栋的指定垃圾投放点。",
    howZhTW: "紮緊袋口，放在大樓的指定垃圾投放點。",
    howPt: "Amarre bem e deixe no local de coleta de lixo designado do seu prédio.",
    howEs: "Átalo bien y déjalo en el punto de recolección de basura designado de tu edificio.",
  },
  {
    emoji: "🍌",
    nameEn: "Food Waste",
    nameKo: "음식물쓰레기",
    nameJa: "生ゴミ",
    nameZhCN: "厨余垃圾",
    nameZhTW: "廚餘垃圾",
    namePt: "Resíduos Orgânicos",
    nameEs: "Residuos Orgánicos",
    bagColor: "Yellow/translucent food waste bag",
    bagColorKo: "노란색/투명 음식물쓰레기 봉투",
    bagColorJa: "黄色/半透明の生ゴミ袋（음식물쓰레기 봉투）",
    bagColorZhCN: "黄色/透明厨余垃圾袋（음식물쓰레기 봉투）",
    bagColorZhTW: "黃色/透明廚餘垃圾袋（음식물쓰레기 봉투）",
    bagColorPt: "Saco amarelo/translúcido para resíduos orgânicos (음식물쓰레기 봉투)",
    bagColorEs: "Bolsa amarilla/translúcida para residuos orgánicos (음식물쓰레기 봉투)",
    descEn: "All food scraps: vegetable peels, leftovers, coffee grounds. Separate from general trash. In apartment buildings, use the designated food waste bin.",
    descKo: "모든 음식물: 채소 껍질, 음식 찌꺼기, 커피 찌꺼기. 일반쓰레기와 분리. 아파트는 지정된 음식물 쓰레기통 이용.",
    descJa: "すべての食べ残し：野菜の皮、残飯、コーヒーかす。一般ゴミとは分別。マンションでは専用の生ゴミ箱を使用。",
    descZhCN: "所有厨余：蔬菜皮、剩饭剩菜、咖啡渣。须与一般垃圾分开。公寓楼请使用专用厨余垃圾桶。",
    descZhTW: "所有廚餘：蔬菜皮、剩飯剩菜、咖啡渣。須與一般垃圾分開。公寓請使用專用廚餘垃圾桶。",
    descPt: "Todos os restos de comida: cascas de vegetais, sobras, borra de café. Separe do lixo comum. Em prédios de apartamentos, use o recipiente de lixo orgânico designado.",
    descEs: "Todos los restos de comida: cáscaras de vegetales, sobras, posos de café. Separa de la basura general. En edificios de apartamentos, usa el contenedor de residuos orgánicos designado.",
    tipsEn: ["Do NOT include hard shells (shellfish, walnut, peach pit)", "Do NOT include bones, tea bags, or toothpicks", "It's turned into animal feed or compost — drain moisture first"],
    tipsKo: ["조개껍데기, 호두 껍데기, 복숭아씨 등 딱딱한 껍질은 불가", "뼈, 티백, 이쑤시개 불가", "사료나 퇴비로 재활용 — 수분 제거 후 배출"],
    tipsJa: ["硬い殻（貝殻、くるみ、桃の種）は入れない", "骨、ティーバッグ、爪楊枝は不可", "飼料や堆肥になる — 水分を切ってから出すこと"],
    tipsZhCN: ["不可放入硬壳（贝壳、核桃壳、桃核）", "不可放入骨头、茶包或牙签", "会被制成饲料或堆肥——请先沥干水分"],
    tipsZhTW: ["不可放入硬殼（貝殼、核桃殼、桃核）", "不可放入骨頭、茶包或牙籤", "會被製成飼料或堆肥——請先瀝乾水分"],
    tipsPt: ["NÃO inclua cascas duras (mariscos, nozes, caroço de pêssego)", "NÃO inclua ossos, saquinhos de chá ou palitos", "É transformado em ração animal ou composto — escorra o excesso de umidade primeiro"],
    tipsEs: ["NO incluyas cáscaras duras (mariscos, nueces, hueso de durazno)", "NO incluyas huesos, bolsitas de té ni palillos", "Se convierte en alimento animal o composta — escurre la humedad primero"],
    how: "Use food waste bags (음식물쓰레기 봉투) or community bins. In some buildings, you swipe a card to open the food waste bin.",
    howKo: "음식물쓰레기 봉투 또는 공동 음식물 쓰레기통 이용. 일부 건물에서는 카드 태그 방식 사용.",
    howJa: "生ゴミ袋（음식물쓰레기 봉투）または共用ゴミ箱を使用。建物によってはカードをタッチして開けるタイプもある。",
    howZhCN: "使用厨余垃圾袋（음식물쓰레기 봉투）或公共厨余垃圾桶。部分楼栋采用刷卡开盖方式。",
    howZhTW: "使用廚餘垃圾袋（음식물쓰레기 봉투）或公共廚餘垃圾桶。部分大樓採用刷卡開蓋方式。",
    howPt: "Use sacos de resíduos orgânicos (음식물쓰레기 봉투) ou os recipientes comunitários. Em alguns prédios, você passa um cartão para abrir o recipiente.",
    howEs: "Usa bolsas de residuos orgánicos (음식물쓰레기 봉투) o los contenedores comunitarios. En algunos edificios, se desliza una tarjeta para abrir el contenedor.",
  },
  {
    emoji: "📦",
    nameEn: "Recyclables",
    nameKo: "재활용",
    nameJa: "リサイクル",
    nameZhCN: "可回收物",
    nameZhTW: "可回收物",
    namePt: "Recicláveis",
    nameEs: "Reciclables",
    bagColor: "Any clear bag (transparent)",
    bagColorKo: "투명한 봉투",
    bagColorJa: "透明な袋（任意）",
    bagColorZhCN: "任意透明袋",
    bagColorZhTW: "任意透明袋",
    bagColorPt: "Qualquer saco transparente",
    bagColorEs: "Cualquier bolsa transparente",
    descEn: "Paper, cardboard, plastic, glass, cans, metal. Sort into separate bags or bins at your building's recycling area.",
    descKo: "종이, 박스, 플라스틱, 유리, 캔, 금속. 건물 재활용 공간에서 항목별로 분리 배출.",
    descJa: "紙、段ボール、プラスチック、ガラス、缶、金属。建物のリサイクルエリアで種類ごとに分別。",
    descZhCN: "纸张、纸板、塑料、玻璃、罐头、金属。在楼栋回收区按类别分别投放。",
    descZhTW: "紙張、紙板、塑料、玻璃、罐頭、金屬。在大樓回收區按類別分別投放。",
    descPt: "Papel, papelão, plástico, vidro, latas, metal. Separe em sacos ou lixeiras distintas na área de reciclagem do seu prédio.",
    descEs: "Papel, cartón, plástico, vidrio, latas, metal. Separa en bolsas o contenedores distintos en el área de reciclaje de tu edificio.",
    tipsEn: ["Remove food residue before recycling", "Flatten cardboard boxes", "Remove caps from bottles", "Separate paper from other recyclables"],
    tipsKo: ["재활용 전 음식물 제거", "박스는 납작하게 접기", "병뚜껑 제거", "종이류와 다른 재활용품 분리"],
    tipsJa: ["リサイクル前に食べ物の残りを取り除く", "段ボールは平らにたたむ", "ボトルのキャップを外す", "紙類は他のリサイクル品と分ける"],
    tipsZhCN: ["回收前去除食物残渣", "压平纸板箱", "去除瓶盖", "纸张与其他可回收物分开"],
    tipsZhTW: ["回收前去除食物殘渣", "壓平紙板箱", "去除瓶蓋", "紙張與其他可回收物分開"],
    tipsPt: ["Remova resíduos de comida antes de reciclar", "Dobre as caixas de papelão", "Remova tampas de garrafas", "Separe o papel dos outros recicláveis"],
    tipsEs: ["Elimina restos de comida antes de reciclar", "Aplana las cajas de cartón", "Quita las tapas de las botellas", "Separa el papel del resto de reciclables"],
    how: "Place in the color-coded bins at your building's recycling station. Most buildings have this in the underground parking or side of building.",
    howKo: "건물 재활용 공간의 색깔별 분리수거함에 배출. 대부분 지하주차장 또는 건물 옆에 있음.",
    howJa: "建物のリサイクルステーションのカラーコード別ゴミ箱に入れる。多くは地下駐車場または建物の脇にある。",
    howZhCN: "放入楼栋回收站的分类垃圾桶中。大多位于地下停车场或楼侧。",
    howZhTW: "放入大樓回收站的分類垃圾桶中。大多位於地下停車場或樓側。",
    howPt: "Coloque nas lixeiras codificadas por cor na estação de reciclagem do seu prédio. A maioria fica no estacionamento subterrâneo ou na lateral do prédio.",
    howEs: "Coloca en los contenedores codificados por color en la estación de reciclaje de tu edificio. La mayoría está en el estacionamiento subterráneo o en el lateral del edificio.",
  },
  {
    emoji: "🪴",
    nameEn: "Large Items / Bulky Waste",
    nameKo: "대형폐기물",
    nameJa: "粗大ゴミ",
    nameZhCN: "大件废弃物",
    nameZhTW: "大件廢棄物",
    namePt: "Itens Grandes / Entulho",
    nameEs: "Artículos Grandes / Voluminosos",
    bagColor: "Special sticker required",
    bagColorKo: "대형폐기물 스티커 필요",
    bagColorJa: "専用シール（대형폐기물 스티커）が必要",
    bagColorZhCN: "需贴大件废弃物贴纸（대형폐기물 스티커）",
    bagColorZhTW: "需貼大件廢棄物貼紙（대형폐기물 스티커）",
    bagColorPt: "Adesivo especial necessário (대형폐기물 스티커)",
    bagColorEs: "Pegatina especial requerida (대형폐기물 스티커)",
    descEn: "Furniture, appliances, mattresses, large electronics. Cannot be left with regular trash — must purchase a disposal sticker.",
    descKo: "가구, 가전, 매트리스, 대형 전자제품 등. 일반쓰레기와 함께 버릴 수 없음 — 스티커 구입 필요.",
    descJa: "家具、家電、マットレス、大型電子機器など。通常のゴミとして捨てることはできない — 専用シールの購入が必要。",
    descZhCN: "家具、家电、床垫、大型电子产品等。不可与普通垃圾一起丢弃——须购买处置贴纸。",
    descZhTW: "家具、家電、床墊、大型電子產品等。不可與普通垃圾一起丟棄——須購買處置貼紙。",
    descPt: "Móveis, eletrodomésticos, colchões, eletrônicos grandes. Não podem ser deixados com o lixo comum — é necessário comprar um adesivo de descarte.",
    descEs: "Muebles, electrodomésticos, colchones, electrónicos grandes. No pueden dejarse con la basura normal — se debe comprar una pegatina de descarte.",
    tipsEn: ["Buy a disposal sticker (대형폐기물 스티커) from your local district office (구청) or dong community center (동 주민센터)", "Cost varies by item size: ₩3,000–₩30,000", "Attach sticker visibly and place outside on designated collection day"],
    tipsKo: ["구청 또는 동 주민센터에서 대형폐기물 스티커 구입", "물품 크기에 따라 3,000~30,000원", "스티커 잘 보이게 붙이고 지정 수거일에 배출"],
    tipsJa: ["地域の区庁（구청）または洞主民センター（동 주민센터）で処分シール（대형폐기물 스티커）を購入", "品目サイズにより3,000〜30,000ウォン", "シールを見えやすい場所に貼り、指定収集日に外に出す"],
    tipsZhCN: ["在当地区厅（구청）或洞居民中心（동 주민센터）购买大件废弃物贴纸", "根据物品大小收费：₩3,000–₩30,000", "将贴纸贴在显眼处，并在指定收集日放出"],
    tipsZhTW: ["在當地區廳（구청）或洞居民中心（동 주민센터）購買大件廢棄物貼紙", "根據物品大小收費：₩3,000–₩30,000", "將貼紙貼在顯眼處，並在指定收集日放出"],
    tipsPt: ["Compre o adesivo de descarte (대형폐기물 스티커) no escritório distrital local (구청) ou no centro comunitário (동 주민센터)", "O custo varia conforme o tamanho do item: ₩3.000–₩30.000", "Cole o adesivo de forma visível e coloque do lado de fora no dia de coleta designado"],
    tipsEs: ["Compra la pegatina de descarte (대형폐기물 스티커) en la oficina distrital local (구청) o en el centro comunitario (동 주민센터)", "El costo varía según el tamaño del artículo: ₩3.000–₩30.000", "Pega la pegatina de forma visible y colócalo afuera el día de recolección designado"],
    how: "Reserve collection online at your district's website (gu.go.kr) or visit in person.",
    howKo: "각 구청 홈페이지에서 온라인 예약 또는 방문 신청.",
    howJa: "各区のウェブサイト（gu.go.kr）でオンライン予約するか、直接窓口へ。",
    howZhCN: "在各区官网（gu.go.kr）在线预约，或亲自前往办理。",
    howZhTW: "在各區官網（gu.go.kr）線上預約，或親自前往辦理。",
    howPt: "Reserve a coleta online no site do seu distrito (gu.go.kr) ou vá pessoalmente.",
    howEs: "Reserva la recogida en línea en el sitio web de tu distrito (gu.go.kr) o ve en persona.",
  },
];

export const PHONE_PLANS = [
  {
    carrier: "SKT",
    carrierKo: "SK텔레콤",
    plan: "Foreigner Pre-Paid SIM",
    planKo: "외국인 선불 유심",
    planJa: "外国人向けプリペイドSIM",
    planZhCN: "外国人预付费SIM卡",
    planZhTW: "外國人預付費SIM卡",
    planPt: "SIM Pré-Pago para Estrangeiros",
    planEs: "SIM Prepago para Extranjeros",
    priceKRW: 33000,
    data: "1.5GB + unlimited LTE (throttled after)",
    dataKo: "1.5GB + 속도 제한 LTE 무제한",
    dataJa: "1.5GB + 速度制限後LTE使い放題",
    dataZhCN: "1.5GB + 限速后LTE无限流量",
    dataZhTW: "1.5GB + 限速後LTE無限流量",
    dataPt: "1,5GB + LTE ilimitado (reduzido após)",
    dataEs: "1,5GB + LTE ilimitado (reducido luego)",
    calls: "300 min",
    callsKo: "300분",
    callsJa: "300分",
    callsZhCN: "300分钟",
    callsZhTW: "300分鐘",
    callsPt: "300 min",
    callsEs: "300 min",
    contractRequired: false,
    arcRequired: false,
    descEn: "Available at airports, SKT stores, convenience stores. Good for short-term visitors and new arrivals without ARC.",
    descKo: "공항, SKT 매장, 편의점에서 구입 가능. ARC 없는 단기 방문자에 적합.",
    descJa: "空港、SKTショップ、コンビニで購入可能。ARC（外国人登録証）がない短期滞在者や新着者に最適。",
    descZhCN: "可在机场、SKT门店、便利店购买。适合无ARC的短期访客及初到韩国者。",
    descZhTW: "可在機場、SKT門店、便利商店購買。適合無ARC的短期訪客及初到韓國者。",
    descPt: "Disponível em aeroportos, lojas SKT e conveniências. Ideal para visitantes de curta duração e recém-chegados sem ARC.",
    descEs: "Disponible en aeropuertos, tiendas SKT y tiendas de conveniencia. Ideal para visitantes de corta estadía y recién llegados sin ARC.",
  },
  {
    carrier: "KT",
    carrierKo: "KT",
    plan: "LTE Data SIM (Foreigner)",
    planKo: "외국인 LTE 데이터 유심",
    planJa: "外国人向けLTEデータSIM",
    planZhCN: "外国人LTE数据SIM卡",
    planZhTW: "外國人LTE數據SIM卡",
    planPt: "SIM de Dados LTE (Estrangeiros)",
    planEs: "SIM de Datos LTE (Extranjeros)",
    priceKRW: 30000,
    data: "2GB/month unlimited (throttled after 2GB)",
    dataKo: "월 2GB 무제한 (2GB 초과 시 속도 제한)",
    dataJa: "月2GB使い放題（2GB後速度制限）",
    dataZhCN: "每月2GB无限（超2GB限速）",
    dataZhTW: "每月2GB無限（超2GB限速）",
    dataPt: "2GB/mês ilimitado (reduzido após 2GB)",
    dataEs: "2GB/mes ilimitado (reducido luego de 2GB)",
    calls: "Unlimited (domestic)",
    callsKo: "국내 무제한",
    callsJa: "国内通話無制限",
    callsZhCN: "国内无限通话",
    callsZhTW: "國內無限通話",
    callsPt: "Ilimitado (nacional)",
    callsEs: "Ilimitado (nacional)",
    contractRequired: false,
    arcRequired: true,
    descEn: "Requires ARC. Good monthly value. KT has solid nationwide coverage.",
    descKo: "ARC 필요. 월정액 성능 좋음. KT 전국 커버리지 우수.",
    descJa: "ARC必要。月額コスパ良好。KTは全国カバレッジが優秀。",
    descZhCN: "需要ARC。月费性价比高。KT全国覆盖优秀。",
    descZhTW: "需要ARC。月費性價比高。KT全國覆蓋優秀。",
    descPt: "Requer ARC. Bom custo-benefício mensal. A KT tem cobertura sólida em todo o país.",
    descEs: "Requiere ARC. Buen valor mensual. KT tiene cobertura sólida en todo el país.",
  },
  {
    carrier: "LG U+",
    carrierKo: "LG 유플러스",
    plan: "Monthly Foreigner Plan",
    planKo: "외국인 월정액 요금제",
    planJa: "外国人向け月額プラン",
    planZhCN: "外国人月租套餐",
    planZhTW: "外國人月租方案",
    planPt: "Plano Mensal para Estrangeiros",
    planEs: "Plan Mensual para Extranjeros",
    priceKRW: 38000,
    data: "5GB + unlimited (throttled)",
    dataKo: "5GB + 속도 제한 무제한",
    dataJa: "5GB + 速度制限後使い放題",
    dataZhCN: "5GB + 限速无限流量",
    dataZhTW: "5GB + 限速無限流量",
    dataPt: "5GB + ilimitado (reduzido)",
    dataEs: "5GB + ilimitado (reducido)",
    calls: "Unlimited domestic",
    callsKo: "국내 무제한",
    callsJa: "国内通話無制限",
    callsZhCN: "国内无限通话",
    callsZhTW: "國內無限通話",
    callsPt: "Ilimitado nacional",
    callsEs: "Ilimitado nacional",
    contractRequired: false,
    arcRequired: true,
    descEn: "More data than competitors. Requires ARC. Good choice if you stream a lot.",
    descKo: "타사 대비 데이터 많음. ARC 필요. 스트리밍 많이 하는 경우 추천.",
    descJa: "他社より多くのデータ。ARC必要。ストリーミングをよく使う方におすすめ。",
    descZhCN: "数据量多于竞争对手。需要ARC。适合经常流媒体使用者。",
    descZhTW: "數據量多於競爭對手。需要ARC。適合經常串流使用者。",
    descPt: "Mais dados que os concorrentes. Requer ARC. Boa opção se você assiste muito a streaming.",
    descEs: "Más datos que los competidores. Requiere ARC. Buena opción si haces mucho streaming.",
  },
  {
    carrier: "MVNO (알뜰폰)",
    carrierKo: "알뜰폰",
    plan: "Budget MVNO Plans",
    planKo: "알뜰폰 요금제",
    planJa: "格安MVNOプラン（알뜰폰）",
    planZhCN: "实惠型MVNO套餐（알뜰폰）",
    planZhTW: "實惠型MVNO方案（알뜰폰）",
    planPt: "Planos Econômicos MVNO (알뜰폰)",
    planEs: "Planes Económicos MVNO (알뜰폰)",
    priceKRW: 10000,
    data: "1-3GB (varies by plan)",
    dataKo: "1-3GB (요금제별 상이)",
    dataJa: "1〜3GB（プランによる）",
    dataZhCN: "1-3GB（视套餐而定）",
    dataZhTW: "1-3GB（視方案而定）",
    dataPt: "1-3GB (varia por plano)",
    dataEs: "1-3GB (varía según el plan)",
    calls: "50-100 min or unlimited (plan-dependent)",
    callsKo: "50-100분 또는 무제한 (요금제 따라)",
    callsJa: "50〜100分または無制限（プランによる）",
    callsZhCN: "50-100分钟或无限（视套餐）",
    callsZhTW: "50-100分鐘或無限（視方案）",
    callsPt: "50-100 min ou ilimitado (depende do plano)",
    callsEs: "50-100 min o ilimitado (depende del plan)",
    contractRequired: false,
    arcRequired: true,
    descEn: "MVNO carriers (Hellovision, U+알뜰폰, etc.) piggyback on major networks at 1/3 the price. Great for budget-conscious residents.",
    descKo: "알뜰폰 사업자(헬로비전 등)는 대형 통신사 망 이용, 요금은 1/3 수준. 절약 원하는 거주자에게 좋음.",
    descJa: "MVNO事業者（Hellovision、U+알뜰폰など）は大手回線を使いながら料金は1/3程度。節約志向の居住者に最適。",
    descZhCN: "MVNO运营商（Hellovision、U+알뜰폰等）借用大网，价格约为1/3。适合注重节省的居民。",
    descZhTW: "MVNO業者（Hellovision、U+알뜰폰等）借用大網，價格約為1/3。適合注重省錢的居民。",
    descPt: "Operadoras MVNO (Hellovision, U+알뜰폰, etc.) usam as redes das grandes operadoras por 1/3 do preço. Ótimo para residentes que buscam economia.",
    descEs: "Los operadores MVNO (Hellovision, U+알뜰폰, etc.) usan las redes de los grandes operadores a 1/3 del precio. Ideal para residentes que buscan ahorrar.",
  },
];

export const ESSENTIAL_APPS = [
  {
    category: "Navigation",
    categoryKo: "지도/내비",
    categoryJa: "地図・ナビ",
    categoryZhCN: "地图/导航",
    categoryZhTW: "地圖/導航",
    categoryPt: "Navegação",
    categoryEs: "Navegación",
    apps: [
      {
        name: "Naver Maps (네이버 지도)",
        descEn: "The best navigation in Korea. Google Maps is unreliable here — Naver Maps knows every alley, every restaurant, real-time transit.",
        descKo: "한국 최고의 지도 앱. 구글맵은 여기서 부정확. 골목길, 실시간 대중교통 완벽 지원.",
        descJa: "韓国最高のナビアプリ。Googleマップは不正確。路地、レストラン、リアルタイム交通に完全対応。",
        descZhCN: "韩国最佳导航应用。Google地图在此不可靠——Naver Maps熟知每条小巷、餐厅及实时公交。",
        descZhTW: "韓國最佳導航應用。Google地圖在此不可靠——Naver Maps熟知每條小巷、餐廳及即時公車。",
        descPt: "A melhor navegação na Coreia. O Google Maps é pouco confiável aqui — o Naver Maps conhece cada beco, restaurante e transporte em tempo real.",
        descEs: "La mejor navegación en Corea. Google Maps no es confiable aquí — Naver Maps conoce cada callejón, restaurante y transporte en tiempo real.",
        platform: "iOS + Android",
      },
      {
        name: "Kakao Metro (카카오 지하철)",
        descEn: "Subway route planner with real-time train tracking. Shows transfer routes and estimated arrival.",
        descKo: "실시간 지하철 위치와 환승 경로 안내. 도착 예정 시간 표시.",
        descJa: "リアルタイム列車追跡付き地下鉄ルートプランナー。乗り換え経路と到着予定時刻を表示。",
        descZhCN: "实时列车追踪地铁路线规划器。显示换乘路线和预计到达时间。",
        descZhTW: "即時列車追蹤地鐵路線規劃器。顯示換乘路線和預計到達時間。",
        descPt: "Planejador de rotas de metrô com rastreamento de trens em tempo real. Mostra rotas de transferência e chegada estimada.",
        descEs: "Planificador de rutas de metro con seguimiento de trenes en tiempo real. Muestra rutas de transferencia y hora estimada de llegada.",
        platform: "iOS + Android",
      },
      {
        name: "T Map",
        descEn: "Best driving navigation app in Korea. Integrates with car GPS systems. Good for road trips.",
        descKo: "한국 최고의 자동차 내비. 차량 GPS와 연동 가능. 장거리 이동에 좋음.",
        descJa: "韓国最高のカーナビアプリ。車のGPSシステムと連動。長距離ドライブに最適。",
        descZhCN: "韩国最佳驾车导航应用。与车载GPS系统整合。适合长途驾车。",
        descZhTW: "韓國最佳駕車導航應用。與車載GPS系統整合。適合長途駕車。",
        descPt: "O melhor aplicativo de navegação para dirigir na Coreia. Integra-se com sistemas GPS do carro. Bom para viagens de carro.",
        descEs: "La mejor app de navegación para conducir en Corea. Se integra con los sistemas GPS del coche. Ideal para viajes en coche.",
        platform: "iOS + Android",
      },
    ],
  },
  {
    category: "Food & Delivery",
    categoryKo: "음식/배달",
    categoryJa: "フード・デリバリー",
    categoryZhCN: "餐饮/外卖",
    categoryZhTW: "餐飲/外送",
    categoryPt: "Comida e Delivery",
    categoryEs: "Comida y Delivery",
    apps: [
      {
        name: "Baemin (배달의민족)",
        descEn: "The #1 food delivery app. Every Korean restaurant delivers. Requires Korean phone number. Some UI now in English.",
        descKo: "배달 앱 1위. 거의 모든 음식점이 배달 됨. 한국 전화번호 필요.",
        descJa: "フードデリバリーアプリNo.1。ほぼ全ての韓国料理店が配達対応。韓国の電話番号が必要。一部UIは英語対応。",
        descZhCN: "韩国外卖应用第一名。几乎所有韩国餐厅均可配送。需要韩国手机号。部分界面现已支持英文。",
        descZhTW: "韓國外送應用第一名。幾乎所有韓國餐廳均可外送。需要韓國手機號。部分介面現已支援英文。",
        descPt: "O aplicativo de delivery de comida nº 1. Todo restaurante coreano entrega. Requer número de telefone coreano. Parte da UI já está em inglês.",
        descEs: "La app de delivery de comida nº 1. Todos los restaurantes coreanos hacen delivery. Requiere número de teléfono coreano. Parte de la UI ya está en inglés.",
        platform: "iOS + Android",
      },
      {
        name: "Coupang Eats (쿠팡이츠)",
        descEn: "Faster than Baemin (often 30 min). Smaller restaurant selection but excellent for quick orders.",
        descKo: "배민보다 빠름 (보통 30분). 음식점 수는 적으나 빠른 배달에 최적.",
        descJa: "Baeminより速い（多くは30分）。飲食店数は少ないが素早い注文に最適。",
        descZhCN: "比Baemin更快（通常30分钟）。餐厅选择较少，但非常适合快速点单。",
        descZhTW: "比Baemin更快（通常30分鐘）。餐廳選擇較少，但非常適合快速點餐。",
        descPt: "Mais rápido que o Baemin (geralmente 30 min). Menor seleção de restaurantes, mas excelente para pedidos rápidos.",
        descEs: "Más rápido que Baemin (generalmente 30 min). Menor selección de restaurantes, pero excelente para pedidos rápidos.",
        platform: "iOS + Android",
      },
      {
        name: "Coupang (쿠팡)",
        descEn: "Amazon equivalent in Korea. Next-day or same-day delivery for almost everything. Rocket delivery is extraordinary.",
        descKo: "한국의 아마존. 거의 모든 물건 당일/익일 배달. 로켓배송 체험 필수.",
        descJa: "韓国のAmazon。ほぼ何でも翌日・当日配達。ロケット配送は驚異的。",
        descZhCN: "韩国的亚马逊。几乎所有商品次日或当日送达。火箭配送体验非凡。",
        descZhTW: "韓國的亞馬遜。幾乎所有商品次日或當日送達。火箭配送體驗非凡。",
        descPt: "O equivalente da Amazon na Coreia. Entrega no dia seguinte ou no mesmo dia para quase tudo. O Rocket Delivery é extraordinário.",
        descEs: "El equivalente de Amazon en Corea. Entrega al día siguiente o el mismo día para casi todo. El Rocket Delivery es extraordinario.",
        platform: "iOS + Android",
      },
    ],
  },
  {
    category: "Communication",
    categoryKo: "소통",
    categoryJa: "コミュニケーション",
    categoryZhCN: "通讯",
    categoryZhTW: "通訊",
    categoryPt: "Comunicação",
    categoryEs: "Comunicación",
    apps: [
      {
        name: "KakaoTalk (카카오톡)",
        descEn: "THE messaging app in Korea. Everyone uses it. You need this. Download it before you even land.",
        descKo: "한국의 국민 메신저. 모두가 사용. 입국 전에 미리 설치할 것.",
        descJa: "韓国のメッセージアプリ。全員が使っている。必須。入国前にダウンロードを。",
        descZhCN: "韩国的国民即时通讯应用。人人都用。必备。入境前就要下载。",
        descZhTW: "韓國的國民即時通訊應用。人人都用。必備。入境前就要下載。",
        descPt: "O aplicativo de mensagens da Coreia. Todo mundo usa. Você precisa deste. Baixe antes mesmo de pousar.",
        descEs: "LA app de mensajería en Corea. Todo el mundo la usa. La necesitas. Descárgala antes de llegar.",
        platform: "iOS + Android",
      },
      {
        name: "Papago",
        descEn: "Naver's translation app. Superior to Google Translate for Korean. Camera translation is excellent for reading menus, signs, contracts.",
        descKo: "네이버 번역 앱. 한국어는 구글 번역보다 우수. 카메라 번역으로 메뉴, 간판, 계약서 번역 가능.",
        descJa: "Naverの翻訳アプリ。韓国語はGoogle翻訳より優秀。カメラ翻訳でメニュー、看板、契約書を翻訳可能。",
        descZhCN: "Naver的翻译应用。韩语翻译优于Google翻译。相机翻译可用于阅读菜单、标牌、合同。",
        descZhTW: "Naver的翻譯應用。韓語翻譯優於Google翻譯。相機翻譯可用於閱讀菜單、標誌、合約。",
        descPt: "O aplicativo de tradução da Naver. Superior ao Google Translate para o coreano. A tradução por câmera é excelente para ler cardápios, placas e contratos.",
        descEs: "La app de traducción de Naver. Superior a Google Translate para el coreano. La traducción por cámara es excelente para leer menús, señales y contratos.",
        platform: "iOS + Android",
      },
      {
        name: "Naver Dictionary (네이버 사전)",
        descEn: "Deep Korean-English dictionary with example sentences, conjugations, and pronunciation.",
        descKo: "예문, 활용형, 발음까지 제공하는 심층 한-영 사전.",
        descJa: "例文、活用形、発音付きの詳細な韓英辞典。",
        descZhCN: "收录例句、词形变化和发音的深度韩英词典。",
        descZhTW: "收錄例句、詞形變化和發音的深度韓英詞典。",
        descPt: "Dicionário profundo coreano-inglês com exemplos de frases, conjugações e pronúncia.",
        descEs: "Diccionario profundo coreano-inglés con frases de ejemplo, conjugaciones y pronunciación.",
        platform: "iOS + Android",
      },
    ],
  },
  {
    category: "Banking & Finance",
    categoryKo: "금융",
    categoryJa: "銀行・金融",
    categoryZhCN: "银行/金融",
    categoryZhTW: "銀行/金融",
    categoryPt: "Banco e Finanças",
    categoryEs: "Banca y Finanzas",
    apps: [
      {
        name: "Toss (토스)",
        descEn: "Korea's fintech super-app. Easy money transfers, credit score checking, spending analysis. Works with most Korean bank accounts.",
        descKo: "한국 핀테크 슈퍼앱. 간편 송금, 신용점수 확인, 지출 분석. 대부분의 한국 은행 계좌 연동 가능.",
        descJa: "韓国のフィンテックスーパーアプリ。簡単送金、信用スコア確認、支出分析。ほとんどの韓国銀行口座と連動。",
        descZhCN: "韩国金融科技超级应用。便捷转账、信用分查询、消费分析。与大多数韩国银行账户兼容。",
        descZhTW: "韓國金融科技超級應用。便捷轉帳、信用分查詢、消費分析。與大多數韓國銀行帳戶相容。",
        descPt: "O super-app de fintech da Coreia. Transferências fáceis, verificação de crédito, análise de gastos. Funciona com a maioria das contas bancárias coreanas.",
        descEs: "La super-app de fintech de Corea. Transferencias fáciles, verificación de crédito, análisis de gastos. Funciona con la mayoría de las cuentas bancarias coreanas.",
        platform: "iOS + Android",
      },
      {
        name: "Your bank's app",
        descEn: "Hana, Shinhan, KB each have apps. Hana and Shinhan have decent English support.",
        descKo: "하나, 신한, KB 앱 각각 제공. 하나, 신한 영어 지원 양호.",
        descJa: "Hana、Shinhan、KBそれぞれにアプリあり。HanaとShinhanは英語サポートが比較的良好。",
        descZhCN: "Hana、Shinhan、KB各有应用。Hana和Shinhan有较好的英文支持。",
        descZhTW: "Hana、Shinhan、KB各有應用。Hana和Shinhan有較好的英文支援。",
        descPt: "Hana, Shinhan e KB têm seus próprios apps. Hana e Shinhan têm suporte razoável em inglês.",
        descEs: "Hana, Shinhan y KB tienen sus propias apps. Hana y Shinhan tienen un soporte decente en inglés.",
        platform: "iOS + Android",
      },
    ],
  },
  {
    category: "Health",
    categoryKo: "건강",
    categoryJa: "健康",
    categoryZhCN: "健康",
    categoryZhTW: "健康",
    categoryPt: "Saúde",
    categoryEs: "Salud",
    apps: [
      {
        name: "Goodoc (굿닥)",
        descEn: "Find English-speaking doctors and clinics. Book appointments directly from the app. Filter by specialty and language.",
        descKo: "영어 가능 병원 찾기. 앱에서 바로 예약. 전문과목, 언어별 필터 가능.",
        descJa: "英語対応の医師・クリニックを検索。アプリから直接予約。専門科目と言語でフィルター可能。",
        descZhCN: "查找会说英语的医生和诊所。直接在应用内预约。可按专科和语言筛选。",
        descZhTW: "查找會說英語的醫生和診所。直接在應用內預約。可按專科和語言篩選。",
        descPt: "Encontre médicos e clínicas com inglês. Agende consultas diretamente no app. Filtre por especialidade e idioma.",
        descEs: "Encuentra médicos y clínicas que hablen inglés. Agenda citas directamente desde la app. Filtra por especialidad e idioma.",
        platform: "iOS + Android",
      },
      {
        name: "NaverMap → pharmacy",
        descEn: "Search '약국' on Naver Maps to find open pharmacies near you with real-time hours.",
        descKo: "네이버 지도에서 '약국' 검색으로 근처 약국 실시간 영업 시간 확인.",
        descJa: "Naver Mapsで「약국」と検索すると、近くの薬局とリアルタイムの営業時間がわかる。",
        descZhCN: "在Naver地图搜索「약국」即可找到附近营业中的药店及实时营业时间。",
        descZhTW: "在Naver地圖搜尋「약국」即可找到附近營業中的藥局及即時營業時間。",
        descPt: "Pesquise '약국' no Naver Maps para encontrar farmácias abertas perto de você com horários em tempo real.",
        descEs: "Busca '약국' en Naver Maps para encontrar farmacias abiertas cerca de ti con horarios en tiempo real.",
        platform: "iOS + Android",
      },
    ],
  },
  {
    category: "Shopping & Lifestyle",
    categoryKo: "쇼핑/생활",
    categoryJa: "ショッピング・ライフスタイル",
    categoryZhCN: "购物/生活",
    categoryZhTW: "購物/生活",
    categoryPt: "Compras e Estilo de Vida",
    categoryEs: "Compras y Estilo de Vida",
    apps: [
      {
        name: "당근 (Daangn)",
        descEn: "Korea's Craigslist/Facebook Marketplace. Buy/sell second-hand items locally. Great for finding furniture when you first arrive.",
        descKo: "한국의 중고거래 플랫폼. 동네에서 중고 물건 사고팔기. 처음 입국 시 가구 구하기 좋음.",
        descJa: "韓国のCraigslist/FacebookマーケットPlaceに相当。近所で中古品の売買。最初の入国時に家具を探すのに便利。",
        descZhCN: "韩国的Craigslist/Facebook Marketplace。在本地买卖二手物品。初到韩国时找家具的好地方。",
        descZhTW: "韓國的Craigslist/Facebook Marketplace。在本地買賣二手物品。初到韓國時找家具的好地方。",
        descPt: "O Craigslist/Facebook Marketplace da Coreia. Compre/venda itens usados localmente. Ótimo para encontrar móveis quando você chega pela primeira vez.",
        descEs: "El Craigslist/Facebook Marketplace de Corea. Compra/vende artículos de segunda mano localmente. Ideal para encontrar muebles cuando llegas por primera vez.",
        platform: "iOS + Android",
      },
      {
        name: "Naver Shopping",
        descEn: "Price comparison across all Korean online shops. Best way to find the cheapest price for any product.",
        descKo: "국내 모든 온라인 쇼핑몰 가격 비교. 최저가 찾기 최적.",
        descJa: "国内全オンラインショップの価格比較。どんな商品でも最安値を見つけるのに最適。",
        descZhCN: "比较韩国所有网店价格。查找任何商品最低价的最佳方式。",
        descZhTW: "比較韓國所有網路商店價格。查找任何商品最低價的最佳方式。",
        descPt: "Comparação de preços em todas as lojas online coreanas. A melhor maneira de encontrar o preço mais barato para qualquer produto.",
        descEs: "Comparación de precios en todas las tiendas online coreanas. La mejor manera de encontrar el precio más barato para cualquier producto.",
        platform: "Web + App",
      },
    ],
  },
];

export const DELIVERY_GUIDE = [
  {
    service: "Coupang Rocket (로켓배송)",
    emoji: "🚀",
    descEn: "Order before midnight, get it next morning. Often same-day for orders before 2pm. Extraordinary service. Sign up for Coupang Rocket Wow membership (₩4,990/month) for free shipping.",
    descKo: "자정 전 주문 시 다음날 아침 배달. 오후 2시 전 주문 시 당일 배달도 가능. 로켓와우 멤버십(월 4,990원)으로 무료배송.",
    descJa: "深夜0時前に注文すると翌朝届く。午後2時前の注文は当日配達も可能。ロケットワウ会員（月4,990ウォン）で送料無料。",
    descZhCN: "午夜前下单，次日早晨送达。下午2点前下单通常当日送达。服务卓越。订阅Coupang Rocket Wow会员（₩4,990/月）可享免运费。",
    descZhTW: "午夜前下單，次日早晨送達。下午2點前下單通常當日送達。服務卓越。訂閱Coupang Rocket Wow會員（₩4,990/月）可享免運費。",
    descPt: "Peça antes da meia-noite, receba na manhã seguinte. Geralmente no mesmo dia para pedidos antes das 14h. Serviço extraordinário. Assine o Coupang Rocket Wow (₩4.990/mês) para frete grátis.",
    descEs: "Pide antes de medianoche, recíbelo a la mañana siguiente. A menudo el mismo día para pedidos antes de las 2pm. Servicio extraordinario. Suscríbete a Coupang Rocket Wow (₩4.990/mes) para envío gratis.",
  },
  {
    service: "Baemin (배달의민족)",
    emoji: "🍕",
    descEn: "30-60 min food delivery. Download the app, set your address, and browse. Most restaurants have photos. Minimum orders apply (usually ₩15,000-20,000).",
    descKo: "30-60분 음식 배달. 앱 설치, 주소 설정 후 주문. 대부분 사진 있음. 최소 주문 금액 있음 (보통 15,000-20,000원).",
    descJa: "30〜60分のフードデリバリー。アプリをダウンロードし、住所を設定して注文。ほとんどの店に写真あり。最低注文金額あり（通常15,000〜20,000ウォン）。",
    descZhCN: "30-60分钟送餐。下载应用，设置地址后浏览下单。大多数餐厅有照片。有最低起送金额（通常₩15,000-20,000）。",
    descZhTW: "30-60分鐘送餐。下載應用，設置地址後瀏覽下單。大多數餐廳有照片。有最低起送金額（通常₩15,000-20,000）。",
    descPt: "Delivery de comida em 30-60 min. Baixe o app, configure seu endereço e navegue. A maioria dos restaurantes tem fotos. Pedido mínimo aplicável (geralmente ₩15.000-20.000).",
    descEs: "Delivery de comida en 30-60 min. Descarga la app, configura tu dirección y navega. La mayoría de los restaurantes tienen fotos. Se aplica pedido mínimo (generalmente ₩15.000-20.000).",
  },
  {
    service: "Address issues",
    emoji: "📍",
    descEn: "Your delivery address in Korea should be in Korean format. When setting up apps, use your building's Korean address (찾기 with Naver Maps or ask your landlord). English addresses rarely work.",
    descKo: "배달 주소는 한국어 형식으로 입력. 건물의 한국어 주소 사용 (네이버 지도 또는 집주인에게 확인). 영어 주소는 잘 안 됨.",
    descJa: "韓国での配達先住所は韓国語フォーマットで入力すること。アプリ設定時は建物の韓国語住所を使用（Naver Mapsで検索するか家主に確認）。英語住所はほぼ機能しない。",
    descZhCN: "韩国配送地址应使用韩文格式。设置应用时，使用您楼栋的韩文地址（通过Naver地图查找或询问房东）。英文地址通常无效。",
    descZhTW: "韓國配送地址應使用韓文格式。設置應用時，使用您大樓的韓文地址（透過Naver地圖查找或詢問房東）。英文地址通常無效。",
    descPt: "Seu endereço de entrega na Coreia deve estar no formato coreano. Ao configurar os apps, use o endereço coreano do seu prédio (pesquise no Naver Maps ou pergunte ao seu proprietário). Endereços em inglês raramente funcionam.",
    descEs: "Tu dirección de entrega en Corea debe estar en formato coreano. Al configurar las apps, usa la dirección coreana de tu edificio (busca en Naver Maps o pregúntale a tu arrendador). Las direcciones en inglés rara vez funcionan.",
  },
  {
    service: "Delivery to the door",
    emoji: "🏠",
    descEn: "Most delivery people will call/text when they arrive (in Korean). Having a basic phrase ready helps: '문 앞에 놔주세요' (leave at the door) is useful.",
    descKo: "대부분 배달 기사가 도착 시 전화/문자 (한국어). 기본 문구 준비 도움: '문 앞에 놔주세요' (문 앞에 두고 가기).",
    descJa: "ほとんどの配達員は到着時に電話またはメッセージ（韓国語）を送ってくる。基本フレーズを準備しておくと便利：'문 앞에 놔주세요'（ドアの前に置いてください）。",
    descZhCN: "大多数配送员到达时会用韩语打电话或发短信。准备好基本用语会有帮助：'문 앞에 놔주세요'（请放在门口）。",
    descZhTW: "大多數配送員到達時會用韓語打電話或發簡訊。準備好基本用語會有幫助：'문 앞에 놔주세요'（請放在門口）。",
    descPt: "A maioria dos entregadores liga/manda mensagem quando chega (em coreano). Ter uma frase básica pronta ajuda: '문 앞에 놔주세요' (deixe na porta) é muito útil.",
    descEs: "La mayoría de los repartidores llaman/escriben cuando llegan (en coreano). Tener una frase básica lista ayuda: '문 앞에 놔주세요' (déjalo en la puerta) es muy útil.",
  },
];

export const DRIVERS_LICENSE = {
  conversionEn: "If your home country has a reciprocal agreement with Korea, you can convert your existing license without a test. Countries include: USA, Canada, UK, Australia, Germany, France, and 100+ others.",
  conversionKo: "본국과 한국 간 상호 인정 협정이 있는 경우 시험 없이 면허 변환 가능. 미국, 캐나다, 영국, 호주, 독일, 프랑스 등 100개국 이상.",
  conversionJa: "母国と韓国の間に相互協定がある場合、試験なしで免許を転換できる。米国、カナダ、英国、オーストラリア、ドイツ、フランスなど100カ国以上が対象。",
  conversionZhCN: "若您的母国与韩国签有相互认可协议，可免试转换驾照。涵盖美国、加拿大、英国、澳大利亚、德国、法国等100多个国家。",
  conversionZhTW: "若您的母國與韓國簽有相互認可協議，可免試轉換駕照。涵蓋美國、加拿大、英國、澳大利亞、德國、法國等100多個國家。",
  conversionPt: "Se o seu país de origem tem um acordo recíproco com a Coreia, você pode converter sua habilitação sem fazer uma prova. Países incluem: EUA, Canadá, Reino Unido, Austrália, Alemanha, França e mais de 100 outros.",
  conversionEs: "Si tu país de origen tiene un acuerdo recíproco con Corea, puedes convertir tu licencia sin examen. Los países incluyen: EE. UU., Canadá, Reino Unido, Australia, Alemania, Francia y más de 100 otros.",
  conversionSteps: [
    {
      stepEn: "Visit a Driver's License Examination Office (운전면허시험장)",
      stepKo: "운전면허시험장 방문",
      stepJa: "運転免許試験場（운전면허시험장）を訪問",
      stepZhCN: "前往驾照考试中心（운전면허시험장）",
      stepZhTW: "前往駕照考試中心（운전면허시험장）",
      stepPt: "Visite um Escritório de Exame de Carteira de Motorista (운전면허시험장)",
      stepEs: "Visita una Oficina de Examen de Licencia de Conducir (운전면허시험장)",
    },
    {
      stepEn: "Bring: ARC, passport, your home country license + Korean translation (from a notary or Naver), 1 passport photo, ₩10,000 fee",
      stepKo: "ARC, 여권, 본국 면허증 + 한국어 번역본 (공증 또는 네이버), 여권 사진 1매, 수수료 10,000원 지참",
      stepJa: "持参物：ARC、パスポート、母国免許証 + 韓国語翻訳（公証または Naver経由）、証明写真1枚、手数料10,000ウォン",
      stepZhCN: "携带：ARC、护照、本国驾照+韩文翻译件（公证或通过Naver）、1张护照照片、₩10,000手续费",
      stepZhTW: "攜帶：ARC、護照、本國駕照+韓文翻譯件（公證或透過Naver）、1張護照照片、₩10,000手續費",
      stepPt: "Traga: ARC, passaporte, sua habilitação do país de origem + tradução coreana (por cartório ou Naver), 1 foto de passaporte, taxa de ₩10.000",
      stepEs: "Lleva: ARC, pasaporte, tu licencia del país de origen + traducción coreana (de un notario o Naver), 1 foto de pasaporte, tarifa de ₩10.000",
    },
    {
      stepEn: "Take an eye test on-site (quick, about 5 minutes)",
      stepKo: "현장 시력 검사 (빠름, 약 5분)",
      stepJa: "現地で視力検査（簡単、約5分）",
      stepZhCN: "现场进行视力测试（快速，约5分钟）",
      stepZhTW: "現場進行視力測試（快速，約5分鐘）",
      stepPt: "Faça um teste de visão no local (rápido, cerca de 5 minutos)",
      stepEs: "Realiza una prueba de visión en el lugar (rápida, unos 5 minutos)",
    },
    {
      stepEn: "If your country requires it: take a short road safety quiz (25 questions, easy, in English)",
      stepKo: "일부 국가의 경우: 교통안전 퀴즈 (25문제, 쉬움, 영어 가능)",
      stepJa: "国によっては：短い交通安全クイズ（25問、簡単、英語対応）",
      stepZhCN: "如您的国家需要：参加简短的道路安全测验（25题，简单，可用英语）",
      stepZhTW: "如您的國家需要：參加簡短的道路安全測驗（25題，簡單，可用英語）",
      stepPt: "Se o seu país exigir: faça um pequeno quiz de segurança viária (25 questões, fácil, em inglês)",
      stepEs: "Si tu país lo requiere: realiza un pequeño cuestionario de seguridad vial (25 preguntas, fácil, en inglés)",
    },
    {
      stepEn: "Receive your Korean license same day (or next day)",
      stepKo: "당일 (또는 다음날) 한국 면허 수령",
      stepJa: "当日（または翌日）に韓国免許を受領",
      stepZhCN: "当天（或次日）领取韩国驾照",
      stepZhTW: "當天（或次日）領取韓國駕照",
      stepPt: "Receba sua habilitação coreana no mesmo dia (ou no dia seguinte)",
      stepEs: "Recibe tu licencia coreana el mismo día (o al día siguiente)",
    },
  ],
  newTestEn: "If your country doesn't have an agreement, you'll need to take the full Korean driving test (written + practical). Visit Kakao Navi's website or the Road Traffic Authority (도로교통공단) site for study materials in English.",
  newTestKo: "협정 미체결 국가 국민은 한국 면허 시험(필기+실기) 응시 필요. 카카오내비 웹사이트 또는 도로교통공단 사이트에서 영어 공부자료 확인 가능.",
  newTestJa: "協定未締結国の方は、韓国の運転免許試験（筆記+実技）を受験する必要がある。英語の学習教材は카카오내비のウェブサイトまたは道路交通公団（도로교통공단）サイトで確認可能。",
  newTestZhCN: "未签订协议国家的公民需参加完整的韩国驾照考试（笔试+实操）。英文学习材料可在카카오내비网站或道路交通公团（도로교통공단）网站查阅。",
  newTestZhTW: "未簽訂協議國家的公民需參加完整的韓國駕照考試（筆試+實操）。英文學習材料可在카카오내비網站或道路交通公團（도로교통공단）網站查閱。",
  newTestPt: "Se o seu país não tem um acordo, você precisará fazer o exame completo de direção coreano (escrito + prático). Visite o site da Kakao Navi ou o site da Autoridade de Trânsito Rodoviário (도로교통공단) para materiais de estudo em inglês.",
  newTestEs: "Si tu país no tiene un acuerdo, necesitarás hacer el examen completo de conducir coreano (escrito + práctico). Visita el sitio de Kakao Navi o el sitio de la Autoridad de Tráfico Vial (도로교통공단) para materiales de estudio en inglés.",
};
