export interface FAQItem { q: string; a: string; }
export type GuideFAQs = Record<string, FAQItem[]>;

export const GUIDE_FAQS: GuideFAQs = {
  settle: [
    { q: "How long do I have to register my ARC (Alien Registration Card) after arriving in Korea?", a: "You must register your ARC within 90 days of arrival in South Korea. Visit your nearest Immigration Office with your passport, visa, one 3x4cm passport photo, and a registration fee of 30,000 KRW. Overstaying the 90-day deadline can result in fines." },
    { q: "Which Korean bank is best for foreigners?", a: "Hana Bank (KEB Hana) and Shinhan Bank are the most foreigner-friendly options in 2026. Both offer English-language apps and have branches near major expat areas like Itaewon, Hongdae, and Gangnam. You'll need your ARC, passport, and a Korean phone number to open an account." },
    { q: "Do foreigners need to enroll in Korean national health insurance (NHIS)?", a: "Yes. All foreigners staying in Korea for 6 months or more are automatically enrolled in the National Health Insurance Service (NHIS, 건강보험). For work visa holders, your employer handles enrollment. Monthly premiums in 2026 start at approximately 140,000 KRW, covering about 60-80% of medical costs." },
    { q: "What is the T-money card and where do I get one?", a: "T-money is a rechargeable transit card used on Seoul's buses, subway, and taxis. Pick one up at any convenience store (GS25, CU, 7-Eleven) for about 2,500 KRW, then charge it at subway station kiosks or convenience stores. A single subway ride in Seoul is about 1,400-1,800 KRW with T-money." },
    { q: "Which apps do I need when I first arrive in Korea?", a: "Essential apps: KakaoTalk (messaging), Naver Maps or Kakao Maps (navigation), Baemin or Coupang Eats (food delivery), Seoul Metro (subway routes), Papago (translation), and KakaoBank or Toss (banking). Most are free on the App Store and Play Store." },
  ],
  visa: [
    { q: "What is the most common visa for English teachers in Korea?", a: "The E-2 visa (Foreign Language Instructor Visa) is the standard visa for English teachers at Korean schools, hagwons, and universities. Requirements include a bachelor's degree, a criminal background check from your home country, and a signed employment contract. Your employer typically sponsors the visa application." },
    { q: "Can I work in Korea on a tourist visa?", a: "No. Working in Korea without an appropriate work visa is illegal and can result in deportation and a ban from re-entering Korea. Tourist visa holders (B-1, B-2) are explicitly prohibited from working. Common work visas include E-1 through E-7, and F-series visas for long-term residents." },
    { q: "How long does it take to get an ARC after applying?", a: "ARC processing at Korean Immigration takes approximately 2-3 weeks. You'll receive an SMS when your card is ready. During this waiting period, your passport with the immigration stamp serves as proof of legal residency. The main Seoul Immigration Office is located in Mokdong (목동), Yangcheon-gu." },
    { q: "Can I change my visa type while staying in Korea?", a: "Yes, visa status changes are possible without leaving Korea in most cases. You apply at the Korean Immigration Service (Hi Korea) with the required documents for your target visa. Common changes include tourist to student (D-2), or E-series work visas to F-2 (long-term residency). Processing fees and times vary by visa type." },
    { q: "What is an F-2 visa and how do I qualify?", a: "The F-2 visa (Residency Visa) is a long-term residency visa for foreigners who have lived in Korea legally for an extended period. You can qualify through the KIIP (Korea Immigration and Integration Program) by earning 60+ points through a combination of income, Korean language ability, assets, and years of residence. It allows almost unrestricted work rights." },
  ],
  housing: [
    { q: "What is jeonse (전세) and how does it work?", a: "Jeonse is a uniquely Korean rental system where you pay a large lump-sum deposit (typically 50-80% of the property value) and pay no monthly rent for the lease term (usually 2 years). At the end of the lease, the full deposit is returned. In 2026, jeonse deposits in Seoul range from 100 million KRW in outer neighborhoods to 500+ million KRW in Gangnam." },
    { q: "Is it safe to pay a jeonse deposit as a foreigner?", a: "Jeonse carries real risks — deposit scams (전세 사기) have defrauded thousands of tenants. Always check the property's 등기부등본 (ownership and lien records) at the Korea Court Registry. Ensure the landlord's name matches, verify there are no mortgages exceeding your deposit, and register your move-in (전입신고) at your district office within 14 days of signing." },
    { q: "What is the typical deposit for a monthly rental (wolse) apartment in Seoul?", a: "Wolse (월세) apartments in Seoul typically require a deposit (보증금) of 5-30 million KRW plus monthly rent. In 2026, a studio (원룸) in areas like Sinchon, Hongdae, or near universities costs 500,000-900,000 KRW/month with a 5-10 million KRW deposit. Gangnam and Mapo-gu are significantly more expensive." },
    { q: "Can foreigners rent apartments in Korea without a Korean guarantor?", a: "Yes, many landlords rent to foreigners without a Korean guarantor, especially in areas with high expat populations (Itaewon, Mapo, Yongsan, Mapo). However, some landlords may ask for a larger deposit to offset perceived risk. Having an ARC and proof of income or employment significantly helps your application." },
    { q: "What should I check before signing a Korean lease contract?", a: "Key checks: (1) Verify the landlord's identity matches the 등기부등본 (property registry). (2) Confirm there are no mortgages or liens that exceed your deposit. (3) Ensure the contract specifies the exact deposit, monthly rent, lease term, and any maintenance responsibilities. (4) Check that the property address matches official records. (5) Have a Korean-speaking friend or lawyer review the contract." },
  ],
  money: [
    { q: "Can foreigners open a bank account in Korea without an ARC?", a: "Most Korean banks require an ARC to open a full bank account. However, some banks offer limited accounts for non-residents: KEB Hana Bank and Shinhan Bank allow accounts with just a passport and D-type visas in some cases. For a full account with wire transfer capability, you generally need your ARC, passport, and a registered Korean phone number." },
    { q: "What is the cheapest way to send money from Korea abroad?", a: "In 2026, Wise (formerly TransferWise) offers some of the lowest fees for international transfers from Korea, typically 0.4-0.8% with mid-market exchange rates. Korean services Sentbe and Hana Bank's GLN also offer competitive rates. Western Union and traditional bank wires are significantly more expensive (2-5% in fees)." },
    { q: "Do foreigners in Korea have to pay income tax?", a: "Yes. All income earned in Korea is subject to Korean income tax, regardless of nationality. South Korea's income tax rates range from 6% to 45%. Foreign residents who have lived in Korea for fewer than 5 of the last 10 years are only taxed on Korea-sourced income. Your employer handles monthly withholding; year-end tax settlement (연말정산) happens in January-February." },
    { q: "Can I get a pension refund when I leave Korea?", a: "Yes. Foreigners who have contributed to Korea's National Pension System (NPS, 국민연금) for less than 10 years can claim a lump-sum refund when permanently leaving Korea. Apply within 3 years of departure at the NPS or Korean embassy. Many countries have Social Security Totalization Agreements with Korea — check if your country qualifies." },
    { q: "What is the average cost of living in Seoul for a single person?", a: "In 2026, a comfortable single-person lifestyle in Seoul typically costs 1,800,000-2,800,000 KRW/month ($1,350-$2,100). This includes: rent 700,000-1,500,000 KRW, food 400,000-600,000 KRW, transport 100,000-150,000 KRW, phone 33,000-70,000 KRW, utilities 80,000-150,000 KRW. Seoul is significantly more affordable than Tokyo, Singapore, or most Western cities." },
  ],
  daily: [
    { q: "How does recycling work in Korea?", a: "Korea uses a mandatory pay-per-bag waste system. Standard trash must go in official 종량제 봉투 (volume-rate bags), available at convenience stores for 100-600 KRW depending on size. Recyclables (paper, plastic, glass, cans) are separated and put out for free on designated collection days. Food waste goes in separate biodegradable bags or the green bins. Illegal dumping can result in fines up to 1,000,000 KRW." },
    { q: "Which food delivery app should I use in Korea?", a: "The three main delivery apps in 2026 are Baemin (배달의민족), Coupang Eats, and Yogiyo. Baemin has the widest restaurant selection and works in English mode. Coupang Eats often has lower delivery fees and faster delivery. All three accept international cards and offer English interfaces. Delivery fees are typically 0-3,000 KRW and orders arrive in 20-40 minutes." },
    { q: "What phone plan should I get as a foreigner in Korea?", a: "Major carriers (SK Telecom, KT, LG U+) offer foreigner-friendly plans starting from 33,000 KRW/month for unlimited data. For cheaper options, MVNO plans from KT M-Mobile or SK 7Mobile start from 9,900 KRW/month with limited data. You need your ARC and passport to sign up. Short-term visitors can buy prepaid SIM cards at Incheon Airport." },
    { q: "How do I convert my foreign driver's license in Korea?", a: "Foreigners from most countries can convert their home country license at a driver's license examination office (운전면허시험장). Required documents: foreign license, ARC, passport, official Korean translation of your license (from an embassy or notary), and a fee of about 13,000 KRW. Some countries require an eye test and a short practical test. The process takes 1-2 hours." },
    { q: "How do I pay for public transit in Seoul?", a: "Use a T-money card (티머니) or Cashbee card, available at convenience stores for 2,500 KRW. Charge at subway station kiosks or convenience stores. Tap in and out of buses and subways. A single subway ride costs 1,400-1,800 KRW. You can also pay with credit/debit cards that support contactless payment. Monthly transit passes are available for heavy commuters." },
  ],
  work: [
    { q: "What are the legal working hours in Korea?", a: "Under the Korean Labor Standards Act (근로기준법), standard working hours are 40 hours per week (8 hours per day). Overtime is capped at 12 hours per week (52 hours total). As of 2024, this limit applies to companies with 5+ employees. Overtime must be paid at 150% of the regular wage rate. Working more than 52 hours/week is illegal for your employer." },
    { q: "Am I entitled to severance pay in Korea?", a: "Yes. Under Korean law, any employee who has worked for the same employer for 1+ year is entitled to severance pay (퇴직금) equal to approximately 1 month's average wage per year of service. This applies regardless of nationality. If your employer refuses to pay, you can file a complaint with the Ministry of Employment and Labor (고용노동부)." },
    { q: "What is 4대보험 and am I required to enroll?", a: "4대보험 (Four Major Insurance Programs) are: National Health Insurance (건강보험), National Pension (국민연금), Employment Insurance (고용보험), and Industrial Accident Insurance (산재보험). If you're on a work visa and employed full-time, your employer must enroll you in all four. Your combined contribution is approximately 8-9% of your salary; the employer matches a similar amount." },
    { q: "What should I check before signing a Korean employment contract?", a: "Critical items: (1) Salary stated in Korean won (KRW) and whether it's gross or net. (2) Whether housing, flights, or health insurance are included. (3) Start and end date, and whether it auto-renews. (4) Notice period for resignation or termination. (5) Severance pay eligibility. (6) Whether 4대보험 is provided. (7) Overtime expectations and compensation. Request a copy in English if possible." },
    { q: "What is 회식 (hoesik) and can I decline?", a: "회식 is the Korean work culture of group dining or drinking events with colleagues, often organized by managers. While participation is technically voluntary, there can be cultural pressure to attend. In 2026, many Korean companies have relaxed hoesik culture, especially in international or tech environments. It's acceptable to attend without drinking alcohol by citing health or personal reasons." },
  ],
  health: [
    { q: "How do I find an English-speaking doctor in Seoul?", a: "Several options: (1) International clinics in Itaewon, Gangnam, and Sinchon typically have English-speaking staff. (2) The Seoul Global Center's helpline (1345) connects you with English-speaking assistance. (3) Severance Hospital (세브란스), Asan Medical Center, and Samsung Medical Center all have international patient centers with English services. (4) Google 'English-speaking clinic [neighborhood] Seoul' for local options." },
    { q: "How does National Health Insurance (NHIS) work for foreigners?", a: "Foreigners staying 6+ months are automatically enrolled in NHIS (건강보험). Monthly premiums in 2026 are approximately 140,000-200,000 KRW for most foreign employees, deducted from salary. NHIS covers 60-80% of most medical costs. To use it, bring your ARC and insurance card to any clinic. Emergency care is covered immediately; a regular clinic visit costs about 5,000-15,000 KRW out-of-pocket." },
    { q: "What is the difference between a 의원, 병원, and 종합병원?", a: "Korean healthcare has three tiers: 의원 (clinic) treats common conditions and is your first stop for most issues. 병원 (hospital, 30-100 beds) handles more complex cases. 종합병원 (general hospital, 100+ beds) handles specialized and serious conditions. For non-emergency issues, always start at a 의원 — it's cheaper and faster. Referrals from lower tiers get you priority at higher tiers." },
    { q: "What should I do in a medical emergency in Korea?", a: "Call 119 for ambulance and fire emergencies (multilingual service available). Call 1339 for the 24-hour medical helpline (some English). For non-life-threatening emergencies, ER (응급실) access is available at all 종합병원 without appointments. Bring your ARC, insurance card, and if possible a Korean-speaking friend. 1345 is the Seoul Global Center helpline for general foreigner assistance." },
    { q: "How do pharmacies work in Korea?", a: "Korean pharmacies (약국) are everywhere and pharmacists are highly trained. You don't need a prescription for many common medications. Show the pharmacist your symptoms and they'll recommend appropriate medicine — many pharmacists in tourist areas speak basic English. For prescription medications (전문의약품), you'll need a doctor's prescription. Pharmacies are typically open 9am-9pm; some operate 24 hours." },
  ],
  "mental-health": [
    { q: "What are the stages of culture shock in Korea?", a: "Culture shock typically follows 4 stages: (1) Honeymoon — excitement about everything new (weeks 1-4). (2) Frustration — language barriers, cultural misunderstandings, and loneliness become overwhelming (weeks 4-12). (3) Adjustment — developing coping strategies and a routine (months 3-6). (4) Adaptation — feeling comfortable and finding genuine connections (6+ months). Most expats in Korea experience stages 1-3; reaching stage 4 takes time and active effort." },
    { q: "Are there English-speaking therapists and counselors in Seoul?", a: "Yes. Several options exist in 2026: (1) Hope Counseling Center in Mapo-gu has English-speaking counselors starting from 80,000 KRW/session. (2) Many international hospitals (Severance, Samsung) have psychiatric departments with English support. (3) Online platforms like BetterHelp connect you with English-speaking therapists globally. (4) The Seoul Global Center (1345) can refer you to mental health resources." },
    { q: "What is the Korean mental health crisis hotline?", a: "Korea's mental health crisis hotline is 1577-0199, available 24 hours in Korean. For English speakers: the Seoul Global Center (1345) offers multilingual support. Suicide prevention: 1393 (Korean, 24/7). For immediate danger, call 119 (emergency services). International Association for Suicide Prevention maintains a global directory of crisis centers at iasp.info." },
    { q: "How do I find expat community support groups in Seoul?", a: "Active communities include: (1) Internations Seoul (internations.org) — regular meetups and events. (2) Seoul Facebook expat groups (search 'Expats in Seoul' or 'Foreigners in Korea'). (3) r/korea and r/Living_in_Korea on Reddit. (4) Koreans Next Door (koreansnextdoor.com) — community events, language exchanges, and social gatherings organized by locals. (5) Many churches in Seoul run international English-language services with expat communities." },
    { q: "Is it normal to feel lonely or depressed when living abroad in Korea?", a: "Completely normal and very common. Studies suggest 60-80% of expatriates experience significant loneliness within their first year abroad. The combination of language barriers, cultural differences, distance from family, and the pressure to appear happy makes expat life uniquely challenging. Recognizing these feelings as normal — not a personal failure — is the first step. Active community building, maintaining home connections, and seeking professional help when needed are all valid responses." },
  ],
  pinch: [
    { q: "What are the emergency numbers in South Korea?", a: "Korea's emergency numbers: 119 (ambulance + fire), 112 (police), 122 (coast guard). For foreigners: 1345 (Seoul Global Center, multilingual support including English, Chinese, Japanese — 24/7). 1339 is the medical helpline. All emergency services have interpretation support for major languages. Save 1345 in your phone immediately — it's the most important number for foreigners in a non-emergency crisis." },
    { q: "Is South Korea safe for foreigners?", a: "South Korea consistently ranks among the safest countries in the world. Seoul has one of the lowest violent crime rates of any major city globally. Petty crime like pickpocketing is rare compared to European or American cities. The main safety concerns are: occasional protests near Gwanghwamun or the US Embassy, extreme weather (typhoons in summer, heavy snowfall in winter), and air quality (fine dust/미세먼지) from March-May." },
    { q: "What should I know about Korean social etiquette to avoid offending people?", a: "Key cultural norms: (1) Remove shoes when entering someone's home. (2) Pour drinks for others before your own — never pour for yourself first. (3) Use two hands when giving or receiving items. (4) Address older people as 선생님 (teacher) or 어르신 if unsure — never by their first name unless told to. (5) Refuse food or gifts once before accepting — it's polite to decline initially. (6) Don't stick chopsticks upright in a bowl of rice (resembles funeral rites)." },
    { q: "What do I do if I lose my ARC in Korea?", a: "Report the loss to the police first to get a 도난신고서 (theft/loss report). Then visit your nearest Immigration Office (출입국사무소) to apply for a replacement. Bring your passport, the police report, one 3x4cm passport photo, and 30,000 KRW. Processing takes approximately 2-3 weeks. During this period, carry your passport as ID. You can use the HiKorea website (hikorea.go.kr) for some services online." },
    { q: "How do I handle a medical emergency if I don't speak Korean?", a: "Call 119 for an ambulance — they have interpretation services for major languages. Show your phone translator or a medical ID card with your name, blood type, allergies, and medical conditions in Korean. The Seoul Global Center (1345) provides multilingual emergency assistance. Major hospitals like Severance, Asan, and Samsung have 24-hour international patient centers. Have a Korean-speaking contact in your phone under ICE (In Case of Emergency)." },
  ],
};
