export const CULTURE_SHOCK_STAGES = [
  {
    stage: 1,
    nameEn: "The Honeymoon",
    nameKo: "허니문",
    emoji: "🌟",
    timeframeEn: "Weeks 1-4",
    timeframeKo: "1-4주",
    descEn: "Everything is new and exciting. Korean food is amazing, the city is beautiful, every day is an adventure. Euphoric and curious.",
    descKo: "모든 것이 새롭고 흥미롭습니다. 한국 음식도 맛있고, 도시도 아름답고, 매일이 모험. 기쁘고 호기심 가득.",
    signsEn: ["Enthusiastic about everything", "Overlooking difficulties", "Idealized view of Korean culture"],
    signsKo: ["모든 것에 열정적", "어려움을 무시", "한국 문화를 이상화"],
    tipsEn: ["Enjoy it! This is a real phase, not naive", "Take photos, make notes — you'll want to remember this", "Start building routines now while energy is high"],
    tipsKo: ["즐기세요! 이건 진짜 감정입니다", "사진 찍고 기록해두세요", "에너지 높을 때 루틴 만들기 시작"],
  },
  {
    stage: 2,
    nameEn: "The Crash",
    nameKo: "충격",
    emoji: "😤",
    timeframeEn: "Months 1-3",
    timeframeKo: "1-3개월",
    descEn: "Frustrations start building. Language barriers feel insurmountable. Little things irritate you disproportionately. You miss home intensely.",
    descKo: "좌절감이 쌓이기 시작합니다. 언어 장벽이 넘을 수 없이 느껴집니다. 사소한 것들에 과하게 짜증이 납니다. 고향이 몹시 그립습니다.",
    signsEn: ["Irritability and frustration", "Homesickness", "Fatigue and withdrawal", "Feeling stupid or helpless", "Hostility toward Korean culture"],
    signsKo: ["짜증과 좌절감", "향수병", "피로와 위축", "멍청하거나 무력한 느낌", "한국 문화에 대한 적대감"],
    tipsEn: ["This is completely normal. Every expat goes through this.", "Don't isolate — reach out to other expats or KND", "Give yourself permission to be bad at things", "Limit news from home (it amplifies distance)"],
    tipsKo: ["완전히 정상입니다. 모든 외국인이 겪는 단계입니다.", "혼자 있지 마세요. 다른 외국인이나 KND에 연락하세요.", "잘 못해도 괜찮다는 허락을 스스로에게 주세요.", "본국 뉴스 줄이기 (거리감을 증폭시킴)"],
  },
  {
    stage: 3,
    nameEn: "Adjustment",
    nameKo: "적응",
    emoji: "⚖️",
    timeframeEn: "Months 3-6",
    timeframeKo: "3-6개월",
    descEn: "You start navigating Korea more confidently. You have routines. You know your favorite 김밥 spot. The irritations are still there but less overwhelming.",
    descKo: "한국 생활을 더 자신 있게 해나갑니다. 루틴이 생깁니다. 단골 김밥집도 생겼습니다. 짜증은 여전히 있지만 덜 벅차게 느껴집니다.",
    signsEn: ["Building small habits and routines", "Laughing at cultural misunderstandings instead of crying", "Starting to make Korean friends (slowly)", "Reading situations more accurately"],
    signsKo: ["소소한 습관과 루틴 형성", "문화적 오해에 웃을 수 있게 됨", "한국인 친구 생기기 시작 (천천히)", "상황을 더 정확하게 읽기"],
    tipsEn: ["Celebrate small wins", "Keep investing in relationships — they compound over time", "Learn 5 new Korean words per week"],
    tipsKo: ["작은 성공을 축하하세요", "관계에 계속 투자하세요 — 시간이 지나면 더해집니다", "매주 한국어 5단어 배우기"],
  },
  {
    stage: 4,
    nameEn: "Adaptation",
    nameKo: "통합",
    emoji: "🌱",
    timeframeEn: "6+ months",
    timeframeKo: "6개월 이상",
    descEn: "Korea feels like a second home. You have Korean friends. You navigate the city effortlessly. You might even start explaining things to newer arrivals.",
    descKo: "한국이 제2의 고향처럼 느껴집니다. 한국인 친구도 생겼습니다. 도시를 자유롭게 다닙니다. 이제 다른 신규 외국인에게 설명해주기도 합니다.",
    signsEn: ["Thinking of Korea as 'home'", "Picking up Korean slang naturally", "Being the one who 'knows Korea' in your friend group", "Missing Korean things when you travel abroad"],
    signsKo: ["한국을 '집'으로 생각", "한국어 슬랭이 자연스럽게 나옴", "친구들 중 '한국 잘 아는 사람'이 됨", "해외 여행 시 한국 것들이 그리워짐"],
    tipsEn: ["This isn't the end — expat life has its own unique ongoing challenges", "Stay connected to the expat community even as you integrate"],
    tipsKo: ["이게 끝이 아닙니다 — 외국인 생활만의 지속적인 어려움이 있습니다", "통합되면서도 외국인 커뮤니티와 연결 유지"],
  },
];

export const THERAPISTS = [
  {
    name: "Seoul Foreign Language Medical Service",
    nameKo: "서울 외국어 의료 서비스",
    type: "Counseling referral",
    typeKo: "상담 연결 서비스",
    languages: ["English", "Chinese", "Japanese", "French"],
    locationEn: "Seoul Global Center, Jongno-gu",
    locationKo: "서울글로벌센터, 종로구",
    lat: 37.5762,
    lng: 126.9780,
    priceRangeEn: "Free - paid options",
    priceRangeKo: "무료~유료",
    descEn: "The Seoul Global Center provides free mental health consultations and referrals to English-speaking therapists. A great first point of contact.",
    descKo: "서울글로벌센터는 무료 정신 건강 상담 및 영어 가능 치료사 연결 서비스를 제공합니다.",
    contact: "02-2075-4180",
    website: "global.seoul.go.kr",
  },
  {
    name: "Maum Psychological Counseling",
    nameKo: "마음 심리상담센터",
    type: "Individual therapy",
    typeKo: "개인 심리상담",
    languages: ["English", "Korean"],
    locationEn: "Mapo-gu, Seoul",
    locationKo: "서울 마포구",
    lat: 37.5519,
    lng: 126.9246,
    priceRangeEn: "₩80,000–₩120,000/session",
    priceRangeKo: "회당 80,000~120,000원",
    descEn: "English-speaking Korean therapists specializing in expat adjustment, relationship issues, and anxiety. Warm, holistic approach.",
    descKo: "영어 가능 한국인 치료사. 외국인 적응, 관계 문제, 불안 전문. 따뜻하고 전인적 접근.",
    contact: "Available via website",
    website: "Naver search: 마음 심리상담센터 영어",
  },
  {
    name: "Korea Association for Spiritual, Ethical & Religious Issues in Counseling (KASERIC)",
    nameKo: "KASERIC",
    type: "Counseling network",
    typeKo: "상담사 네트워크",
    languages: ["English", "Multiple"],
    locationEn: "Various locations, Seoul",
    locationKo: "서울 내 다양한 장소",
    lat: 37.5665,
    lng: 126.9780,
    priceRangeEn: "Varies by therapist",
    priceRangeKo: "치료사에 따라 상이",
    descEn: "Network of English-speaking counselors and therapists in Korea. Can help find the right fit for your needs.",
    descKo: "한국 내 영어 가능 상담사 네트워크. 필요에 맞는 치료사 매칭 가능.",
    contact: "kaseric.org",
    website: "kaseric.org",
  },
  {
    name: "Online Therapy (BetterHelp / Talkspace)",
    nameKo: "온라인 상담 (해외)",
    type: "Online therapy",
    typeKo: "온라인 상담",
    languages: ["English", "Multiple"],
    locationEn: "Online, available in Korea",
    locationKo: "온라인, 한국에서 이용 가능",
    lat: 37.5665,
    lng: 126.9780,
    priceRangeEn: "~$60–$100/week",
    priceRangeKo: "주당 약 $60~$100",
    descEn: "BetterHelp and Talkspace are US-based platforms accessible from Korea. Good for those who want a therapist from their home country or culture.",
    descKo: "미국 기반 플랫폼으로 한국에서도 이용 가능. 본국 문화권 치료사를 원하는 경우 적합.",
    contact: "betterhelp.com / talkspace.com",
    website: "betterhelp.com",
  },
  {
    name: "IAAP (International Assistance & Advice Program)",
    nameKo: "국제 지원 상담 프로그램",
    type: "Support program",
    typeKo: "지원 프로그램",
    languages: ["English"],
    locationEn: "Itaewon / Online",
    locationKo: "이태원 / 온라인",
    lat: 37.5345,
    lng: 126.9947,
    priceRangeEn: "Low-cost sliding scale",
    priceRangeKo: "저비용 차등 요금제",
    descEn: "English-language support groups and individual counseling for foreigners in Korea. Focuses on adjustment issues.",
    descKo: "한국 내 외국인을 위한 영어 지원 그룹 및 개인 상담. 적응 문제 중점.",
    contact: "Search 'IAAP Korea' on Facebook",
    website: "Facebook group",
  },
];

export const CRISIS_RESOURCES = [
  {
    emoji: "🚨",
    name: "Emergency (Police / Ambulance)",
    nameKo: "긴급 (경찰/구급)",
    number: "112 / 119",
    descEn: "Call 112 for police, 119 for fire and ambulance. English interpretation available — ask for '영어 통역' (yeongeo tong-yeok).",
    descKo: "경찰 112, 소방/구급 119. 영어 통역 서비스: '영어 통역'이라고 말하세요.",
    available: "24/7",
  },
  {
    emoji: "💚",
    name: "Korea Suicide Prevention Hotline",
    nameKo: "자살 예방 상담 전화",
    number: "1393",
    descEn: "Free, 24/7 mental health crisis line. English interpretation available. Call if you are in crisis or concerned about someone.",
    descKo: "무료 24시간 정신 건강 위기상담 전화. 영어 통역 가능. 위기 상황이거나 주변이 걱정될 때 전화하세요.",
    available: "24/7",
  },
  {
    emoji: "📞",
    name: "Seoul Mental Health Welfare Center",
    nameKo: "서울시 정신건강 복지센터",
    number: "02-3444-9934",
    descEn: "Seoul's mental health service. Can refer you to English-speaking professionals. Consultation available.",
    descKo: "서울시 정신건강 서비스. 영어 가능 전문가 연결 가능. 상담 서비스 제공.",
    available: "Weekdays 9am-6pm",
  },
  {
    emoji: "🌍",
    name: "Seoul Global Center",
    nameKo: "서울글로벌센터",
    number: "02-2075-4180",
    descEn: "Free consultation for foreigners in Seoul. English, Chinese, Japanese, French. Can help with mental health referrals.",
    descKo: "서울 거주 외국인 무료 상담. 영어, 중국어, 일본어, 프랑스어 지원. 정신 건강 연결 가능.",
    available: "Mon-Fri 9am-6pm",
  },
];

export const SUPPORT_GROUPS = [
  { nameEn: "KND (Koreans Next Door)", nameKo: "코리안스 넥스트 도어", descEn: "Our own community. Language exchanges, events, and genuine connection with Korean locals. The real neighbor experience.", descKo: "우리 커뮤니티. 언어 교환, 이벤트, 한국인 이웃과의 진짜 연결.", contact: "Instagram: @koreans.next.door" },
  { nameEn: "Expats in Seoul (Facebook)", nameKo: "서울 외국인 (페이스북)", descEn: "Largest English-speaking expat group in Seoul. Active community with events, advice, and housing listings.", descKo: "서울 최대 영어권 외국인 그룹. 이벤트, 조언, 주거 정보 활발.", contact: "Facebook: 'Expats in Seoul'" },
  { nameEn: "AA / NA Seoul", nameKo: "AA/NA 서울", descEn: "English-language Alcoholics Anonymous and Narcotics Anonymous meetings in Seoul. Schedule and locations on aa-korea.org.", descKo: "서울 영어 익명 알코올/마약 중독자 모임. aa-korea.org에서 일정 확인.", contact: "aa-korea.org" },
  { nameEn: "InterNations Seoul", nameKo: "인터네이션스 서울", descEn: "Professional expat networking group. Monthly events, activity groups (hiking, cooking, language). Good for meeting people when you first arrive.", descKo: "전문직 외국인 네트워킹 그룹. 월례 이벤트, 활동 그룹(등산, 요리, 언어).", contact: "internations.org/seoul-expats" },
];

export const SELF_CARE_TIPS = [
  { emoji: "🏃", tipEn: "Move your body", tipKo: "몸을 움직이세요", descEn: "Korea has incredible hiking right in the city (Bukhansan, Gwanaksan, Namsan). Local gyms (헬스장) are cheap (₩30-60K/month). Physical activity is the most proven antidepressant.", descKo: "도심 속 좋은 등산로 (북한산, 관악산, 남산). 동네 헬스장 저렴 (월 3-6만원). 신체 활동은 가장 검증된 항우울제입니다." },
  { emoji: "😴", tipEn: "Sleep consistently", tipKo: "규칙적인 수면", descEn: "Irregular sleep destroys mental health. Seoul's 24/7 culture makes it easy to stay up too late. Protect your sleep schedule like your life depends on it — because it kind of does.", descKo: "불규칙한 수면은 정신 건강을 해칩니다. 서울의 24시간 문화에 야행성이 되기 쉽습니다. 수면 패턴을 지키세요." },
  { emoji: "☕", tipEn: "Create a 'home base'", tipKo: "'홈베이스' 만들기", descEn: "Find one café, one restaurant, one neighborhood where you feel at ease. Regularity reduces isolation. Korean café culture is perfect for this — your 단골 (regular spot) becomes an anchor.", descKo: "편안한 카페, 식당, 동네를 만드세요. 규칙성이 고립감을 줄입니다. 한국의 카페 문화에서 단골이 되는 것이 닻이 됩니다." },
  { emoji: "✉️", tipEn: "Stay connected to home (but not obsessively)", tipKo: "고향과 연결 유지 (과도하지 않게)", descEn: "Regular calls with family and close friends are important. But doom-scrolling your home country's news or social media at 2am will make you feel worse. Curate your connection.", descKo: "가족, 친한 친구와 정기적인 통화 중요. 하지만 새벽 2시에 본국 뉴스나 SNS를 무한 스크롤하면 더 힘들어집니다. 연결을 조율하세요." },
  { emoji: "🇰🇷", tipEn: "Learn some Korean (seriously)", tipKo: "진짜로 한국어 배우기", descEn: "Even 100 words of Korean massively reduces isolation. Being able to order food yourself, joke with a taxi driver, or read a sign — it changes how you feel about being here. It's also deeply respected by Koreans.", descKo: "한국어 단어 100개만 알아도 고립감이 확 줄어듭니다. 혼자 음식 주문하고, 택시 기사와 농담하고, 간판 읽기 — 여기 있는 느낌이 달라집니다. 한국인들도 매우 좋아합니다." },
];
