// lib/phrasebookData.ts

export interface PhraseCategory {
  id: string;
  nameEn: string;
  nameKo: string;
  emoji: string;
  descEn: string;
  descKo: string;
}

export interface Phrase {
  id: string;
  categoryId: string;
  korean: string;
  romanization: string;
  english: string;
  contextEn: string;
  contextKo: string;
  priority: "essential" | "useful" | "bonus";
}

export const CATEGORIES: PhraseCategory[] = [
  {
    id: "hospital",
    nameEn: "At the Hospital",
    nameKo: "병원에서",
    emoji: "🏥",
    descEn: "Describe symptoms, ask about insurance, request prescriptions",
    descKo: "증상 설명, 보험 문의, 처방 요청",
  },
  {
    id: "pharmacy",
    nameEn: "At the Pharmacy",
    nameKo: "약국에서",
    emoji: "💊",
    descEn: "Ask for medicine, describe symptoms, request refills",
    descKo: "약 구입, 증상 설명, 재처방 요청",
  },
  {
    id: "bank",
    nameEn: "At the Bank",
    nameKo: "은행에서",
    emoji: "🏦",
    descEn: "Open accounts, transfer money, ask about your card",
    descKo: "계좌 개설, 송금, 카드 문의",
  },
  {
    id: "landlord",
    nameEn: "With Your Landlord",
    nameKo: "집주인과",
    emoji: "🔑",
    descEn: "Maintenance requests, contract questions, moving out",
    descKo: "수리 요청, 계약 문의, 이사",
  },
  {
    id: "immigration",
    nameEn: "At Immigration",
    nameKo: "출입국에서",
    emoji: "📋",
    descEn: "ARC questions, visa extensions, documents",
    descKo: "외국인등록증, 비자 연장, 서류",
  },
  {
    id: "restaurant",
    nameEn: "At a Restaurant",
    nameKo: "식당에서",
    emoji: "🍽️",
    descEn: "Order food, ask about ingredients, dietary restrictions",
    descKo: "음식 주문, 재료 문의, 식이 제한",
  },
  {
    id: "shopping",
    nameEn: "Shopping",
    nameKo: "쇼핑",
    emoji: "🛍️",
    descEn: "Ask for help, check sizes, returns and exchanges",
    descKo: "도움 요청, 사이즈 확인, 교환/환불",
  },
  {
    id: "taxi",
    nameEn: "In a Taxi / Bus",
    nameKo: "택시/버스에서",
    emoji: "🚕",
    descEn: "Give directions, ask the driver to stop, payment",
    descKo: "길 안내, 정차 요청, 결제",
  },
  {
    id: "emergency",
    nameEn: "Emergency Situations",
    nameKo: "긴급 상황",
    emoji: "🚨",
    descEn: "Critical phrases for accidents, theft, getting lost",
    descKo: "사고, 도난, 길을 잃었을 때",
  },
  {
    id: "daily",
    nameEn: "Everyday Korean",
    nameKo: "일상 한국어",
    emoji: "☀️",
    descEn: "Greetings, polite phrases, asking for help",
    descKo: "인사, 예의 표현, 도움 요청",
  },
];

export const PHRASES: Phrase[] = [
  // ─── HOSPITAL ───────────────────────────────────────────────────────────────
  {
    id: "h-01",
    categoryId: "hospital",
    korean: "머리가 아파요",
    romanization: "Meori-ga apayo",
    english: "I have a headache",
    contextEn: "When describing head pain to the doctor",
    contextKo: "두통을 설명할 때",
    priority: "essential",
  },
  {
    id: "h-02",
    categoryId: "hospital",
    korean: "열이 있어요",
    romanization: "Yeori isseoyo",
    english: "I have a fever",
    contextEn: "When checking in with a fever",
    contextKo: "발열 증상으로 접수할 때",
    priority: "essential",
  },
  {
    id: "h-03",
    categoryId: "hospital",
    korean: "배가 아파요",
    romanization: "Baega apayo",
    english: "I have a stomachache",
    contextEn: "For stomach or abdominal pain",
    contextKo: "복통을 호소할 때",
    priority: "essential",
  },
  {
    id: "h-04",
    categoryId: "hospital",
    korean: "기침이 나요",
    romanization: "Gichimi nayo",
    english: "I'm coughing",
    contextEn: "Describing cough symptoms to the doctor",
    contextKo: "기침 증상을 설명할 때",
    priority: "essential",
  },
  {
    id: "h-05",
    categoryId: "hospital",
    korean: "어지러워요",
    romanization: "Eojireowoyo",
    english: "I feel dizzy",
    contextEn: "Reporting dizziness or vertigo",
    contextKo: "어지럼증을 호소할 때",
    priority: "essential",
  },
  {
    id: "h-06",
    categoryId: "hospital",
    korean: "알레르기가 있어요",
    romanization: "Allereugi-ga isseoyo",
    english: "I have allergies",
    contextEn: "General allergy declaration before treatment",
    contextKo: "치료 전 알레르기를 알릴 때",
    priority: "essential",
  },
  {
    id: "h-07",
    categoryId: "hospital",
    korean: "페니실린에 알레르기가 있어요",
    romanization: "Penisyllin-e allereugi-ga isseoyo",
    english: "I'm allergic to penicillin",
    contextEn: "Replace 'penicillin' with your specific allergy",
    contextKo: "'페니실린' 자리에 본인 알레르기 항목을 넣으세요",
    priority: "essential",
  },
  {
    id: "h-08",
    categoryId: "hospital",
    korean: "건강보험이 있어요",
    romanization: "Geongang-boheomi isseoyo",
    english: "I have health insurance",
    contextEn: "When checking in at reception",
    contextKo: "접수 시 보험 여부를 알릴 때",
    priority: "essential",
  },
  {
    id: "h-09",
    categoryId: "hospital",
    korean: "처방전이 필요해요",
    romanization: "Cheobangjeoni piryohaeyo",
    english: "I need a prescription",
    contextEn: "Requesting a written prescription",
    contextKo: "처방전 발급을 요청할 때",
    priority: "essential",
  },
  {
    id: "h-10",
    categoryId: "hospital",
    korean: "약이 떨어졌어요",
    romanization: "Yagi tteorojyeosseoyo",
    english: "I've run out of medicine",
    contextEn: "When needing a refill of existing medication",
    contextKo: "기존 약을 다 먹고 재처방이 필요할 때",
    priority: "useful",
  },
  {
    id: "h-11",
    categoryId: "hospital",
    korean: "영어 하시는 선생님 계세요?",
    romanization: "Yeongeo hasineun seonsaengnim gyeseyo?",
    english: "Is there a doctor who speaks English?",
    contextEn: "Finding an English-speaking doctor at the clinic",
    contextKo: "영어 가능한 의사 선생님을 찾을 때",
    priority: "essential",
  },
  {
    id: "h-12",
    categoryId: "hospital",
    korean: "몇 번이나 먹어야 해요?",
    romanization: "Myeot beon-ina meogeoya haeyo?",
    english: "How many times do I take this?",
    contextEn: "Asking about medication dosage frequency",
    contextKo: "복용 횟수를 확인할 때",
    priority: "useful",
  },
  {
    id: "h-13",
    categoryId: "hospital",
    korean: "언제 다시 와야 해요?",
    romanization: "Eonje dasi waya haeyo?",
    english: "When do I need to come back?",
    contextEn: "Asking about follow-up appointments",
    contextKo: "재진 일정을 확인할 때",
    priority: "useful",
  },
  {
    id: "h-14",
    categoryId: "hospital",
    korean: "이 증상이 심각한가요?",
    romanization: "I jeungsang-i simgak-hangayo?",
    english: "Is this serious?",
    contextEn: "Checking how serious your condition is",
    contextKo: "증상의 심각도를 확인할 때",
    priority: "useful",
  },
  {
    id: "h-15",
    categoryId: "hospital",
    korean: "수술이 필요한가요?",
    romanization: "Susuri piryohangayo?",
    english: "Do I need surgery?",
    contextEn: "When a serious diagnosis may require surgery",
    contextKo: "수술 여부를 물을 때",
    priority: "useful",
  },
  {
    id: "h-16",
    categoryId: "hospital",
    korean: "진통제 주세요",
    romanization: "Jintongje juseyo",
    english: "Please give me painkillers",
    contextEn: "Requesting pain relief medication",
    contextKo: "진통제를 요청할 때",
    priority: "useful",
  },
  {
    id: "h-17",
    categoryId: "hospital",
    korean: "피검사는 어디서 해요?",
    romanization: "Pigeomsa-neun eodiseo haeyo?",
    english: "Where do I get blood drawn?",
    contextEn: "Finding the lab for blood tests",
    contextKo: "채혈실 위치를 물을 때",
    priority: "bonus",
  },
  {
    id: "h-18",
    categoryId: "hospital",
    korean: "영수증 주세요",
    romanization: "Yeongsujeung juseyo",
    english: "Please give me a receipt",
    contextEn: "For insurance reimbursement claims",
    contextKo: "보험 청구를 위한 영수증을 요청할 때",
    priority: "useful",
  },
  {
    id: "h-19",
    categoryId: "hospital",
    korean: "얼마예요?",
    romanization: "Eolmaeyo?",
    english: "How much is it?",
    contextEn: "Asking the cost of treatment or consultation",
    contextKo: "진료비를 물을 때",
    priority: "essential",
  },
  {
    id: "h-20",
    categoryId: "hospital",
    korean: "다음 예약이 언제예요?",
    romanization: "Daeum yeyak-i eonjeye-yo?",
    english: "When is my next appointment?",
    contextEn: "Confirming or scheduling a follow-up visit",
    contextKo: "다음 진료 예약 일정을 확인할 때",
    priority: "useful",
  },

  // ─── PHARMACY ────────────────────────────────────────────────────────────────
  {
    id: "ph-01",
    categoryId: "pharmacy",
    korean: "감기약 있어요?",
    romanization: "Gamgiyak isseoyo?",
    english: "Do you have cold medicine?",
    contextEn: "Asking for over-the-counter cold medicine",
    contextKo: "감기약을 찾을 때",
    priority: "essential",
  },
  {
    id: "ph-02",
    categoryId: "pharmacy",
    korean: "소화제 주세요",
    romanization: "Sohwaje juseyo",
    english: "Please give me digestive medicine",
    contextEn: "For stomachaches or indigestion",
    contextKo: "소화불량이나 복통이 있을 때",
    priority: "essential",
  },
  {
    id: "ph-03",
    categoryId: "pharmacy",
    korean: "진통제 추천해 주세요",
    romanization: "Jintongje chucheonhae juseyo",
    english: "Please recommend a painkiller",
    contextEn: "Asking the pharmacist to suggest a pain reliever",
    contextKo: "진통제 추천을 요청할 때",
    priority: "essential",
  },
  {
    id: "ph-04",
    categoryId: "pharmacy",
    korean: "이게 뭐예요?",
    romanization: "Ige mwoyeyo?",
    english: "What is this?",
    contextEn: "When handed an unfamiliar medicine",
    contextKo: "모르는 약을 받았을 때",
    priority: "essential",
  },
  {
    id: "ph-05",
    categoryId: "pharmacy",
    korean: "이 약 어떻게 먹어요?",
    romanization: "I yak eotteoke meogeyo?",
    english: "How do I take this medicine?",
    contextEn: "Asking for usage instructions",
    contextKo: "복용 방법을 물을 때",
    priority: "essential",
  },
  {
    id: "ph-06",
    categoryId: "pharmacy",
    korean: "식전에 먹어요, 식후에 먹어요?",
    romanization: "Sikjeone meogeyo, sikhue meogeyo?",
    english: "Before or after meals?",
    contextEn: "Clarifying when to take medication relative to meals",
    contextKo: "식전/식후 복용 여부를 확인할 때",
    priority: "useful",
  },
  {
    id: "ph-07",
    categoryId: "pharmacy",
    korean: "부작용이 있나요?",
    romanization: "Bujagyong-i innayo?",
    english: "Are there side effects?",
    contextEn: "Checking for potential side effects before taking medication",
    contextKo: "부작용 여부를 확인할 때",
    priority: "useful",
  },
  {
    id: "ph-08",
    categoryId: "pharmacy",
    korean: "처방전 없이 살 수 있어요?",
    romanization: "Cheobangjeone eopsi sal su isseoyo?",
    english: "Can I buy this without a prescription?",
    contextEn: "Checking if a medicine is available over-the-counter",
    contextKo: "처방전 없이 구매 가능한지 확인할 때",
    priority: "useful",
  },
  {
    id: "ph-09",
    categoryId: "pharmacy",
    korean: "영양제 추천해 주세요",
    romanization: "Yeongyangjje chucheonhae juseyo",
    english: "Please recommend vitamins or supplements",
    contextEn: "Asking the pharmacist for supplement advice",
    contextKo: "영양제 추천을 요청할 때",
    priority: "bonus",
  },
  {
    id: "ph-10",
    categoryId: "pharmacy",
    korean: "반창고 있어요?",
    romanization: "Banchanggo isseoyo?",
    english: "Do you have bandages?",
    contextEn: "Finding first aid supplies",
    contextKo: "반창고나 응급처치 용품을 찾을 때",
    priority: "useful",
  },
  {
    id: "ph-11",
    categoryId: "pharmacy",
    korean: "더 강한 약 있어요?",
    romanization: "Deo ganghan yak isseoyo?",
    english: "Do you have something stronger?",
    contextEn: "When current medicine isn't working well enough",
    contextKo: "효과가 부족할 때 더 강한 약을 요청할 때",
    priority: "useful",
  },
  {
    id: "ph-12",
    categoryId: "pharmacy",
    korean: "어린이용 있어요?",
    romanization: "Eorini-yong isseoyo?",
    english: "Do you have a children's version?",
    contextEn: "Finding medicine formulated for kids",
    contextKo: "어린이용 약을 찾을 때",
    priority: "useful",
  },
  {
    id: "ph-13",
    categoryId: "pharmacy",
    korean: "임산부도 먹을 수 있어요?",
    romanization: "Imsanbuedo meogeul su isseoyo?",
    english: "Is it safe for pregnant women?",
    contextEn: "Checking pregnancy safety before taking medication",
    contextKo: "임산부 복용 가능 여부를 확인할 때",
    priority: "useful",
  },
  {
    id: "ph-14",
    categoryId: "pharmacy",
    korean: "언제까지 먹어야 해요?",
    romanization: "Eonjekkaji meogeoya haeyo?",
    english: "Until when should I take this?",
    contextEn: "Asking about the duration of treatment",
    contextKo: "복용 기간을 확인할 때",
    priority: "useful",
  },
  {
    id: "ph-15",
    categoryId: "pharmacy",
    korean: "두통약 주세요",
    romanization: "Dutongyak juseyo",
    english: "Please give me headache medicine",
    contextEn: "Requesting medicine specifically for headaches",
    contextKo: "두통약을 요청할 때",
    priority: "essential",
  },

  // ─── BANK ─────────────────────────────────────────────────────────────────────
  {
    id: "bk-01",
    categoryId: "bank",
    korean: "통장을 만들고 싶어요",
    romanization: "Tongjang-eul mandeulgo sipeoyo",
    english: "I want to open a bank account",
    contextEn: "Starting the account opening process",
    contextKo: "계좌를 개설하러 왔을 때",
    priority: "essential",
  },
  {
    id: "bk-02",
    categoryId: "bank",
    korean: "외국인도 계좌를 만들 수 있어요?",
    romanization: "Oegugin-do gyejwa-reul mandeul su isseoyo?",
    english: "Can foreigners open a bank account?",
    contextEn: "Checking eligibility as a foreign national",
    contextKo: "외국인의 계좌 개설 가능 여부를 확인할 때",
    priority: "essential",
  },
  {
    id: "bk-03",
    categoryId: "bank",
    korean: "외국인등록증 가져왔어요",
    romanization: "Oegugin-deungnokjeung gajyeowasseoyo",
    english: "I brought my ARC (Alien Registration Card)",
    contextEn: "Presenting your ID document when opening an account",
    contextKo: "신분증으로 외국인등록증을 제시할 때",
    priority: "essential",
  },
  {
    id: "bk-04",
    categoryId: "bank",
    korean: "카드 신청하고 싶어요",
    romanization: "Kadeu sincheonghago sipeoyo",
    english: "I want to apply for a card",
    contextEn: "Requesting a bank card (debit or credit)",
    contextKo: "카드를 신청할 때",
    priority: "essential",
  },
  {
    id: "bk-05",
    categoryId: "bank",
    korean: "체크카드요, 신용카드요?",
    romanization: "Chekeu-kadeuyo, sinyong-kadeuyo?",
    english: "Debit card or credit card?",
    contextEn: "Clarifying which type of card you want",
    contextKo: "카드 종류를 구분할 때",
    priority: "useful",
  },
  {
    id: "bk-06",
    categoryId: "bank",
    korean: "해외 송금을 하고 싶어요",
    romanization: "Haewoe songgeum-eul hago sipeoyo",
    english: "I want to send money abroad",
    contextEn: "Initiating an international wire transfer",
    contextKo: "해외로 송금하고 싶을 때",
    priority: "essential",
  },
  {
    id: "bk-07",
    categoryId: "bank",
    korean: "얼마까지 송금할 수 있어요?",
    romanization: "Eolmakkaji songgeumhal su isseoyo?",
    english: "What is the transfer limit?",
    contextEn: "Asking about maximum transfer amounts",
    contextKo: "송금 한도를 확인할 때",
    priority: "useful",
  },
  {
    id: "bk-08",
    categoryId: "bank",
    korean: "수수료가 얼마예요?",
    romanization: "Susuryo-ga eolmaeyo?",
    english: "What is the fee?",
    contextEn: "Asking about transaction fees",
    contextKo: "수수료를 확인할 때",
    priority: "useful",
  },
  {
    id: "bk-09",
    categoryId: "bank",
    korean: "카드가 안 돼요",
    romanization: "Kadeuga an dwaeyo",
    english: "My card doesn't work",
    contextEn: "Reporting a card that's not functioning",
    contextKo: "카드가 작동하지 않을 때",
    priority: "essential",
  },
  {
    id: "bk-10",
    categoryId: "bank",
    korean: "카드를 잃어버렸어요",
    romanization: "Kadeu-reul ireobeoryeosseoyo",
    english: "I lost my card",
    contextEn: "Reporting a lost card for cancellation",
    contextKo: "분실 카드를 신고할 때",
    priority: "essential",
  },
  {
    id: "bk-11",
    categoryId: "bank",
    korean: "인터넷 뱅킹을 신청하고 싶어요",
    romanization: "Inteonet baengking-eul sincheonghago sipeoyo",
    english: "I want to set up internet banking",
    contextEn: "Enrolling in online banking services",
    contextKo: "인터넷 뱅킹 신청을 할 때",
    priority: "useful",
  },
  {
    id: "bk-12",
    categoryId: "bank",
    korean: "계좌번호를 알려주세요",
    romanization: "Gyejwabeonho-reul allyeojuseyo",
    english: "Please tell me the account number",
    contextEn: "Getting your account number after opening",
    contextKo: "계좌번호를 확인할 때",
    priority: "useful",
  },
  {
    id: "bk-13",
    categoryId: "bank",
    korean: "잔액이 얼마예요?",
    romanization: "Janaegi eolmaeyo?",
    english: "What is my balance?",
    contextEn: "Checking your current account balance",
    contextKo: "잔액을 확인할 때",
    priority: "essential",
  },
  {
    id: "bk-14",
    categoryId: "bank",
    korean: "영어로 된 서류가 있어요?",
    romanization: "Yeongeo-ro doen seoryuga isseoyo?",
    english: "Is there an English form?",
    contextEn: "Asking for forms in English",
    contextKo: "영문 서류가 있는지 물을 때",
    priority: "useful",
  },
  {
    id: "bk-15",
    categoryId: "bank",
    korean: "ATM 어디 있어요?",
    romanization: "ATM eodi isseoyo?",
    english: "Where is the ATM?",
    contextEn: "Finding the nearest ATM in the bank",
    contextKo: "ATM 위치를 물을 때",
    priority: "essential",
  },
  {
    id: "bk-16",
    categoryId: "bank",
    korean: "환전하고 싶어요",
    romanization: "Hwaenjeonhago sipeoyo",
    english: "I want to exchange currency",
    contextEn: "Exchanging foreign currency to Korean won",
    contextKo: "환전을 요청할 때",
    priority: "essential",
  },
  {
    id: "bk-17",
    categoryId: "bank",
    korean: "오늘 환율이 어떻게 돼요?",
    romanization: "Oneul hwanyul-i eotteoke dwaeyo?",
    english: "What is today's exchange rate?",
    contextEn: "Checking the current exchange rate",
    contextKo: "오늘의 환율을 확인할 때",
    priority: "useful",
  },
  {
    id: "bk-18",
    categoryId: "bank",
    korean: "통장을 해지하고 싶어요",
    romanization: "Tongjang-eul hejihago sipeoyo",
    english: "I want to close my account",
    contextEn: "When you want to close a bank account",
    contextKo: "계좌를 해지하고 싶을 때",
    priority: "bonus",
  },
  {
    id: "bk-19",
    categoryId: "bank",
    korean: "비밀번호를 바꾸고 싶어요",
    romanization: "Bimilbeonho-reul bakkugo sipeoyo",
    english: "I want to change my PIN",
    contextEn: "Requesting a PIN change at the bank",
    contextKo: "비밀번호 변경을 요청할 때",
    priority: "useful",
  },
  {
    id: "bk-20",
    categoryId: "bank",
    korean: "이체 내역을 확인하고 싶어요",
    romanization: "Iche naeyeok-eul hwagin-hago sipeoyo",
    english: "I want to check my transaction history",
    contextEn: "Reviewing past transactions",
    contextKo: "거래 내역을 확인하고 싶을 때",
    priority: "bonus",
  },

  // ─── LANDLORD ─────────────────────────────────────────────────────────────────
  {
    id: "ll-01",
    categoryId: "landlord",
    korean: "수리가 필요해요",
    romanization: "Suriga piryohaeyo",
    english: "I need a repair",
    contextEn: "General maintenance request to your landlord",
    contextKo: "수리를 요청할 때",
    priority: "essential",
  },
  {
    id: "ll-02",
    categoryId: "landlord",
    korean: "뜨거운 물이 안 나와요",
    romanization: "Tteugeoun mul-i an nawayo",
    english: "There's no hot water",
    contextEn: "Reporting a hot water problem",
    contextKo: "온수가 나오지 않을 때",
    priority: "essential",
  },
  {
    id: "ll-03",
    categoryId: "landlord",
    korean: "에어컨이 고장났어요",
    romanization: "Eeokon-i gojang-nasseoyo",
    english: "The air conditioner is broken",
    contextEn: "Reporting a broken AC unit",
    contextKo: "에어컨 고장을 신고할 때",
    priority: "essential",
  },
  {
    id: "ll-04",
    categoryId: "landlord",
    korean: "화장실이 막혔어요",
    romanization: "Hwajangsil-i mak-hyeosseoyo",
    english: "The toilet is clogged",
    contextEn: "Reporting a plumbing blockage",
    contextKo: "변기가 막혔을 때",
    priority: "essential",
  },
  {
    id: "ll-05",
    categoryId: "landlord",
    korean: "냉장고가 고장났어요",
    romanization: "Naengjanggo-ga gojang-nasseoyo",
    english: "The refrigerator is broken",
    contextEn: "Reporting a broken appliance",
    contextKo: "냉장고 고장을 신고할 때",
    priority: "useful",
  },
  {
    id: "ll-06",
    categoryId: "landlord",
    korean: "이사 나가고 싶어요",
    romanization: "Isa nagago sipeoyo",
    english: "I want to move out",
    contextEn: "Notifying the landlord of your intention to move",
    contextKo: "이사 의사를 알릴 때",
    priority: "essential",
  },
  {
    id: "ll-07",
    categoryId: "landlord",
    korean: "언제까지 알려줘야 해요?",
    romanization: "Eonjekkaji allyeojwoya haeyo?",
    english: "How far in advance do I need to tell you?",
    contextEn: "Asking about the required notice period",
    contextKo: "사전 통보 기간을 확인할 때",
    priority: "useful",
  },
  {
    id: "ll-08",
    categoryId: "landlord",
    korean: "보증금은 언제 돌려줘요?",
    romanization: "Bojeunggeum-eun eonje dollyeojwayo?",
    english: "When will you return my deposit?",
    contextEn: "Asking when to expect the deposit refund",
    contextKo: "보증금 반환 시기를 물을 때",
    priority: "essential",
  },
  {
    id: "ll-09",
    categoryId: "landlord",
    korean: "관리비가 왜 이렇게 높아요?",
    romanization: "Gwallibili wae ireoke nopayo?",
    english: "Why is the maintenance fee so high?",
    contextEn: "Questioning an unexpectedly high maintenance fee",
    contextKo: "관리비가 높을 때 이의를 제기할 때",
    priority: "useful",
  },
  {
    id: "ll-10",
    categoryId: "landlord",
    korean: "계약을 연장하고 싶어요",
    romanization: "Gyeyak-eul yeonjang-hago sipeoyo",
    english: "I want to extend the contract",
    contextEn: "Requesting a lease renewal",
    contextKo: "임대 계약 연장을 요청할 때",
    priority: "essential",
  },
  {
    id: "ll-11",
    categoryId: "landlord",
    korean: "계약서를 한 부 더 주세요",
    romanization: "Gyeyaksseo-reul han bu deo juseyo",
    english: "Please give me another copy of the contract",
    contextEn: "Requesting an extra copy of your lease agreement",
    contextKo: "계약서 사본을 추가로 요청할 때",
    priority: "useful",
  },
  {
    id: "ll-12",
    categoryId: "landlord",
    korean: "이웃이 너무 시끄러워요",
    romanization: "Iwut-i neomu sikkeureowoyo",
    english: "The neighbors are too loud",
    contextEn: "Filing a noise complaint with the landlord",
    contextKo: "층간 소음 문제를 알릴 때",
    priority: "useful",
  },
  {
    id: "ll-13",
    categoryId: "landlord",
    korean: "가스 냄새가 나요",
    romanization: "Gaseu naemsaega nayo",
    english: "I smell gas",
    contextEn: "Urgent — report a potential gas leak immediately",
    contextKo: "가스 누출이 의심될 때 — 즉시 신고하세요",
    priority: "essential",
  },
  {
    id: "ll-14",
    categoryId: "landlord",
    korean: "보일러가 고장났어요",
    romanization: "Boilleoga gojang-nasseoyo",
    english: "The boiler / heating is broken",
    contextEn: "Reporting a broken heating system",
    contextKo: "보일러 고장을 신고할 때",
    priority: "essential",
  },
  {
    id: "ll-15",
    categoryId: "landlord",
    korean: "인터넷이 안 돼요",
    romanization: "Inteonesi an dwaeyo",
    english: "The internet doesn't work",
    contextEn: "Reporting an internet outage in your unit",
    contextKo: "인터넷이 작동하지 않을 때",
    priority: "useful",
  },

  // ─── IMMIGRATION ──────────────────────────────────────────────────────────────
  {
    id: "im-01",
    categoryId: "immigration",
    korean: "외국인등록증을 신청하러 왔어요",
    romanization: "Oegugin-deungnokjeung-eul sincheongharyeo wasseoyo",
    english: "I came to apply for my ARC",
    contextEn: "Starting the Alien Registration Card application",
    contextKo: "외국인등록증 신청을 시작할 때",
    priority: "essential",
  },
  {
    id: "im-02",
    categoryId: "immigration",
    korean: "예약을 했어요",
    romanization: "Yeyak-eul haesseoyo",
    english: "I have an appointment",
    contextEn: "Confirming your pre-booked appointment",
    contextKo: "사전 예약을 확인시킬 때",
    priority: "essential",
  },
  {
    id: "im-03",
    categoryId: "immigration",
    korean: "비자를 연장하고 싶어요",
    romanization: "Bija-reul yeonjang-hago sipeoyo",
    english: "I want to extend my visa",
    contextEn: "Requesting a visa extension",
    contextKo: "비자 연장을 신청할 때",
    priority: "essential",
  },
  {
    id: "im-04",
    categoryId: "immigration",
    korean: "어떤 서류가 필요해요?",
    romanization: "Eotteon seoryuga piryohaeyo?",
    english: "What documents do I need?",
    contextEn: "Asking about required paperwork",
    contextKo: "필요한 서류를 확인할 때",
    priority: "essential",
  },
  {
    id: "im-05",
    categoryId: "immigration",
    korean: "비자 종류를 바꾸고 싶어요",
    romanization: "Bija jongnyul-eul bakkugo sipeoyo",
    english: "I want to change my visa type",
    contextEn: "Applying to switch visa categories",
    contextKo: "비자 종류 변경을 신청할 때",
    priority: "useful",
  },
  {
    id: "im-06",
    categoryId: "immigration",
    korean: "얼마나 걸려요?",
    romanization: "Eolmana geollyeoyo?",
    english: "How long does it take?",
    contextEn: "Asking about processing times",
    contextKo: "처리 소요 기간을 물을 때",
    priority: "useful",
  },
  {
    id: "im-07",
    categoryId: "immigration",
    korean: "수수료가 얼마예요?",
    romanization: "Susuryoga eolmaeyo?",
    english: "What is the fee?",
    contextEn: "Asking about application fees",
    contextKo: "신청 수수료를 물을 때",
    priority: "useful",
  },
  {
    id: "im-08",
    categoryId: "immigration",
    korean: "영어로 된 신청서가 있나요?",
    romanization: "Yeongeo-ro doen sincheongseo-ga innayo?",
    english: "Is there an English application form?",
    contextEn: "Requesting forms in English",
    contextKo: "영문 신청서 여부를 확인할 때",
    priority: "useful",
  },
  {
    id: "im-09",
    categoryId: "immigration",
    korean: "진행 상황을 확인하고 싶어요",
    romanization: "Jinhaeng sanghwang-eul hwagin-hago sipeoyo",
    english: "I want to check my application status",
    contextEn: "Following up on a submitted application",
    contextKo: "신청 진행 상황을 문의할 때",
    priority: "useful",
  },
  {
    id: "im-10",
    categoryId: "immigration",
    korean: "직장이 바뀌었어요",
    romanization: "Jikjang-i bakkyuieosseoyo",
    english: "I changed jobs",
    contextEn: "Notifying immigration of an employment change",
    contextKo: "직장 변경을 신고할 때",
    priority: "useful",
  },
  {
    id: "im-11",
    categoryId: "immigration",
    korean: "주소가 바뀌었어요",
    romanization: "Juso-ga bakkyuieosseoyo",
    english: "My address has changed",
    contextEn: "Updating your registered address",
    contextKo: "주소 변경을 신고할 때",
    priority: "useful",
  },
  {
    id: "im-12",
    categoryId: "immigration",
    korean: "여권을 갱신했어요",
    romanization: "Yeogwon-eul gaengsinhasseoyo",
    english: "I renewed my passport",
    contextEn: "Updating immigration records after passport renewal",
    contextKo: "여권 갱신 후 정보 변경을 신고할 때",
    priority: "useful",
  },
  {
    id: "im-13",
    categoryId: "immigration",
    korean: "통역이 필요해요",
    romanization: "Tongyeogi piryohaeyo",
    english: "I need an interpreter",
    contextEn: "Requesting language assistance",
    contextKo: "통역 지원을 요청할 때",
    priority: "essential",
  },
  {
    id: "im-14",
    categoryId: "immigration",
    korean: "결혼했어요",
    romanization: "Gyeolhonhaesseoyo",
    english: "I got married",
    contextEn: "Notifying immigration of a marital status change",
    contextKo: "혼인 신고 관련으로 방문했을 때",
    priority: "useful",
  },
  {
    id: "im-15",
    categoryId: "immigration",
    korean: "출국할 예정이에요",
    romanization: "Chulguk-hal yejeongieyoyo",
    english: "I am planning to leave the country",
    contextEn: "Informing immigration of your departure plans",
    contextKo: "출국 예정을 알릴 때",
    priority: "bonus",
  },

  // ─── RESTAURANT ───────────────────────────────────────────────────────────────
  {
    id: "re-01",
    categoryId: "restaurant",
    korean: "이거 주세요",
    romanization: "Igeo juseyo",
    english: "I'll have this one",
    contextEn: "Point at the menu and say this to order",
    contextKo: "메뉴를 가리키며 주문할 때",
    priority: "essential",
  },
  {
    id: "re-02",
    categoryId: "restaurant",
    korean: "이게 뭐예요?",
    romanization: "Ige mwoyeyo?",
    english: "What is this?",
    contextEn: "Asking about an unfamiliar dish on the menu",
    contextKo: "메뉴에서 모르는 음식을 물을 때",
    priority: "essential",
  },
  {
    id: "re-03",
    categoryId: "restaurant",
    korean: "맵지 않게 해주세요",
    romanization: "Maepji ank-e haejuseyo",
    english: "Please make it not spicy",
    contextEn: "Requesting a non-spicy version of a dish",
    contextKo: "맵지 않게 요리해 달라고 할 때",
    priority: "essential",
  },
  {
    id: "re-04",
    categoryId: "restaurant",
    korean: "맵게 해주세요",
    romanization: "Maepge haejuseyo",
    english: "Please make it spicy",
    contextEn: "Asking for extra spice",
    contextKo: "매운 맛을 원할 때",
    priority: "useful",
  },
  {
    id: "re-05",
    categoryId: "restaurant",
    korean: "고기 없이 해주세요",
    romanization: "Gogi eopsi haejuseyo",
    english: "Please make it without meat",
    contextEn: "Vegetarian or meat-free request",
    contextKo: "채식이나 고기 없이 요리해 달라고 할 때",
    priority: "essential",
  },
  {
    id: "re-06",
    categoryId: "restaurant",
    korean: "땅콩 알레르기가 있어요",
    romanization: "Ttangkong allereugi-ga isseoyo",
    english: "I have a peanut allergy",
    contextEn: "Declaring a peanut allergy before ordering",
    contextKo: "땅콩 알레르기를 알릴 때",
    priority: "essential",
  },
  {
    id: "re-07",
    categoryId: "restaurant",
    korean: "글루텐 알레르기가 있어요",
    romanization: "Geulluten allereugi-ga isseoyo",
    english: "I have a gluten allergy",
    contextEn: "Declaring gluten intolerance",
    contextKo: "글루텐 알레르기를 알릴 때",
    priority: "useful",
  },
  {
    id: "re-08",
    categoryId: "restaurant",
    korean: "계산해 주세요",
    romanization: "Gyesan-hae juseyo",
    english: "Please give me the bill",
    contextEn: "Asking for the check at the end of a meal",
    contextKo: "식사 후 계산서를 요청할 때",
    priority: "essential",
  },
  {
    id: "re-09",
    categoryId: "restaurant",
    korean: "카드로 계산할게요",
    romanization: "Kadeuro gyesan-halgeyo",
    english: "I'll pay by card",
    contextEn: "Indicating card payment at checkout",
    contextKo: "카드로 결제할 때",
    priority: "essential",
  },
  {
    id: "re-10",
    categoryId: "restaurant",
    korean: "영수증 주세요",
    romanization: "Yeongsujeung juseyo",
    english: "Please give me a receipt",
    contextEn: "Requesting a receipt after payment",
    contextKo: "영수증을 요청할 때",
    priority: "useful",
  },
  {
    id: "re-11",
    categoryId: "restaurant",
    korean: "포장해 주세요",
    romanization: "Pojanghae juseyo",
    english: "Please wrap this to go",
    contextEn: "Asking for a takeout box for leftovers",
    contextKo: "남은 음식을 포장해 달라고 할 때",
    priority: "useful",
  },
  {
    id: "re-12",
    categoryId: "restaurant",
    korean: "물 주세요",
    romanization: "Mul juseyo",
    english: "Water, please",
    contextEn: "Requesting water at the table",
    contextKo: "물을 요청할 때",
    priority: "essential",
  },
  {
    id: "re-13",
    categoryId: "restaurant",
    korean: "포크 주세요",
    romanization: "Pokeu juseyo",
    english: "Fork, please",
    contextEn: "Requesting a fork instead of chopsticks",
    contextKo: "젓가락 대신 포크를 요청할 때",
    priority: "useful",
  },
  {
    id: "re-14",
    categoryId: "restaurant",
    korean: "추천 메뉴가 뭐예요?",
    romanization: "Chucheon menyu-ga mwoyeyo?",
    english: "What do you recommend?",
    contextEn: "Asking the server for a menu recommendation",
    contextKo: "추천 메뉴를 물을 때",
    priority: "useful",
  },
  {
    id: "re-15",
    categoryId: "restaurant",
    korean: "혼자예요",
    romanization: "Honjayeyo",
    english: "I'm dining alone",
    contextEn: "Letting the host know you are a single diner",
    contextKo: "혼자 식사할 때 알릴 때",
    priority: "useful",
  },
  {
    id: "re-16",
    categoryId: "restaurant",
    korean: "두 명이요",
    romanization: "Du myeong-iyo",
    english: "Table for two",
    contextEn: "Telling the host your party size",
    contextKo: "일행 수를 알릴 때",
    priority: "essential",
  },
  {
    id: "re-17",
    categoryId: "restaurant",
    korean: "자리 있어요?",
    romanization: "Jari isseoyo?",
    english: "Do you have a table available?",
    contextEn: "Asking if the restaurant has open seating",
    contextKo: "빈 자리가 있는지 물을 때",
    priority: "essential",
  },
  {
    id: "re-18",
    categoryId: "restaurant",
    korean: "너무 맛있어요!",
    romanization: "Neomu massisseoyo!",
    english: "It's absolutely delicious!",
    contextEn: "Complimenting the food — Koreans will love you for this",
    contextKo: "음식이 맛있을 때 칭찬하면 환영받아요",
    priority: "bonus",
  },
  {
    id: "re-19",
    categoryId: "restaurant",
    korean: "아직 먹고 있어요",
    romanization: "Ajik meokgo isseoyo",
    english: "We're still eating",
    contextEn: "When staff tries to clear your plates too early",
    contextKo: "직원이 일찍 치우려 할 때",
    priority: "useful",
  },
  {
    id: "re-20",
    categoryId: "restaurant",
    korean: "소주 한 병 주세요",
    romanization: "Soju han byeong juseyo",
    english: "One bottle of soju, please",
    contextEn: "Ordering Korea's iconic spirit",
    contextKo: "소주를 주문할 때",
    priority: "bonus",
  },

  // ─── SHOPPING ─────────────────────────────────────────────────────────────────
  {
    id: "sh-01",
    categoryId: "shopping",
    korean: "이거 얼마예요?",
    romanization: "Igeo eolmaeyo?",
    english: "How much is this?",
    contextEn: "Asking the price of an item",
    contextKo: "물건 가격을 물을 때",
    priority: "essential",
  },
  {
    id: "sh-02",
    categoryId: "shopping",
    korean: "더 싸게 해줄 수 있어요?",
    romanization: "Deo ssage haejul su isseoyo?",
    english: "Can you give me a discount?",
    contextEn: "Negotiating the price (works at markets, not chain stores)",
    contextKo: "시장 등에서 가격을 흥정할 때",
    priority: "useful",
  },
  {
    id: "sh-03",
    categoryId: "shopping",
    korean: "다른 색깔 있어요?",
    romanization: "Dareun saekkal isseoyo?",
    english: "Do you have another color?",
    contextEn: "Asking for color options",
    contextKo: "다른 색상이 있는지 물을 때",
    priority: "useful",
  },
  {
    id: "sh-04",
    categoryId: "shopping",
    korean: "다른 사이즈 있어요?",
    romanization: "Dareun saijeu isseoyo?",
    english: "Do you have another size?",
    contextEn: "Asking for a different clothing size",
    contextKo: "다른 사이즈가 있는지 물을 때",
    priority: "useful",
  },
  {
    id: "sh-05",
    categoryId: "shopping",
    korean: "입어봐도 돼요?",
    romanization: "Ibeobbwado dwaeyo?",
    english: "Can I try this on?",
    contextEn: "Requesting to use the fitting room",
    contextKo: "옷을 입어보고 싶을 때",
    priority: "essential",
  },
  {
    id: "sh-06",
    categoryId: "shopping",
    korean: "환불할 수 있어요?",
    romanization: "Hwanbul-hal su isseoyo?",
    english: "Can I get a refund?",
    contextEn: "Asking about the return policy",
    contextKo: "환불 가능 여부를 확인할 때",
    priority: "essential",
  },
  {
    id: "sh-07",
    categoryId: "shopping",
    korean: "교환할 수 있어요?",
    romanization: "Gyohwan-hal su isseoyo?",
    english: "Can I exchange this?",
    contextEn: "Requesting a product exchange",
    contextKo: "제품 교환을 요청할 때",
    priority: "essential",
  },
  {
    id: "sh-08",
    categoryId: "shopping",
    korean: "영수증이 있어요",
    romanization: "Yeongsujeung-i isseoyo",
    english: "I have the receipt",
    contextEn: "Showing proof of purchase for a return or exchange",
    contextKo: "영수증을 제시할 때",
    priority: "useful",
  },
  {
    id: "sh-09",
    categoryId: "shopping",
    korean: "어디에 있어요?",
    romanization: "Eodi-e isseoyo?",
    english: "Where is it?",
    contextEn: "Finding a specific item or section in a store",
    contextKo: "물건이나 매장 구역을 찾을 때",
    priority: "essential",
  },
  {
    id: "sh-10",
    categoryId: "shopping",
    korean: "봉투 주세요",
    romanization: "Bongtu juseyo",
    english: "Please give me a bag",
    contextEn: "Requesting a shopping bag (note: bags cost extra in Korea)",
    contextKo: "봉투를 요청할 때 (유료임)",
    priority: "useful",
  },
  {
    id: "sh-11",
    categoryId: "shopping",
    korean: "선물 포장 해주세요",
    romanization: "Seonmul pojang haejuseyo",
    english: "Please gift-wrap this",
    contextEn: "Requesting gift wrapping service",
    contextKo: "선물 포장을 요청할 때",
    priority: "bonus",
  },
  {
    id: "sh-12",
    categoryId: "shopping",
    korean: "카드 돼요?",
    romanization: "Kadeu dwaeyo?",
    english: "Do you accept card payment?",
    contextEn: "Checking if card payment is accepted",
    contextKo: "카드 결제 가능 여부를 확인할 때",
    priority: "essential",
  },
  {
    id: "sh-13",
    categoryId: "shopping",
    korean: "직원 좀 불러주세요",
    romanization: "Jikwon jom bulleojuseyo",
    english: "Please call a staff member",
    contextEn: "Getting assistance from a store employee",
    contextKo: "직원의 도움이 필요할 때",
    priority: "useful",
  },
  {
    id: "sh-14",
    categoryId: "shopping",
    korean: "어디서 계산해요?",
    romanization: "Eodiseo gyesanhaeyo?",
    english: "Where do I pay?",
    contextEn: "Finding the checkout or cashier",
    contextKo: "계산대 위치를 물을 때",
    priority: "essential",
  },
  {
    id: "sh-15",
    categoryId: "shopping",
    korean: "세일 중이에요?",
    romanization: "Seil jung-ieyo?",
    english: "Is this on sale?",
    contextEn: "Checking if an item is discounted",
    contextKo: "할인 여부를 확인할 때",
    priority: "useful",
  },

  // ─── TAXI / BUS ───────────────────────────────────────────────────────────────
  {
    id: "tx-01",
    categoryId: "taxi",
    korean: "여기로 가주세요",
    romanization: "Yeogiro gajuseyo",
    english: "Please take me here",
    contextEn: "Point to the address on your phone and say this",
    contextKo: "핸드폰의 주소를 가리키며 말하세요",
    priority: "essential",
  },
  {
    id: "tx-02",
    categoryId: "taxi",
    korean: "미터기 켜주세요",
    romanization: "Miteogi kyeojuseyo",
    english: "Please turn on the meter",
    contextEn: "Ensuring the taxi meter is running",
    contextKo: "택시 미터기가 켜졌는지 확인할 때",
    priority: "useful",
  },
  {
    id: "tx-03",
    categoryId: "taxi",
    korean: "여기 세워주세요",
    romanization: "Yeogi seweo-juseyo",
    english: "Please stop here",
    contextEn: "Asking the taxi driver to stop at your location",
    contextKo: "여기에서 내릴 때",
    priority: "essential",
  },
  {
    id: "tx-04",
    categoryId: "taxi",
    korean: "조금만 더 가주세요",
    romanization: "Jogeumman deo gajuseyo",
    english: "Please go a little further",
    contextEn: "When the driver stops slightly before your destination",
    contextKo: "조금 더 앞으로 가달라고 할 때",
    priority: "useful",
  },
  {
    id: "tx-05",
    categoryId: "taxi",
    korean: "얼마나 걸려요?",
    romanization: "Eolmana geollyeoyo?",
    english: "How long will it take?",
    contextEn: "Asking about the estimated travel time",
    contextKo: "이동 소요 시간을 물을 때",
    priority: "useful",
  },
  {
    id: "tx-06",
    categoryId: "taxi",
    korean: "카드로 낼게요",
    romanization: "Kadeuro nael-geyo",
    english: "I'll pay by card",
    contextEn: "Indicating card payment in the taxi",
    contextKo: "카드로 택시비를 낼 때",
    priority: "essential",
  },
  {
    id: "tx-07",
    categoryId: "taxi",
    korean: "영수증 주세요",
    romanization: "Yeongsujeung juseyo",
    english: "Please give me a receipt",
    contextEn: "Requesting a taxi receipt for expenses",
    contextKo: "택시 영수증을 요청할 때",
    priority: "useful",
  },
  {
    id: "tx-08",
    categoryId: "taxi",
    korean: "이 버스 강남 가요?",
    romanization: "I beoseu Gangnam gayo?",
    english: "Does this bus go to Gangnam?",
    contextEn: "Replace 'Gangnam' with your destination",
    contextKo: "'강남' 자리에 목적지를 넣으세요",
    priority: "useful",
  },
  {
    id: "tx-09",
    categoryId: "taxi",
    korean: "잠깐만요",
    romanization: "Jamkkan-manyo",
    english: "Wait a moment",
    contextEn: "Asking the driver to wait briefly",
    contextKo: "잠시 기다려 달라고 할 때",
    priority: "useful",
  },
  {
    id: "tx-10",
    categoryId: "taxi",
    korean: "공항으로 가주세요",
    romanization: "Gonghang-euro gajuseyo",
    english: "Please take me to the airport",
    contextEn: "Heading to Incheon or Gimpo airport",
    contextKo: "공항으로 갈 때",
    priority: "useful",
  },
  {
    id: "tx-11",
    categoryId: "taxi",
    korean: "빨리 가주세요, 급해요",
    romanization: "Ppalli gajuseyo, geupaeyo",
    english: "Please hurry, it's urgent",
    contextEn: "When you're in a rush and need to get somewhere fast",
    contextKo: "급하게 이동해야 할 때",
    priority: "useful",
  },
  {
    id: "tx-12",
    categoryId: "taxi",
    korean: "에어컨 좀 켜주세요",
    romanization: "Eeeokon jom kyeojuseyo",
    english: "Could you turn on the AC, please?",
    contextEn: "Requesting air conditioning in the taxi",
    contextKo: "택시 안이 더울 때",
    priority: "bonus",
  },

  // ─── EMERGENCY ────────────────────────────────────────────────────────────────
  {
    id: "em-01",
    categoryId: "emergency",
    korean: "도와주세요!",
    romanization: "Dowajuseyo!",
    english: "Help me!",
    contextEn: "General distress call — say loudly and clearly",
    contextKo: "위험에 처했을 때 크게 외치세요",
    priority: "essential",
  },
  {
    id: "em-02",
    categoryId: "emergency",
    korean: "경찰을 불러주세요",
    romanization: "Gyeongchal-eul bulleojuseyo",
    english: "Please call the police",
    contextEn: "Requesting police assistance — police number is 112",
    contextKo: "경찰 신고 요청 — 112로 신고",
    priority: "essential",
  },
  {
    id: "em-03",
    categoryId: "emergency",
    korean: "구급차를 불러주세요",
    romanization: "Gugeupcha-reul bulleojuseyo",
    english: "Please call an ambulance",
    contextEn: "Medical emergency — ambulance number is 119",
    contextKo: "응급 상황 — 119로 신고",
    priority: "essential",
  },
  {
    id: "em-04",
    categoryId: "emergency",
    korean: "소방서를 불러주세요",
    romanization: "Sobangseo-reul bulleojuseyo",
    english: "Please call the fire department",
    contextEn: "Fire emergency — fire department number is 119",
    contextKo: "화재 신고 — 119로 신고",
    priority: "essential",
  },
  {
    id: "em-05",
    categoryId: "emergency",
    korean: "불이야!",
    romanization: "Buriya!",
    english: "Fire!",
    contextEn: "Shouting to alert others of a fire",
    contextKo: "화재를 발견했을 때 크게 외치세요",
    priority: "essential",
  },
  {
    id: "em-06",
    categoryId: "emergency",
    korean: "도둑이야!",
    romanization: "Dodugiya!",
    english: "Thief! Stop that person!",
    contextEn: "Alerting others to a theft in progress",
    contextKo: "도둑이 있을 때 크게 외치세요",
    priority: "essential",
  },
  {
    id: "em-07",
    categoryId: "emergency",
    korean: "저를 도와줄 수 있어요?",
    romanization: "Jeoreul dowajul su isseoyo?",
    english: "Can you help me?",
    contextEn: "Politely asking someone nearby for help",
    contextKo: "주변 사람에게 도움을 요청할 때",
    priority: "essential",
  },
  {
    id: "em-08",
    categoryId: "emergency",
    korean: "길을 잃었어요",
    romanization: "Gil-eul ireoссeoyo",
    english: "I'm lost",
    contextEn: "When you don't know where you are",
    contextKo: "길을 잃었을 때",
    priority: "essential",
  },
  {
    id: "em-09",
    categoryId: "emergency",
    korean: "영어 할 수 있어요?",
    romanization: "Yeongeo hal su isseoyo?",
    english: "Can you speak English?",
    contextEn: "Finding someone who can communicate with you",
    contextKo: "영어로 소통 가능한 사람을 찾을 때",
    priority: "essential",
  },
  {
    id: "em-10",
    categoryId: "emergency",
    korean: "다쳤어요",
    romanization: "Dachyeosseoyo",
    english: "I'm injured",
    contextEn: "Reporting a physical injury",
    contextKo: "부상을 당했을 때",
    priority: "essential",
  },
  {
    id: "em-11",
    categoryId: "emergency",
    korean: "비상구가 어디예요?",
    romanization: "Bisanggu-ga eodiyeyo?",
    english: "Where is the emergency exit?",
    contextEn: "Finding the emergency exit in a building",
    contextKo: "건물 내 비상구 위치를 물을 때",
    priority: "essential",
  },
  {
    id: "em-12",
    categoryId: "emergency",
    korean: "저는 미국 사람이에요",
    romanization: "Jeoneun Miguk saram-ieyo",
    english: "I'm American",
    contextEn: "Replace 'American' with your nationality for embassy contacts",
    contextKo: "'미국' 자리에 본인 국적을 넣으세요",
    priority: "useful",
  },
  {
    id: "em-13",
    categoryId: "emergency",
    korean: "대사관에 연락해주세요",
    romanization: "Daesagwan-e yeollakhae juseyo",
    english: "Please contact my embassy",
    contextEn: "Requesting embassy contact in a serious emergency",
    contextKo: "심각한 상황에서 대사관 연락을 요청할 때",
    priority: "useful",
  },
  {
    id: "em-14",
    categoryId: "emergency",
    korean: "핸드폰을 잃어버렸어요",
    romanization: "Haendeupon-eul ireobeoryeosseoyo",
    english: "I lost my phone",
    contextEn: "Reporting a lost phone",
    contextKo: "핸드폰을 잃어버렸을 때",
    priority: "useful",
  },
  {
    id: "em-15",
    categoryId: "emergency",
    korean: "지갑을 잃어버렸어요",
    romanization: "Jigap-eul ireobeoryeosseoyo",
    english: "I lost my wallet",
    contextEn: "Reporting a lost wallet",
    contextKo: "지갑을 잃어버렸을 때",
    priority: "useful",
  },

  // ─── DAILY ────────────────────────────────────────────────────────────────────
  {
    id: "dy-01",
    categoryId: "daily",
    korean: "안녕하세요",
    romanization: "Annyeonghaseyo",
    english: "Hello",
    contextEn: "Standard polite greeting for all situations",
    contextKo: "모든 상황에서 사용하는 표준 인사",
    priority: "essential",
  },
  {
    id: "dy-02",
    categoryId: "daily",
    korean: "감사합니다",
    romanization: "Gamsahamnida",
    english: "Thank you",
    contextEn: "Formal expression of gratitude",
    contextKo: "격식 있는 감사 표현",
    priority: "essential",
  },
  {
    id: "dy-03",
    categoryId: "daily",
    korean: "죄송합니다",
    romanization: "Joesonghamnida",
    english: "I'm sorry / Excuse me",
    contextEn: "Formal apology or polite way to get attention",
    contextKo: "격식 있는 사과 또는 실례할 때",
    priority: "essential",
  },
  {
    id: "dy-04",
    categoryId: "daily",
    korean: "괜찮아요",
    romanization: "Gwaenchanaayo",
    english: "It's okay / I'm fine",
    contextEn: "Reassuring someone or accepting an apology",
    contextKo: "괜찮다는 것을 알릴 때",
    priority: "essential",
  },
  {
    id: "dy-05",
    categoryId: "daily",
    korean: "모르겠어요",
    romanization: "Moreugesseoyo",
    english: "I don't know",
    contextEn: "Admitting you don't know something",
    contextKo: "모를 때 솔직하게 말할 때",
    priority: "essential",
  },
  {
    id: "dy-06",
    categoryId: "daily",
    korean: "한국어를 못해요",
    romanization: "Hangugeo-reul mothaeyo",
    english: "I can't speak Korean",
    contextEn: "Explaining your language limitation upfront",
    contextKo: "한국어를 못한다고 미리 알릴 때",
    priority: "essential",
  },
  {
    id: "dy-07",
    categoryId: "daily",
    korean: "조금만 천천히 말해주세요",
    romanization: "Jogeumman cheoncheonhi malhaejuseyo",
    english: "Please speak a little slower",
    contextEn: "Asking someone to slow down their speech",
    contextKo: "너무 빨리 말할 때 천천히 해달라고 할 때",
    priority: "essential",
  },
  {
    id: "dy-08",
    categoryId: "daily",
    korean: "다시 한번 말해주세요",
    romanization: "Dasi hanbeon malhaejuseyo",
    english: "Please say that again",
    contextEn: "Asking for something to be repeated",
    contextKo: "다시 한번 말해달라고 부탁할 때",
    priority: "essential",
  },
  {
    id: "dy-09",
    categoryId: "daily",
    korean: "써주세요",
    romanization: "Sseojuseyo",
    english: "Please write it down",
    contextEn: "When spoken Korean is hard to understand, ask for written form",
    contextKo: "말로 이해가 안 될 때 써달라고 요청할 때",
    priority: "useful",
  },
  {
    id: "dy-10",
    categoryId: "daily",
    korean: "번역 앱으로 해도 돼요?",
    romanization: "Beonyeok ap-euro haedo dwaeyo?",
    english: "Can we use a translation app?",
    contextEn: "Offering to use a translator app like Papago",
    contextKo: "번역 앱을 사용해도 되는지 물을 때",
    priority: "essential",
  },
  {
    id: "dy-11",
    categoryId: "daily",
    korean: "화장실이 어디예요?",
    romanization: "Hwajangsil-i eodiyeyo?",
    english: "Where is the bathroom?",
    contextEn: "Finding the restroom — the most essential phrase ever",
    contextKo: "화장실 위치를 물을 때",
    priority: "essential",
  },
  {
    id: "dy-12",
    categoryId: "daily",
    korean: "와이파이 비밀번호가 뭐예요?",
    romanization: "Waipai bimilbeonho-ga mwoyeyo?",
    english: "What's the WiFi password?",
    contextEn: "Asking for the WiFi password at a cafe or shop",
    contextKo: "카페나 가게에서 와이파이 비밀번호를 물을 때",
    priority: "useful",
  },
  {
    id: "dy-13",
    categoryId: "daily",
    korean: "사진 찍어줄 수 있어요?",
    romanization: "Sajin jjigeojul su isseoyo?",
    english: "Can you take a photo of me?",
    contextEn: "Asking someone to take your photo",
    contextKo: "사진을 찍어달라고 부탁할 때",
    priority: "bonus",
  },
  {
    id: "dy-14",
    categoryId: "daily",
    korean: "이 근처에 편의점이 있어요?",
    romanization: "I geuncheo-e pyeon-uijeom-i isseoyo?",
    english: "Is there a convenience store nearby?",
    contextEn: "Finding a CU, GS25, or 7-Eleven nearby",
    contextKo: "근처 편의점을 찾을 때",
    priority: "useful",
  },
  {
    id: "dy-15",
    categoryId: "daily",
    korean: "지하철역이 어디예요?",
    romanization: "Jihacheolyeog-i eodiyeyo?",
    english: "Where is the subway station?",
    contextEn: "Finding the nearest metro station",
    contextKo: "가까운 지하철역을 찾을 때",
    priority: "essential",
  },
  {
    id: "dy-16",
    categoryId: "daily",
    korean: "맛있어요!",
    romanization: "Massisseoyo!",
    english: "It's delicious!",
    contextEn: "Complimenting food — will always get a smile",
    contextKo: "음식이 맛있을 때 칭찬하면 누구나 좋아해요",
    priority: "bonus",
  },
  {
    id: "dy-17",
    categoryId: "daily",
    korean: "반갑습니다",
    romanization: "Bangapseumnida",
    english: "Nice to meet you",
    contextEn: "Formal greeting when meeting someone for the first time",
    contextKo: "처음 만나는 사람에게 인사할 때",
    priority: "essential",
  },
  {
    id: "dy-18",
    categoryId: "daily",
    korean: "잘 부탁드립니다",
    romanization: "Jal butak deurimnida",
    english: "I'm counting on you / Please take care of me",
    contextEn: "Said at the start of a new relationship or business — shows respect",
    contextKo: "새로운 관계나 업무를 시작할 때 쓰는 예의 표현",
    priority: "useful",
  },
];
