export type VeganPlace = {
  id: string;
  name: string;
  nameEn: string;
  category: string;
  categoryEn: string;
  address: string;
  lat: number;
  lng: number;
  naverMapsUrl: string;
  emoji: string;
  description?: string;
  descriptionKo?: string;
  mustTry?: string[];
  mustTryKo?: string[];
  priceRange?: "₩" | "₩₩" | "₩₩₩";
  tags?: string[];
  tagsKo?: string[];
};

export const VEGAN_PLACES: VeganPlace[] = [
  // ── Mapo-gu ──────────────────────────────────────────────────
  {
    id: "ramuar",
    name: "라므아르",
    nameEn: "L'amour — Vegan Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 마포구 망원동 380-39 2층",
    lat: 37.5557,
    lng: 126.9076,
    naverMapsUrl: "https://map.naver.com/v5/search/라므아르 망원동",
    emoji: "🥐",
    description: "French-inspired vegan bakery in Mangwon-dong known for beautifully crafted pastries and seasonal specials. Small space, big flavors.",
    descriptionKo: "망원동의 프랑스풍 비건 베이커리. 정성스럽게 만든 페이스트리와 시즌 스페셜 메뉴로 유명해요. 작은 공간에 큰 감동.",
    mustTry: ["Vegan croissant", "Seasonal fruit tart"],
    mustTryKo: ["비건 크루아상", "시즌 과일 타르트"],
    priceRange: "₩₩",
    tags: ["Seasonal menu", "Instagram-worthy"],
    tagsKo: ["시즌 메뉴", "포토존"],
  },
  {
    id: "pool-bakery",
    name: "풀 발효부엌",
    nameEn: "Pool Fermented Kitchen",
    category: "채식뷔페",
    categoryEn: "Vegan Buffet",
    address: "서울 마포구 망원동 404-39 2F",
    lat: 37.5561,
    lng: 126.9068,
    naverMapsUrl: "https://map.naver.com/v5/search/풀 발효부엌",
    emoji: "🥗",
    description: "Wholesome vegan buffet using traditionally fermented Korean ingredients. Great way to explore a wide spread of plant-based Korean food in one sitting.",
    descriptionKo: "전통 발효 식재료로 만든 건강한 비건 뷔페. 다양한 한식 비건 요리를 한 번에 맛볼 수 있어요.",
    mustTry: ["Fermented grain bowl", "Seasonal side dishes"],
    mustTryKo: ["발효 곡물 밥", "시즌 반찬"],
    priceRange: "₩₩",
    tags: ["Buffet", "All-you-can-eat"],
    tagsKo: ["뷔페", "무한리필"],
  },
  {
    id: "dakensiel",
    name: "다켄씨엘",
    nameEn: "Dakensiel — Vegan Western",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 마포구 망원동 57-138 1층",
    lat: 37.5548,
    lng: 126.9085,
    naverMapsUrl: "https://map.naver.com/v5/search/다켄씨엘 망원동",
    emoji: "🍽️",
    description: "Laid-back vegan Western restaurant tucked into the alleyways of Mangwon. Think pasta, gratin, and comfort food — all plant-based.",
    descriptionKo: "망원동 골목에 자리한 편안한 비건 양식당. 파스타, 그라탱 등 든든한 플랜트 베이스 요리를 즐길 수 있어요.",
    mustTry: ["Vegan pasta", "Plant-based gratin"],
    mustTryKo: ["비건 파스타", "플랜트 그라탱"],
    priceRange: "₩₩",
    tags: ["Comfort food"],
    tagsKo: ["든든한 식사"],
  },
  {
    id: "bigomi",
    name: "비고미",
    nameEn: "Bigomi — Vegan Cafe",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 마포구 망원동 401-2 101호",
    lat: 37.5552,
    lng: 126.9073,
    naverMapsUrl: "https://map.naver.com/v5/search/비고미 망원동",
    emoji: "☕",
    description: "Cozy vegan cafe in Mangwon with house-made lattes and desserts. Popular with locals for a quiet afternoon.",
    descriptionKo: "망원동의 아늑한 비건 카페. 직접 만든 라떼와 디저트가 인기. 조용한 오후를 보내기 좋은 곳이에요.",
    mustTry: ["Seasonal latte", "Vegan slice cake"],
    mustTryKo: ["시즌 라떼", "비건 케이크 조각"],
    priceRange: "₩₩",
    tags: ["Quiet atmosphere"],
    tagsKo: ["조용한 분위기"],
  },
  {
    id: "veganidaum",
    name: "비건다움 제과점",
    nameEn: "Veganidaum Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 마포구 성산동 134-2 Agate 상가 104호",
    lat: 37.5661,
    lng: 126.9017,
    naverMapsUrl: "https://map.naver.com/v5/search/비건다움 제과점",
    emoji: "🥐",
    description: "A dedicated vegan bakery in Seongsan-dong that doesn't compromise on taste. Fresh-baked daily with a rotating selection of breads and sweets.",
    descriptionKo: "성산동에 자리한 타협 없는 비건 제과점. 매일 신선하게 굽는 다양한 빵과 디저트를 만날 수 있어요.",
    mustTry: ["Daily bread selection", "Red bean pastry"],
    mustTryKo: ["당일 구운 빵", "팥 페이스트리"],
    priceRange: "₩",
    tags: ["Freshly baked daily"],
    tagsKo: ["매일 신선"],
  },
  {
    id: "mabbuz",
    name: "마쁘즈 비건케이크",
    nameEn: "Mabbuz — Vegan Cake",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 마포구 합정동 412-2 1층",
    lat: 37.5491,
    lng: 126.9141,
    naverMapsUrl: "https://map.naver.com/v5/search/마쁘즈 비건케이크",
    emoji: "🎂",
    description: "Specialty vegan cake shop in Hapjeong — whole cakes available for pre-order, slices for walk-ins. Popular for birthdays and celebrations.",
    descriptionKo: "합정동의 비건 케이크 전문점. 홀케이크 예약 주문 가능, 조각 케이크는 당일 구매. 생일과 기념일에 인기 많아요.",
    mustTry: ["Seasonal whole cake (pre-order)", "Slice cake of the day"],
    mustTryKo: ["시즌 홀케이크 (예약)", "오늘의 조각 케이크"],
    priceRange: "₩₩",
    tags: ["Custom cakes", "Pre-order available"],
    tagsKo: ["맞춤 케이크", "예약 주문 가능"],
  },
  {
    id: "chevalerie",
    name: "세발레리",
    nameEn: "Chevalerie — Vegan Western",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 마포구 합정동 433-61 1층",
    lat: 37.5488,
    lng: 126.9143,
    naverMapsUrl: "https://map.naver.com/v5/search/세발레리 합정",
    emoji: "🌿",
    description: "Upscale vegan Western restaurant in Hapjeong. One of the more refined plant-based dining experiences in the Mapo area.",
    descriptionKo: "합정동의 격조 있는 비건 양식당. 마포구에서 가장 세련된 플랜트 베이스 다이닝 중 하나예요.",
    mustTry: ["Plant-based steak", "Vegan risotto"],
    mustTryKo: ["플랜트 스테이크", "비건 리조또"],
    priceRange: "₩₩₩",
    tags: ["Fine dining", "Reservation recommended"],
    tagsKo: ["파인다이닝", "예약 권장"],
  },
  {
    id: "aroundgreen",
    name: "어라운드그린",
    nameEn: "Around Green",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 마포구 합정동 433-8 2층",
    lat: 37.5489,
    lng: 126.9140,
    naverMapsUrl: "https://map.naver.com/v5/search/어라운드그린 합정",
    emoji: "🌿",
    description: "Casual vegan restaurant focused on whole ingredients and natural flavors. Good for groups — relaxed, unpretentious vibe in Hapjeong.",
    descriptionKo: "통 재료와 자연 그대로의 맛에 집중하는 캐주얼 비건 식당. 편안하고 꾸밈없는 분위기, 합정 위치.",
    mustTry: ["Grain bowl", "Vegetable soup"],
    mustTryKo: ["곡물 볼", "야채 수프"],
    priceRange: "₩₩",
    tags: ["Group-friendly"],
    tagsKo: ["단체 방문 가능"],
  },
  {
    id: "popobread",
    name: "포포브레드",
    nameEn: "Popo Bread — Vegan Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 마포구 서교동 464-12 세원빌딩 1층",
    lat: 37.5519,
    lng: 126.9241,
    naverMapsUrl: "https://map.naver.com/v5/search/포포브레드 서교동",
    emoji: "🥐",
    description: "Vegan bakery steps from Hongdae with a cheerful name and an even cheerier selection. Great stop before or after exploring the neighborhood.",
    descriptionKo: "홍대 근처의 활기찬 비건 베이커리. 홍대 구경 전후에 들르기 딱 좋은 곳이에요.",
    mustTry: ["Cinnamon roll", "Sourdough loaf"],
    mustTryKo: ["시나몬 롤", "사워도우 식빵"],
    priceRange: "₩",
    tags: ["Near Hongdae"],
    tagsKo: ["홍대 근처"],
  },
  {
    id: "immu",
    name: "이뮤 베이크샵",
    nameEn: "Immu Bake Shop",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 마포구 서교동 396-61 2층 202호",
    lat: 37.5520,
    lng: 126.9239,
    naverMapsUrl: "https://map.naver.com/v5/search/이뮤 베이크샵",
    emoji: "☕",
    description: "A small, boutique vegan bake shop in Seogyo-dong with handcrafted sweets. Hidden on the second floor — worth seeking out.",
    descriptionKo: "서교동 2층에 자리한 아담한 비건 베이크샵. 손으로 만든 달콤한 메뉴들이 가득. 찾아가는 보람이 있는 곳이에요.",
    mustTry: ["Pound cake", "Daily cookie box"],
    mustTryKo: ["파운드 케이크", "오늘의 쿠키"],
    priceRange: "₩",
    tags: ["Hidden gem"],
    tagsKo: ["숨은 맛집"],
  },
  {
    id: "slunch",
    name: "슬런치 팩토리 홍대점",
    nameEn: "Slunch Factory Hongdae",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 마포구 상수동 72-1",
    lat: 37.5483,
    lng: 126.9207,
    naverMapsUrl: "https://map.naver.com/v5/search/슬런치 팩토리 홍대",
    emoji: "🍽️",
    description: "One of Seoul's most popular plant-based chains. Filling bowls and burgers that convert even the skeptics. English menu available.",
    descriptionKo: "서울에서 가장 인기 있는 플랜트 베이스 체인 중 하나. 든든한 볼과 버거로 비건 식사에 대한 편견을 바꿔줘요. 영어 메뉴 있음.",
    mustTry: ["Black bean burger", "Plant-based rice bowl"],
    mustTryKo: ["검은콩 버거", "플랜트 라이스 볼"],
    priceRange: "₩₩",
    tags: ["English menu", "Foreigner-friendly"],
    tagsKo: ["영어 메뉴", "외국인 환영"],
  },
  {
    id: "sunnyhouse",
    name: "써니하우스",
    nameEn: "Sunny House — Vegan Brunch",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 마포구 상수동 341-17 1층",
    lat: 37.5479,
    lng: 126.9213,
    naverMapsUrl: "https://map.naver.com/v5/search/써니하우스 상수동",
    emoji: "☕",
    description: "Bright, cheerful vegan brunch cafe in Sangsu-dong. Smoothie bowls, avocado toast, and good coffee — exactly what a weekend morning looks like.",
    descriptionKo: "상수동의 밝고 활기찬 비건 브런치 카페. 스무디볼, 아보카도 토스트, 커피까지 — 주말 아침을 위한 완벽한 장소.",
    mustTry: ["Smoothie bowl", "Avocado toast"],
    mustTryKo: ["스무디 볼", "아보카도 토스트"],
    priceRange: "₩₩",
    tags: ["Brunch spot", "Weekend favorite"],
    tagsKo: ["브런치 맛집", "주말 필수"],
  },
  // ── Seodaemun-gu ─────────────────────────────────────────────
  {
    id: "dajeonghan",
    name: "다정한마음",
    nameEn: "Dajeonghan Maeum",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 서대문구 연희동 727",
    lat: 37.5717,
    lng: 126.9338,
    naverMapsUrl: "https://map.naver.com/v5/search/다정한마음 연희동",
    emoji: "🌿",
    description: "Homey vegan Korean restaurant in Yeonhui-dong (meaning: 'warm-hearted'). Simple, nourishing home-style meals. Feels like eating at a friend's house.",
    descriptionKo: "연희동의 정겨운 비건 한식당 (뜻: 다정한 마음). 소박하고 든든한 집밥 스타일. 친구 집에서 밥 먹는 느낌이에요.",
    mustTry: ["Vegan doenjang jjigae", "Korean grain rice set"],
    mustTryKo: ["비건 된장찌개", "잡곡밥 한상"],
    priceRange: "₩₩",
    tags: ["Home-style cooking", "Local favorite"],
    tagsKo: ["집밥 스타일", "동네 맛집"],
  },
  {
    id: "vegis",
    name: "베지스",
    nameEn: "Vegis — Brunch Cafe",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 서대문구 연희동 719-18 1층",
    lat: 37.5721,
    lng: 126.9341,
    naverMapsUrl: "https://map.naver.com/v5/search/베지스 연희동",
    emoji: "☕",
    description: "Vegan brunch cafe in the charming Yeonhui-dong neighborhood. Lovely spot to relax — the neighborhood itself is worth the trip.",
    descriptionKo: "매력적인 연희동에 자리한 비건 브런치 카페. 연희동 자체가 소풍 가기 좋은 동네라 더 즐거운 곳이에요.",
    mustTry: ["Brunch plate", "House latte"],
    mustTryKo: ["브런치 플레이트", "하우스 라떼"],
    priceRange: "₩₩",
    tags: ["Charming neighborhood"],
    tagsKo: ["분위기 좋은 동네"],
  },
  {
    id: "weirdough",
    name: "위어도우",
    nameEn: "Weirdough — Vegan Pizza",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 서대문구 연희동 703 2층 201호",
    lat: 37.5715,
    lng: 126.9335,
    naverMapsUrl: "https://map.naver.com/v5/search/위어도우 연희동",
    emoji: "🍕",
    description: "Possibly Seoul's best vegan pizza — cashew-based cheese, creative toppings, and proper sourdough crust. Small and popular, book ahead.",
    descriptionKo: "서울에서 가장 맛있는 비건 피자를 파는 곳. 캐슈 치즈, 창의적인 토핑, 사워도우 도우까지. 작고 인기 많으니 예약 필수.",
    mustTry: ["Cashew cheese pizza", "Mushroom & truffle pizza"],
    mustTryKo: ["캐슈 치즈 피자", "버섯 & 트러플 피자"],
    priceRange: "₩₩₩",
    tags: ["Reservation recommended", "Must visit"],
    tagsKo: ["예약 필수", "꼭 가봐야 할 곳"],
  },
  {
    id: "veganire",
    name: "비건이레",
    nameEn: "Vegan Ire — Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 서대문구 충정로3가 23-4 1층",
    lat: 37.5578,
    lng: 126.9634,
    naverMapsUrl: "https://map.naver.com/v5/search/비건이레 충정로",
    emoji: "🥐",
    description: "Wholesome vegan bakery near Chungjeongno with a focus on natural fermentation and whole grains. Breads you can feel good about.",
    descriptionKo: "충정로 근처의 건강한 비건 베이커리. 천연 발효와 통곡물에 집중. 먹어도 좋은 빵들로 가득해요.",
    mustTry: ["Whole grain sourdough", "Grain buns"],
    mustTryKo: ["통밀 사워도우", "잡곡 빵"],
    priceRange: "₩",
    tags: ["Natural fermentation", "Whole grain"],
    tagsKo: ["천연 발효", "통곡물"],
  },
  {
    id: "veganique",
    name: "veganique",
    nameEn: "Veganique — Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 서대문구 대현동 34-21",
    lat: 37.5601,
    lng: 126.9397,
    naverMapsUrl: "https://map.naver.com/v5/search/veganique 대현동",
    emoji: "🥐",
    description: "Vegan bakery near Ewha Women's University with a steady following among students and locals. Fresh, affordable daily bakes.",
    descriptionKo: "이화여대 근처의 비건 베이커리. 학생들과 동네 주민들에게 인기 많은 곳. 신선하고 합리적인 가격의 빵들.",
    mustTry: ["Vegan cookies", "Seasonal cake slice"],
    mustTryKo: ["비건 쿠키", "시즌 케이크 조각"],
    priceRange: "₩",
    tags: ["Near Ewha", "Student-friendly"],
    tagsKo: ["이화여대 근처", "학생 친화"],
  },
  // ── Yongsan-gu ───────────────────────────────────────────────
  {
    id: "gukmin-bread",
    name: "국민빵집 용산 용리단길",
    nameEn: "Gukmin Bakery — Yongsan",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 용산구 한강로1가 181-2 1층",
    lat: 37.5348,
    lng: 126.9659,
    naverMapsUrl: "https://map.naver.com/v5/search/국민빵집 용산 용리단길",
    emoji: "🥐",
    description: "Vegan-friendly bakery on the trendy Yongni-dan-gil strip. Great stop while exploring this up-and-coming stretch of Yongsan.",
    descriptionKo: "트렌디한 용리단길의 비건 베이커리. 용산구를 탐방하는 중에 들르기 좋아요.",
    mustTry: ["Whole grain loaf", "Sweet potato bun"],
    mustTryKo: ["통곡물 식빵", "고구마 빵"],
    priceRange: "₩",
    tags: ["On Yongni-dan-gil"],
    tagsKo: ["용리단길"],
  },
  {
    id: "plantude-ipark",
    name: "플랜튜드 아이파크몰 용산점",
    nameEn: "Plantude — iPark Mall Yongsan",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 용산구 한강로3가 40-999 아이파크몰",
    lat: 37.5293,
    lng: 126.9643,
    naverMapsUrl: "https://map.naver.com/v5/search/플랜튜드 아이파크몰 용산",
    emoji: "🌱",
    description: "Plantude's Yongsan outpost inside iPark Mall — Korea's go-to plant-based chain. English menu, easy to find, consistent quality.",
    descriptionKo: "아이파크몰 내 플랜튜드 용산점. 한국의 대표 플랜트 베이스 체인. 영어 메뉴 있고 찾기 쉬워요.",
    mustTry: ["Plant burger", "Potato wedges"],
    mustTryKo: ["플랜트 버거", "포테이토 웨지"],
    priceRange: "₩₩",
    tags: ["English menu", "Mall location", "Foreigner-friendly"],
    tagsKo: ["영어 메뉴", "몰 내 위치", "외국인 환영"],
  },
  {
    id: "nonoshop",
    name: "노노샵",
    nameEn: "Nono Shop — Vegan Cafe",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 용산구 이태원동 21-1 202호",
    lat: 37.5344,
    lng: 126.9952,
    naverMapsUrl: "https://map.naver.com/v5/search/노노샵 이태원",
    emoji: "☕",
    description: "Vegan cafe in Itaewon with a relaxed, international crowd. One of the easiest vegan spots to visit as a foreigner. English spoken.",
    descriptionKo: "이태원의 비건 카페. 편안한 국제적인 분위기. 외국인도 편하게 방문할 수 있는 곳이에요. 영어 가능.",
    mustTry: ["Oat milk latte", "Vegan cheesecake"],
    mustTryKo: ["오트 밀크 라떼", "비건 치즈케이크"],
    priceRange: "₩₩",
    tags: ["English spoken", "Foreigner-friendly", "Itaewon"],
    tagsKo: ["영어 가능", "외국인 환영", "이태원"],
  },
  // ── Jongno / Jung-gu ─────────────────────────────────────────
  {
    id: "maru-gimbap",
    name: "마루자연식김밥",
    nameEn: "Maru Natural Gimbap",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 종로구 관훈동 192-15 본관 1층 105호",
    lat: 37.5739,
    lng: 126.9857,
    naverMapsUrl: "https://map.naver.com/v5/search/마루자연식김밥",
    emoji: "🍙",
    description: "Temple-food inspired gimbap in the heart of Insadong. Natural, clean ingredients — no artificial flavors. A uniquely Korean vegan experience.",
    descriptionKo: "인사동 중심의 사찰음식 스타일 김밥. 인공 조미료 없이 자연 그대로의 재료만 사용. 유니크한 한국 비건 경험.",
    mustTry: ["Natural gimbap", "Japchae"],
    mustTryKo: ["자연식 김밥", "잡채"],
    priceRange: "₩",
    tags: ["Temple food", "Traditional", "Near Insadong"],
    tagsKo: ["사찰음식", "전통", "인사동 근처"],
  },
  {
    id: "hidden-gem",
    name: "히든젬 명동",
    nameEn: "Hidden Gem — Vegan Chocolate",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 중구 남산동2가 44 1층",
    lat: 37.5571,
    lng: 126.9983,
    naverMapsUrl: "https://map.naver.com/v5/search/히든젬 명동",
    emoji: "🍫",
    description: "Raw vegan chocolate specialist near Myeong-dong. Artisanal cacao drinks and truffles made without dairy. A sweet escape from the shopping crowds.",
    descriptionKo: "명동 근처의 로 비건 초콜릿 전문점. 유제품 없는 수제 카카오 음료와 트러플. 쇼핑 인파에서 벗어난 달콤한 휴식.",
    mustTry: ["Raw cacao drink", "Vegan truffle box"],
    mustTryKo: ["로 카카오 음료", "비건 트러플 박스"],
    priceRange: "₩₩",
    tags: ["Raw chocolate", "Artisanal"],
    tagsKo: ["로 초콜릿", "수제"],
  },
  {
    id: "overte",
    name: "오베흐트",
    nameEn: "Overte — Vegan Donuts",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 중구 회현동1가 73-1 1층",
    lat: 37.5577,
    lng: 126.9814,
    naverMapsUrl: "https://map.naver.com/v5/search/오베흐트 회현",
    emoji: "🍩",
    description: "Vegan donut shop near Hoehyeon Station. Creative glazes and seasonal flavors — sell out fast, so go early.",
    descriptionKo: "회현역 근처의 비건 도넛 가게. 창의적인 글레이즈와 시즌 맛. 일찍 품절되니 일찍 가세요.",
    mustTry: ["Glazed donut", "Seasonal special donut"],
    mustTryKo: ["글레이즈 도넛", "시즌 스페셜 도넛"],
    priceRange: "₩",
    tags: ["Go early", "Sells out fast"],
    tagsKo: ["일찍 가야 해요", "조기 품절"],
  },
  // ── Seocho / Gangnam-gu ───────────────────────────────────────
  {
    id: "swallow",
    name: "스왈로 베이커리 카페",
    nameEn: "Swallow Bakery & Cafe",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 서초구 서초동 1457-2 203호",
    lat: 37.4841,
    lng: 127.0077,
    naverMapsUrl: "https://map.naver.com/v5/search/스왈로 베이커리 서초",
    emoji: "☕",
    description: "Polished vegan bakery cafe in Seocho catering to the area's professional crowd. Clean, well-lit space with reliable quality.",
    descriptionKo: "서초의 세련된 비건 베이커리 카페. 깔끔하고 밝은 공간, 믿을 수 있는 품질.",
    mustTry: ["Vegan danish", "Specialty coffee"],
    mustTryKo: ["비건 데니쉬", "스페셜티 커피"],
    priceRange: "₩₩",
    tags: ["Clean and calm"],
    tagsKo: ["깔끔한 분위기"],
  },
  {
    id: "cafe-turtle",
    name: "카페 거북이",
    nameEn: "Cafe Turtle — Vegan Desserts",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 서초구 방배동 454-2 1층",
    lat: 37.4812,
    lng: 126.9986,
    naverMapsUrl: "https://map.naver.com/v5/search/카페 거북이 방배",
    emoji: "☕",
    description: "A beloved long-running vegan cafe in quiet Bangbae-dong. The kind of neighborhood spot you wish existed near your home.",
    descriptionKo: "조용한 방배동의 사랑받는 장수 비건 카페. 내 집 근처에 있었으면 하는 동네 카페 같은 느낌이에요.",
    mustTry: ["Carrot cake", "Vegan waffle"],
    mustTryKo: ["당근 케이크", "비건 와플"],
    priceRange: "₩₩",
    tags: ["Long-running", "Neighborhood gem"],
    tagsKo: ["오래된 맛집", "동네 보물"],
  },
  {
    id: "foods-matter",
    name: "푸드더즈매터",
    nameEn: "Foods That Matter",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 서초구 방배동 868-12 지하 1층",
    lat: 37.4809,
    lng: 126.9989,
    naverMapsUrl: "https://map.naver.com/v5/search/푸드더즈매터 방배",
    emoji: "🍽️",
    description: "Serious vegan restaurant in the Bangbae vegan corridor with a focus on nutrition and flavor. Known for creative, satisfying plant-based meals.",
    descriptionKo: "방배동 비건 거리에 자리한 진지한 비건 식당. 영양과 맛에 집중한 창의적인 플랜트 베이스 요리.",
    mustTry: ["Grain & protein bowl", "Seasonal soup"],
    mustTryKo: ["곡물 & 단백질 볼", "시즌 수프"],
    priceRange: "₩₩₩",
    tags: ["Nutrition-focused", "Bangbae vegan cluster"],
    tagsKo: ["영양 중심", "방배동 비건 거리"],
  },
  {
    id: "nammi-plant",
    name: "남미플랜트랩",
    nameEn: "Nammi Plant Lab",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 서초구 방배동 455-20 2층",
    lat: 37.4812,
    lng: 126.9987,
    naverMapsUrl: "https://map.naver.com/v5/search/남미플랜트랩 방배",
    emoji: "🌱",
    description: "Plant-based lab concept in Bangbae-dong experimenting with creative vegan ingredients. Part restaurant, part culinary experiment.",
    descriptionKo: "방배동의 플랜트 베이스 랩 콘셉트. 창의적인 비건 재료 실험 중. 식당이자 요리 실험실.",
    mustTry: ["Chef's recommendation bowl", "Plant-based protein dish"],
    mustTryKo: ["오늘의 추천 볼", "플랜트 단백질 요리"],
    priceRange: "₩₩",
    tags: ["Creative menu", "Bangbae vegan cluster"],
    tagsKo: ["창의적 메뉴", "방배동 비건 거리"],
  },
  {
    id: "lovinghut-land",
    name: "러빙헛 랜드",
    nameEn: "Loving Hut Land — Vegan Buffet",
    category: "채식뷔페",
    categoryEn: "Vegan Buffet",
    address: "서울 강남구 개포동 1230-9 1층",
    lat: 37.4814,
    lng: 127.0465,
    naverMapsUrl: "https://map.naver.com/v5/search/러빙헛 랜드 개포동",
    emoji: "🥗",
    description: "Large vegan buffet in the Gaepodong vegan cluster — a neighborhood known for having multiple vegan spots in one area. Great for groups.",
    descriptionKo: "개포동 비건 클러스터에 자리한 대형 비건 뷔페. 여러 비건 가게가 모여 있는 동네. 단체 방문에 좋아요.",
    mustTry: ["Vegan Korean buffet spread", "Tofu-based dishes"],
    mustTryKo: ["비건 한식 뷔페", "두부 요리"],
    priceRange: "₩₩",
    tags: ["Buffet", "Group-friendly", "Gaepodong vegan cluster"],
    tagsKo: ["뷔페", "단체 방문 가능", "개포동 비건 거리"],
  },
  {
    id: "vegigreen",
    name: "베지그린",
    nameEn: "VegiGreen — Vegan Buffet",
    category: "채식뷔페",
    categoryEn: "Vegan Buffet",
    address: "서울 강남구 개포동 1234-8 광민빌딩 1층",
    lat: 37.4815,
    lng: 127.0469,
    naverMapsUrl: "https://map.naver.com/v5/search/베지그린 개포동",
    emoji: "🥗",
    description: "Popular vegan buffet in Gaepodong, steps from Loving Hut Land. Solid spread of Korean vegan home-style dishes at a reasonable price.",
    descriptionKo: "개포동 비건 뷔페. 러빙헛 랜드와 도보 거리. 합리적인 가격에 한국 비건 가정식 뷔페.",
    mustTry: ["Korean vegan home-style spread", "Seasonal vegetable dishes"],
    mustTryKo: ["한국 비건 가정식", "시즌 채소 요리"],
    priceRange: "₩₩",
    tags: ["Buffet", "Gaepodong vegan cluster"],
    tagsKo: ["뷔페", "개포동 비건 거리"],
  },
  {
    id: "lovinghut-cafe",
    name: "러빙헛 카페",
    nameEn: "Loving Hut Cafe",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 강남구 개포동 1218-16",
    lat: 37.4816,
    lng: 127.0462,
    naverMapsUrl: "https://map.naver.com/v5/search/러빙헛 카페 개포동",
    emoji: "☕",
    description: "Vegan cafe companion to the Loving Hut restaurants in Gaepodong. Good for coffee and a sweet after your buffet visit.",
    descriptionKo: "개포동 러빙헛 식당의 비건 카페. 뷔페 후 커피 한 잔과 달콤한 디저트 즐기기 딱이에요.",
    mustTry: ["Vegan coffee drink", "Slice cake"],
    mustTryKo: ["비건 커피 음료", "조각 케이크"],
    priceRange: "₩",
    tags: ["Gaepodong vegan cluster"],
    tagsKo: ["개포동 비건 거리"],
  },
  {
    id: "plantude-coex",
    name: "플랜튜드 스타필드코엑스점",
    nameEn: "Plantude — Starfield COEX",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 강남구 삼성동 159 스타필드 지하1층 I-111호",
    lat: 37.5125,
    lng: 127.0596,
    naverMapsUrl: "https://map.naver.com/v5/search/플랜튜드 스타필드 코엑스",
    emoji: "🌱",
    description: "Plantude inside COEX mall — convenient if you're already in Gangnam. Same reliable plant-based menu with an English-friendly setup.",
    descriptionKo: "코엑스 몰 내 플랜튜드. 강남에 있다면 편리하게 방문 가능. 영어 메뉴와 함께 믿을 수 있는 플랜트 베이스 메뉴.",
    mustTry: ["Plant burger", "Sweet potato fries"],
    mustTryKo: ["플랜트 버거", "고구마 프라이"],
    priceRange: "₩₩",
    tags: ["English menu", "Mall location", "Gangnam"],
    tagsKo: ["영어 메뉴", "몰 내 위치", "강남"],
  },
  // ── Yeongdeungpo / Gwanak-gu ──────────────────────────────────
  {
    id: "soinick",
    name: "소이닉",
    nameEn: "Soinic — Vegan Korean",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 영등포구 양평동2가 31-5 1층",
    lat: 37.5279,
    lng: 126.8888,
    naverMapsUrl: "https://map.naver.com/v5/search/소이닉 영등포",
    emoji: "🍚",
    description: "Soy-based vegan Korean restaurant in Yeongdeungpo. Hearty, protein-forward meals using tofu and soy — filling and satisfying.",
    descriptionKo: "영등포의 콩 기반 비건 한식당. 두부와 콩을 활용한 든든하고 영양가 높은 식사.",
    mustTry: ["Soy protein rice bowl", "Tofu steak"],
    mustTryKo: ["콩 단백질 덮밥", "두부 스테이크"],
    priceRange: "₩₩",
    tags: ["High-protein", "Soy-based"],
    tagsKo: ["고단백", "콩 기반"],
  },
  {
    id: "aseungji",
    name: "아승지",
    nameEn: "Aseungji — Temple Food",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 영등포구 신길동 223-17",
    lat: 37.5082,
    lng: 126.9063,
    naverMapsUrl: "https://map.naver.com/v5/search/아승지 신길동",
    emoji: "🍵",
    description: "Authentic Korean temple food restaurant serving the five-grain Buddhist cuisine. A meditative dining experience — no garlic, onion, or meat.",
    descriptionKo: "정통 한국 사찰 음식을 제공하는 식당. 오곡 기반의 불교 채식. 마늘, 파, 육류 없는 명상적인 식사 경험.",
    mustTry: ["Temple food course meal", "Vegan bibimbap"],
    mustTryKo: ["사찰음식 코스", "비건 비빔밥"],
    priceRange: "₩₩₩",
    tags: ["Temple food", "Authentic", "Reservation recommended"],
    tagsKo: ["사찰음식", "정통", "예약 권장"],
  },
  {
    id: "veganmama",
    name: "비건마마",
    nameEn: "Vegan Mama — Cafe",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 관악구 봉천동 871-74 1층",
    lat: 37.4758,
    lng: 126.9567,
    naverMapsUrl: "https://map.naver.com/v5/search/비건마마 봉천동",
    emoji: "☕",
    description: "Neighborhood vegan cafe in Bongcheon-dong (Gwanak) — serving the local community with house-baked goods and warm drinks.",
    descriptionKo: "봉천동 비건 카페. 자체 제작 베이커리와 따뜻한 음료로 동네를 지키고 있어요.",
    mustTry: ["Matcha latte", "House-baked goods"],
    mustTryKo: ["말차 라떼", "직접 구운 빵"],
    priceRange: "₩",
    tags: ["Neighborhood cafe"],
    tagsKo: ["동네 카페"],
  },
  // ── East Seoul ────────────────────────────────────────────────
  {
    id: "yongtokki",
    name: "용토끼",
    nameEn: "Yong Tokki — Vegan Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 동대문구 이문동 431 단지내 상가",
    lat: 37.5904,
    lng: 127.0631,
    naverMapsUrl: "https://map.naver.com/v5/search/용토끼 이문동",
    emoji: "🥐",
    description: "Vegan bakery tucked inside a residential complex in Imun-dong. Beloved by locals — the kind of place residents don't want outsiders to discover.",
    descriptionKo: "이문동 아파트 단지 내 비건 베이커리. 동네 주민들의 사랑을 받는 곳 — 외부에 알려지길 바라지 않는 그런 곳이에요.",
    mustTry: ["Whole grain bread", "Daily pastries"],
    mustTryKo: ["통곡물 빵", "오늘의 페이스트리"],
    priceRange: "₩",
    tags: ["Hidden gem", "Residential area"],
    tagsKo: ["숨은 맛집", "주거 지역"],
  },
  {
    id: "bakeyourday",
    name: "베이크유어데이",
    nameEn: "Bake Your Day — Vegan Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 광진구 중곡동 165-18 1층",
    lat: 37.5534,
    lng: 127.0762,
    naverMapsUrl: "https://map.naver.com/v5/search/베이크유어데이 중곡동",
    emoji: "🥐",
    description: "Cheerful vegan bakery in Junggok-dong, Gwangjin. Variety of daily bakes — the name says it all.",
    descriptionKo: "광진구 중곡동의 활기찬 비건 베이커리. 매일 다양하게 구워요 — 이름이 다 말해주죠.",
    mustTry: ["Muffins", "Seasonal loaf cake"],
    mustTryKo: ["머핀", "시즌 파운드 케이크"],
    priceRange: "₩",
    tags: ["Daily fresh bakes"],
    tagsKo: ["매일 신선"],
  },
  {
    id: "omoomu",
    name: "오무오무",
    nameEn: "Omu Omu — Vegan Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 광진구 중곡동 640-7 1층",
    lat: 37.5537,
    lng: 127.0764,
    naverMapsUrl: "https://map.naver.com/v5/search/오무오무 중곡동",
    emoji: "🥐",
    description: "Vegan bakery in Junggok-dong with a fun name and a loyal following. Known for their croissants and rotating seasonal sweets.",
    descriptionKo: "중곡동의 개성 있는 이름의 비건 베이커리. 크루아상과 시즌 디저트로 팬층이 탄탄해요.",
    mustTry: ["Vegan croissant", "Seasonal dessert"],
    mustTryKo: ["비건 크루아상", "시즌 디저트"],
    priceRange: "₩₩",
    tags: ["Popular croissants"],
    tagsKo: ["크루아상 유명"],
  },
  {
    id: "gangnam-lovinghut-realluv",
    name: "러빙헛리얼러브",
    nameEn: "Loving Hut Real Love — Korean",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 성북구 상월곡동 101-2 B106호",
    lat: 37.5974,
    lng: 127.0298,
    naverMapsUrl: "https://map.naver.com/v5/search/러빙헛리얼러브 상월곡동",
    emoji: "🍚",
    description: "Vegan Korean restaurant in Sangwolgok-dong, part of the well-established Loving Hut family. Comforting Korean vegan meals in a quiet area.",
    descriptionKo: "상월곡동의 비건 한식당, 러빙헛 계열. 조용한 동네에서 즐기는 편안한 비건 한식.",
    mustTry: ["Korean vegan set meal", "Vegan japchae"],
    mustTryKo: ["비건 한식 정식", "비건 잡채"],
    priceRange: "₩₩",
    tags: ["Loving Hut family"],
    tagsKo: ["러빙헛 계열"],
  },
  {
    id: "vegannature",
    name: "비건네이처",
    nameEn: "Vegan Nature — Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 송파구 송파동 15-7 102, 103호",
    lat: 37.5033,
    lng: 127.1078,
    naverMapsUrl: "https://map.naver.com/v5/search/비건네이처 송파",
    emoji: "🥐",
    description: "Vegan bakery serving the Songpa community — from naturally leavened breads to sweet buns. A go-to for healthy eating in the east.",
    descriptionKo: "송파 동네를 위한 비건 베이커리. 천연 발효 빵부터 달콤한 빵까지. 동쪽 서울의 건강한 빵집.",
    mustTry: ["Naturally leavened bread", "Sweet whole grain bun"],
    mustTryKo: ["천연 발효 빵", "달콤한 통곡물 빵"],
    priceRange: "₩",
    tags: ["Natural leavening"],
    tagsKo: ["천연 발효"],
  },
  {
    id: "rooted",
    name: "루티드",
    nameEn: "Rooted — Vegan Western",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 송파구 방이동 104-3 1층",
    lat: 37.5076,
    lng: 127.1242,
    naverMapsUrl: "https://map.naver.com/v5/search/루티드 방이동",
    emoji: "🌱",
    description: "Upscale vegan Western restaurant in Bangi-dong. Thoughtfully plated dishes with a focus on local, seasonal produce.",
    descriptionKo: "방이동의 고급 비건 양식당. 로컬 제철 재료에 집중한 정성스러운 플레이팅.",
    mustTry: ["Plant-based burger", "Seasonal pasta"],
    mustTryKo: ["플랜트 버거", "시즌 파스타"],
    priceRange: "₩₩₩",
    tags: ["Seasonal menu", "Fine casual"],
    tagsKo: ["시즌 메뉴", "파인 캐주얼"],
  },
  {
    id: "gonggan-nokeum",
    name: "공간녹음",
    nameEn: "Gonggan Nokeum — Fusion",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 강서구 마곡동 774-4 403호",
    lat: 37.5601,
    lng: 126.8304,
    naverMapsUrl: "https://map.naver.com/v5/search/공간녹음 마곡동",
    emoji: "🌿",
    description: "Vegan fusion restaurant in Magok (the tech business district). A welcome lunch option for office workers looking beyond 편의점.",
    descriptionKo: "마곡 테크 비즈니스 지구의 비건 퓨전 식당. 편의점 너머를 찾는 직장인들에게 반가운 선택지.",
    mustTry: ["Fusion vegan bowl", "Seasonal soup"],
    mustTryKo: ["퓨전 비건 볼", "시즌 수프"],
    priceRange: "₩₩",
    tags: ["Magok area", "Office lunch"],
    tagsKo: ["마곡 지역", "직장인 점심"],
  },
  {
    id: "jigoo-norae",
    name: "지구를 위한 노래",
    nameEn: "A Song for the Earth",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 강동구 둔촌동 622-2 1층",
    lat: 37.4940,
    lng: 127.1353,
    naverMapsUrl: "https://map.naver.com/v5/search/지구를 위한 노래 둔촌동",
    emoji: "🌍",
    description: "Eco-conscious vegan restaurant with a poetic name ('A Song for the Earth'). Zero-waste ethos, hearty plant-based Korean meals.",
    descriptionKo: "시적인 이름의 친환경 비건 식당. 제로웨이스트 정신, 든든한 플랜트 베이스 한식.",
    mustTry: ["Vegan Korean set", "Daily special"],
    mustTryKo: ["비건 한식 세트", "오늘의 특선"],
    priceRange: "₩₩",
    tags: ["Eco-conscious", "Zero-waste ethos"],
    tagsKo: ["친환경", "제로웨이스트"],
  },
  {
    id: "plantude-godeok",
    name: "플랜튜드 고덕점",
    nameEn: "Plantude — Godeok",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 강동구 고덕동 353-23 415호 4F",
    lat: 37.5537,
    lng: 127.1524,
    naverMapsUrl: "https://map.naver.com/v5/search/플랜튜드 고덕점",
    emoji: "🌱",
    description: "Plantude's outpost serving east Seoul. Same solid plant-based menu as other branches — burgers, bowls, and shakes done right.",
    descriptionKo: "서울 동부를 위한 플랜튜드. 다른 지점과 동일하게 믿을 수 있는 플랜트 베이스 메뉴.",
    mustTry: ["Plant burger", "Smoothie"],
    mustTryKo: ["플랜트 버거", "스무디"],
    priceRange: "₩₩",
    tags: ["East Seoul"],
    tagsKo: ["서울 동부"],
  },
  // ── Outside Seoul ─────────────────────────────────────────────
  {
    id: "maison-de-vegan",
    name: "메종드비건",
    nameEn: "Maison de Vegan — Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "경기도 파주시 목동동 1061-1 1층",
    lat: 37.7964,
    lng: 126.7374,
    naverMapsUrl: "https://map.naver.com/v5/search/메종드비건 파주",
    emoji: "🥐",
    description: "Scenic vegan bakery in Paju — a worthwhile day trip from Seoul. French-style breads and pastries made with plant-based ingredients in a relaxed country setting.",
    descriptionKo: "파주의 풍경 좋은 비건 베이커리 — 서울에서 당일치기 여행으로 가볼 만한 곳. 여유로운 교외 환경에서 즐기는 프랑스풍 비건 빵.",
    mustTry: ["Vegan baguette", "Seasonal croissant"],
    mustTryKo: ["비건 바게트", "시즌 크루아상"],
    priceRange: "₩₩",
    tags: ["Day trip from Seoul", "Outside Seoul", "Scenic"],
    tagsKo: ["서울 당일치기", "서울 외", "경치 좋음"],
  },
];

export function veganListJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    "name": "Vegan Restaurants and Cafes in Seoul",
    "description": "Curated list of vegan-friendly restaurants, cafes, and bakeries across Seoul",
    "numberOfItems": VEGAN_PLACES.length,
    "itemListElement": VEGAN_PLACES.map((p, i) => ({
      "@type": "ListItem",
      "position": i + 1,
      "item": {
        "@type": "FoodEstablishment",
        "name": p.name,
        "description": p.description,
        "address": {
          "@type": "PostalAddress",
          "streetAddress": p.address,
          "addressLocality": "Seoul",
          "addressCountry": "KR",
        },
        "geo": {
          "@type": "GeoCoordinates",
          "latitude": p.lat,
          "longitude": p.lng,
        },
        "priceRange": p.priceRange,
        "servesCuisine": ["Vegan", p.categoryEn],
        "url": p.naverMapsUrl,
      },
    })),
  };
}
