export type VeganPlace = {
  id: string;
  name: string;
  nameEn: string;
  category: string;
  categoryEn: string;
  address: string;
  lat: number;
  lng: number;
  naverMapsUrl: string;
  emoji: string;
};

export const VEGAN_PLACES: VeganPlace[] = [
  // ── Mapo-gu ──────────────────────────────────────────────────
  {
    id: "ramuar",
    name: "라므아르",
    nameEn: "L'amour — Vegan Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 마포구 망원동 380-39 2층",
    lat: 37.5557,
    lng: 126.9076,
    naverMapsUrl: "https://map.naver.com/v5/search/라므아르 망원동",
    emoji: "🥐",
  },
  {
    id: "pool-bakery",
    name: "풀 발효부엌",
    nameEn: "Pool Fermented Kitchen",
    category: "채식뷔페",
    categoryEn: "Vegan Buffet",
    address: "서울 마포구 망원동 404-39 2F",
    lat: 37.5561,
    lng: 126.9068,
    naverMapsUrl: "https://map.naver.com/v5/search/풀 발효부엌",
    emoji: "🥗",
  },
  {
    id: "dakensiel",
    name: "다켄씨엘",
    nameEn: "Dakensiel — Vegan Western",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 마포구 망원동 57-138 1층",
    lat: 37.5548,
    lng: 126.9085,
    naverMapsUrl: "https://map.naver.com/v5/search/다켄씨엘 망원동",
    emoji: "🍽️",
  },
  {
    id: "bigomi",
    name: "비고미",
    nameEn: "Bigomi — Vegan Cafe",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 마포구 망원동 401-2 101호",
    lat: 37.5552,
    lng: 126.9073,
    naverMapsUrl: "https://map.naver.com/v5/search/비고미 망원동",
    emoji: "☕",
  },
  {
    id: "veganidaum",
    name: "비건다움 제과점",
    nameEn: "Veganidaum Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 마포구 성산동 134-2 Agate 상가 104호",
    lat: 37.5661,
    lng: 126.9017,
    naverMapsUrl: "https://map.naver.com/v5/search/비건다움 제과점",
    emoji: "🥐",
  },
  {
    id: "mabbuz",
    name: "마쁘즈 비건케이크",
    nameEn: "Mabbuz — Vegan Cake",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 마포구 합정동 412-2 1층",
    lat: 37.5491,
    lng: 126.9141,
    naverMapsUrl: "https://map.naver.com/v5/search/마쁘즈 비건케이크",
    emoji: "🎂",
  },
  {
    id: "chevalerie",
    name: "세발레리",
    nameEn: "Chevalerie — Vegan Western",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 마포구 합정동 433-61 1층",
    lat: 37.5488,
    lng: 126.9143,
    naverMapsUrl: "https://map.naver.com/v5/search/세발레리 합정",
    emoji: "🌿",
  },
  {
    id: "aroundgreen",
    name: "어라운드그린",
    nameEn: "Around Green",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 마포구 합정동 433-8 2층",
    lat: 37.5489,
    lng: 126.9140,
    naverMapsUrl: "https://map.naver.com/v5/search/어라운드그린 합정",
    emoji: "🌿",
  },
  {
    id: "popobread",
    name: "포포브레드",
    nameEn: "Popo Bread — Vegan Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 마포구 서교동 464-12 세원빌딩 1층",
    lat: 37.5519,
    lng: 126.9241,
    naverMapsUrl: "https://map.naver.com/v5/search/포포브레드 서교동",
    emoji: "🥐",
  },
  {
    id: "immu",
    name: "이뮤 베이크샵",
    nameEn: "Immu Bake Shop",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 마포구 서교동 396-61 2층 202호",
    lat: 37.5520,
    lng: 126.9239,
    naverMapsUrl: "https://map.naver.com/v5/search/이뮤 베이크샵",
    emoji: "☕",
  },
  {
    id: "slunch",
    name: "슬런치 팩토리 홍대점",
    nameEn: "Slunch Factory Hongdae",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 마포구 상수동 72-1",
    lat: 37.5483,
    lng: 126.9207,
    naverMapsUrl: "https://map.naver.com/v5/search/슬런치 팩토리 홍대",
    emoji: "🍽️",
  },
  {
    id: "sunnyhouse",
    name: "써니하우스",
    nameEn: "Sunny House — Vegan Brunch",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 마포구 상수동 341-17 1층",
    lat: 37.5479,
    lng: 126.9213,
    naverMapsUrl: "https://map.naver.com/v5/search/써니하우스 상수동",
    emoji: "☕",
  },
  // ── Seodaemun-gu ─────────────────────────────────────────────
  {
    id: "dajeonghan",
    name: "다정한마음",
    nameEn: "Dajeonghan Maeum",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 서대문구 연희동 727",
    lat: 37.5717,
    lng: 126.9338,
    naverMapsUrl: "https://map.naver.com/v5/search/다정한마음 연희동",
    emoji: "🌿",
  },
  {
    id: "vegis",
    name: "베지스",
    nameEn: "Vegis — Brunch Cafe",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 서대문구 연희동 719-18 1층",
    lat: 37.5721,
    lng: 126.9341,
    naverMapsUrl: "https://map.naver.com/v5/search/베지스 연희동",
    emoji: "☕",
  },
  {
    id: "weirdough",
    name: "위어도우",
    nameEn: "Weirdough — Vegan Pizza",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 서대문구 연희동 703 2층 201호",
    lat: 37.5715,
    lng: 126.9335,
    naverMapsUrl: "https://map.naver.com/v5/search/위어도우 연희동",
    emoji: "🍕",
  },
  {
    id: "veganire",
    name: "비건이레",
    nameEn: "Vegan Ire — Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 서대문구 충정로3가 23-4 1층",
    lat: 37.5578,
    lng: 126.9634,
    naverMapsUrl: "https://map.naver.com/v5/search/비건이레 충정로",
    emoji: "🥐",
  },
  {
    id: "veganique",
    name: "veganique",
    nameEn: "Veganique — Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 서대문구 대현동 34-21",
    lat: 37.5601,
    lng: 126.9397,
    naverMapsUrl: "https://map.naver.com/v5/search/veganique 대현동",
    emoji: "🥐",
  },
  // ── Yongsan-gu ───────────────────────────────────────────────
  {
    id: "gukmin-bread",
    name: "국민빵집 용산 용리단길",
    nameEn: "Gukmin Bakery — Yongsan",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 용산구 한강로1가 181-2 1층",
    lat: 37.5348,
    lng: 126.9659,
    naverMapsUrl: "https://map.naver.com/v5/search/국민빵집 용산 용리단길",
    emoji: "🥐",
  },
  {
    id: "plantude-ipark",
    name: "플랜튜드 아이파크몰 용산점",
    nameEn: "Plantude — iPark Mall Yongsan",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 용산구 한강로3가 40-999 아이파크몰",
    lat: 37.5293,
    lng: 126.9643,
    naverMapsUrl: "https://map.naver.com/v5/search/플랜튜드 아이파크몰 용산",
    emoji: "🌱",
  },
  {
    id: "nonoshop",
    name: "노노샵",
    nameEn: "Nono Shop — Vegan Cafe",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 용산구 이태원동 21-1 202호",
    lat: 37.5344,
    lng: 126.9952,
    naverMapsUrl: "https://map.naver.com/v5/search/노노샵 이태원",
    emoji: "☕",
  },
  // ── Jongno / Jung-gu ─────────────────────────────────────────
  {
    id: "maru-gimbap",
    name: "마루자연식김밥",
    nameEn: "Maru Natural Gimbap",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 종로구 관훈동 192-15 본관 1층 105호",
    lat: 37.5739,
    lng: 126.9857,
    naverMapsUrl: "https://map.naver.com/v5/search/마루자연식김밥",
    emoji: "🍙",
  },
  {
    id: "hidden-gem",
    name: "히든젬 명동",
    nameEn: "Hidden Gem — Vegan Chocolate",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 중구 남산동2가 44 1층",
    lat: 37.5571,
    lng: 126.9983,
    naverMapsUrl: "https://map.naver.com/v5/search/히든젬 명동",
    emoji: "🍫",
  },
  {
    id: "overte",
    name: "오베흐트",
    nameEn: "Overte — Vegan Donuts",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 중구 회현동1가 73-1 1층",
    lat: 37.5577,
    lng: 126.9814,
    naverMapsUrl: "https://map.naver.com/v5/search/오베흐트 회현",
    emoji: "🍩",
  },
  // ── Seocho / Gangnam-gu ───────────────────────────────────────
  {
    id: "swallow",
    name: "스왈로 베이커리 카페",
    nameEn: "Swallow Bakery & Cafe",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 서초구 서초동 1457-2 203호",
    lat: 37.4841,
    lng: 127.0077,
    naverMapsUrl: "https://map.naver.com/v5/search/스왈로 베이커리 서초",
    emoji: "☕",
  },
  {
    id: "cafe-turtle",
    name: "카페 거북이",
    nameEn: "Cafe Turtle — Vegan Desserts",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 서초구 방배동 454-2 1층",
    lat: 37.4812,
    lng: 126.9986,
    naverMapsUrl: "https://map.naver.com/v5/search/카페 거북이 방배",
    emoji: "☕",
  },
  {
    id: "foods-matter",
    name: "푸드더즈매터",
    nameEn: "Foods That Matter",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 서초구 방배동 868-12 지하 1층",
    lat: 37.4809,
    lng: 126.9989,
    naverMapsUrl: "https://map.naver.com/v5/search/푸드더즈매터 방배",
    emoji: "🍽️",
  },
  {
    id: "nammi-plant",
    name: "남미플랜트랩",
    nameEn: "Nammi Plant Lab",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 서초구 방배동 455-20 2층",
    lat: 37.4812,
    lng: 126.9987,
    naverMapsUrl: "https://map.naver.com/v5/search/남미플랜트랩 방배",
    emoji: "🌱",
  },
  {
    id: "lovinghut-land",
    name: "러빙헛 랜드",
    nameEn: "Loving Hut Land — Vegan Buffet",
    category: "채식뷔페",
    categoryEn: "Vegan Buffet",
    address: "서울 강남구 개포동 1230-9 1층",
    lat: 37.4814,
    lng: 127.0465,
    naverMapsUrl: "https://map.naver.com/v5/search/러빙헛 랜드 개포동",
    emoji: "🥗",
  },
  {
    id: "vegigreen",
    name: "베지그린",
    nameEn: "VegiGreen — Vegan Buffet",
    category: "채식뷔페",
    categoryEn: "Vegan Buffet",
    address: "서울 강남구 개포동 1234-8 광민빌딩 1층",
    lat: 37.4815,
    lng: 127.0469,
    naverMapsUrl: "https://map.naver.com/v5/search/베지그린 개포동",
    emoji: "🥗",
  },
  {
    id: "lovinghut-cafe",
    name: "러빙헛 카페",
    nameEn: "Loving Hut Cafe",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 강남구 개포동 1218-16",
    lat: 37.4816,
    lng: 127.0462,
    naverMapsUrl: "https://map.naver.com/v5/search/러빙헛 카페 개포동",
    emoji: "☕",
  },
  {
    id: "plantude-coex",
    name: "플랜튜드 스타필드코엑스점",
    nameEn: "Plantude — Starfield COEX",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 강남구 삼성동 159 스타필드 지하1층 I-111호",
    lat: 37.5125,
    lng: 127.0596,
    naverMapsUrl: "https://map.naver.com/v5/search/플랜튜드 스타필드 코엑스",
    emoji: "🌱",
  },
  // ── Yeongdeungpo / Gwanak-gu ──────────────────────────────────
  {
    id: "soinick",
    name: "소이닉",
    nameEn: "Soinic — Vegan Korean",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 영등포구 양평동2가 31-5 1층",
    lat: 37.5279,
    lng: 126.8888,
    naverMapsUrl: "https://map.naver.com/v5/search/소이닉 영등포",
    emoji: "🍚",
  },
  {
    id: "aseungji",
    name: "아승지",
    nameEn: "Aseungji — Temple Food",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 영등포구 신길동 223-17",
    lat: 37.5082,
    lng: 126.9063,
    naverMapsUrl: "https://map.naver.com/v5/search/아승지 신길동",
    emoji: "🍵",
  },
  {
    id: "veganmama",
    name: "비건마마",
    nameEn: "Vegan Mama — Cafe",
    category: "카페/디저트",
    categoryEn: "Cafe & Dessert",
    address: "서울 관악구 봉천동 871-74 1층",
    lat: 37.4758,
    lng: 126.9567,
    naverMapsUrl: "https://map.naver.com/v5/search/비건마마 봉천동",
    emoji: "☕",
  },
  // ── East Seoul ────────────────────────────────────────────────
  {
    id: "yongtokki",
    name: "용토끼",
    nameEn: "Yong Tokki — Vegan Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 동대문구 이문동 431 단지내 상가",
    lat: 37.5904,
    lng: 127.0631,
    naverMapsUrl: "https://map.naver.com/v5/search/용토끼 이문동",
    emoji: "🥐",
  },
  {
    id: "bakeyourday",
    name: "베이크유어데이",
    nameEn: "Bake Your Day — Vegan Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 광진구 중곡동 165-18 1층",
    lat: 37.5534,
    lng: 127.0762,
    naverMapsUrl: "https://map.naver.com/v5/search/베이크유어데이 중곡동",
    emoji: "🥐",
  },
  {
    id: "omoomu",
    name: "오무오무",
    nameEn: "Omu Omu — Vegan Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 광진구 중곡동 640-7 1층",
    lat: 37.5537,
    lng: 127.0764,
    naverMapsUrl: "https://map.naver.com/v5/search/오무오무 중곡동",
    emoji: "🥐",
  },
  {
    id: "gangnam-lovinghut-realluv",
    name: "러빙헛리얼러브",
    nameEn: "Loving Hut Real Love — Korean",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 성북구 상월곡동 101-2 B106호",
    lat: 37.5974,
    lng: 127.0298,
    naverMapsUrl: "https://map.naver.com/v5/search/러빙헛리얼러브 상월곡동",
    emoji: "🍚",
  },
  {
    id: "vegannature",
    name: "비건네이처",
    nameEn: "Vegan Nature — Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "서울 송파구 송파동 15-7 102, 103호",
    lat: 37.5033,
    lng: 127.1078,
    naverMapsUrl: "https://map.naver.com/v5/search/비건네이처 송파",
    emoji: "🥐",
  },
  {
    id: "rooted",
    name: "루티드",
    nameEn: "Rooted — Vegan Western",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 송파구 방이동 104-3 1층",
    lat: 37.5076,
    lng: 127.1242,
    naverMapsUrl: "https://map.naver.com/v5/search/루티드 방이동",
    emoji: "🌱",
  },
  {
    id: "gonggan-nokeum",
    name: "공간녹음",
    nameEn: "Gonggan Nokeum — Fusion",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 강서구 마곡동 774-4 403호",
    lat: 37.5601,
    lng: 126.8304,
    naverMapsUrl: "https://map.naver.com/v5/search/공간녹음 마곡동",
    emoji: "🌿",
  },
  {
    id: "jigoo-norae",
    name: "지구를 위한 노래",
    nameEn: "A Song for the Earth",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 강동구 둔촌동 622-2 1층",
    lat: 37.4940,
    lng: 127.1353,
    naverMapsUrl: "https://map.naver.com/v5/search/지구를 위한 노래 둔촌동",
    emoji: "🌍",
  },
  {
    id: "plantude-godeok",
    name: "플랜튜드 고덕점",
    nameEn: "Plantude — Godeok",
    category: "식당",
    categoryEn: "Restaurant",
    address: "서울 강동구 고덕동 353-23 415호 4F",
    lat: 37.5537,
    lng: 127.1524,
    naverMapsUrl: "https://map.naver.com/v5/search/플랜튜드 고덕점",
    emoji: "🌱",
  },
  // ── Outside Seoul ─────────────────────────────────────────────
  {
    id: "maison-de-vegan",
    name: "메종드비건",
    nameEn: "Maison de Vegan — Bakery",
    category: "베이커리",
    categoryEn: "Bakery",
    address: "경기도 파주시 목동동 1061-1 1층",
    lat: 37.7964,
    lng: 126.7374,
    naverMapsUrl: "https://map.naver.com/v5/search/메종드비건 파주",
    emoji: "🥐",
  },
];

export function veganListJsonLd() {
  return {
    "@type": "ItemList",
    "name": "Vegan Restaurants and Cafes in Seoul",
    "description": "Curated list of vegan-friendly restaurants, cafes, and bakeries across Seoul",
    "numberOfItems": VEGAN_PLACES.length,
    "itemListElement": VEGAN_PLACES.map((p, i) => ({
      "@type": "ListItem",
      "position": i + 1,
      "item": {
        "@type": "FoodEstablishment",
        "name": p.name,
        "address": {
          "@type": "PostalAddress",
          "streetAddress": p.address,
          "addressLocality": "Seoul",
          "addressCountry": "KR",
        },
        "geo": {
          "@type": "GeoCoordinates",
          "latitude": p.lat,
          "longitude": p.lng,
        },
        "servesCuisine": ["Vegan", p.categoryEn],
        "url": p.naverMapsUrl,
      },
    })),
  };
}
