export const VISA_TYPES = [
  {
    code: "D-2",
    nameEn: "Student Visa",
    nameKo: "학생비자",
    nameJa: "学生ビザ",
    nameZhCN: "学生签证",
    nameZhTW: "學生簽證",
    namePt: "Visto de Estudante",
    nameEs: "Visa de Estudiante",
    purposeEn: "Enrolled in a Korean university or language institute",
    purposeKo: "국내 대학교 또는 어학원 재학",
    purposeJa: "韓国の大学または語学学校に在籍",
    purposeZhCN: "就读于韩国大学或语言学校",
    purposeZhTW: "就讀於韓國大學或語言學校",
    purposePt: "Matriculado em universidade coreana ou instituto de idiomas",
    purposeEs: "Matriculado en universidad o instituto de idiomas coreano",
    durationEn: "Duration of study program, typically 1-2 years",
    durationKo: "수학 기간 (보통 1-2년)",
    durationJa: "在学期間（通常1〜2年）",
    durationZhCN: "学习期间，通常1-2年",
    durationZhTW: "學習期間，通常1-2年",
    durationPt: "Duração do programa de estudos, geralmente 1-2 anos",
    durationEs: "Duración del programa de estudios, generalmente 1-2 años",
    canWork: true,
    workNoteEn: "Part-time work allowed (up to 20 hrs/week with permission)",
    workNoteKo: "허가 시 주 20시간 이내 아르바이트 가능",
    workNoteJa: "許可があれば週20時間以内のアルバイト可",
    workNoteZhCN: "经批准可兼职工作（每周最多20小时）",
    workNoteZhTW: "經批准可兼職工作（每週最多20小時）",
    workNotePt: "Trabalho de meio período permitido (até 20 h/semana com autorização)",
    workNoteEs: "Trabajo a tiempo parcial permitido (hasta 20 h/semana con permiso)",
    requirementsEn: ["University acceptance letter", "Proof of tuition payment", "Bank statement (min $10,000)", "Passport photos"],
    requirementsKo: ["대학 입학허가서", "등록금 납부 증명", "잔고증명서 (최소 1000만원)", "여권 사진"],
    requirementsJa: ["大学入学許可書", "授業料支払い証明", "残高証明書（最低$10,000相当）", "パスポート写真"],
    requirementsZhCN: ["大学录取通知书", "学费支付证明", "银行存款证明（最低$10,000）", "护照照片"],
    requirementsZhTW: ["大學錄取通知書", "學費繳納證明", "銀行存款證明（最低$10,000）", "護照照片"],
    requirementsPt: ["Carta de aceitação da universidade", "Comprovante de pagamento de matrícula", "Extrato bancário (mín. $10.000)", "Fotos de passaporte"],
    requirementsEs: ["Carta de aceptación universitaria", "Comprobante de pago de matrícula", "Estado de cuenta bancario (mín. $10,000)", "Fotos de pasaporte"],
    category: "study",
  },
  {
    code: "D-4",
    nameEn: "General Training Visa",
    nameKo: "일반연수비자",
    nameJa: "一般研修ビザ",
    nameZhCN: "一般培训签证",
    nameZhTW: "一般培訓簽證",
    namePt: "Visto de Treinamento Geral",
    nameEs: "Visa de Entrenamiento General",
    purposeEn: "Korean language studies, short-term training programs",
    purposeKo: "한국어 연수, 단기 교육 프로그램",
    purposeJa: "韓国語研修、短期トレーニングプログラム",
    purposeZhCN: "韩语学习、短期培训项目",
    purposeZhTW: "韓語學習、短期培訓項目",
    purposePt: "Estudos de idioma coreano, programas de treinamento de curto prazo",
    purposeEs: "Estudios de idioma coreano, programas de capacitación a corto plazo",
    durationEn: "Up to 1 year, extendable",
    durationKo: "최대 1년, 연장 가능",
    durationJa: "最長1年、延長可能",
    durationZhCN: "最长1年，可延期",
    durationZhTW: "最長1年，可延期",
    durationPt: "Até 1 ano, prorrogável",
    durationEs: "Hasta 1 año, prorrogable",
    canWork: false,
    workNoteEn: "Work not permitted without additional permission",
    workNoteKo: "별도 허가 없이 취업 불가",
    workNoteJa: "追加許可なしでは就労不可",
    workNoteZhCN: "未经额外许可不得工作",
    workNoteZhTW: "未經額外許可不得工作",
    workNotePt: "Trabalho não permitido sem autorização adicional",
    workNoteEs: "Trabajo no permitido sin permiso adicional",
    requirementsEn: ["Enrollment letter from language school", "Financial proof", "Passport"],
    requirementsKo: ["어학원 등록 확인서", "재정 증명", "여권"],
    requirementsJa: ["語学学校の入学証明書", "財政証明", "パスポート"],
    requirementsZhCN: ["语言学校入学证明", "财力证明", "护照"],
    requirementsZhTW: ["語言學校入學證明", "財力證明", "護照"],
    requirementsPt: ["Carta de matrícula da escola de idiomas", "Comprovante financeiro", "Passaporte"],
    requirementsEs: ["Carta de inscripción de la escuela de idiomas", "Prueba financiera", "Pasaporte"],
    category: "study",
  },
  {
    code: "E-1",
    nameEn: "Professor Visa",
    nameKo: "교수비자",
    nameJa: "教授ビザ",
    nameZhCN: "教授签证",
    nameZhTW: "教授簽證",
    namePt: "Visto de Professor",
    nameEs: "Visa de Profesor",
    purposeEn: "Professors and lecturers at Korean universities",
    purposeKo: "국내 대학교 교수 및 강사",
    purposeJa: "韓国の大学の教授・講師",
    purposeZhCN: "韩国大学教授及讲师",
    purposeZhTW: "韓國大學教授及講師",
    purposePt: "Professores e instrutores em universidades coreanas",
    purposeEs: "Profesores e instructores en universidades coreanas",
    durationEn: "1-2 years, renewable",
    durationKo: "1-2년, 갱신 가능",
    durationJa: "1〜2年、更新可能",
    durationZhCN: "1-2年，可续签",
    durationZhTW: "1-2年，可續簽",
    durationPt: "1-2 anos, renovável",
    durationEs: "1-2 años, renovable",
    canWork: true,
    workNoteEn: "Work permitted at sponsoring institution",
    workNoteKo: "초청 기관에서 취업 가능",
    workNoteJa: "招聘機関での就労可能",
    workNoteZhCN: "可在担保机构工作",
    workNoteZhTW: "可在擔保機構工作",
    workNotePt: "Trabalho permitido na instituição patrocinadora",
    workNoteEs: "Trabajo permitido en la institución patrocinadora",
    requirementsEn: ["Employment contract", "PhD certificate", "University sponsor letter"],
    requirementsKo: ["고용 계약서", "박사학위증", "대학 초청장"],
    requirementsJa: ["雇用契約書", "博士号証明書", "大学の招聘状"],
    requirementsZhCN: ["劳动合同", "博士学位证书", "大学邀请函"],
    requirementsZhTW: ["勞動合同", "博士學位證書", "大學邀請函"],
    requirementsPt: ["Contrato de trabalho", "Certificado de doutorado", "Carta de patrocínio da universidade"],
    requirementsEs: ["Contrato de trabajo", "Certificado de doctorado", "Carta de patrocinio universitario"],
    category: "work",
  },
  {
    code: "E-2",
    nameEn: "English Teacher Visa",
    nameKo: "원어민 영어교사 비자",
    nameJa: "英語教師ビザ",
    nameZhCN: "英语教师签证",
    nameZhTW: "英語教師簽證",
    namePt: "Visto de Professor de Inglês",
    nameEs: "Visa de Profesor de Inglés",
    purposeEn: "Native English speakers teaching at schools, hagwons, or universities",
    purposeKo: "학교, 학원, 대학교 원어민 영어교사",
    purposeJa: "学校・塾・大学での英語ネイティブ教師",
    purposeZhCN: "在学校、补习班或大学任教的英语母语者",
    purposeZhTW: "在學校、補習班或大學任教的英語母語者",
    purposePt: "Falantes nativos de inglês lecionando em escolas, hagwons ou universidades",
    purposeEs: "Hablantes nativos de inglés que enseñan en escuelas, hagwons o universidades",
    durationEn: "1 year (contract-based), renewable",
    durationKo: "1년 (계약 기준), 갱신 가능",
    durationJa: "1年（契約ベース）、更新可能",
    durationZhCN: "1年（合同制），可续签",
    durationZhTW: "1年（合約制），可續簽",
    durationPt: "1 ano (baseado em contrato), renovável",
    durationEs: "1 año (basado en contrato), renovable",
    canWork: true,
    workNoteEn: "Work permitted at sponsoring employer only",
    workNoteKo: "초청 고용주 기관에서만 취업 가능",
    workNoteJa: "招聘雇用主の機関のみ就労可能",
    workNoteZhCN: "仅可在担保雇主处工作",
    workNoteZhTW: "僅可在擔保雇主處工作",
    workNotePt: "Trabalho permitido apenas no empregador patrocinador",
    workNoteEs: "Trabajo permitido solo en el empleador patrocinador",
    requirementsEn: ["Bachelor's degree (any field)", "Criminal background check (apostilled)", "Health certificate", "Employer sponsorship"],
    requirementsKo: ["학사학위 (전공 무관)", "범죄 경력 확인서 (아포스티유)", "건강진단서", "고용주 스폰서십"],
    requirementsJa: ["学士号（専攻不問）", "犯罪経歴証明書（アポスティーユ付き）", "健康診断書", "雇用主のスポンサーシップ"],
    requirementsZhCN: ["学士学位（专业不限）", "无犯罪记录证明（附认证）", "健康证明", "雇主担保"],
    requirementsZhTW: ["學士學位（專業不限）", "無犯罪記錄證明（附認證）", "健康證明", "雇主擔保"],
    requirementsPt: ["Bacharelado (qualquer área)", "Verificação de antecedentes criminais (apostilada)", "Certificado de saúde", "Patrocínio do empregador"],
    requirementsEs: ["Licenciatura (cualquier campo)", "Verificación de antecedentes penales (apostillada)", "Certificado médico", "Patrocinio del empleador"],
    category: "work",
  },
  {
    code: "E-6",
    nameEn: "Arts & Entertainment Visa",
    nameKo: "예술흥행비자",
    nameJa: "芸術興行ビザ",
    nameZhCN: "艺术娱乐签证",
    nameZhTW: "藝術娛樂簽證",
    namePt: "Visto de Artes e Entretenimento",
    nameEs: "Visa de Artes y Entretenimiento",
    purposeEn: "Performing artists, entertainers working in Korea",
    purposeKo: "공연 예술가, 연예인",
    purposeJa: "韓国で活動する舞台芸術家・エンターテイナー",
    purposeZhCN: "在韩从事表演艺术或娱乐业者",
    purposeZhTW: "在韓從事表演藝術或娛樂業者",
    purposePt: "Artistas performáticos e entretenedores trabalhando na Coreia",
    purposeEs: "Artistas y entretenedores que trabajan en Corea",
    durationEn: "Up to 1 year, renewable",
    durationKo: "최대 1년, 갱신 가능",
    durationJa: "最長1年、更新可能",
    durationZhCN: "最长1年，可续签",
    durationZhTW: "最長1年，可續簽",
    durationPt: "Até 1 ano, renovável",
    durationEs: "Hasta 1 año, renovable",
    canWork: true,
    workNoteEn: "Work permitted in the arts/entertainment sector",
    workNoteKo: "예술/공연 분야 취업 가능",
    workNoteJa: "芸術・エンターテインメント分野での就労可能",
    workNoteZhCN: "可在艺术/娱乐领域工作",
    workNoteZhTW: "可在藝術/娛樂領域工作",
    workNotePt: "Trabalho permitido no setor de artes/entretenimento",
    workNoteEs: "Trabajo permitido en el sector de artes/entretenimiento",
    requirementsEn: ["Employment contract", "Portfolio or performance credentials"],
    requirementsKo: ["고용 계약서", "포트폴리오 또는 실적"],
    requirementsJa: ["雇用契約書", "ポートフォリオまたは実績証明"],
    requirementsZhCN: ["劳动合同", "作品集或演出资历证明"],
    requirementsZhTW: ["勞動合同", "作品集或演出資歷證明"],
    requirementsPt: ["Contrato de trabalho", "Portfólio ou credenciais de performance"],
    requirementsEs: ["Contrato de trabajo", "Portafolio o credenciales de actuación"],
    category: "work",
  },
  {
    code: "E-7",
    nameEn: "Specialized Work Visa",
    nameKo: "특정활동비자",
    nameJa: "特定活動ビザ",
    nameZhCN: "特定活动签证",
    nameZhTW: "特定活動簽證",
    namePt: "Visto de Trabalho Especializado",
    nameEs: "Visa de Trabajo Especializado",
    purposeEn: "Skilled professionals in designated fields (IT, engineering, design, etc.)",
    purposeKo: "IT, 엔지니어링, 디자인 등 전문직",
    purposeJa: "IT・エンジニアリング・デザイン等の指定分野の専門職",
    purposeZhCN: "指定领域（IT、工程、设计等）的专业技术人才",
    purposeZhTW: "指定領域（IT、工程、設計等）的專業技術人才",
    purposePt: "Profissionais qualificados em áreas designadas (TI, engenharia, design, etc.)",
    purposeEs: "Profesionales calificados en campos designados (TI, ingeniería, diseño, etc.)",
    durationEn: "1-3 years, renewable",
    durationKo: "1-3년, 갱신 가능",
    durationJa: "1〜3年、更新可能",
    durationZhCN: "1-3年，可续签",
    durationZhTW: "1-3年，可續簽",
    durationPt: "1-3 anos, renovável",
    durationEs: "1-3 años, renovable",
    canWork: true,
    workNoteEn: "Work permitted in the specific designated occupation",
    workNoteKo: "지정된 직종에서 취업 가능",
    workNoteJa: "指定された職種での就労可能",
    workNoteZhCN: "可在指定职业领域工作",
    workNoteZhTW: "可在指定職業領域工作",
    workNotePt: "Trabalho permitido na ocupação designada específica",
    workNoteEs: "Trabajo permitido en la ocupación designada específica",
    requirementsEn: ["Job offer from Korean employer", "Relevant degree + experience", "Employer sponsorship"],
    requirementsKo: ["한국 고용주 채용 확정", "관련 학위 + 경력", "고용주 스폰서십"],
    requirementsJa: ["韓国の雇用主からの内定", "関連学位＋経験", "雇用主のスポンサーシップ"],
    requirementsZhCN: ["韩国雇主的录用通知", "相关学位+工作经验", "雇主担保"],
    requirementsZhTW: ["韓國雇主的錄用通知", "相關學位+工作經驗", "雇主擔保"],
    requirementsPt: ["Oferta de emprego de empregador coreano", "Grau relevante + experiência", "Patrocínio do empregador"],
    requirementsEs: ["Oferta de trabajo de empleador coreano", "Título relevante + experiencia", "Patrocinio del empleador"],
    category: "work",
  },
  {
    code: "F-2",
    nameEn: "Resident Visa",
    nameKo: "거주비자",
    nameJa: "居住ビザ",
    nameZhCN: "居住签证",
    nameZhTW: "居住簽證",
    namePt: "Visto de Residente",
    nameEs: "Visa de Residente",
    purposeEn: "Long-term residents: spouse of Korean citizen, points-based, skilled immigrants",
    purposeKo: "한국인 배우자, 점수제, 숙련 이민자",
    purposeJa: "長期在留者：韓国人配偶者、ポイント制、熟練移民",
    purposeZhCN: "长期居留者：韩国公民配偶、积分制、技术移民",
    purposeZhTW: "長期居留者：韓國公民配偶、積分制、技術移民",
    purposePt: "Residentes de longo prazo: cônjuge de cidadão coreano, sistema de pontos, imigrantes qualificados",
    purposeEs: "Residentes de largo plazo: cónyuge de ciudadano coreano, sistema de puntos, inmigrantes calificados",
    durationEn: "1-3 years, renewable toward F-5",
    durationKo: "1-3년, F-5 영주권으로 갱신 가능",
    durationJa: "1〜3年、F-5永住権へ更新可能",
    durationZhCN: "1-3年，可续签至F-5永久居留",
    durationZhTW: "1-3年，可續簽至F-5永久居留",
    durationPt: "1-3 anos, renovável em direção ao F-5",
    durationEs: "1-3 años, renovable hacia el F-5",
    canWork: true,
    workNoteEn: "Most employment restrictions removed",
    workNoteKo: "대부분의 취업 제한 해제",
    workNoteJa: "ほとんどの就労制限が解除",
    workNoteZhCN: "大部分就业限制已解除",
    workNoteZhTW: "大部分就業限制已解除",
    workNotePt: "A maioria das restrições de emprego removida",
    workNoteEs: "La mayoría de las restricciones laborales eliminadas",
    requirementsEn: ["Marriage certificate (for F-2-1)", "TOPIK score or points system", "Income verification"],
    requirementsKo: ["혼인관계증명서 (F-2-1의 경우)", "TOPIK 점수 또는 점수제", "소득 증명"],
    requirementsJa: ["婚姻関係証明書（F-2-1の場合）", "TOPIKスコアまたはポイント制", "収入証明"],
    requirementsZhCN: ["结婚证（适用于F-2-1）", "TOPIK成绩或积分制", "收入证明"],
    requirementsZhTW: ["結婚證（適用於F-2-1）", "TOPIK成績或積分制", "收入證明"],
    requirementsPt: ["Certidão de casamento (para F-2-1)", "Pontuação TOPIK ou sistema de pontos", "Comprovante de renda"],
    requirementsEs: ["Acta de matrimonio (para F-2-1)", "Puntuación TOPIK o sistema de puntos", "Verificación de ingresos"],
    category: "resident",
  },
  {
    code: "F-4",
    nameEn: "Overseas Korean Visa",
    nameKo: "재외동포비자",
    nameJa: "在外同胞ビザ",
    nameZhCN: "海外韩裔签证",
    nameZhTW: "海外韓裔簽證",
    namePt: "Visto de Coreano do Exterior",
    nameEs: "Visa para Coreanos en el Exterior",
    purposeEn: "Ethnic Koreans with foreign nationality (gyopo)",
    purposeKo: "외국 국적 재외동포 (교포)",
    purposeJa: "外国籍の在外同胞（コリアン・ディアスポラ）",
    purposeZhCN: "拥有外国国籍的海外韩裔（교포）",
    purposeZhTW: "擁有外國國籍的海外韓裔（교포）",
    purposePt: "Coreanos étnicos com nacionalidade estrangeira (gyopo)",
    purposeEs: "Coreanos étnicos con nacionalidad extranjera (gyopo)",
    durationEn: "2 years, renewable indefinitely",
    durationKo: "2년, 무기한 갱신 가능",
    durationJa: "2年、無期限に更新可能",
    durationZhCN: "2年，可无限期续签",
    durationZhTW: "2年，可無限期續簽",
    durationPt: "2 anos, renovável indefinidamente",
    durationEs: "2 años, renovable indefinidamente",
    canWork: true,
    workNoteEn: "Work permitted in most sectors (some restrictions apply)",
    workNoteKo: "대부분의 분야 취업 가능 (일부 제한 있음)",
    workNoteJa: "ほとんどの分野で就労可能（一部制限あり）",
    workNoteZhCN: "大多数行业可就业（部分限制适用）",
    workNoteZhTW: "大多數行業可就業（部分限制適用）",
    workNotePt: "Trabalho permitido na maioria dos setores (algumas restrições se aplicam)",
    workNoteEs: "Trabajo permitido en la mayoría de sectores (algunas restricciones aplican)",
    requirementsEn: ["Proof of Korean ancestry", "Foreign passport", "Family registry documents"],
    requirementsKo: ["한국 혈통 증명", "외국 여권", "가족관계증명서"],
    requirementsJa: ["韓国系血統の証明", "外国パスポート", "家族関係証明書"],
    requirementsZhCN: ["韩国血统证明", "外国护照", "家庭关系证明文件"],
    requirementsZhTW: ["韓國血統證明", "外國護照", "家庭關係證明文件"],
    requirementsPt: ["Comprovante de ascendência coreana", "Passaporte estrangeiro", "Documentos de registro familiar"],
    requirementsEs: ["Prueba de ascendencia coreana", "Pasaporte extranjero", "Documentos de registro familiar"],
    category: "resident",
  },
  {
    code: "F-6",
    nameEn: "Marriage Visa",
    nameKo: "결혼이민비자",
    nameJa: "結婚移民ビザ",
    nameZhCN: "结婚移民签证",
    nameZhTW: "結婚移民簽證",
    namePt: "Visto de Casamento",
    nameEs: "Visa de Matrimonio",
    purposeEn: "Spouse of a Korean national",
    purposeKo: "한국 국민의 배우자",
    purposeJa: "韓国国民の配偶者",
    purposeZhCN: "韩国公民的配偶",
    purposeZhTW: "韓國公民的配偶",
    purposePt: "Cônjuge de um nacional coreano",
    purposeEs: "Cónyuge de un nacional coreano",
    durationEn: "1 year (initial), then 2 years, then F-2 path",
    durationKo: "최초 1년, 이후 2년, F-2 취득 경로",
    durationJa: "初回1年、その後2年、F-2への経路",
    durationZhCN: "首次1年，之后2年，F-2申请路径",
    durationZhTW: "首次1年，之後2年，F-2申請路徑",
    durationPt: "1 ano (inicial), depois 2 anos, depois caminho F-2",
    durationEs: "1 año (inicial), luego 2 años, luego camino F-2",
    canWork: true,
    workNoteEn: "Work permitted without employer sponsorship",
    workNoteKo: "고용주 스폰서십 없이 취업 가능",
    workNoteJa: "雇用主のスポンサーシップなしで就労可能",
    workNoteZhCN: "无需雇主担保即可工作",
    workNoteZhTW: "無需雇主擔保即可工作",
    workNotePt: "Trabalho permitido sem patrocínio do empregador",
    workNoteEs: "Trabajo permitido sin patrocinio del empleador",
    requirementsEn: ["Marriage certificate", "Korean spouse's ID and family registration", "Proof of meeting in person"],
    requirementsKo: ["혼인관계증명서", "한국인 배우자 신분증 및 가족관계증명서", "대면 만남 증명"],
    requirementsJa: ["婚姻証明書", "韓国人配偶者のIDと家族関係証明書", "直接面会の証明"],
    requirementsZhCN: ["结婚证", "韩国配偶的身份证及家庭关系证明", "线下会面证明"],
    requirementsZhTW: ["結婚證", "韓國配偶的身份證及家庭關係證明", "線下會面證明"],
    requirementsPt: ["Certidão de casamento", "Identidade e registro familiar do cônjuge coreano", "Comprovante de encontro presencial"],
    requirementsEs: ["Acta de matrimonio", "ID y registro familiar del cónyuge coreano", "Comprobante de encuentro en persona"],
    category: "resident",
  },
  {
    code: "C-3",
    nameEn: "Short-term Visitor (Tourist)",
    nameKo: "단기방문비자",
    nameJa: "短期訪問（観光）ビザ",
    nameZhCN: "短期访问（旅游）签证",
    nameZhTW: "短期訪問（旅遊）簽證",
    namePt: "Visitante de Curto Prazo (Turista)",
    nameEs: "Visitante a Corto Plazo (Turista)",
    purposeEn: "Tourism, visiting family, short business trips. Many nationalities get 90 days visa-free.",
    purposeKo: "관광, 가족 방문, 단기 출장. 많은 국적자 90일 무비자 입국 가능.",
    purposeJa: "観光、家族訪問、短期出張。多くの国籍が90日間ビザなし入国可能。",
    purposeZhCN: "旅游、探亲、短期商务出行。许多国籍可免签入境90天。",
    purposeZhTW: "旅遊、探親、短期商務出行。許多國籍可免簽入境90天。",
    purposePt: "Turismo, visita a familiares, viagens de negócios de curto prazo. Muitas nacionalidades têm 90 dias sem visto.",
    purposeEs: "Turismo, visita a familiares, viajes de negocios cortos. Muchas nacionalidades tienen 90 días sin visa.",
    durationEn: "Up to 90 days (visa-free for many nationalities)",
    durationKo: "최대 90일 (많은 국적 무비자)",
    durationJa: "最長90日（多くの国籍でビザ免除）",
    durationZhCN: "最长90天（许多国籍免签）",
    durationZhTW: "最長90天（許多國籍免簽）",
    durationPt: "Até 90 dias (isenção de visto para muitas nacionalidades)",
    durationEs: "Hasta 90 días (exención de visa para muchas nacionalidades)",
    canWork: false,
    workNoteEn: "Work strictly prohibited",
    workNoteKo: "취업 엄격히 금지",
    workNoteJa: "就労は厳格に禁止",
    workNoteZhCN: "严禁工作",
    workNoteZhTW: "嚴禁工作",
    workNotePt: "Trabalho estritamente proibido",
    workNoteEs: "Trabajo estrictamente prohibido",
    requirementsEn: ["Valid passport", "Return ticket", "Proof of accommodation"],
    requirementsKo: ["유효한 여권", "귀국 항공권", "숙소 증명"],
    requirementsJa: ["有効なパスポート", "帰国チケット", "宿泊証明"],
    requirementsZhCN: ["有效护照", "回程机票", "住宿证明"],
    requirementsZhTW: ["有效護照", "回程機票", "住宿證明"],
    requirementsPt: ["Passaporte válido", "Passagem de volta", "Comprovante de acomodação"],
    requirementsEs: ["Pasaporte válido", "Billete de vuelta", "Comprobante de alojamiento"],
    category: "tourist",
  },
];

export const VISA_WIZARD_STEPS = [
  {
    id: "purpose",
    questionEn: "Why are you coming to Korea?",
    questionKo: "한국 방문 목적이 무엇인가요?",
    questionJa: "韓国に来る目的は何ですか？",
    questionZhCN: "您来韩国的目的是什么？",
    questionZhTW: "您來韓國的目的是什麼？",
    questionPt: "Por que você está vindo para a Coreia?",
    questionEs: "¿Por qué vienes a Corea?",
    options: [
      {
        id: "study",
        labelEn: "Study / Language school",
        labelKo: "학업 / 어학 연수",
        labelJa: "留学・語学学校",
        labelZhCN: "学习/语言学校",
        labelZhTW: "學習/語言學校",
        labelPt: "Estudo / Escola de idiomas",
        labelEs: "Estudio / Escuela de idiomas",
        emoji: "📚",
      },
      {
        id: "teach",
        labelEn: "Teaching English",
        labelKo: "영어 강사",
        labelJa: "英語教師",
        labelZhCN: "英语教学",
        labelZhTW: "英語教學",
        labelPt: "Ensino de inglês",
        labelEs: "Enseñanza de inglés",
        emoji: "🍎",
      },
      {
        id: "work",
        labelEn: "Work (skilled professional)",
        labelKo: "취업 (전문직)",
        labelJa: "就労（専門職）",
        labelZhCN: "工作（专业人士）",
        labelZhTW: "工作（專業人士）",
        labelPt: "Trabalho (profissional qualificado)",
        labelEs: "Trabajo (profesional calificado)",
        emoji: "💼",
      },
      {
        id: "family",
        labelEn: "Family / Marriage",
        labelKo: "가족 / 결혼",
        labelJa: "家族・結婚",
        labelZhCN: "家庭/婚姻",
        labelZhTW: "家庭/婚姻",
        labelPt: "Família / Casamento",
        labelEs: "Familia / Matrimonio",
        emoji: "❤️",
      },
      {
        id: "gyopo",
        labelEn: "I have Korean heritage",
        labelKo: "재외동포",
        labelJa: "韓国系（在外同胞）",
        labelZhCN: "我有韩国血统",
        labelZhTW: "我有韓國血統",
        labelPt: "Tenho ascendência coreana",
        labelEs: "Tengo ascendencia coreana",
        emoji: "🇰🇷",
      },
      {
        id: "tourist",
        labelEn: "Tourism / Short visit",
        labelKo: "관광 / 단기 방문",
        labelJa: "観光・短期訪問",
        labelZhCN: "旅游/短期访问",
        labelZhTW: "旅遊/短期訪問",
        labelPt: "Turismo / Visita curta",
        labelEs: "Turismo / Visita corta",
        emoji: "✈️",
      },
    ],
  },
  {
    id: "duration",
    questionEn: "How long do you plan to stay?",
    questionKo: "얼마나 체류할 예정인가요?",
    questionJa: "どのくらい滞在する予定ですか？",
    questionZhCN: "您计划停留多长时间？",
    questionZhTW: "您計劃停留多長時間？",
    questionPt: "Por quanto tempo você planeja ficar?",
    questionEs: "¿Cuánto tiempo planeas quedarte?",
    options: [
      {
        id: "short",
        labelEn: "Under 3 months",
        labelKo: "3개월 미만",
        labelJa: "3ヶ月未満",
        labelZhCN: "3个月以内",
        labelZhTW: "3個月以內",
        labelPt: "Menos de 3 meses",
        labelEs: "Menos de 3 meses",
        emoji: "📅",
      },
      {
        id: "medium",
        labelEn: "3 months to 1 year",
        labelKo: "3개월~1년",
        labelJa: "3ヶ月〜1年",
        labelZhCN: "3个月至1年",
        labelZhTW: "3個月至1年",
        labelPt: "3 meses a 1 ano",
        labelEs: "3 meses a 1 año",
        emoji: "🗓️",
      },
      {
        id: "long",
        labelEn: "1-3 years",
        labelKo: "1~3년",
        labelJa: "1〜3年",
        labelZhCN: "1-3年",
        labelZhTW: "1-3年",
        labelPt: "1-3 anos",
        labelEs: "1-3 años",
        emoji: "📆",
      },
      {
        id: "permanent",
        labelEn: "Long-term / permanent",
        labelKo: "장기 / 영구 거주",
        labelJa: "長期・永住",
        labelZhCN: "长期/永久居留",
        labelZhTW: "長期/永久居留",
        labelPt: "Longo prazo / permanente",
        labelEs: "Largo plazo / permanente",
        emoji: "🏡",
      },
    ],
  },
];

// Purpose + duration → visa recommendation
export const VISA_RECOMMENDATIONS: Record<string, {
  code: string;
  noteEn: string; noteKo: string;
  noteJa: string; noteZhCN: string; noteZhTW: string;
  notePt: string; noteEs: string;
}[]> = {
  "study-short": [{ code: "D-4", noteEn: "Language school visa for short-term Korean study", noteKo: "단기 한국어 연수용 비자", noteJa: "短期韓国語研修用ビザ", noteZhCN: "短期韩语学习签证", noteZhTW: "短期韓語學習簽證", notePt: "Visto de escola de idiomas para estudo de curto prazo", noteEs: "Visa de escuela de idiomas para estudio a corto plazo" }],
  "study-medium": [
    { code: "D-4", noteEn: "Language school visa", noteKo: "어학원 비자", noteJa: "語学学校ビザ", noteZhCN: "语言学校签证", noteZhTW: "語言學校簽證", notePt: "Visto de escola de idiomas", noteEs: "Visa de escuela de idiomas" },
    { code: "D-2", noteEn: "If enrolled in a degree program", noteKo: "학위 과정 재학 시", noteJa: "学位プログラムに在籍の場合", noteZhCN: "如就读学位课程", noteZhTW: "如就讀學位課程", notePt: "Se matriculado em um programa de graduação", noteEs: "Si está inscrito en un programa de grado" },
  ],
  "study-long": [{ code: "D-2", noteEn: "University student visa for degree programs", noteKo: "대학교 학위 과정 비자", noteJa: "大学学位プログラム用学生ビザ", noteZhCN: "大学学位课程学生签证", noteZhTW: "大學學位課程學生簽證", notePt: "Visto de estudante universitário para programas de graduação", noteEs: "Visa de estudiante universitario para programas de grado" }],
  "study-permanent": [{ code: "D-2", noteEn: "Start with student visa, build toward F-2", noteKo: "학생 비자로 시작해 F-2로 전환", noteJa: "学生ビザから始めF-2を目指す", noteZhCN: "从学生签证开始，向F-2转变", noteZhTW: "從學生簽證開始，向F-2轉變", notePt: "Comece com visto de estudante, construa caminho para F-2", noteEs: "Comience con visa de estudiante, avance hacia F-2" }],
  "teach-medium": [{ code: "E-2", noteEn: "English teacher visa — most common for native speakers", noteKo: "원어민 영어교사 비자", noteJa: "英語教師ビザ—ネイティブスピーカーに最も一般的", noteZhCN: "英语教师签证—母语者最常见选择", noteZhTW: "英語教師簽證—母語者最常見選擇", notePt: "Visto de professor de inglês — mais comum para falantes nativos", noteEs: "Visa de profesor de inglés — la más común para hablantes nativos" }],
  "teach-long": [{ code: "E-2", noteEn: "English teacher visa, renewable annually", noteKo: "원어민 영어교사 비자, 매년 갱신", noteJa: "英語教師ビザ、毎年更新", noteZhCN: "英语教师签证，每年续签", noteZhTW: "英語教師簽證，每年續簽", notePt: "Visto de professor de inglês, renovável anualmente", noteEs: "Visa de profesor de inglés, renovable anualmente" }],
  "teach-short": [{ code: "E-2", noteEn: "E-2 requires employer sponsorship, minimum ~1 year contracts", noteKo: "E-2는 고용주 스폰서십 필요, 최소 1년 계약", noteJa: "E-2は雇用主のスポンサーシップが必要、最低約1年契約", noteZhCN: "E-2需要雇主担保，合同最短约1年", noteZhTW: "E-2需要雇主擔保，合約最短約1年", notePt: "E-2 exige patrocínio do empregador, contratos mínimos de ~1 ano", noteEs: "E-2 requiere patrocinio del empleador, contratos mínimos de ~1 año" }],
  "teach-permanent": [{ code: "E-2", noteEn: "E-2 is renewed annually — build toward F-2 after 5+ years", noteKo: "E-2는 매년 갱신 — 5년 이상 후 F-2 취득 가능", noteJa: "E-2は毎年更新—5年以上後にF-2取得可能", noteZhCN: "E-2每年续签—5年以上后可获得F-2", noteZhTW: "E-2每年續簽—5年以上後可獲得F-2", notePt: "E-2 é renovado anualmente — construa caminho para F-2 após 5+ anos", noteEs: "E-2 se renueva anualmente — avance hacia F-2 después de 5+ años" }],
  "work-medium": [{ code: "E-7", noteEn: "Specialized work visa for skilled professionals", noteKo: "전문직 특정활동비자", noteJa: "専門職向け特定活動ビザ", noteZhCN: "专业技术人才特定活动签证", noteZhTW: "專業技術人才特定活動簽證", notePt: "Visto de trabalho especializado para profissionais qualificados", noteEs: "Visa de trabajo especializado para profesionales calificados" }],
  "work-long": [{ code: "E-7", noteEn: "Specialized work visa, path to F-2 long-term", noteKo: "E-7 후 F-2 거주비자 취득 가능", noteJa: "専門職ビザ、長期的にはF-2への道", noteZhCN: "专业技术签证，长期可转F-2居住签证", noteZhTW: "專業技術簽證，長期可轉F-2居住簽證", notePt: "Visto de trabalho especializado, caminho para F-2 a longo prazo", noteEs: "Visa de trabajo especializado, camino hacia F-2 a largo plazo" }],
  "work-permanent": [{ code: "E-7", noteEn: "Work visa → F-2 (resident) → F-5 (permanent)", noteKo: "E-7 → F-2 (거주) → F-5 (영주권)", noteJa: "就労ビザ → F-2（居住） → F-5（永住）", noteZhCN: "工作签证 → F-2（居住）→ F-5（永久居留）", noteZhTW: "工作簽證 → F-2（居住）→ F-5（永久居留）", notePt: "Visto de trabalho → F-2 (residente) → F-5 (permanente)", noteEs: "Visa de trabajo → F-2 (residente) → F-5 (permanente)" }],
  "work-short": [{ code: "E-7", noteEn: "Most work visas require at least 1-year contracts", noteKo: "대부분의 취업 비자는 최소 1년 계약 필요", noteJa: "ほとんどの就労ビザは最低1年契約が必要", noteZhCN: "大多数工作签证要求至少1年合同", noteZhTW: "大多數工作簽證要求至少1年合約", notePt: "A maioria dos vistos de trabalho exige contratos de pelo menos 1 ano", noteEs: "La mayoría de las visas de trabajo requieren contratos de al menos 1 año" }],
  "family-medium": [{ code: "F-6", noteEn: "Marriage visa for spouses of Korean nationals", noteKo: "한국인 배우자 결혼이민비자", noteJa: "韓国人配偶者向け結婚移民ビザ", noteZhCN: "韩国公民配偶结婚移民签证", noteZhTW: "韓國公民配偶結婚移民簽證", notePt: "Visto de casamento para cônjuges de nacionais coreanos", noteEs: "Visa de matrimonio para cónyuges de nacionales coreanos" }],
  "family-long": [{ code: "F-6", noteEn: "Marriage visa, leads to F-2 and eventually F-5", noteKo: "결혼이민비자, F-2 → F-5 경로", noteJa: "結婚移民ビザ、F-2そしてF-5へ", noteZhCN: "结婚移民签证，可转F-2再转F-5", noteZhTW: "結婚移民簽證，可轉F-2再轉F-5", notePt: "Visto de casamento, leva ao F-2 e eventualmente ao F-5", noteEs: "Visa de matrimonio, lleva a F-2 y eventualmente a F-5" }],
  "family-permanent": [{ code: "F-6", noteEn: "Marriage visa path: F-6 → F-2 → F-5 permanent", noteKo: "F-6 → F-2 → F-5 영주권", noteJa: "結婚ビザの道：F-6 → F-2 → F-5永住権", noteZhCN: "结婚签证路径：F-6 → F-2 → F-5永久居留", noteZhTW: "結婚簽證路徑：F-6 → F-2 → F-5永久居留", notePt: "Caminho do visto de casamento: F-6 → F-2 → F-5 permanente", noteEs: "Camino de visa de matrimonio: F-6 → F-2 → F-5 permanente" }],
  "family-short": [{ code: "C-3", noteEn: "Short visit to see family — tourist visa or visa-free entry", noteKo: "가족 방문 — 관광 비자 또는 무비자 입국", noteJa: "家族訪問—観光ビザまたはビザ免除入国", noteZhCN: "家庭探访—旅游签证或免签入境", noteZhTW: "家庭探訪—旅遊簽證或免簽入境", notePt: "Visita curta à família — visto de turista ou entrada sem visto", noteEs: "Visita corta a familia — visa de turista o entrada sin visa" }],
  "gyopo-medium": [{ code: "F-4", noteEn: "Overseas Korean visa — minimal restrictions, renewable every 2 years", noteKo: "재외동포비자 — 제한 적고 2년마다 갱신", noteJa: "在外同胞ビザ—制限少なく2年毎に更新", noteZhCN: "海外韩裔签证—限制少，每2年续签", noteZhTW: "海外韓裔簽證—限制少，每2年續簽", notePt: "Visto de coreano do exterior — restrições mínimas, renovável a cada 2 anos", noteEs: "Visa para coreanos en el exterior — restricciones mínimas, renovable cada 2 años" }],
  "gyopo-long": [{ code: "F-4", noteEn: "F-4 is renewable indefinitely and gives most work rights", noteKo: "F-4는 무기한 갱신 가능, 취업 권리 폭넓음", noteJa: "F-4は無期限に更新可能で、ほとんどの就労権を付与", noteZhCN: "F-4可无限期续签，拥有广泛就业权利", noteZhTW: "F-4可無限期續簽，擁有廣泛就業權利", notePt: "F-4 é renovável indefinidamente e dá a maioria dos direitos de trabalho", noteEs: "F-4 es renovable indefinidamente y otorga la mayoría de los derechos laborales" }],
  "gyopo-permanent": [{ code: "F-4", noteEn: "F-4 → F-5 (permanent residency) after 2 years", noteKo: "F-4 → F-5 영주권 취득 가능", noteJa: "F-4 → 2年後にF-5（永住権）取得可能", noteZhCN: "F-4 → 2年后可获F-5永久居留", noteZhTW: "F-4 → 2年後可獲F-5永久居留", notePt: "F-4 → F-5 (residência permanente) após 2 anos", noteEs: "F-4 → F-5 (residencia permanente) después de 2 años" }],
  "gyopo-short": [{ code: "F-4", noteEn: "Even for short stays, F-4 gives you more flexibility than a tourist visa", noteKo: "단기 체류라도 F-4는 관광비자보다 유연함", noteJa: "短期滞在でもF-4は観光ビザより柔軟", noteZhCN: "即使短期停留，F-4也比旅游签证更灵活", noteZhTW: "即使短期停留，F-4也比旅遊簽證更靈活", notePt: "Mesmo para estadias curtas, F-4 oferece mais flexibilidade que um visto de turista", noteEs: "Incluso para estadías cortas, F-4 da más flexibilidad que una visa de turista" }],
  "tourist-short": [{ code: "C-3", noteEn: "Many nationalities get 90 days visa-free. Check your country.", noteKo: "많은 국적자 90일 무비자. 국가 확인 필요.", noteJa: "多くの国籍が90日間ビザ免除。国別に確認を。", noteZhCN: "许多国籍可免签90天，请确认您的国家。", noteZhTW: "許多國籍可免簽90天，請確認您的國家。", notePt: "Muitas nacionalidades têm 90 dias sem visto. Verifique o seu país.", noteEs: "Muchas nacionalidades tienen 90 días sin visa. Verifica tu país." }],
  "tourist-medium": [{ code: "C-3", noteEn: "Tourist visa cannot be extended beyond 90 days. You'll need a different visa for longer stays.", noteKo: "관광 비자는 90일 초과 연장 불가. 장기 체류는 다른 비자 필요.", noteJa: "観光ビザは90日を超えて延長不可。長期滞在には別のビザが必要。", noteZhCN: "旅游签证不能延期超过90天，长期停留需申请其他签证。", noteZhTW: "旅遊簽證不能延期超過90天，長期停留需申請其他簽證。", notePt: "Visto de turista não pode ser estendido além de 90 dias. Você precisará de outro visto para estadias mais longas.", noteEs: "La visa de turista no puede extenderse más de 90 días. Necesitarás otra visa para estadías más largas." }],
  "tourist-long": [{ code: "C-3", noteEn: "A tourist visa won't work for 1+ year stays. Consider switching to a long-term visa type.", noteKo: "1년 이상 체류는 관광비자로 불가. 장기 체류 비자 전환 필요.", noteJa: "1年以上の滞在に観光ビザは使えません。長期ビザへの切り替えを検討してください。", noteZhCN: "旅游签证不适用于1年以上的停留，请考虑转为长期签证。", noteZhTW: "旅遊簽證不適用於1年以上的停留，請考慮轉為長期簽證。", notePt: "Um visto de turista não funciona para estadias de 1+ ano. Considere mudar para um visto de longo prazo.", noteEs: "Una visa de turista no funcionará para estadías de 1+ año. Considera cambiar a un tipo de visa a largo plazo." }],
  "tourist-permanent": [{ code: "C-3", noteEn: "Permanent residence is not possible on a tourist visa. Explore F-2 or F-5 options.", noteKo: "관광비자로 영구 거주 불가. F-2 또는 F-5 비자를 알아보세요.", noteJa: "観光ビザでの永住は不可。F-2またはF-5オプションを検討してください。", noteZhCN: "旅游签证无法永久居留，请了解F-2或F-5签证选项。", noteZhTW: "旅遊簽證無法永久居留，請了解F-2或F-5簽證選項。", notePt: "Residência permanente não é possível com visto de turista. Explore as opções F-2 ou F-5.", noteEs: "La residencia permanente no es posible con visa de turista. Explora las opciones F-2 o F-5." }],
};

export const ARC_STEPS = [
  {
    step: 1,
    titleEn: "Within 90 days of arrival",
    titleKo: "입국 후 90일 이내",
    titleJa: "入国後90日以内",
    titleZhCN: "入境后90天内",
    titleZhTW: "入境後90天內",
    titlePt: "Dentro de 90 dias da chegada",
    titleEs: "Dentro de los 90 días de llegada",
    descEn: "You must register for an ARC (Alien Registration Card) within 90 days of arriving in Korea on a long-stay visa. Failing to register is a violation and can result in fines.",
    descKo: "장기 체류 비자로 입국한 경우 90일 이내에 외국인등록증(ARC)을 신청해야 합니다. 미등록 시 과태료 부과 대상입니다.",
    descJa: "長期滞在ビザで入国後90日以内に外国人登録証（ARC）を申請する必要があります。未登録は違反となり、罰金が科される場合があります。",
    descZhCN: "持长期居留签证入境韩国后，必须在90天内申请外国人登录证（ARC）。未登记属于违规行为，可能导致罚款。",
    descZhTW: "持長期居留簽證入境韓國後，必須在90天內申請外國人登錄證（ARC）。未登記屬於違規行為，可能導致罰款。",
    descPt: "Você deve se registrar para um ARC (Cartão de Registro de Estrangeiro) dentro de 90 dias após chegar à Coreia com um visto de longa permanência. Não se registrar é uma violação e pode resultar em multas.",
    descEs: "Debes registrarte para obtener un ARC (Tarjeta de Registro de Extranjero) dentro de los 90 días de llegar a Corea con una visa de larga estadía. No registrarse es una infracción y puede resultar en multas.",
  },
  {
    step: 2,
    titleEn: "Make an appointment",
    titleKo: "예약하기",
    titleJa: "予約をする",
    titleZhCN: "预约",
    titleZhTW: "預約",
    titlePt: "Agendar uma consulta",
    titleEs: "Hacer una cita",
    descEn: "Book an appointment at the Hi Korea website (hikorea.go.kr) or call 1345 for the nearest immigration office. Walk-ins are possible but wait times can be 2-4 hours.",
    descKo: "하이코리아 (hikorea.go.kr) 에서 예약하거나 1345로 전화해 가까운 출입국 사무소 예약을 하세요. 현장 접수도 가능하지만 대기 2-4시간 예상.",
    descJa: "Hi Koreaウェブサイト（hikorea.go.kr）で予約するか、1345に電話して最寄りの出入国管理局を確認してください。当日受付も可能ですが、待ち時間は2〜4時間になる場合があります。",
    descZhCN: "在Hi Korea网站（hikorea.go.kr）预约，或拨打1345了解最近的出入境管理局。可以现场办理，但等待时间可能为2-4小时。",
    descZhTW: "在Hi Korea網站（hikorea.go.kr）預約，或撥打1345了解最近的出入境管理局。可以現場辦理，但等待時間可能為2-4小時。",
    descPt: "Agende uma consulta no site Hi Korea (hikorea.go.kr) ou ligue para 1345 para o escritório de imigração mais próximo. Entrada sem agendamento é possível, mas os tempos de espera podem ser de 2 a 4 horas.",
    descEs: "Reserva una cita en el sitio web Hi Korea (hikorea.go.kr) o llama al 1345 para la oficina de inmigración más cercana. Es posible ir sin cita, pero los tiempos de espera pueden ser de 2 a 4 horas.",
  },
  {
    step: 3,
    titleEn: "Documents to bring",
    titleKo: "준비 서류",
    titleJa: "持参書類",
    titleZhCN: "需携带的文件",
    titleZhTW: "需攜帶的文件",
    titlePt: "Documentos a trazer",
    titleEs: "Documentos a llevar",
    descEn: "Passport + visa, 2 passport photos (3.5cm x 4.5cm), completed application form, proof of address, fee (30,000 KRW), and any employer/school documents.",
    descKo: "여권+비자, 여권 사진 2매(3.5x4.5cm), 작성된 신청서, 주소 증명서류, 수수료 3만원, 직장/학교 서류 등.",
    descJa: "パスポート＋ビザ、パスポート写真2枚（3.5cm×4.5cm）、記入済み申請書、住所証明、手数料（30,000ウォン）、雇用主・学校書類など。",
    descZhCN: "护照+签证、2张护照照片（3.5cm×4.5cm）、填写完整的申请表、地址证明、费用（30,000韩元）以及雇主/学校相关文件。",
    descZhTW: "護照+簽證、2張護照照片（3.5cm×4.5cm）、填寫完整的申請表、地址證明、費用（30,000韓元）以及雇主/學校相關文件。",
    descPt: "Passaporte + visto, 2 fotos de passaporte (3,5cm x 4,5cm), formulário de inscrição preenchido, comprovante de endereço, taxa (30.000 KRW) e documentos do empregador/escola.",
    descEs: "Pasaporte + visa, 2 fotos de pasaporte (3,5cm x 4,5cm), formulario de solicitud completado, comprobante de domicilio, tarifa (30,000 KRW) y documentos del empleador/escuela.",
  },
  {
    step: 4,
    titleEn: "At the immigration office",
    titleKo: "출입국 사무소에서",
    titleJa: "出入国管理局にて",
    titleZhCN: "在出入境管理局",
    titleZhTW: "在出入境管理局",
    titlePt: "No escritório de imigração",
    titleEs: "En la oficina de inmigración",
    descEn: "Take a number, wait, submit your documents, get fingerprinted. The officer will keep your passport temporarily and give you a receipt.",
    descKo: "번호표 뽑고 대기 후 서류 제출, 지문 등록. 담당자가 여권을 임시 보관하고 영수증을 줍니다.",
    descJa: "番号票を取り、待機後に書類を提出し、指紋登録を行います。担当官がパスポートを一時預かりし、受領証を渡します。",
    descZhCN: "取号等候，提交文件，进行指纹采集。工作人员将临时保管您的护照并给您一张收据。",
    descZhTW: "取號等候，提交文件，進行指紋採集。工作人員將臨時保管您的護照並給您一張收據。",
    descPt: "Pegue uma senha, aguarde, entregue seus documentos, faça o registro de impressão digital. O agente guardará seu passaporte temporariamente e lhe dará um recibo.",
    descEs: "Toma un número, espera, entrega tus documentos, registra tus huellas dactilares. El agente guardará tu pasaporte temporalmente y te dará un recibo.",
  },
  {
    step: 5,
    titleEn: "Processing time",
    titleKo: "처리 기간",
    titleJa: "処理期間",
    titleZhCN: "处理时间",
    titleZhTW: "處理時間",
    titlePt: "Prazo de processamento",
    titleEs: "Tiempo de procesamiento",
    descEn: "About 2-3 weeks. You'll receive a text when ready. You can track status on Hi Korea. Pick up in person at the same office.",
    descKo: "약 2-3주. 완료 시 문자 알림. 하이코리아에서 상태 확인 가능. 동일 사무소에서 직접 수령.",
    descJa: "約2〜3週間。完了時にSMSが届きます。Hi Koreaでステータスを確認できます。同じ事務所で直接受け取ります。",
    descZhCN: "约2-3周。完成后将收到短信通知。可在Hi Korea上追踪状态。在同一办公室亲自领取。",
    descZhTW: "約2-3週。完成後將收到簡訊通知。可在Hi Korea上追蹤狀態。在同一辦公室親自領取。",
    descPt: "Cerca de 2-3 semanas. Você receberá uma mensagem de texto quando estiver pronto. Pode acompanhar o status no Hi Korea. Retirada pessoal no mesmo escritório.",
    descEs: "Aproximadamente 2-3 semanas. Recibirás un mensaje de texto cuando esté listo. Puedes rastrear el estado en Hi Korea. Recoge en persona en la misma oficina.",
  },
];

export const COMMON_PITFALLS = [
  {
    visa: "E-2",
    issueEn: "Working at a second school without permission",
    issueKo: "허가 없이 다른 학원에서 추가 강의",
    issueJa: "許可なく別の学校で追加授業",
    issueZhCN: "未经许可在其他学校兼职任教",
    issueZhTW: "未經許可在其他學校兼職任教",
    issuePt: "Trabalhar em uma segunda escola sem permissão",
    issueEs: "Trabajar en una segunda escuela sin permiso",
    solutionEn: "E-2 holders can only work at their sponsoring employer. Any additional teaching requires a separate work authorization from immigration. Violation can result in deportation.",
    solutionKo: "E-2 비자 소지자는 초청 고용주에서만 일할 수 있습니다. 추가 강의 시 출입국 허가 필요. 위반 시 강제 출국 가능.",
    solutionJa: "E-2保持者は招聘雇用主でのみ就労できます。追加授業には出入国管理局の別途許可が必要です。違反すると強制退去になる場合があります。",
    solutionZhCN: "E-2签证持有人只能在担保雇主处工作。任何额外授课需要向出入境管理局申请单独的工作授权。违规可能导致驱逐出境。",
    solutionZhTW: "E-2簽證持有人只能在擔保雇主處工作。任何額外授課需要向出入境管理局申請單獨的工作授權。違規可能導致驅逐出境。",
    solutionPt: "Detentores do E-2 só podem trabalhar no empregador patrocinador. Qualquer ensino adicional requer uma autorização de trabalho separada da imigração. A violação pode resultar em deportação.",
    solutionEs: "Los titulares de E-2 solo pueden trabajar en su empleador patrocinador. Cualquier enseñanza adicional requiere una autorización de trabajo separada de inmigración. La violación puede resultar en deportación.",
  },
  {
    visa: "D-2/D-4",
    issueEn: "Overstaying during school breaks",
    issueKo: "방학 중 체류 기간 초과",
    issueJa: "学校の休暇中のオーバーステイ",
    issueZhCN: "学校假期期间超期居留",
    issueZhTW: "學校假期期間超期居留",
    issuePt: "Ultrapassar o prazo durante as férias escolares",
    issueEs: "Exceder el tiempo permitido durante las vacaciones escolares",
    solutionEn: "Your visa must be valid even during breaks. Check your visa expiry date — not just your school calendar. Apply for extension at least 2 weeks before expiry.",
    solutionKo: "방학 중에도 비자 유효 기간이 적용됩니다. 학교 일정이 아닌 비자 만료일을 확인하세요. 만료 최소 2주 전에 연장 신청하세요.",
    solutionJa: "休暇中もビザは有効でなければなりません。学校のカレンダーではなくビザの有効期限を確認してください。期限の少なくとも2週間前に更新申請をしてください。",
    solutionZhCN: "即使在假期期间，签证也必须有效。请检查签证到期日，而非学校日历。请在到期前至少2周申请延期。",
    solutionZhTW: "即使在假期期間，簽證也必須有效。請檢查簽證到期日，而非學校日曆。請在到期前至少2週申請延期。",
    solutionPt: "Seu visto deve ser válido mesmo durante as férias. Verifique a data de validade do visto — não apenas o calendário escolar. Solicite a extensão pelo menos 2 semanas antes do vencimento.",
    solutionEs: "Tu visa debe ser válida incluso durante las vacaciones. Verifica la fecha de vencimiento de tu visa, no solo el calendario escolar. Solicita la extensión al menos 2 semanas antes del vencimiento.",
  },
  {
    visa: "All",
    issueEn: "Changing employers/schools without updating ARC",
    issueKo: "직장/학교 변경 후 ARC 미갱신",
    issueJa: "雇用主・学校変更後にARCを更新しない",
    issueZhCN: "更换雇主/学校后未更新外国人登录证",
    issueZhTW: "更換雇主/學校後未更新外國人登錄證",
    issuePt: "Mudar de empregador/escola sem atualizar o ARC",
    issueEs: "Cambiar de empleador/escuela sin actualizar el ARC",
    solutionEn: "You must notify immigration within 15 days of changing employers. Failure to report is technically a violation. Visit your local immigration office or use Hi Korea online.",
    solutionKo: "직장 변경 후 15일 이내에 출입국에 신고해야 합니다. 미신고는 위반 사항입니다. 출입국 사무소 방문 또는 하이코리아 온라인으로 신고하세요.",
    solutionJa: "雇用主変更後15日以内に出入国管理局に届け出る必要があります。未届出は技術的に違反です。最寄りの出入国管理局を訪問するかHi Koreaオンラインを利用してください。",
    solutionZhCN: "更换雇主后必须在15天内通知出入境管理局。未上报在技术上属于违规。请前往当地出入境管理局或使用Hi Korea在线报告。",
    solutionZhTW: "更換雇主後必須在15天內通知出入境管理局。未上報在技術上屬於違規。請前往當地出入境管理局或使用Hi Korea在線報告。",
    solutionPt: "Você deve notificar a imigração dentro de 15 dias após mudar de empregador. Deixar de reportar é tecnicamente uma violação. Visite seu escritório de imigração local ou use o Hi Korea online.",
    solutionEs: "Debes notificar a inmigración dentro de los 15 días posteriores al cambio de empleador. No reportarlo es técnicamente una infracción. Visita tu oficina de inmigración local o usa Hi Korea en línea.",
  },
  {
    visa: "C-3",
    issueEn: "Working on a tourist visa",
    issueKo: "관광 비자로 취업",
    issueJa: "観光ビザでの就労",
    issueZhCN: "持旅游签证工作",
    issueZhTW: "持旅遊簽證工作",
    issuePt: "Trabalhar com visto de turista",
    issueEs: "Trabajar con visa de turista",
    solutionEn: "Any paid work on a C-3 visa is illegal. This includes English tutoring, content creation for Korean companies, and remote work paid by Korean entities. The consequences can be severe.",
    solutionKo: "C-3 비자로의 어떤 유급 활동도 불법입니다. 영어 개인 교습, 한국 회사 콘텐츠 제작, 한국 회사 대상 재택근무 포함. 적발 시 심각한 결과.",
    solutionJa: "C-3ビザでのいかなる有給労働も違法です。英語個人指導、韓国企業向けコンテンツ制作、韓国企業が支払うリモートワークを含みます。結果は深刻になり得ます。",
    solutionZhCN: "持C-3签证从事任何有偿工作均属违法，包括英语家教、为韩国公司创作内容以及韩国公司支付报酬的远程工作。后果可能十分严重。",
    solutionZhTW: "持C-3簽證從事任何有償工作均屬違法，包括英語家教、為韓國公司創作內容以及韓國公司支付報酬的遠程工作。後果可能十分嚴重。",
    solutionPt: "Qualquer trabalho remunerado com visto C-3 é ilegal. Isso inclui tutoria de inglês, criação de conteúdo para empresas coreanas e trabalho remoto pago por entidades coreanas. As consequências podem ser graves.",
    solutionEs: "Cualquier trabajo remunerado con visa C-3 es ilegal. Esto incluye tutorías de inglés, creación de contenido para empresas coreanas y trabajo remoto pagado por entidades coreanas. Las consecuencias pueden ser severas.",
  },
  {
    visa: "F-6",
    issueEn: "Divorce affecting visa status",
    issueKo: "이혼이 비자 자격에 미치는 영향",
    issueJa: "離婚がビザ状況に与える影響",
    issueZhCN: "离婚对签证状态的影响",
    issueZhTW: "離婚對簽證狀態的影響",
    issuePt: "Divórcio afetando o status de visto",
    issueEs: "El divorcio que afecta el estado de la visa",
    solutionEn: "F-6 is tied to your Korean spouse. Divorce doesn't automatically end your visa, but you'll need to notify immigration and may need to transition to another visa type, especially if you have children.",
    solutionKo: "F-6는 한국인 배우자와 연결되어 있습니다. 이혼 시 즉시 비자가 취소되지는 않지만 출입국 신고가 필요하고, 특히 자녀가 있는 경우 다른 비자로 전환이 필요할 수 있습니다.",
    solutionJa: "F-6は韓国人配偶者に紐づいています。離婚しても自動的にビザが失効するわけではありませんが、出入国管理局への届け出が必要で、特に子供がいる場合は別のビザへの切り替えが必要になる場合があります。",
    solutionZhCN: "F-6与您的韩国配偶绑定。离婚不会自动使签证失效，但您需要通知出入境管理局，特别是有子女的情况下，可能需要转为其他签证类型。",
    solutionZhTW: "F-6與您的韓國配偶綁定。離婚不會自動使簽證失效，但您需要通知出入境管理局，特別是有子女的情況下，可能需要轉為其他簽證類型。",
    solutionPt: "F-6 está vinculado ao seu cônjuge coreano. O divórcio não encerra automaticamente seu visto, mas você precisará notificar a imigração e pode precisar fazer a transição para outro tipo de visto, especialmente se tiver filhos.",
    solutionEs: "F-6 está vinculada a tu cónyuge coreano. El divorcio no termina automáticamente tu visa, pero deberás notificar a inmigración y puede que necesites transicionar a otro tipo de visa, especialmente si tienes hijos.",
  },
];

export const IMMIGRATION_OFFICES = [
  { name: "Seoul Immigration Office", nameKo: "서울출입국·외국인청", address: "18 Yangjaecheon-ro, Seocho-gu, Seoul", addressKo: "서울 서초구 양재천로 18", station: "Yangjae (3, Bundang)", phone: "1345" },
  { name: "Seoul Foreign Population Office (Mapo)", nameKo: "마포출장소", address: "27 Eoulmadag-ro, Mapo-gu, Seoul", addressKo: "서울 마포구 어울마당로 27", station: "Hongik University Station", phone: "02-6309-8999" },
  { name: "Seoul Foreign Population Office (Nowon)", nameKo: "노원출장소", address: "8 Harang-ro, Nowon-gu, Seoul", addressKo: "서울 노원구 하랑로 8", station: "Suraksan (7)", phone: "02-6309-8988" },
  { name: "Incheon Immigration Office", nameKo: "인천출입국·외국인청", address: "8 Jajeong-ro, Namdong-gu, Incheon", addressKo: "인천 남동구 자정로 8", station: "Seo-Incheon (1)", phone: "032-890-6100" },
];
