export const VISA_TYPES = [
  {
    code: "D-2",
    nameEn: "Student Visa",
    nameKo: "학생비자",
    nameJa: "学生ビザ",
    nameZhCN: "学生签证",
    nameZhTW: "學生簽證",
    namePt: "Visto de Estudante",
    nameEs: "Visa de Estudiante",
    purposeEn: "Enrolled in a Korean university or language institute",
    purposeKo: "국내 대학교 또는 어학원 재학",
    purposeJa: "韓国の大学または語学学校に在籍",
    purposeZhCN: "就读于韩国大学或语言学校",
    purposeZhTW: "就讀於韓國大學或語言學校",
    purposePt: "Matriculado em universidade coreana ou instituto de idiomas",
    purposeEs: "Matriculado en universidad o instituto de idiomas coreano",
    durationEn: "Duration of study program, typically 1-2 years",
    durationKo: "수학 기간 (보통 1-2년)",
    durationJa: "在学期間（通常1〜2年）",
    durationZhCN: "学习期间，通常1-2年",
    durationZhTW: "學習期間，通常1-2年",
    durationPt: "Duração do programa de estudos, geralmente 1-2 anos",
    durationEs: "Duración del programa de estudios, generalmente 1-2 años",
    canWork: true,
    workNoteEn: "Part-time work allowed (up to 20 hrs/week with permission)",
    workNoteKo: "허가 시 주 20시간 이내 아르바이트 가능",
    workNoteJa: "許可があれば週20時間以内のアルバイト可",
    workNoteZhCN: "经批准可兼职工作（每周最多20小时）",
    workNoteZhTW: "經批准可兼職工作（每週最多20小時）",
    workNotePt: "Trabalho de meio período permitido (até 20 h/semana com autorização)",
    workNoteEs: "Trabajo a tiempo parcial permitido (hasta 20 h/semana con permiso)",
    requirementsEn: ["University acceptance letter", "Proof of tuition payment", "Bank statement (min $10,000)", "Passport photos"],
    requirementsKo: ["대학 입학허가서", "등록금 납부 증명", "잔고증명서 (최소 1000만원)", "여권 사진"],
    requirementsJa: ["大学入学許可書", "授業料支払い証明", "残高証明書（最低$10,000相当）", "パスポート写真"],
    requirementsZhCN: ["大学录取通知书", "学费支付证明", "银行存款证明（最低$10,000）", "护照照片"],
    requirementsZhTW: ["大學錄取通知書", "學費繳納證明", "銀行存款證明（最低$10,000）", "護照照片"],
    requirementsPt: ["Carta de aceitação da universidade", "Comprovante de pagamento de matrícula", "Extrato bancário (mín. $10.000)", "Fotos de passaporte"],
    requirementsEs: ["Carta de aceptación universitaria", "Comprobante de pago de matrícula", "Estado de cuenta bancario (mín. $10,000)", "Fotos de pasaporte"],
    category: "study",
  },
  {
    code: "D-4",
    nameEn: "General Training Visa",
    nameKo: "일반연수비자",
    nameJa: "一般研修ビザ",
    nameZhCN: "一般培训签证",
    nameZhTW: "一般培訓簽證",
    namePt: "Visto de Treinamento Geral",
    nameEs: "Visa de Entrenamiento General",
    purposeEn: "Korean language studies, short-term training programs",
    purposeKo: "한국어 연수, 단기 교육 프로그램",
    purposeJa: "韓国語研修、短期トレーニングプログラム",
    purposeZhCN: "韩语学习、短期培训项目",
    purposeZhTW: "韓語學習、短期培訓項目",
    purposePt: "Estudos de idioma coreano, programas de treinamento de curto prazo",
    purposeEs: "Estudios de idioma coreano, programas de capacitación a corto plazo",
    durationEn: "Up to 1 year, extendable",
    durationKo: "최대 1년, 연장 가능",
    durationJa: "最長1年、延長可能",
    durationZhCN: "最长1年，可延期",
    durationZhTW: "最長1年，可延期",
    durationPt: "Até 1 ano, prorrogável",
    durationEs: "Hasta 1 año, prorrogable",
    canWork: false,
    workNoteEn: "Work not permitted without additional permission",
    workNoteKo: "별도 허가 없이 취업 불가",
    workNoteJa: "追加許可なしでは就労不可",
    workNoteZhCN: "未经额外许可不得工作",
    workNoteZhTW: "未經額外許可不得工作",
    workNotePt: "Trabalho não permitido sem autorização adicional",
    workNoteEs: "Trabajo no permitido sin permiso adicional",
    requirementsEn: ["Enrollment letter from language school", "Financial proof", "Passport"],
    requirementsKo: ["어학원 등록 확인서", "재정 증명", "여권"],
    requirementsJa: ["語学学校の入学証明書", "財政証明", "パスポート"],
    requirementsZhCN: ["语言学校入学证明", "财力证明", "护照"],
    requirementsZhTW: ["語言學校入學證明", "財力證明", "護照"],
    requirementsPt: ["Carta de matrícula da escola de idiomas", "Comprovante financeiro", "Passaporte"],
    requirementsEs: ["Carta de inscripción de la escuela de idiomas", "Prueba financiera", "Pasaporte"],
    category: "study",
  },
  {
    code: "E-1",
    nameEn: "Professor Visa",
    nameKo: "교수비자",
    nameJa: "教授ビザ",
    nameZhCN: "教授签证",
    nameZhTW: "教授簽證",
    namePt: "Visto de Professor",
    nameEs: "Visa de Profesor",
    purposeEn: "Professors and lecturers at Korean universities",
    purposeKo: "국내 대학교 교수 및 강사",
    purposeJa: "韓国の大学の教授・講師",
    purposeZhCN: "韩国大学教授及讲师",
    purposeZhTW: "韓國大學教授及講師",
    purposePt: "Professores e instrutores em universidades coreanas",
    purposeEs: "Profesores e instructores en universidades coreanas",
    durationEn: "1-2 years, renewable",
    durationKo: "1-2년, 갱신 가능",
    durationJa: "1〜2年、更新可能",
    durationZhCN: "1-2年，可续签",
    durationZhTW: "1-2年，可續簽",
    durationPt: "1-2 anos, renovável",
    durationEs: "1-2 años, renovable",
    canWork: true,
    workNoteEn: "Work permitted at sponsoring institution",
    workNoteKo: "초청 기관에서 취업 가능",
    workNoteJa: "招聘機関での就労可能",
    workNoteZhCN: "可在担保机构工作",
    workNoteZhTW: "可在擔保機構工作",
    workNotePt: "Trabalho permitido na instituição patrocinadora",
    workNoteEs: "Trabajo permitido en la institución patrocinadora",
    requirementsEn: ["Employment contract", "PhD certificate", "University sponsor letter"],
    requirementsKo: ["고용 계약서", "박사학위증", "대학 초청장"],
    requirementsJa: ["雇用契約書", "博士号証明書", "大学の招聘状"],
    requirementsZhCN: ["劳动合同", "博士学位证书", "大学邀请函"],
    requirementsZhTW: ["勞動合同", "博士學位證書", "大學邀請函"],
    requirementsPt: ["Contrato de trabalho", "Certificado de doutorado", "Carta de patrocínio da universidade"],
    requirementsEs: ["Contrato de trabajo", "Certificado de doctorado", "Carta de patrocinio universitario"],
    category: "work",
  },
  {
    code: "E-2",
    nameEn: "English Teacher Visa",
    nameKo: "원어민 영어교사 비자",
    nameJa: "英語教師ビザ",
    nameZhCN: "英语教师签证",
    nameZhTW: "英語教師簽證",
    namePt: "Visto de Professor de Inglês",
    nameEs: "Visa de Profesor de Inglés",
    purposeEn: "Native English speakers teaching at schools, hagwons, or universities",
    purposeKo: "학교, 학원, 대학교 원어민 영어교사",
    purposeJa: "学校・塾・大学での英語ネイティブ教師",
    purposeZhCN: "在学校、补习班或大学任教的英语母语者",
    purposeZhTW: "在學校、補習班或大學任教的英語母語者",
    purposePt: "Falantes nativos de inglês lecionando em escolas, hagwons ou universidades",
    purposeEs: "Hablantes nativos de inglés que enseñan en escuelas, hagwons o universidades",
    durationEn: "1 year (contract-based), renewable",
    durationKo: "1년 (계약 기준), 갱신 가능",
    durationJa: "1年（契約ベース）、更新可能",
    durationZhCN: "1年（合同制），可续签",
    durationZhTW: "1年（合約制），可續簽",
    durationPt: "1 ano (baseado em contrato), renovável",
    durationEs: "1 año (basado en contrato), renovable",
    canWork: true,
    workNoteEn: "Work permitted at sponsoring employer only",
    workNoteKo: "초청 고용주 기관에서만 취업 가능",
    workNoteJa: "招聘雇用主の機関のみ就労可能",
    workNoteZhCN: "仅可在担保雇主处工作",
    workNoteZhTW: "僅可在擔保雇主處工作",
    workNotePt: "Trabalho permitido apenas no empregador patrocinador",
    workNoteEs: "Trabajo permitido solo en el empleador patrocinador",
    requirementsEn: ["Bachelor's degree (any field)", "Criminal background check (apostilled, valid within 6 months of submission)", "Health certificate", "Employer sponsorship"],
    requirementsKo: ["학사학위 (전공 무관)", "범죄 경력 확인서 (아포스티유, 제출일 기준 6개월 이내 발급)", "건강진단서", "고용주 스폰서십"],
    requirementsJa: ["学士号（専攻不問）", "犯罪経歴証明書（アポスティーユ付き、提出日から6ヶ月以内に発行）", "健康診断書", "雇用主のスポンサーシップ"],
    requirementsZhCN: ["学士学位（专业不限）", "无犯罪记录证明（附认证，须在提交日期前6个月内开具）", "健康证明", "雇主担保"],
    requirementsZhTW: ["學士學位（專業不限）", "無犯罪記錄證明（附認證，須在提交日期前6個月內開具）", "健康證明", "雇主擔保"],
    requirementsPt: ["Bacharelado (qualquer área)", "Verificação de antecedentes criminais (apostilada, válida dentro de 6 meses da submissão)", "Certificado de saúde", "Patrocínio do empregador"],
    requirementsEs: ["Licenciatura (cualquier campo)", "Verificación de antecedentes penales (apostillada, válida dentro de 6 meses de la presentación)", "Certificado médico", "Patrocinio del empleador"],
    category: "work",
  },
  {
    code: "E-6",
    nameEn: "Arts & Entertainment Visa",
    nameKo: "예술흥행비자",
    nameJa: "芸術興行ビザ",
    nameZhCN: "艺术娱乐签证",
    nameZhTW: "藝術娛樂簽證",
    namePt: "Visto de Artes e Entretenimento",
    nameEs: "Visa de Artes y Entretenimiento",
    purposeEn: "Arts and entertainment professionals: E-6-1 for music, fashion modeling, and performing arts; E-6-2 for hotel and venue entertainment (singers, dancers); E-6-3 for professional athletes and coaches only (not entertainers or models).",
    purposeKo: "예술 및 공연 전문가: E-6-1은 음악, 패션 모델, 공연 예술; E-6-2는 호텔/공연장 엔터테인먼트(가수, 댄서); E-6-3은 프로 운동선수 및 코치 전용(연예인 또는 모델 아님).",
    purposeJa: "芸術・エンターテインメント専門家：E-6-1は音楽・ファッションモデル・舞台芸術；E-6-2はホテル・会場エンターテインメント（歌手・ダンサー）；E-6-3はプロアスリートとコーチのみ（エンターテイナーやモデルは対象外）。",
    purposeZhCN: "艺术及娱乐专业人士：E-6-1适用于音乐、时装模特及表演艺术；E-6-2适用于酒店及场馆娱乐（歌手、舞者）；E-6-3仅适用于职业运动员及教练（不包括艺人或模特）。",
    purposeZhTW: "藝術及娛樂專業人士：E-6-1適用於音樂、時裝模特及表演藝術；E-6-2適用於飯店及場館娛樂（歌手、舞者）；E-6-3僅適用於職業運動員及教練（不包括藝人或模特）。",
    purposePt: "Profissionais de artes e entretenimento: E-6-1 para música, moda e artes cênicas; E-6-2 para entretenimento em hotéis e locais (cantores, dançarinos); E-6-3 apenas para atletas e treinadores profissionais (não para artistas ou modelos).",
    purposeEs: "Profesionales de artes y entretenimiento: E-6-1 para música, moda y artes escénicas; E-6-2 para entretenimiento en hoteles y locales (cantantes, bailarines); E-6-3 solo para atletas y entrenadores profesionales (no para artistas ni modelos).",
    durationEn: "Up to 1 year, renewable",
    durationKo: "최대 1년, 갱신 가능",
    durationJa: "最長1年、更新可能",
    durationZhCN: "最长1年，可续签",
    durationZhTW: "最長1年，可續簽",
    durationPt: "Até 1 ano, renovável",
    durationEs: "Hasta 1 año, renovable",
    canWork: true,
    workNoteEn: "E-6-1 modeling: requires 3+ years documented experience, MCST recommendation letter, and agency registered as 대중문화예술기획업. Bilingual Korean and English contracts required from 2026.",
    workNoteKo: "E-6-1 모델: 3년 이상 입증된 경력, 문화체육관광부(MCST) 추천서, 대중문화예술기획업 등록 에이전시 필요. 2026년부터 한국어/영어 이중 계약서 필수.",
    workNoteJa: "E-6-1モデル：3年以上の証明された経験、MCST推薦状、대중문화예술기획업登録エージェンシーが必要。2026年より韓国語・英語バイリンガル契約書が必須。",
    workNoteZhCN: "E-6-1模特：需要3年以上有记录的经验、MCST推荐信，以及登记为대중문화예술기획업的经纪公司。2026年起须签署韩英双语合同。",
    workNoteZhTW: "E-6-1模特：需要3年以上有記錄的經驗、MCST推薦信，以及登記為대중문화예술기획업的經紀公司。2026年起須簽署韓英雙語合約。",
    workNotePt: "E-6-1 modelagem: requer 3+ anos de experiência documentada, carta de recomendação MCST e agência registrada como 대중문화예술기획업. Contratos bilíngues (coreano e inglês) exigidos a partir de 2026.",
    workNoteEs: "E-6-1 modelado: requiere 3+ años de experiencia documentada, carta de recomendación MCST y agencia registrada como 대중문화예술기획업. Contratos bilingues coreano e inglés requeridos desde 2026.",
    requirementsEn: ["Employment contract (bilingual Korean and English from 2026)", "Portfolio or performance credentials", "Sponsoring agency registered as 대중문화예술기획업 (E-6-1 modeling)", "Medical exam on arrival (HIV, TB, drugs)"],
    requirementsKo: ["고용 계약서 (2026년부터 한국어/영어 이중 계약)", "포트폴리오 또는 실적", "대중문화예술기획업 등록 에이전시 (E-6-1 모델의 경우)", "입국 후 건강검진 (HIV, 결핵, 약물)"],
    requirementsJa: ["雇用契約書（2026年より韓国語・英語バイリンガル）", "ポートフォリオまたは実績証明", "대중문화예술기획업登録エージェンシー（E-6-1モデルの場合）", "入国後の健康診断（HIV・結核・薬物）"],
    requirementsZhCN: ["劳动合同（2026年起须为韩英双语）", "作品集或演出资历证明", "登记为대중문화예술기획업的经纪公司（E-6-1模特须提供）", "入境后体检（HIV、结核、药物）"],
    requirementsZhTW: ["勞動合約（2026年起須為韓英雙語）", "作品集或演出資歷證明", "登記為대중문화예술기획업的經紀公司（E-6-1模特須提供）", "入境後體檢（HIV、結核、藥物）"],
    requirementsPt: ["Contrato de trabalho (bilíngue coreano e inglês a partir de 2026)", "Portfólio ou credenciais de performance", "Agência registrada como 대중문화예술기획업 (modelagem E-6-1)", "Exame médico na chegada (HIV, TB, drogas)"],
    requirementsEs: ["Contrato de trabajo (bilingue coreano e inglés desde 2026)", "Portafolio o credenciales de actuación", "Agencia registrada como 대중문화예술기획업 (modelado E-6-1)", "Examen médico a la llegada (VIH, TB, drogas)"],
    category: "work",
  },
  {
    code: "E-7",
    nameEn: "Specialized Work Visa",
    nameKo: "특정활동비자",
    nameJa: "特定活動ビザ",
    nameZhCN: "特定活动签证",
    nameZhTW: "特定活動簽證",
    namePt: "Visto de Trabalho Especializado",
    nameEs: "Visa de Trabajo Especializado",
    purposeEn: "Skilled professionals in approximately 90 designated occupations (IT, engineering, design, finance, and more). Unified wage standard applies from April 2025.",
    purposeKo: "IT, 엔지니어링, 디자인, 금융 등 약 90개 지정 직종 전문직. 2025년 4월부터 통합 임금 기준 적용.",
    purposeJa: "IT・エンジニアリング・デザイン・金融など約90の指定職種の専門職。2025年4月より統一賃金基準が適用。",
    purposeZhCN: "IT、工程、设计、金融等约90个指定职业的专业技术人才。统一薪资标准自2025年4月起适用。",
    purposeZhTW: "IT、工程、設計、金融等約90個指定職業的專業技術人才。統一薪資標準自2025年4月起適用。",
    purposePt: "Profissionais qualificados em aproximadamente 90 ocupações designadas (TI, engenharia, design, finanças e mais). Padrão salarial unificado vigente a partir de abril de 2025.",
    purposeEs: "Profesionales calificados en aproximadamente 90 ocupaciones designadas (TI, ingeniería, diseño, finanzas y más). Estándar salarial unificado vigente desde abril de 2025.",
    durationEn: "1-3 years, renewable",
    durationKo: "1-3년, 갱신 가능",
    durationJa: "1〜3年、更新可能",
    durationZhCN: "1-3年，可续签",
    durationZhTW: "1-3年，可續簽",
    durationPt: "1-3 anos, renovável",
    durationEs: "1-3 años, renovable",
    canWork: true,
    workNoteEn: "Work permitted in the specific designated occupation only. Unified wage system introduced April 2025; 2026 floor set at KRW 31.12M per year for E-7-1 (effective February 1, 2026). Note: bonuses and allowances generally do not count toward the salary threshold.",
    workNoteKo: "지정된 직종에서만 취업 가능. 통합 임금 기준 2025년 4월 도입; 2026년 E-7-1 최저 연봉 3,112만 원 (2026년 2월 1일부터 적용). 참고: 상여금과 수당은 일반적으로 급여 기준에 포함되지 않습니다.",
    workNoteJa: "指定された職種のみ就労可能。統一賃金制度2025年4月導入；2026年E-7-1最低年収3,112万ウォン（2026年2月1日施行）。注：賞与・手当は通常給与基準に算入されません。",
    workNoteZhCN: "仅可在指定职业领域工作。统一薪资制度于2025年4月推出；2026年E-7-1年薪底线为3,112万韩元（2026年2月1日起生效）。注：奖金和津贴通常不计入薪资门槛。",
    workNoteZhTW: "僅可在指定職業領域工作。統一薪資制度於2025年4月推出；2026年E-7-1年薪底線為3,112萬韓元（2026年2月1日起生效）。注：獎金和津貼通常不計入薪資門檻。",
    workNotePt: "Trabalho permitido apenas na ocupação designada específica. Sistema salarial unificado introduzido em abril de 2025; piso 2026 fixado em KRW 31,12M por ano para E-7-1 (vigente a partir de 1o/fev/2026). Bônus e adicionais geralmente não contam para o piso.",
    workNoteEs: "Trabajo permitido solo en la ocupación designada específica. Sistema salarial unificado introducido en abril 2025; piso 2026 fijado en KRW 31,12M por año para E-7-1 (vigente desde el 1 de febrero de 2026). Bonificaciones y asignaciones generalmente no cuentan hacia el umbral.",
    requirementsEn: ["Job offer from Korean employer in a designated occupation", "Relevant degree plus experience (5-year work experience can substitute for a degree in some cases)", "Employer sponsorship and a specific 고용사유서 (employment justification letter)", "Annual salary of at least KRW 31.12M (2026 floor, E-7-1; base salary only, bonuses excluded)", "Bilingual employment contract recommended; confirm with your employer and immigration consultant"],
    requirementsKo: ["지정 직종 한국 고용주 채용 확정", "관련 학위 + 경력 (일부 직종은 5년 경력으로 학위 대체 가능)", "고용주 스폰서십 및 구체적인 고용사유서", "연봉 최소 3,112만 원 (2026년 기준, E-7-1; 기본급 기준, 상여금 제외)", "한국어/영어 이중 계약서 권장; 고용주 및 행정사와 확인 필요"],
    requirementsJa: ["指定職種での韓国雇用主からの内定", "関連学位＋経験（一部職種では5年経験で学位代替可）", "雇用主のスポンサーシップおよび具体的な고용사유서（雇用理由書）", "年収最低3,112万ウォン（2026年基準、E-7-1；基本給のみ、賞与除く）", "バイリンガル雇用契約書推奨；雇用主および行政士に確認を"],
    requirementsZhCN: ["获得韩国雇主在指定职业的录用通知", "相关学位+工作经验（部分职种可以5年工作经验替代学位）", "雇主担保及具体的고용사유서（雇用理由书）", "年薪至少3,112万韩元（2026年标准，E-7-1；仅基本工资，不含奖金）", "建议提供韩英双语劳动合同；请与雇主及移民顾问确认"],
    requirementsZhTW: ["獲得韓國雇主在指定職業的錄用通知", "相關學位+工作經驗（部分職種可以5年工作經驗替代學位）", "雇主擔保及具體的고용사유서（雇用理由書）", "年薪至少3,112萬韓元（2026年標準，E-7-1；僅基本工資，不含獎金）", "建議提供韓英雙語勞動合約；請與雇主及移民顧問確認"],
    requirementsPt: ["Oferta de emprego de empregador coreano em ocupação designada", "Grau relevante mais experiência (5 anos de experiência podem substituir diploma em alguns casos)", "Patrocínio do empregador e uma 고용사유서 específica (carta de justificativa de emprego)", "Salário anual de pelo menos KRW 31,12M (piso 2026, E-7-1; salário base apenas, bônus excluídos)", "Contrato de trabalho bilíngue recomendado; confirme com seu empregador e consultor de imigração"],
    requirementsEs: ["Oferta de trabajo de empleador coreano en ocupación designada", "Título relevante más experiencia (5 años de experiencia pueden sustituir título en algunos casos)", "Patrocinio del empleador y un 고용사유서 específico (carta de justificación de empleo)", "Salario anual de al menos KRW 31,12M (piso 2026, E-7-1; salario base únicamente, bonificaciones excluidas)", "Contrato de trabajo bilingue recomendado; confirma con tu empleador y consultor de inmigración"],
    category: "work",
  },
  {
    code: "E-9",
    nameEn: "Non-Professional Employment (EPS)",
    nameKo: "비전문취업비자 (고용허가제)",
    nameJa: "非専門就労ビザ（雇用許可制）",
    nameZhCN: "非专业就业签证（雇用许可制度）",
    nameZhTW: "非專業就業簽證（雇用許可制度）",
    namePt: "Visto de Emprego Não Especializado (EPS)",
    nameEs: "Visa de Empleo No Especializado (EPS)",
    purposeEn: "Manufacturing, construction, agriculture, and service work through the Employment Permit System (EPS). Available to nationals from 17 designated countries (Tajikistan added October 2024). 2026 quota: 80,000.",
    purposeKo: "고용허가제(EPS)를 통한 제조업, 건설업, 농업 등 취업. 17개 지정 국가 국민 대상 (2024년 10월 타지키스탄 추가). 2026년 쿼터: 8만 명.",
    purposeJa: "雇用許可制度（EPS）を通じた製造業・建設業・農業などの就労。17の指定国の国民が対象（2024年10月タジキスタン追加）。2026年クォータ：8万人。",
    purposeZhCN: "通过雇用许可制度（EPS）从事制造业、建筑业、农业等工作。适用于17个指定国家国民（2024年10月新增塔吉克斯坦）。2026年配额：8万名。",
    purposeZhTW: "通過雇用許可制度（EPS）從事製造業、建築業、農業等工作。適用於17個指定國家國民（2024年10月新增塔吉克斯坦）。2026年配額：8萬名。",
    purposePt: "Trabalho em manufatura, construção, agricultura e serviços através do Sistema de Permissão de Emprego (EPS). Disponível para nacionais de 17 países designados (Tajiquistão adicionado em outubro de 2024). Cota 2026: 80.000.",
    purposeEs: "Trabajo en manufactura, construcción, agricultura y servicios a través del Sistema de Permiso de Empleo (EPS). Disponible para nacionales de 17 países designados (Tayikistán añadido en octubre de 2024). Cuota 2026: 80,000.",
    durationEn: "Up to 4 years 10 months; sincere-worker extension available",
    durationKo: "최대 4년 10개월; 성실근로자 연장 가능",
    durationJa: "最長4年10ヶ月；誠実労働者延長制度あり",
    durationZhCN: "最长4年10个月；诚实劳动者可申请延期",
    durationZhTW: "最長4年10個月；誠實勞動者可申請延期",
    durationPt: "Até 4 anos e 10 meses; extensão para trabalhador dedicado disponível",
    durationEs: "Hasta 4 años y 10 meses; extensión para trabajador dedicado disponible",
    canWork: true,
    workNoteEn: "Work permitted only at EPS-registered employer. Changing employers requires Ministry of Employment and Labor approval; you cannot simply leave.",
    workNoteKo: "EPS 등록 사업체에서만 취업 가능. 고용주 변경은 고용노동부 승인 필요; 임의 이직 불가.",
    workNoteJa: "EPS登録雇用主のもとでのみ就労可能。雇用主変更には雇用労働省の承認が必要；勝手に退職することはできません。",
    workNoteZhCN: "仅可在EPS注册雇主处就业。更换雇主须经雇佣劳动部批准，不得擅自离职。",
    workNoteZhTW: "僅可在EPS登錄雇主處就業。更換雇主須經雇傭勞動部批准，不得擅自離職。",
    workNotePt: "Trabalho permitido apenas com empregador registrado no EPS. Mudanças de empregador requerem aprovação do Ministério do Emprego e Trabalho; não é possível simplesmente sair.",
    workNoteEs: "Trabajo permitido solo con empleador registrado bajo EPS. Los cambios de empleador requieren aprobación del Ministerio de Empleo y Trabajo; no se puede simplemente renunciar.",
    requirementsEn: ["Pass EPS-TOPIK Korean language test", "Skills assessment (if required for the sector)", "Employer job offer through EPS system", "No prior illegal stay in Korea"],
    requirementsKo: ["EPS-TOPIK 한국어 시험 합격", "기능검정 합격 (업종에 따라)", "EPS 시스템을 통한 고용주 채용 확정", "한국 내 불법 체류 이력 없음"],
    requirementsJa: ["韓国語試験（EPS-TOPIK）合格", "技能試験合格（業種によって）", "EPSシステムを通じた雇用主の内定", "韓国での不法滞在歴なし"],
    requirementsZhCN: ["韩语考试（EPS-TOPIK）合格", "技能评估合格（视行业而定）", "通过EPS系统获得雇主聘用", "无在韩非法居留记录"],
    requirementsZhTW: ["韓語考試（EPS-TOPIK）合格", "技能評估合格（視行業而定）", "透過EPS系統獲得雇主聘用", "無在韓非法居留記錄"],
    requirementsPt: ["Aprovação no teste de coreano EPS-TOPIK", "Avaliação de habilidades (se exigida pelo setor)", "Oferta de emprego do empregador através do sistema EPS", "Sem histórico de estadia ilegal na Coreia"],
    requirementsEs: ["Aprobar el examen de coreano EPS-TOPIK", "Evaluación de habilidades (si es requerida por el sector)", "Oferta de trabajo del empleador a través del sistema EPS", "Sin historial de estadía ilegal en Corea"],
    category: "work",
  },
  {
    code: "D-8",
    nameEn: "Corporate Investment Visa",
    nameKo: "기업투자비자",
    nameJa: "企業投資ビザ",
    nameZhCN: "企业投资签证",
    nameZhTW: "企業投資簽證",
    namePt: "Visto de Investimento Corporativo",
    nameEs: "Visa de Inversión Corporativa",
    purposeEn: "Founders and investors in Korean companies. D-8-4 is a startup-specific track using a points system; patent or utility model registration earns bonus points.",
    purposeKo: "한국 법인 설립자 및 투자자. D-8-4는 점수제 기반 스타트업 창업 트랙으로, 특허 또는 실용신안 등록 시 가점 부여.",
    purposeJa: "韓国法人の設立者・投資家。D-8-4はポイント制を使用したスタートアップ向けトラックで、特許・実用新案登録でボーナスポイントが得られます。",
    purposeZhCN: "韩国公司的创始人及投资者。D-8-4是面向创业的积分制通道，注册专利或实用新型可获得加分。",
    purposeZhTW: "韓國公司的創始人及投資者。D-8-4是面向創業的積分制通道，登記專利或新型專利可獲得加分。",
    purposePt: "Fundadores e investidores em empresas coreanas. D-8-4 é uma trilha específica para startups usando um sistema de pontos; registro de patente ou modelo de utilidade acumula pontos bônus.",
    purposeEs: "Fundadores e inversores en empresas coreanas. D-8-4 es una modalidad específica para startups usando un sistema de puntos; el registro de patente o modelo de utilidad otorga puntos adicionales.",
    durationEn: "1-3 years, renewable",
    durationKo: "1-3년, 갱신 가능",
    durationJa: "1〜3年、更新可能",
    durationZhCN: "1-3年，可续签",
    durationZhTW: "1-3年，可續簽",
    durationPt: "1-3 anos, renovável",
    durationEs: "1-3 años, renovable",
    canWork: true,
    workNoteEn: "Work permitted within the invested company; D-8-4 startup founders can operate their registered business",
    workNoteKo: "투자 법인 내 취업 가능; D-8-4 스타트업 창업자는 등록 사업체 운영 가능",
    workNoteJa: "投資法人内での就労可能；D-8-4スタートアップ創業者は登録事業体の運営が可能",
    workNoteZhCN: "可在投资公司内就业；D-8-4创业者可经营其登记的企业",
    workNoteZhTW: "可在投資公司內就業；D-8-4創業者可經營其登記的企業",
    workNotePt: "Trabalho permitido dentro da empresa investida; fundadores de startup D-8-4 podem operar seu negócio registrado",
    workNoteEs: "Trabajo permitido dentro de la empresa invertida; fundadores de startup D-8-4 pueden operar su negocio registrado",
    requirementsEn: ["Investment of at least KRW 100M in a Korean company (or point system for D-8-4)", "Company registration in Korea", "Business plan or patent portfolio", "Clean financial and criminal record"],
    requirementsKo: ["한국 법인 최소 1억 원 투자 (또는 D-8-4 점수제)", "국내 법인 등록", "사업계획서 또는 특허 포트폴리오", "재정 및 범죄 이력 무결"],
    requirementsJa: ["韓国法人への最低1億ウォン投資（またはD-8-4ポイント制）", "国内法人登録", "事業計画書または特許ポートフォリオ", "財務・犯罪歴のクリーン記録"],
    requirementsZhCN: ["向韩国法人投资至少1亿韩元（或D-8-4积分制）", "在韩国注册公司", "商业计划书或专利组合", "财务及犯罪记录清白"],
    requirementsZhTW: ["向韓國法人投資至少1億韓元（或D-8-4積分制）", "在韓國登記公司", "商業計劃書或專利組合", "財務及犯罪記錄清白"],
    requirementsPt: ["Investimento de pelo menos KRW 100M em uma empresa coreana (ou sistema de pontos para D-8-4)", "Registro de empresa na Coreia", "Plano de negócios ou portfólio de patentes", "Registro financeiro e criminal limpo"],
    requirementsEs: ["Inversión de al menos KRW 100M en una empresa coreana (o sistema de puntos para D-8-4)", "Registro de empresa en Corea", "Plan de negocios o portafolio de patentes", "Historial financiero y criminal limpio"],
    category: "work",
  },
  {
    code: "D-10",
    nameEn: "Job-Seeker Visa",
    nameKo: "구직비자",
    nameJa: "求職ビザ",
    nameZhCN: "求职签证",
    nameZhTW: "求職簽證",
    namePt: "Visto de Procura de Emprego",
    nameEs: "Visa de Búsqueda de Empleo",
    purposeEn: "For those seeking employment in Korea. D-10-1 is the standard track. D-10-T (Top-Tier) is for graduates of top-100 world-ranked master's and PhD programs. Internship cap abolished October 2025.",
    purposeKo: "한국 내 취업 준비자 대상. D-10-1 일반 트랙. D-10-T (탑티어)는 세계 100위권 석박사 과정 졸업자 전용. 2025년 10월 인턴십 상한 폐지.",
    purposeJa: "韓国での就職活動者向け。D-10-1は一般トラック。D-10-T（トップティア）は世界上位100校の修士・博士課程修了者向け。2025年10月にインターンシップ上限廃止。",
    purposeZhCN: "适用于在韩求职者。D-10-1为普通通道。D-10-T（顶尖人才）适用于世界前100名大学硕博士毕业生。2025年10月废除实习上限。",
    purposeZhTW: "適用於在韓求職者。D-10-1為普通通道。D-10-T（頂尖人才）適用於世界前100名大學碩博士畢業生。2025年10月廢除實習上限。",
    purposePt: "Para quem busca emprego na Coreia. D-10-1 é a modalidade padrão. D-10-T (Top-Tier) é para formados em programas de mestrado e doutorado de universidades entre as 100 melhores do mundo. Limite de estágio abolido em outubro de 2025.",
    purposeEs: "Para quienes buscan empleo en Corea. D-10-1 es la modalidad estándar. D-10-T (Top-Tier) es para graduados de programas de maestría y doctorado de universidades entre las 100 mejores del mundo. Límite de pasantías abolido en octubre de 2025.",
    durationEn: "6 months to 2 years depending on track",
    durationKo: "트랙에 따라 6개월~2년",
    durationJa: "トラックによって6ヶ月〜2年",
    durationZhCN: "视通道而定，6个月至2年",
    durationZhTW: "視通道而定，6個月至2年",
    durationPt: "6 meses a 2 anos dependendo da modalidade",
    durationEs: "6 meses a 2 años dependiendo de la modalidad",
    canWork: true,
    workNoteEn: "Internship and part-time work permitted; full employment requires changing to the appropriate work visa (E-7 or similar)",
    workNoteKo: "인턴십 및 아르바이트 가능; 정규직 취업은 해당 취업 비자(E-7 등)로 전환 필요",
    workNoteJa: "インターンシップおよびアルバイト可能；正規雇用は該当する就労ビザ（E-7等）への切り替えが必要",
    workNoteZhCN: "可从事实习及兼职工作；正式就业需转换为相应工作签证（E-7等）",
    workNoteZhTW: "可從事實習及兼職工作；正式就業需轉換為相應工作簽證（E-7等）",
    workNotePt: "Estágio e trabalho de meio período permitidos; emprego integral requer mudança para o visto de trabalho adequado (E-7 ou similar)",
    workNoteEs: "Pasantías y trabajo a tiempo parcial permitidos; el empleo de tiempo completo requiere cambiar a la visa de trabajo adecuada (E-7 o similar)",
    requirementsEn: ["Bachelor's degree minimum", "Proof of job search activities", "Financial sufficiency proof", "For D-10-T: graduate diploma from top-100 ranked university"],
    requirementsKo: ["최소 학사학위", "구직 활동 증빙", "재정 충분성 증명", "D-10-T: 세계 100위권 대학 석박사 졸업증"],
    requirementsJa: ["最低学士号", "就職活動の証明", "財政的充分性の証明", "D-10-T：世界上位100校の修士・博士号"],
    requirementsZhCN: ["最低学士学位", "求职活动证明", "财务充足性证明", "D-10-T：世界前100名大学的硕博士学位证"],
    requirementsZhTW: ["最低學士學位", "求職活動證明", "財務充足性證明", "D-10-T：世界前100名大學的碩博士學位證"],
    requirementsPt: ["Bacharelado no mínimo", "Comprovante de atividades de busca de emprego", "Comprovante de suficiência financeira", "Para D-10-T: diploma de pós-graduação de universidade entre as 100 melhores do mundo"],
    requirementsEs: ["Licenciatura como mínimo", "Prueba de actividades de búsqueda de empleo", "Prueba de suficiencia financiera", "Para D-10-T: diploma de posgrado de universidad entre las 100 mejores del mundo"],
    category: "work",
  },
  {
    code: "F-1-D",
    nameEn: "Workation Visa (Digital Nomad)",
    nameKo: "워케이션비자 (디지털노마드)",
    nameJa: "ワーケーションビザ（デジタルノマド）",
    nameZhCN: "数字游民签证（远程办公）",
    nameZhTW: "數位遊牧簽證（遠端工作）",
    namePt: "Visto de Workation (Nômade Digital)",
    nameEs: "Visa de Workation (Nómada Digital)",
    purposeEn: "Remote workers employed by non-Korean companies who want to live in Korea. Launched January 2024, now a permanent program. Foreign-source income only; no work for Korean clients permitted.",
    purposeKo: "한국 외 기업에 재직 중인 원격근무자 대상. 2024년 1월 도입, 현재 영구 제도. 해외 소득만 허용; 한국 고객사 업무 불가.",
    purposeJa: "韓国以外の企業に雇用されて韓国で生活したいリモートワーカー向け。2024年1月開始、現在は恒久制度。外国源泉所得のみ；韓国クライアントへの業務は不可。",
    purposeZhCN: "受雇于非韩国公司、希望在韩国生活的远程工作者。2024年1月推出，现已成为永久性制度。仅限境外收入；不得为韩国客户提供服务。",
    purposeZhTW: "受雇於非韓國公司、希望在韓國生活的遠端工作者。2024年1月推出，現已成為永久性制度。僅限境外收入；不得為韓國客戶提供服務。",
    purposePt: "Trabalhadores remotos empregados por empresas não coreanas que desejam viver na Coreia. Lançado em janeiro de 2024, agora programa permanente. Apenas renda de fonte estrangeira; trabalho para clientes coreanos não é permitido.",
    purposeEs: "Trabajadores remotos empleados por empresas no coreanas que desean vivir en Corea. Lanzado en enero de 2024, ahora programa permanente. Solo ingresos de fuente extranjera; no se permite trabajar para clientes coreanos.",
    durationEn: "1 year, renewable once (up to 2 years total)",
    durationKo: "1년, 1회 갱신 가능 (최대 2년)",
    durationJa: "1年、1回更新可能（最長2年）",
    durationZhCN: "1年，可续签一次（最长2年）",
    durationZhTW: "1年，可續簽一次（最長2年）",
    durationPt: "1 ano, renovável uma vez (até 2 anos no total)",
    durationEs: "1 año, renovable una vez (hasta 2 años en total)",
    canWork: true,
    workNoteEn: "Remote work for non-Korean employer only. No work for Korean companies or clients is permitted, even informally or unpaid.",
    workNoteKo: "한국 외 고용주에 대한 원격근무만 가능. 한국 기업 또는 고객에 대한 업무는 비공식, 무급이라도 엄격히 금지.",
    workNoteJa: "韓国以外の雇用主へのリモートワークのみ。韓国企業やクライアントへの業務は非公式・無給であっても一切不可。",
    workNoteZhCN: "仅限为非韩国雇主进行远程工作。即使是非正式或无偿，也不得为韩国公司或客户提供任何服务。",
    workNoteZhTW: "僅限為非韓國雇主進行遠端工作。即使是非正式或無償，也不得為韓國公司或客戶提供任何服務。",
    workNotePt: "Apenas trabalho remoto para empregador não coreano. Nenhum trabalho para empresas ou clientes coreanos é permitido, mesmo informalmente ou sem remuneração.",
    workNoteEs: "Solo trabajo remoto para empleador no coreano. No se permite ningún trabajo para empresas o clientes coreanos, ni siquiera de forma informal o sin remuneración.",
    requirementsEn: ["Employment contract with non-Korean company", "Annual income of at least KRW 88M (approx. USD 64,000)", "Minimum 1 year employment with current employer", "Health insurance coverage"],
    requirementsKo: ["한국 외 기업 고용 계약서", "연간 소득 최소 8,800만 원 (약 $64,000)", "현 고용주 재직 1년 이상", "건강보험 가입"],
    requirementsJa: ["韓国以外の企業との雇用契約書", "年収最低8,800万ウォン（約64,000ドル）", "現雇用主への在職1年以上", "健康保険加入証明"],
    requirementsZhCN: ["与非韩国公司签订的劳动合同", "年收入至少8,800万韩元（约64,000美元）", "在现雇主处工作满1年", "医疗保险证明"],
    requirementsZhTW: ["與非韓國公司簽訂的勞動合約", "年收入至少8,800萬韓元（約64,000美元）", "在現雇主處工作滿1年", "醫療保險證明"],
    requirementsPt: ["Contrato de trabalho com empresa não coreana", "Renda anual de pelo menos KRW 88M (aprox. USD 64.000)", "Mínimo 1 ano de emprego com o empregador atual", "Cobertura de seguro saúde"],
    requirementsEs: ["Contrato de trabajo con empresa no coreana", "Ingreso anual de al menos KRW 88M (aprox. USD 64,000)", "Mínimo 1 año de empleo con el empleador actual", "Cobertura de seguro médico"],
    category: "work",
  },
  {
    code: "Top-Tier",
    nameEn: "Top-Tier Talent Visa",
    nameKo: "탑티어비자",
    nameJa: "トップティアビザ",
    nameZhCN: "顶尖人才签证",
    nameZhTW: "頂尖人才簽證",
    namePt: "Visto de Talento de Alto Nível",
    nameEs: "Visa de Talento de Alto Nivel",
    purposeEn: "Elite track for STEM, biotech, and advanced technology professionals. Launched March 2025. Grants F-2 residency immediately; F-5 permanent residency eligible after 3 years. Two routes: academic (Master's plus 8 years at a top global company, or PhD plus 5-year post-doc at 3x GNI salary) or salary shortcut (4x GNI annual salary waives all education and experience requirements).",
    purposeKo: "STEM, 바이오테크, 첨단기술 분야 엘리트 트랙. 2025년 3월 도입. F-2 거주자격 즉시 부여; 3년 후 F-5 영주권 신청 가능. 두 가지 자격 요건: 학력 기반 (석사 + 글로벌 상위 기업 8년 경력 또는 GNI 3배 연봉으로 박사 + 5년 포스트닥) 또는 고연봉 특례 (연봉 GNI 4배 이상 시 학력/경력 면제).",
    purposeJa: "STEM・バイオテク・先端技術分野のエリートトラック。2025年3月開始。F-2居住資格を即時付与；3年後にF-5永住権申請可能。二つのルート：学歴ベース（修士号+グローバル上位企業8年経験、またはGNI3倍給与の博士+5年ポスドク）または給与ショートカット（GNI4倍の年収で学歴・経験要件免除）。",
    purposeZhCN: "STEM、生物技术及先进技术领域精英通道。2025年3月推出。立即授予F-2居住资格；3年后可申请F-5永久居留权。两种资格途径：学历通道（硕士+全球顶级企业8年经验，或博士+3倍GNI薪资的5年博士后）或高薪捷径（年薪达4倍GNI可豁免学历和经验要求）。",
    purposeZhTW: "STEM、生物技術及先進技術領域精英通道。2025年3月推出。立即授予F-2居住資格；3年後可申請F-5永久居留權。兩種資格途徑：學歷通道（碩士+全球頂級企業8年經驗，或博士+3倍GNI薪資的5年博士後）或高薪捷徑（年薪達4倍GNI可豁免學歷和經驗要求）。",
    purposePt: "Trilha de elite para profissionais de STEM, biotecnologia e tecnologia avançada. Lançado em março de 2025. Concede residência F-2 imediatamente; F-5 permanente elegível após 3 anos. Duas rotas: acadêmica (Mestrado mais 8 anos em empresa global de topo, ou Doutorado mais 5 anos de pós-doc com salário 3x GNI) ou atalho salarial (salário anual 4x GNI dispensa todos os requisitos de educação e experiência).",
    purposeEs: "Modalidad de élite para profesionales de STEM, biotecnología y tecnología avanzada. Lanzado en marzo de 2025. Otorga residencia F-2 de inmediato; F-5 permanente elegible después de 3 años. Dos rutas: académica (Maestría más 8 años en empresa global de nivel superior, o Doctorado más 5 años de postdoctorado con salario 3x GNI) o atajo salarial (salario anual 4x GNI exime todos los requisitos de educación y experiencia).",
    durationEn: "2-3 years; F-2 residency granted immediately, F-5 permanent residency eligible after 3 years",
    durationKo: "2-3년; F-2 즉시 부여, 3년 후 F-5 신청 가능",
    durationJa: "2〜3年；F-2即時付与、3年後F-5申請可能",
    durationZhCN: "2-3年；F-2即时授予，3年后可申请F-5",
    durationZhTW: "2-3年；F-2即時授予，3年後可申請F-5",
    durationPt: "2-3 anos; F-2 concedido imediatamente, F-5 elegível após 3 anos",
    durationEs: "2-3 años; F-2 otorgado de inmediato, F-5 elegible después de 3 años",
    canWork: true,
    workNoteEn: "Full employment freedom within advanced technology sectors; employer changes permitted without visa re-sponsorship",
    workNoteKo: "첨단기술 분야 내 자유로운 취업; 비자 재스폰서십 없이 이직 가능",
    workNoteJa: "先端技術分野内での就労完全自由；ビザ再スポンサーなしで転職可能",
    workNoteZhCN: "在先进技术领域内完全自由就业；更换雇主无需重新担保签证",
    workNoteZhTW: "在先進技術領域內完全自由就業；更換雇主無需重新擔保簽證",
    workNotePt: "Liberdade total de emprego em setores de tecnologia avançada; mudanças de empregador permitidas sem novo patrocínio de visto",
    workNoteEs: "Plena libertad de empleo en sectores de tecnología avanzada; cambios de empleador permitidos sin nuevo patrocinio de visa",
    requirementsEn: ["Master's degree plus 8 years at a top global company (Forbes Global 2000, Fortune Global 500, or TIME 100 Most Influential Companies) (academic route A)", "OR PhD plus 5-year post-doc with salary at 3x Korea GNI (academic route B)", "OR annual salary of 4x Korea GNI, no degree or experience required (salary shortcut)", "Employment offer from Korean advanced-technology employer"],
    requirementsKo: ["석사학위 + 글로벌 상위 기업 8년 경력 (Forbes Global 2000, Fortune Global 500, 또는 TIME 100 기준) (학력 트랙 A)", "또는 박사학위 + GNI 3배 연봉으로 5년 포스트닥 (학력 트랙 B)", "또는 연봉 GNI 4배 이상 (고연봉 특례, 학력/경력 불문)", "한국 첨단기술 기업의 채용 확정"],
    requirementsJa: ["修士号+グローバル上位企業8年経験（Forbes Global 2000、Fortune Global 500、またはTIME 100基準）（学歴ルートA）", "または博士号+GNI3倍給与の5年ポスドク（学歴ルートB）", "またはGNI4倍の年収（給与ショートカット、学歴・経験不問）", "韓国先端技術企業からの内定"],
    requirementsZhCN: ["硕士学位+全球顶级企业8年经验（Forbes Global 2000、Fortune Global 500或TIME 100）（学历路线A）", "或博士学位+3倍GNI薪资的5年博士后（学历路线B）", "或年薪达4倍GNI（高薪捷径，不限学历及经验）", "获得韩国先进技术企业录用通知"],
    requirementsZhTW: ["碩士學位+全球頂級企業8年經驗（Forbes Global 2000、Fortune Global 500或TIME 100）（學歷路線A）", "或博士學位+3倍GNI薪資的5年博士後（學歷路線B）", "或年薪達4倍GNI（高薪捷徑，不限學歷及經驗）", "獲得韓國先進技術企業錄用通知"],
    requirementsPt: ["Mestrado mais 8 anos em empresa global de topo (Forbes Global 2000, Fortune Global 500 ou TIME 100) (rota acadêmica A)", "OU Doutorado mais 5 anos de pós-doc com salário 3x GNI da Coreia (rota acadêmica B)", "OU salário anual de 4x GNI da Coreia (atalho salarial, sem requisito de diploma ou experiência)", "Oferta de emprego de empregador coreano de tecnologia avançada"],
    requirementsEs: ["Maestría más 8 años en empresa global de nivel superior (Forbes Global 2000, Fortune Global 500 o TIME 100) (ruta académica A)", "O Doctorado más 5 años de postdoctorado con salario 3x GNI de Corea (ruta académica B)", "O salario anual de 4x GNI de Corea (atajo salarial, sin requisito de título o experiencia)", "Oferta de trabajo de empleador coreano de tecnología avanzada"],
    category: "work",
  },
  {
    code: "K-STAR",
    nameEn: "K-STAR Visa (STEM Fast Track)",
    nameKo: "K-STAR 비자 (이공계 패스트트랙)",
    nameJa: "K-STARビザ（理工系ファストトラック）",
    nameZhCN: "K-STAR签证（理工科快速通道）",
    nameZhTW: "K-STAR簽證（理工科快速通道）",
    namePt: "Visto K-STAR (Via Rápida STEM)",
    nameEs: "Visa K-STAR (Vía Rápida STEM)",
    purposeEn: "Fast track to long-term residency for STEM graduates of Korean universities. Graduates of 32 partner universities (expanded December 2025) qualify for direct F-2 residency with a clear path to F-5 permanent residency.",
    purposeKo: "국내 대학교 이공계 졸업자 대상 장기 체류 패스트트랙. 2025년 12월 기준 32개 협약 대학 졸업자는 F-2 거주비자 직접 취득 가능, F-5 영주권 경로 제공.",
    purposeJa: "韓国の大学STEM課程卒業者向けの長期居留ファストトラック。2025年12月現在32の提携大学の卒業者はF-2居住ビザを直接取得でき、F-5永住権への経路も用意されています。",
    purposeZhCN: "面向韩国大学理工科毕业生的长期居留快速通道。截至2025年12月，32所合作大学的毕业生可直接获得F-2居住签证，并提供F-5永久居留权路径。",
    purposeZhTW: "面向韓國大學理工科畢業生的長期居留快速通道。截至2025年12月，32所合作大學的畢業生可直接獲得F-2居住簽證，並提供F-5永久居留權路徑。",
    purposePt: "Via rápida para residência de longo prazo para graduados em STEM de universidades coreanas. Graduados de 32 universidades parceiras (expandido em dezembro de 2025) se qualificam para residência F-2 direta com caminho claro para residência permanente F-5.",
    purposeEs: "Vía rápida hacia residencia a largo plazo para graduados en STEM de universidades coreanas. Graduados de 32 universidades asociadas (expandido en diciembre de 2025) califican para residencia F-2 directa con un camino claro hacia residencia permanente F-5.",
    durationEn: "Leads to F-2 residency (1-3 years, renewable toward F-5 permanent residency)",
    durationKo: "F-2 거주비자 취득 (1-3년, F-5 영주권으로 갱신 가능)",
    durationJa: "F-2居住ビザ取得（1〜3年、F-5永住権へ更新可能）",
    durationZhCN: "可获F-2居住签证（1-3年，可续签至F-5永久居留）",
    durationZhTW: "可獲F-2居住簽證（1-3年，可續簽至F-5永久居留）",
    durationPt: "Leva à residência F-2 (1-3 anos, renovável para F-5 residência permanente)",
    durationEs: "Lleva a residencia F-2 (1-3 años, renovable hacia F-5 residencia permanente)",
    canWork: true,
    workNoteEn: "F-2 status allows work in most sectors with minimal restrictions",
    workNoteKo: "F-2 상태에서 대부분의 분야 취업 가능, 제한 최소화",
    workNoteJa: "F-2身分はほとんどの分野での就労を認め、制限は最小限",
    workNoteZhCN: "F-2身份允许在大多数行业就业，限制最少",
    workNoteZhTW: "F-2身份允許在大多數行業就業，限制最少",
    workNotePt: "Status F-2 permite trabalho na maioria dos setores com restrições mínimas",
    workNoteEs: "El estatus F-2 permite trabajar en la mayoría de los sectores con restricciones mínimas",
    requirementsEn: ["STEM degree from one of the 32 designated Korean partner universities", "Job offer or proof of enrollment in job-seeking program", "TOPIK level 3 or above recommended", "No serious criminal history"],
    requirementsKo: ["지정 32개 협약 대학 이공계 졸업", "채용 확정 또는 구직 프로그램 등록 증명", "TOPIK 3급 이상 권장", "중대 범죄 이력 없음"],
    requirementsJa: ["32の指定協定大学STEM課程卒業", "内定または求職プログラム登録証明", "TOPIK3級以上推奨", "重大犯罪歴なし"],
    requirementsZhCN: ["在32所指定合作大学完成理工科学位", "获得工作录用或参加求职项目的证明", "推荐TOPIK 3级或以上", "无重大犯罪记录"],
    requirementsZhTW: ["在32所指定合作大學完成理工科學位", "獲得工作錄用或參加求職項目的證明", "推薦TOPIK 3級或以上", "無重大犯罪記錄"],
    requirementsPt: ["Diploma STEM de uma das 32 universidades coreanas parceiras designadas", "Oferta de emprego ou comprovante de inscrição em programa de busca de emprego", "TOPIK nível 3 ou acima recomendado", "Sem histórico criminal grave"],
    requirementsEs: ["Título STEM de una de las 32 universidades coreanas asociadas designadas", "Oferta de trabajo o comprobante de inscripción en programa de búsqueda de empleo", "TOPIK nivel 3 o superior recomendado", "Sin historial criminal grave"],
    category: "work",
  },
  {
    code: "D-4-7",
    nameEn: "K-Culture Training Visa",
    nameKo: "K-컬처 연수비자 (D-4-7)",
    nameJa: "K-カルチャー研修ビザ（D-4-7）",
    nameZhCN: "K-文化培训签证（D-4-7）",
    nameZhTW: "K-文化培訓簽證（D-4-7）",
    namePt: "Visto de Treinamento K-Culture",
    nameEs: "Visa de Entrenamiento K-Culture",
    purposeEn: "Training in K-pop performance, dance, modeling, beauty, and content creation at designated institutions. Part of the D-4 general training family. No audition or agency contract is required to apply.",
    purposeKo: "지정 기관에서 K-팝 공연, 댄스, 모델링, 뷰티, 콘텐츠 창작 연수. D-4 일반연수 계열. 오디션이나 에이전시 계약 없이 신청 가능.",
    purposeJa: "指定機関でのK-POPパフォーマンス・ダンス・モデリング・ビューティー・コンテンツ制作研修。D-4一般研修ファミリーの一部。オーディションや芸能事務所契約なしで申請可能。",
    purposeZhCN: "在指定机构进行K-pop表演、舞蹈、模特、美容及内容创作培训。属于D-4一般培训系列。申请无需通过试镜或签订经纪公司合同。",
    purposeZhTW: "在指定機構進行K-pop表演、舞蹈、模特、美容及內容創作培訓。屬於D-4一般培訓系列。申請無需通過試鏡或簽訂經紀公司合約。",
    purposePt: "Treinamento em performance K-pop, dança, modelagem, beleza e criação de conteúdo em instituições designadas. Parte da família de treinamento geral D-4. Não é necessário audição ou contrato de agência para se inscrever.",
    purposeEs: "Entrenamiento en actuación K-pop, danza, modelado, belleza y creación de contenido en instituciones designadas. Parte de la familia de entrenamiento general D-4. No se requiere audición ni contrato de agencia para postularse.",
    durationEn: "Up to 1 year, extendable",
    durationKo: "최대 1년, 연장 가능",
    durationJa: "最長1年、延長可能",
    durationZhCN: "最长1年，可延期",
    durationZhTW: "最長1年，可延期",
    durationPt: "Até 1 ano, prorrogável",
    durationEs: "Hasta 1 año, prorrogable",
    canWork: false,
    workNoteEn: "Training only; paid performances or modeling jobs require a separate E-6 or C-4 work visa",
    workNoteKo: "연수 전용; 유급 공연 또는 모델 업무는 별도 E-6 또는 C-4 비자 필요",
    workNoteJa: "研修専用；有給パフォーマンスやモデリング業務には別途E-6またはC-4就労ビザが必要",
    workNoteZhCN: "仅限培训；有偿演出或模特工作需另行申请E-6或C-4工作签证",
    workNoteZhTW: "僅限培訓；有償演出或模特工作需另行申請E-6或C-4工作簽證",
    workNotePt: "Somente treinamento; performances pagas ou trabalhos de modelagem requerem visto de trabalho E-6 ou C-4 separado",
    workNoteEs: "Solo entrenamiento; actuaciones pagas o trabajos de modelado requieren una visa de trabajo E-6 o C-4 separada",
    requirementsEn: ["Enrollment letter from designated K-culture training institution", "Financial proof (tuition and living expenses)", "Passport", "No prior illegal stay in Korea"],
    requirementsKo: ["지정 K-컬처 연수 기관 등록 확인서", "재정 증명 (수업료 및 생활비)", "여권", "한국 내 불법 체류 이력 없음"],
    requirementsJa: ["指定K-カルチャー研修機関からの入学証明書", "財政証明（授業料と生活費）", "パスポート", "韓国での不法滞在歴なし"],
    requirementsZhCN: ["指定K-文化培训机构的入学确认函", "财力证明（学费及生活费）", "护照", "无在韩非法居留记录"],
    requirementsZhTW: ["指定K-文化培訓機構的入學確認函", "財力證明（學費及生活費）", "護照", "無在韓非法居留記錄"],
    requirementsPt: ["Carta de matrícula de instituição de treinamento K-culture designada", "Comprovante financeiro (mensalidade e despesas de vida)", "Passaporte", "Sem histórico de estadia ilegal na Coreia"],
    requirementsEs: ["Carta de inscripción de institución de entrenamiento K-culture designada", "Prueba financiera (matrícula y gastos de vida)", "Pasaporte", "Sin historial de estadía ilegal en Corea"],
    category: "study",
  },
  {
    code: "F-2",
    nameEn: "Resident Visa",
    nameKo: "거주비자",
    nameJa: "居住ビザ",
    nameZhCN: "居住签证",
    nameZhTW: "居住簽證",
    namePt: "Visto de Residente",
    nameEs: "Visa de Residente",
    purposeEn: "Long-term residents: spouse of Korean citizen, points-based, skilled immigrants",
    purposeKo: "한국인 배우자, 점수제, 숙련 이민자",
    purposeJa: "長期在留者：韓国人配偶者、ポイント制、熟練移民",
    purposeZhCN: "长期居留者：韩国公民配偶、积分制、技术移民",
    purposeZhTW: "長期居留者：韓國公民配偶、積分制、技術移民",
    purposePt: "Residentes de longo prazo: cônjuge de cidadão coreano, sistema de pontos, imigrantes qualificados",
    purposeEs: "Residentes de largo plazo: cónyuge de ciudadano coreano, sistema de puntos, inmigrantes calificados",
    durationEn: "1-3 years, renewable toward F-5",
    durationKo: "1-3년, F-5 영주권으로 갱신 가능",
    durationJa: "1〜3年、F-5永住権へ更新可能",
    durationZhCN: "1-3年，可续签至F-5永久居留",
    durationZhTW: "1-3年，可續簽至F-5永久居留",
    durationPt: "1-3 anos, renovável em direção ao F-5",
    durationEs: "1-3 años, renovable hacia el F-5",
    canWork: true,
    workNoteEn: "Most employment restrictions removed",
    workNoteKo: "대부분의 취업 제한 해제",
    workNoteJa: "ほとんどの就労制限が解除",
    workNoteZhCN: "大部分就业限制已解除",
    workNoteZhTW: "大部分就業限制已解除",
    workNotePt: "A maioria das restrições de emprego removida",
    workNoteEs: "La mayoría de las restricciones laborales eliminadas",
    requirementsEn: ["Marriage certificate (for F-2-1)", "TOPIK score or points system", "Income verification"],
    requirementsKo: ["혼인관계증명서 (F-2-1의 경우)", "TOPIK 점수 또는 점수제", "소득 증명"],
    requirementsJa: ["婚姻関係証明書（F-2-1の場合）", "TOPIKスコアまたはポイント制", "収入証明"],
    requirementsZhCN: ["结婚证（适用于F-2-1）", "TOPIK成绩或积分制", "收入证明"],
    requirementsZhTW: ["結婚證（適用於F-2-1）", "TOPIK成績或積分制", "收入證明"],
    requirementsPt: ["Certidão de casamento (para F-2-1)", "Pontuação TOPIK ou sistema de pontos", "Comprovante de renda"],
    requirementsEs: ["Acta de matrimonio (para F-2-1)", "Puntuación TOPIK o sistema de puntos", "Verificación de ingresos"],
    category: "resident",
  },
  {
    code: "F-4",
    nameEn: "Overseas Korean Visa",
    nameKo: "재외동포비자",
    nameJa: "在外同胞ビザ",
    nameZhCN: "海外韩裔签证",
    nameZhTW: "海外韓裔簽證",
    namePt: "Visto de Coreano do Exterior",
    nameEs: "Visa para Coreanos en el Exterior",
    purposeEn: "Ethnic Koreans with foreign nationality (gyopo)",
    purposeKo: "외국 국적 재외동포 (교포)",
    purposeJa: "外国籍の在外同胞（コリアン・ディアスポラ）",
    purposeZhCN: "拥有外国国籍的海外韩裔（교포）",
    purposeZhTW: "擁有外國國籍的海外韓裔（교포）",
    purposePt: "Coreanos étnicos com nacionalidade estrangeira (gyopo)",
    purposeEs: "Coreanos étnicos con nacionalidad extranjera (gyopo)",
    durationEn: "2 years, renewable indefinitely",
    durationKo: "2년, 무기한 갱신 가능",
    durationJa: "2年、無期限に更新可能",
    durationZhCN: "2年，可无限期续签",
    durationZhTW: "2年，可無限期續簽",
    durationPt: "2 anos, renovável indefinidamente",
    durationEs: "2 años, renovable indefinidamente",
    canWork: true,
    workNoteEn: "Work permitted in most sectors (some restrictions apply)",
    workNoteKo: "대부분의 분야 취업 가능 (일부 제한 있음)",
    workNoteJa: "ほとんどの分野で就労可能（一部制限あり）",
    workNoteZhCN: "大多数行业可就业（部分限制适用）",
    workNoteZhTW: "大多數行業可就業（部分限制適用）",
    workNotePt: "Trabalho permitido na maioria dos setores (algumas restrições se aplicam)",
    workNoteEs: "Trabajo permitido en la mayoría de sectores (algunas restricciones aplican)",
    requirementsEn: ["Proof of Korean ancestry", "Foreign passport", "Family registry documents"],
    requirementsKo: ["한국 혈통 증명", "외국 여권", "가족관계증명서"],
    requirementsJa: ["韓国系血統の証明", "外国パスポート", "家族関係証明書"],
    requirementsZhCN: ["韩国血统证明", "外国护照", "家庭关系证明文件"],
    requirementsZhTW: ["韓國血統證明", "外國護照", "家庭關係證明文件"],
    requirementsPt: ["Comprovante de ascendência coreana", "Passaporte estrangeiro", "Documentos de registro familiar"],
    requirementsEs: ["Prueba de ascendencia coreana", "Pasaporte extranjero", "Documentos de registro familiar"],
    category: "resident",
  },
  {
    code: "F-6",
    nameEn: "Marriage Visa",
    nameKo: "결혼이민비자",
    nameJa: "結婚移民ビザ",
    nameZhCN: "结婚移民签证",
    nameZhTW: "結婚移民簽證",
    namePt: "Visto de Casamento",
    nameEs: "Visa de Matrimonio",
    purposeEn: "Spouse of a Korean national",
    purposeKo: "한국 국민의 배우자",
    purposeJa: "韓国国民の配偶者",
    purposeZhCN: "韩国公民的配偶",
    purposeZhTW: "韓國公民的配偶",
    purposePt: "Cônjuge de um nacional coreano",
    purposeEs: "Cónyuge de un nacional coreano",
    durationEn: "1 year (initial), then 2 years, then F-2 path",
    durationKo: "최초 1년, 이후 2년, F-2 취득 경로",
    durationJa: "初回1年、その後2年、F-2への経路",
    durationZhCN: "首次1年，之后2年，F-2申请路径",
    durationZhTW: "首次1年，之後2年，F-2申請路徑",
    durationPt: "1 ano (inicial), depois 2 anos, depois caminho F-2",
    durationEs: "1 año (inicial), luego 2 años, luego camino F-2",
    canWork: true,
    workNoteEn: "Work permitted without employer sponsorship",
    workNoteKo: "고용주 스폰서십 없이 취업 가능",
    workNoteJa: "雇用主のスポンサーシップなしで就労可能",
    workNoteZhCN: "无需雇主担保即可工作",
    workNoteZhTW: "無需雇主擔保即可工作",
    workNotePt: "Trabalho permitido sem patrocínio do empregador",
    workNoteEs: "Trabajo permitido sin patrocinio del empleador",
    requirementsEn: ["Marriage certificate", "Korean spouse's ID and family registration", "Proof of meeting in person"],
    requirementsKo: ["혼인관계증명서", "한국인 배우자 신분증 및 가족관계증명서", "대면 만남 증명"],
    requirementsJa: ["婚姻証明書", "韓国人配偶者のIDと家族関係証明書", "直接面会の証明"],
    requirementsZhCN: ["结婚证", "韩国配偶的身份证及家庭关系证明", "线下会面证明"],
    requirementsZhTW: ["結婚證", "韓國配偶的身份證及家庭關係證明", "線下會面證明"],
    requirementsPt: ["Certidão de casamento", "Identidade e registro familiar do cônjuge coreano", "Comprovante de encontro presencial"],
    requirementsEs: ["Acta de matrimonio", "ID y registro familiar del cónyuge coreano", "Comprobante de encuentro en persona"],
    category: "resident",
  },
  {
    code: "C-3",
    nameEn: "Short-term Visitor (Tourist)",
    nameKo: "단기방문비자",
    nameJa: "短期訪問（観光）ビザ",
    nameZhCN: "短期访问（旅游）签证",
    nameZhTW: "短期訪問（旅遊）簽證",
    namePt: "Visitante de Curto Prazo (Turista)",
    nameEs: "Visitante a Corto Plazo (Turista)",
    purposeEn: "Tourism, visiting family, short business trips. Many nationalities get 90 days visa-free.",
    purposeKo: "관광, 가족 방문, 단기 출장. 많은 국적자 90일 무비자 입국 가능.",
    purposeJa: "観光、家族訪問、短期出張。多くの国籍が90日間ビザなし入国可能。",
    purposeZhCN: "旅游、探亲、短期商务出行。许多国籍可免签入境90天。",
    purposeZhTW: "旅遊、探親、短期商務出行。許多國籍可免簽入境90天。",
    purposePt: "Turismo, visita a familiares, viagens de negócios de curto prazo. Muitas nacionalidades têm 90 dias sem visto.",
    purposeEs: "Turismo, visita a familiares, viajes de negocios cortos. Muchas nacionalidades tienen 90 días sin visa.",
    durationEn: "Up to 90 days (visa-free for many nationalities)",
    durationKo: "최대 90일 (많은 국적 무비자)",
    durationJa: "最長90日（多くの国籍でビザ免除）",
    durationZhCN: "最长90天（许多国籍免签）",
    durationZhTW: "最長90天（許多國籍免簽）",
    durationPt: "Até 90 dias (isenção de visto para muitas nacionalidades)",
    durationEs: "Hasta 90 días (exención de visa para muchas nacionalidades)",
    canWork: false,
    workNoteEn: "Work strictly prohibited",
    workNoteKo: "취업 엄격히 금지",
    workNoteJa: "就労は厳格に禁止",
    workNoteZhCN: "严禁工作",
    workNoteZhTW: "嚴禁工作",
    workNotePt: "Trabalho estritamente proibido",
    workNoteEs: "Trabajo estrictamente prohibido",
    requirementsEn: ["Valid passport", "Return ticket", "Proof of accommodation"],
    requirementsKo: ["유효한 여권", "귀국 항공권", "숙소 증명"],
    requirementsJa: ["有効なパスポート", "帰国チケット", "宿泊証明"],
    requirementsZhCN: ["有效护照", "回程机票", "住宿证明"],
    requirementsZhTW: ["有效護照", "回程機票", "住宿證明"],
    requirementsPt: ["Passaporte válido", "Passagem de volta", "Comprovante de acomodação"],
    requirementsEs: ["Pasaporte válido", "Billete de vuelta", "Comprobante de alojamiento"],
    category: "tourist",
  },
];

export const VISA_WIZARD_STEPS = [
  {
    id: "purpose",
    questionEn: "Why are you coming to Korea?",
    questionKo: "한국 방문 목적이 무엇인가요?",
    questionJa: "韓国に来る目的は何ですか？",
    questionZhCN: "您来韩国的目的是什么？",
    questionZhTW: "您來韓國的目的是什麼？",
    questionPt: "Por que você está vindo para a Coreia?",
    questionEs: "¿Por qué vienes a Corea?",
    options: [
      {
        id: "study",
        labelEn: "Study / Language school",
        labelKo: "학업 / 어학 연수",
        labelJa: "留学・語学学校",
        labelZhCN: "学习/语言学校",
        labelZhTW: "學習/語言學校",
        labelPt: "Estudo / Escola de idiomas",
        labelEs: "Estudio / Escuela de idiomas",
        emoji: "📚",
      },
      {
        id: "teach",
        labelEn: "Teaching English",
        labelKo: "영어 강사",
        labelJa: "英語教師",
        labelZhCN: "英语教学",
        labelZhTW: "英語教學",
        labelPt: "Ensino de inglês",
        labelEs: "Enseñanza de inglés",
        emoji: "🍎",
      },
      {
        id: "work",
        labelEn: "Work (skilled professional)",
        labelKo: "취업 (전문직)",
        labelJa: "就労（専門職）",
        labelZhCN: "工作（专业人士）",
        labelZhTW: "工作（專業人士）",
        labelPt: "Trabalho (profissional qualificado)",
        labelEs: "Trabajo (profesional calificado)",
        emoji: "💼",
      },
      {
        id: "family",
        labelEn: "Family / Marriage",
        labelKo: "가족 / 결혼",
        labelJa: "家族・結婚",
        labelZhCN: "家庭/婚姻",
        labelZhTW: "家庭/婚姻",
        labelPt: "Família / Casamento",
        labelEs: "Familia / Matrimonio",
        emoji: "❤️",
      },
      {
        id: "gyopo",
        labelEn: "I have Korean heritage",
        labelKo: "재외동포",
        labelJa: "韓国系（在外同胞）",
        labelZhCN: "我有韩国血统",
        labelZhTW: "我有韓國血統",
        labelPt: "Tenho ascendência coreana",
        labelEs: "Tengo ascendencia coreana",
        emoji: "🇰🇷",
      },
      {
        id: "tourist",
        labelEn: "Tourism / Short visit",
        labelKo: "관광 / 단기 방문",
        labelJa: "観光・短期訪問",
        labelZhCN: "旅游/短期访问",
        labelZhTW: "旅遊/短期訪問",
        labelPt: "Turismo / Visita curta",
        labelEs: "Turismo / Visita corta",
        emoji: "✈️",
      },
      {
        id: "remote",
        labelEn: "Remote work for foreign company",
        labelKo: "해외 기업 원격근무",
        labelJa: "外国企業へのリモートワーク",
        labelZhCN: "为境外公司远程办公",
        labelZhTW: "為境外公司遠端工作",
        labelPt: "Trabalho remoto para empresa estrangeira",
        labelEs: "Trabajo remoto para empresa extranjera",
        emoji: "🌐",
      },
      {
        id: "model",
        labelEn: "Modeling / Entertainment",
        labelKo: "모델 / 연예",
        labelJa: "モデル・エンターテインメント",
        labelZhCN: "模特/娱乐",
        labelZhTW: "模特/娛樂",
        labelPt: "Modelagem / Entretenimento",
        labelEs: "Modelado / Entretenimiento",
        emoji: "📸",
      },
      {
        id: "stemgrad",
        labelEn: "STEM graduate of Korean university",
        labelKo: "국내 대학 이공계 졸업자",
        labelJa: "韓国大学STEM課程卒業者",
        labelZhCN: "韩国大学理工科毕业生",
        labelZhTW: "韓國大學理工科畢業生",
        labelPt: "Graduado em STEM de universidade coreana",
        labelEs: "Graduado en STEM de universidad coreana",
        emoji: "🧪",
      },
    ],
  },
  {
    id: "duration",
    questionEn: "How long do you plan to stay?",
    questionKo: "얼마나 체류할 예정인가요?",
    questionJa: "どのくらい滞在する予定ですか？",
    questionZhCN: "您计划停留多长时间？",
    questionZhTW: "您計劃停留多長時間？",
    questionPt: "Por quanto tempo você planeja ficar?",
    questionEs: "¿Cuánto tiempo planeas quedarte?",
    options: [
      {
        id: "short",
        labelEn: "Under 3 months",
        labelKo: "3개월 미만",
        labelJa: "3ヶ月未満",
        labelZhCN: "3个月以内",
        labelZhTW: "3個月以內",
        labelPt: "Menos de 3 meses",
        labelEs: "Menos de 3 meses",
        emoji: "📅",
      },
      {
        id: "medium",
        labelEn: "3 months to 1 year",
        labelKo: "3개월~1년",
        labelJa: "3ヶ月〜1年",
        labelZhCN: "3个月至1年",
        labelZhTW: "3個月至1年",
        labelPt: "3 meses a 1 ano",
        labelEs: "3 meses a 1 año",
        emoji: "🗓️",
      },
      {
        id: "long",
        labelEn: "1-3 years",
        labelKo: "1~3년",
        labelJa: "1〜3年",
        labelZhCN: "1-3年",
        labelZhTW: "1-3年",
        labelPt: "1-3 anos",
        labelEs: "1-3 años",
        emoji: "📆",
      },
      {
        id: "permanent",
        labelEn: "Long-term / permanent",
        labelKo: "장기 / 영구 거주",
        labelJa: "長期・永住",
        labelZhCN: "长期/永久居留",
        labelZhTW: "長期/永久居留",
        labelPt: "Longo prazo / permanente",
        labelEs: "Largo plazo / permanente",
        emoji: "🏡",
      },
    ],
  },
];

// Purpose + duration → visa recommendation
export const VISA_RECOMMENDATIONS: Record<string, {
  code: string;
  noteEn: string; noteKo: string;
  noteJa: string; noteZhCN: string; noteZhTW: string;
  notePt: string; noteEs: string;
}[]> = {
  "study-short": [{ code: "D-4", noteEn: "Language school visa for short-term Korean study", noteKo: "단기 한국어 연수용 비자", noteJa: "短期韓国語研修用ビザ", noteZhCN: "短期韩语学习签证", noteZhTW: "短期韓語學習簽證", notePt: "Visto de escola de idiomas para estudo de curto prazo", noteEs: "Visa de escuela de idiomas para estudio a corto plazo" }],
  "study-medium": [
    { code: "D-4", noteEn: "Language school visa", noteKo: "어학원 비자", noteJa: "語学学校ビザ", noteZhCN: "语言学校签证", noteZhTW: "語言學校簽證", notePt: "Visto de escola de idiomas", noteEs: "Visa de escuela de idiomas" },
    { code: "D-2", noteEn: "If enrolled in a degree program", noteKo: "학위 과정 재학 시", noteJa: "学位プログラムに在籍の場合", noteZhCN: "如就读学位课程", noteZhTW: "如就讀學位課程", notePt: "Se matriculado em um programa de graduação", noteEs: "Si está inscrito en un programa de grado" },
  ],
  "study-long": [{ code: "D-2", noteEn: "University student visa for degree programs", noteKo: "대학교 학위 과정 비자", noteJa: "大学学位プログラム用学生ビザ", noteZhCN: "大学学位课程学生签证", noteZhTW: "大學學位課程學生簽證", notePt: "Visto de estudante universitário para programas de graduação", noteEs: "Visa de estudiante universitario para programas de grado" }],
  "study-permanent": [{ code: "D-2", noteEn: "Start with student visa, build toward F-2", noteKo: "학생 비자로 시작해 F-2로 전환", noteJa: "学生ビザから始めF-2を目指す", noteZhCN: "从学生签证开始，向F-2转变", noteZhTW: "從學生簽證開始，向F-2轉變", notePt: "Comece com visto de estudante, construa caminho para F-2", noteEs: "Comience con visa de estudiante, avance hacia F-2" }],
  "teach-medium": [{ code: "E-2", noteEn: "English teacher visa — most common for native speakers", noteKo: "원어민 영어교사 비자", noteJa: "英語教師ビザ—ネイティブスピーカーに最も一般的", noteZhCN: "英语教师签证—母语者最常见选择", noteZhTW: "英語教師簽證—母語者最常見選擇", notePt: "Visto de professor de inglês — mais comum para falantes nativos", noteEs: "Visa de profesor de inglés — la más común para hablantes nativos" }],
  "teach-long": [{ code: "E-2", noteEn: "English teacher visa, renewable annually", noteKo: "원어민 영어교사 비자, 매년 갱신", noteJa: "英語教師ビザ、毎年更新", noteZhCN: "英语教师签证，每年续签", noteZhTW: "英語教師簽證，每年續簽", notePt: "Visto de professor de inglês, renovável anualmente", noteEs: "Visa de profesor de inglés, renovable anualmente" }],
  "teach-short": [{ code: "E-2", noteEn: "E-2 requires employer sponsorship, minimum ~1 year contracts", noteKo: "E-2는 고용주 스폰서십 필요, 최소 1년 계약", noteJa: "E-2は雇用主のスポンサーシップが必要、最低約1年契約", noteZhCN: "E-2需要雇主担保，合同最短约1年", noteZhTW: "E-2需要雇主擔保，合約最短約1年", notePt: "E-2 exige patrocínio do empregador, contratos mínimos de ~1 ano", noteEs: "E-2 requiere patrocinio del empleador, contratos mínimos de ~1 año" }],
  "teach-permanent": [{ code: "E-2", noteEn: "E-2 is renewed annually — build toward F-2 after 5+ years", noteKo: "E-2는 매년 갱신 — 5년 이상 후 F-2 취득 가능", noteJa: "E-2は毎年更新—5年以上後にF-2取得可能", noteZhCN: "E-2每年续签—5年以上后可获得F-2", noteZhTW: "E-2每年續簽—5年以上後可獲得F-2", notePt: "E-2 é renovado anualmente — construa caminho para F-2 após 5+ anos", noteEs: "E-2 se renueva anualmente — avance hacia F-2 después de 5+ años" }],
  "work-medium": [{ code: "E-7", noteEn: "Specialized work visa for skilled professionals", noteKo: "전문직 특정활동비자", noteJa: "専門職向け特定活動ビザ", noteZhCN: "专业技术人才特定活动签证", noteZhTW: "專業技術人才特定活動簽證", notePt: "Visto de trabalho especializado para profissionais qualificados", noteEs: "Visa de trabajo especializado para profesionales calificados" }],
  "work-long": [{ code: "E-7", noteEn: "Specialized work visa, path to F-2 long-term", noteKo: "E-7 후 F-2 거주비자 취득 가능", noteJa: "専門職ビザ、長期的にはF-2への道", noteZhCN: "专业技术签证，长期可转F-2居住签证", noteZhTW: "專業技術簽證，長期可轉F-2居住簽證", notePt: "Visto de trabalho especializado, caminho para F-2 a longo prazo", noteEs: "Visa de trabajo especializado, camino hacia F-2 a largo plazo" }],
  "work-permanent": [{ code: "E-7", noteEn: "Work visa → F-2 (resident) → F-5 (permanent)", noteKo: "E-7 → F-2 (거주) → F-5 (영주권)", noteJa: "就労ビザ → F-2（居住） → F-5（永住）", noteZhCN: "工作签证 → F-2（居住）→ F-5（永久居留）", noteZhTW: "工作簽證 → F-2（居住）→ F-5（永久居留）", notePt: "Visto de trabalho → F-2 (residente) → F-5 (permanente)", noteEs: "Visa de trabajo → F-2 (residente) → F-5 (permanente)" }],
  "work-short": [{ code: "E-7", noteEn: "Most work visas require at least 1-year contracts", noteKo: "대부분의 취업 비자는 최소 1년 계약 필요", noteJa: "ほとんどの就労ビザは最低1年契約が必要", noteZhCN: "大多数工作签证要求至少1年合同", noteZhTW: "大多數工作簽證要求至少1年合約", notePt: "A maioria dos vistos de trabalho exige contratos de pelo menos 1 ano", noteEs: "La mayoría de las visas de trabajo requieren contratos de al menos 1 año" }],
  "family-medium": [{ code: "F-6", noteEn: "Marriage visa for spouses of Korean nationals", noteKo: "한국인 배우자 결혼이민비자", noteJa: "韓国人配偶者向け結婚移民ビザ", noteZhCN: "韩国公民配偶结婚移民签证", noteZhTW: "韓國公民配偶結婚移民簽證", notePt: "Visto de casamento para cônjuges de nacionais coreanos", noteEs: "Visa de matrimonio para cónyuges de nacionales coreanos" }],
  "family-long": [{ code: "F-6", noteEn: "Marriage visa, leads to F-2 and eventually F-5", noteKo: "결혼이민비자, F-2 → F-5 경로", noteJa: "結婚移民ビザ、F-2そしてF-5へ", noteZhCN: "结婚移民签证，可转F-2再转F-5", noteZhTW: "結婚移民簽證，可轉F-2再轉F-5", notePt: "Visto de casamento, leva ao F-2 e eventualmente ao F-5", noteEs: "Visa de matrimonio, lleva a F-2 y eventualmente a F-5" }],
  "family-permanent": [{ code: "F-6", noteEn: "Marriage visa path: F-6 → F-2 → F-5 permanent", noteKo: "F-6 → F-2 → F-5 영주권", noteJa: "結婚ビザの道：F-6 → F-2 → F-5永住権", noteZhCN: "结婚签证路径：F-6 → F-2 → F-5永久居留", noteZhTW: "結婚簽證路徑：F-6 → F-2 → F-5永久居留", notePt: "Caminho do visto de casamento: F-6 → F-2 → F-5 permanente", noteEs: "Camino de visa de matrimonio: F-6 → F-2 → F-5 permanente" }],
  "family-short": [{ code: "C-3", noteEn: "Short visit to see family — tourist visa or visa-free entry", noteKo: "가족 방문 — 관광 비자 또는 무비자 입국", noteJa: "家族訪問—観光ビザまたはビザ免除入国", noteZhCN: "家庭探访—旅游签证或免签入境", noteZhTW: "家庭探訪—旅遊簽證或免簽入境", notePt: "Visita curta à família — visto de turista ou entrada sem visto", noteEs: "Visita corta a familia — visa de turista o entrada sin visa" }],
  "gyopo-medium": [{ code: "F-4", noteEn: "Overseas Korean visa — minimal restrictions, renewable every 2 years", noteKo: "재외동포비자 — 제한 적고 2년마다 갱신", noteJa: "在外同胞ビザ—制限少なく2年毎に更新", noteZhCN: "海外韩裔签证—限制少，每2年续签", noteZhTW: "海外韓裔簽證—限制少，每2年續簽", notePt: "Visto de coreano do exterior — restrições mínimas, renovável a cada 2 anos", noteEs: "Visa para coreanos en el exterior — restricciones mínimas, renovable cada 2 años" }],
  "gyopo-long": [{ code: "F-4", noteEn: "F-4 is renewable indefinitely and gives most work rights", noteKo: "F-4는 무기한 갱신 가능, 취업 권리 폭넓음", noteJa: "F-4は無期限に更新可能で、ほとんどの就労権を付与", noteZhCN: "F-4可无限期续签，拥有广泛就业权利", noteZhTW: "F-4可無限期續簽，擁有廣泛就業權利", notePt: "F-4 é renovável indefinidamente e dá a maioria dos direitos de trabalho", noteEs: "F-4 es renovable indefinidamente y otorga la mayoría de los derechos laborales" }],
  "gyopo-permanent": [{ code: "F-4", noteEn: "F-4 → F-5 (permanent residency) after 2 years", noteKo: "F-4 → F-5 영주권 취득 가능", noteJa: "F-4 → 2年後にF-5（永住権）取得可能", noteZhCN: "F-4 → 2年后可获F-5永久居留", noteZhTW: "F-4 → 2年後可獲F-5永久居留", notePt: "F-4 → F-5 (residência permanente) após 2 anos", noteEs: "F-4 → F-5 (residencia permanente) después de 2 años" }],
  "gyopo-short": [{ code: "F-4", noteEn: "Even for short stays, F-4 gives you more flexibility than a tourist visa", noteKo: "단기 체류라도 F-4는 관광비자보다 유연함", noteJa: "短期滞在でもF-4は観光ビザより柔軟", noteZhCN: "即使短期停留，F-4也比旅游签证更灵活", noteZhTW: "即使短期停留，F-4也比旅遊簽證更靈活", notePt: "Mesmo para estadias curtas, F-4 oferece mais flexibilidade que um visto de turista", noteEs: "Incluso para estadías cortas, F-4 da más flexibilidad que una visa de turista" }],
  "tourist-short": [{ code: "C-3", noteEn: "Many nationalities get 90 days visa-free. Check your country.", noteKo: "많은 국적자 90일 무비자. 국가 확인 필요.", noteJa: "多くの国籍が90日間ビザ免除。国別に確認を。", noteZhCN: "许多国籍可免签90天，请确认您的国家。", noteZhTW: "許多國籍可免簽90天，請確認您的國家。", notePt: "Muitas nacionalidades têm 90 dias sem visto. Verifique o seu país.", noteEs: "Muchas nacionalidades tienen 90 días sin visa. Verifica tu país." }],
  "tourist-medium": [{ code: "C-3", noteEn: "Tourist visa cannot be extended beyond 90 days. You'll need a different visa for longer stays.", noteKo: "관광 비자는 90일 초과 연장 불가. 장기 체류는 다른 비자 필요.", noteJa: "観光ビザは90日を超えて延長不可。長期滞在には別のビザが必要。", noteZhCN: "旅游签证不能延期超过90天，长期停留需申请其他签证。", noteZhTW: "旅遊簽證不能延期超過90天，長期停留需申請其他簽證。", notePt: "Visto de turista não pode ser estendido além de 90 dias. Você precisará de outro visto para estadias mais longas.", noteEs: "La visa de turista no puede extenderse más de 90 días. Necesitarás otra visa para estadías más largas." }],
  "tourist-long": [{ code: "C-3", noteEn: "A tourist visa won't work for 1+ year stays. Consider switching to a long-term visa type.", noteKo: "1년 이상 체류는 관광비자로 불가. 장기 체류 비자 전환 필요.", noteJa: "1年以上の滞在に観光ビザは使えません。長期ビザへの切り替えを検討してください。", noteZhCN: "旅游签证不适用于1年以上的停留，请考虑转为长期签证。", noteZhTW: "旅遊簽證不適用於1年以上的停留，請考慮轉為長期簽證。", notePt: "Um visto de turista não funciona para estadias de 1+ ano. Considere mudar para um visto de longo prazo.", noteEs: "Una visa de turista no funcionará para estadías de 1+ año. Considera cambiar a un tipo de visa a largo plazo." }],
  "tourist-permanent": [{ code: "C-3", noteEn: "Permanent residence is not possible on a tourist visa. Explore F-2 or F-5 options.", noteKo: "관광비자로 영구 거주 불가. F-2 또는 F-5 비자를 알아보세요.", noteJa: "観光ビザでの永住は不可。F-2またはF-5オプションを検討してください。", noteZhCN: "旅游签证无法永久居留，请了解F-2或F-5签证选项。", noteZhTW: "旅遊簽證無法永久居留，請了解F-2或F-5簽證選項。", notePt: "Residência permanente não é possível com visto de turista. Explore as opções F-2 ou F-5.", noteEs: "La residencia permanente no es posible con visa de turista. Explora las opciones F-2 o F-5." }],
  "remote-short": [{ code: "C-3", noteEn: "Up to 90 days visa-free is technically permitted, but you cannot legally work for anyone in Korea. For stays beyond 90 days, you need the F-1-D Workation visa.", noteKo: "최대 90일 무비자 체류는 가능하지만 한국 내 업무는 불가. 90일 초과 체류 시 F-1-D 워케이션 비자 필요.", noteJa: "最長90日間の無査証滞在は技術的に可能ですが、韓国では誰のためにも合法的に働けません。90日超の滞在にはF-1-Dワーケーションビザが必要。", noteZhCN: "技术上可以免签停留最多90天，但在韩国不得合法为任何人工作。超过90天需要F-1-D远程办公签证。", noteZhTW: "技術上可以免簽停留最多90天，但在韓國不得合法為任何人工作。超過90天需要F-1-D遠端工作簽證。", notePt: "Até 90 dias sem visto é tecnicamente permitido, mas você não pode trabalhar legalmente para ninguém na Coreia. Para estadias além de 90 dias, você precisa do visto F-1-D Workation.", noteEs: "Hasta 90 días sin visa está técnicamente permitido, pero no puedes trabajar legalmente para nadie en Corea. Para estadías más de 90 días, necesitas la visa F-1-D Workation." }],
  "remote-medium": [{ code: "F-1-D", noteEn: "Workation (Digital Nomad) visa — for remote employees of non-Korean companies. Income floor: KRW 88M per year. No Korean clients allowed.", noteKo: "워케이션(디지털노마드) 비자 — 한국 외 기업 원격근무자 대상. 최저 소득 기준: 연 8,800만 원. 한국 고객사 업무 불가.", noteJa: "ワーケーション（デジタルノマド）ビザ — 韓国以外の企業のリモート従業員向け。所得基準：年8,800万ウォン。韓国クライアントへの業務不可。", noteZhCN: "远程办公（数字游民）签证，适用于非韩国公司的远程雇员。最低收入：年8,800万韩元。不得为韩国客户服务。", noteZhTW: "遠端工作（數位遊牧）簽證，適用於非韓國公司的遠端雇員。最低收入：年8,800萬韓元。不得為韓國客戶服務。", notePt: "Visto Workation (Nômade Digital) — para funcionários remotos de empresas não coreanas. Piso de renda: KRW 88M por ano. Clientes coreanos não são permitidos.", noteEs: "Visa Workation (Nómada Digital) — para empleados remotos de empresas no coreanas. Piso de ingresos: KRW 88M por año. No se permiten clientes coreanos." }],
  "remote-long": [{ code: "F-1-D", noteEn: "F-1-D is renewable once for up to 2 years total. After that, you may explore the F-2 points-based residency path.", noteKo: "F-1-D는 최대 2년까지 1회 갱신 가능. 이후 F-2 점수제 거주비자 경로 검토 가능.", noteJa: "F-1-Dは最長2年まで1回更新可能。その後F-2ポイント制居住ビザの経路を検討できます。", noteZhCN: "F-1-D可续签一次，最长2年。之后可考虑F-2积分制居住签证路径。", noteZhTW: "F-1-D可續簽一次，最長2年。之後可考慮F-2積分制居住簽證路徑。", notePt: "F-1-D é renovável uma vez por até 2 anos no total. Depois disso, você pode explorar o caminho de residência F-2 baseado em pontos.", noteEs: "F-1-D es renovable una vez por hasta 2 años en total. Después de eso, puede explorar el camino de residencia F-2 basado en puntos." }],
  "remote-permanent": [{ code: "F-1-D", noteEn: "Start with F-1-D for up to 2 years, then transition to F-2 points-based residency if you qualify. Long-term permanent residency (F-5) requires at least 5 years of legal stay.", noteKo: "F-1-D로 최대 2년 체류 후, 자격 충족 시 F-2 점수제 거주비자로 전환. 영주권(F-5)은 최소 5년 합법 체류 필요.", noteJa: "最長2年F-1-Dで滞在後、資格があればF-2ポイント制居住ビザへ移行。永住権（F-5）には最低5年の合法滞在が必要。", noteZhCN: "先以F-1-D停留最长2年，如符合条件可转为F-2积分制居住签证。永久居留权（F-5）需至少5年合法居住。", noteZhTW: "先以F-1-D停留最長2年，如符合條件可轉為F-2積分制居住簽證。永久居留權（F-5）需至少5年合法居住。", notePt: "Comece com F-1-D por até 2 anos, depois faça a transição para residência F-2 baseada em pontos se qualificar. Residência permanente (F-5) requer pelo menos 5 anos de estadia legal.", noteEs: "Comienza con F-1-D por hasta 2 años, luego transiciona a residencia F-2 basada en puntos si calificas. La residencia permanente (F-5) requiere al menos 5 años de estadía legal." }],
  "model-short": [{ code: "C-3", noteEn: "For shoots under 90 days, a C-4-5 short-term work visa may apply instead of E-6-1. Contact the Korea Media Rating Board for the recommendation letter (not MCST).", noteKo: "90일 미만 단기 촬영은 E-6-1 대신 C-4-5 단기취업비자 활용 가능. 추천서는 MCST가 아닌 영상물등급위원회에서 발급.", noteJa: "90日未満の短期撮影はE-6-1の代わりにC-4-5短期就労ビザが適用される場合があります。推薦状はMCSTではなく映像物等級委員会から取得。", noteZhCN: "90天以内的短期拍摄可使用C-4-5短期工作签证代替E-6-1。推荐信由韩国媒体评级委员会出具（非MCST）。", noteZhTW: "90天以內的短期拍攝可使用C-4-5短期工作簽證代替E-6-1。推薦信由韓國媒體評級委員會出具（非MCST）。", notePt: "Para filmagens com menos de 90 dias, um visto de trabalho de curto prazo C-4-5 pode ser aplicado em vez de E-6-1. Contate o Korea Media Rating Board para a carta de recomendação (não o MCST).", noteEs: "Para rodajes de menos de 90 días, puede aplicarse una visa de trabajo de corto plazo C-4-5 en lugar de E-6-1. Contacta al Korea Media Rating Board para la carta de recomendación (no el MCST)." }],
  "model-medium": [{ code: "E-6", noteEn: "E-6-1 is the correct visa for fashion models and performing artists. You need 3+ years documented experience, a MCST recommendation letter, and a registered Korean agency.", noteKo: "패션 모델 및 공연 예술가에게 적합한 비자는 E-6-1. 3년 이상 입증된 경력, MCST 추천서, 등록된 한국 에이전시 필요.", noteJa: "ファッションモデルや舞台芸術家に適切なビザはE-6-1。3年以上の証明された経験、MCST推薦状、登録韓国エージェンシーが必要。", noteZhCN: "时装模特和表演艺术家适用的签证是E-6-1。需要3年以上有记录的经验、MCST推荐信及已注册的韩国经纪公司。", noteZhTW: "時裝模特和表演藝術家適用的簽證是E-6-1。需要3年以上有記錄的經驗、MCST推薦信及已登記的韓國經紀公司。", notePt: "E-6-1 é o visto correto para modelos de moda e artistas performáticos. Você precisa de 3+ anos de experiência documentada, uma carta de recomendação do MCST e uma agência coreana registrada.", noteEs: "E-6-1 es la visa correcta para modelos de moda y artistas escénicos. Necesitas 3+ años de experiencia documentada, una carta de recomendación del MCST y una agencia coreana registrada." }],
  "model-long": [{ code: "E-6", noteEn: "E-6-1 is renewable annually. After 5+ years, you may qualify for F-2 points-based residency.", noteKo: "E-6-1은 매년 갱신 가능. 5년 이상 체류 후 F-2 점수제 거주비자 자격 취득 가능.", noteJa: "E-6-1は毎年更新可能。5年以上後にF-2ポイント制居住ビザの資格が得られる場合があります。", noteZhCN: "E-6-1可每年续签。5年以上后可能有资格申请F-2积分制居住签证。", noteZhTW: "E-6-1可每年續簽。5年以上後可能有資格申請F-2積分制居住簽證。", notePt: "E-6-1 é renovável anualmente. Após 5+ anos, você pode se qualificar para residência F-2 baseada em pontos.", noteEs: "E-6-1 es renovable anualmente. Después de 5+ años, puedes calificar para residencia F-2 basada en puntos." }],
  "model-permanent": [{ code: "E-6", noteEn: "E-6-1 for the career, then F-2 after 5+ years, then F-5 permanent residency. Requires consistent annual renewals and clean immigration record.", noteKo: "E-6-1로 커리어 시작, 5년 이상 후 F-2, 이후 F-5 영주권. 매년 갱신 및 깨끗한 출입국 기록 필요.", noteJa: "E-6-1でキャリアスタート、5年以上後にF-2、その後F-5永住権。毎年の更新とクリーンな出入国記録が必要。", noteZhCN: "从E-6-1开始职业生涯，5年以上后转F-2，再转F-5永久居留。需每年续签并保持良好的出入境记录。", noteZhTW: "從E-6-1開始職業生涯，5年以上後轉F-2，再轉F-5永久居留。需每年續簽並保持良好的出入境記錄。", notePt: "E-6-1 para a carreira, depois F-2 após 5+ anos, depois residência permanente F-5. Requer renovações anuais consistentes e histórico limpo de imigração.", noteEs: "E-6-1 para la carrera, luego F-2 después de 5+ años, luego residencia permanente F-5. Requiere renovaciones anuales consistentes y registro de inmigración limpio." }],
  "stemgrad-short": [{ code: "D-10", noteEn: "Start with a D-10 job-seeker visa while looking for a position. If you graduated from one of the 32 K-STAR partner universities, the K-STAR track gives you direct F-2 status.", noteKo: "D-10 구직비자로 취업 준비 시작. K-STAR 협약 32개 대학 졸업자는 K-STAR 트랙으로 F-2 직접 취득 가능.", noteJa: "就職活動中はD-10求職ビザから始めましょう。32のK-STAR提携大学の卒業者は、K-STARトラックでF-2を直接取得できます。", noteZhCN: "求职期间从D-10求职签证开始。如果您毕业于32所K-STAR合作大学之一，K-STAR通道可直接获得F-2身份。", noteZhTW: "求職期間從D-10求職簽證開始。如果您畢業於32所K-STAR合作大學之一，K-STAR通道可直接獲得F-2身份。", notePt: "Comece com um visto D-10 de busca de emprego enquanto procura uma posição. Se você se formou em uma das 32 universidades parceiras K-STAR, o caminho K-STAR dá a você status F-2 direto.", noteEs: "Comienza con una visa D-10 de búsqueda de empleo mientras buscas una posición. Si te graduaste en una de las 32 universidades asociadas K-STAR, el camino K-STAR te da estado F-2 directo." }],
  "stemgrad-medium": [{ code: "K-STAR", noteEn: "K-STAR fast track: direct F-2 residency for STEM graduates of 32 designated Korean universities. Much faster than the standard E-7 work visa route.", noteKo: "K-STAR 패스트트랙: 32개 지정 국내 대학 이공계 졸업자 대상 F-2 직접 취득. 일반 E-7 취업비자보다 훨씬 빠름.", noteJa: "K-STARファストトラック：32の指定韓国大学STEM課程卒業者へのF-2直接取得。通常のE-7就労ビザルートよりはるかに速い。", noteZhCN: "K-STAR快速通道：32所指定韩国大学理工科毕业生可直接获得F-2居住资格。比普通E-7工作签证途径快得多。", noteZhTW: "K-STAR快速通道：32所指定韓國大學理工科畢業生可直接獲得F-2居住資格。比普通E-7工作簽證途徑快得多。", notePt: "Via rápida K-STAR: residência F-2 direta para graduados em STEM de 32 universidades coreanas designadas. Muito mais rápido do que a rota padrão de visto de trabalho E-7.", noteEs: "Vía rápida K-STAR: residencia F-2 directa para graduados en STEM de 32 universidades coreanas designadas. Mucho más rápido que la ruta estándar de visa de trabajo E-7." }],
  "stemgrad-long": [{ code: "K-STAR", noteEn: "K-STAR to F-2 residency, then F-5 permanent residency after meeting the requirements (typically 5 years of lawful residence).", noteKo: "K-STAR로 F-2 거주비자 취득, 이후 요건 충족 시 (통상 합법 체류 5년) F-5 영주권 취득.", noteJa: "K-STARでF-2居住ビザ取得、その後要件充足（通常は合法滞在5年）後にF-5永住権取得。", noteZhCN: "通过K-STAR获得F-2居住签证，满足条件后（通常为5年合法居住）获得F-5永久居留权。", noteZhTW: "通過K-STAR獲得F-2居住簽證，滿足條件後（通常為5年合法居住）獲得F-5永久居留權。", notePt: "K-STAR para residência F-2, depois residência permanente F-5 após atender aos requisitos (normalmente 5 anos de residência legal).", noteEs: "K-STAR para residencia F-2, luego residencia permanente F-5 después de cumplir los requisitos (normalmente 5 años de residencia legal)." }],
  "stemgrad-permanent": [{ code: "K-STAR", noteEn: "Fastest PR path for Korean STEM grads: K-STAR direct F-2, then F-5 in approximately 3-5 years. If joining an advanced-tech employer, the Top-Tier visa may offer an even faster F-5-T route.", noteKo: "국내 이공계 졸업자 최단 영주권 경로: K-STAR F-2 직접 취득 후 약 3-5년 내 F-5. 첨단기술 기업 취업 시 탑티어 비자를 통한 F-5-T 경로가 더 빠를 수 있음.", noteJa: "韓国STEM卒業者の最速PR経路：K-STAR直接F-2取得後、約3〜5年でF-5。先端技術企業に就職する場合、トップティアビザによるF-5-Tルートがさらに速い場合があります。", noteZhCN: "韩国理工科毕业生最快永居路径：K-STAR直接获得F-2，约3-5年后获F-5。如入职先进技术企业，顶尖人才签证的F-5-T通道可能更快。", noteZhTW: "韓國理工科畢業生最快永居路徑：K-STAR直接獲得F-2，約3-5年後獲F-5。如入職先進技術企業，頂尖人才簽證的F-5-T通道可能更快。", notePt: "Caminho mais rápido para PR para graduados coreanos em STEM: K-STAR F-2 direto, depois F-5 em aproximadamente 3-5 anos. Se ingressar em um empregador de tecnologia avançada, a visa Top-Tier pode oferecer uma rota F-5-T ainda mais rápida.", noteEs: "Camino más rápido a PR para graduados coreanos en STEM: K-STAR F-2 directo, luego F-5 en aproximadamente 3-5 años. Si se une a un empleador de tecnología avanzada, la visa Top-Tier puede ofrecer una ruta F-5-T aún más rápida." }],
};

export const ARC_STEPS = [
  {
    step: 1,
    titleEn: "Within 90 days of arrival",
    titleKo: "입국 후 90일 이내",
    titleJa: "入国後90日以内",
    titleZhCN: "入境后90天内",
    titleZhTW: "入境後90天內",
    titlePt: "Dentro de 90 dias da chegada",
    titleEs: "Dentro de los 90 días de llegada",
    descEn: "You must register for an ARC (Alien Registration Card) within 90 days of arriving in Korea on a long-stay visa. Failing to register is a violation and can result in fines.",
    descKo: "장기 체류 비자로 입국한 경우 90일 이내에 외국인등록증(ARC)을 신청해야 합니다. 미등록 시 과태료 부과 대상입니다.",
    descJa: "長期滞在ビザで入国後90日以内に外国人登録証（ARC）を申請する必要があります。未登録は違反となり、罰金が科される場合があります。",
    descZhCN: "持长期居留签证入境韩国后，必须在90天内申请外国人登录证（ARC）。未登记属于违规行为，可能导致罚款。",
    descZhTW: "持長期居留簽證入境韓國後，必須在90天內申請外國人登錄證（ARC）。未登記屬於違規行為，可能導致罰款。",
    descPt: "Você deve se registrar para um ARC (Cartão de Registro de Estrangeiro) dentro de 90 dias após chegar à Coreia com um visto de longa permanência. Não se registrar é uma violação e pode resultar em multas.",
    descEs: "Debes registrarte para obtener un ARC (Tarjeta de Registro de Extranjero) dentro de los 90 días de llegar a Corea con una visa de larga estadía. No registrarse es una infracción y puede resultar en multas.",
  },
  {
    step: 2,
    titleEn: "Make an appointment",
    titleKo: "예약하기",
    titleJa: "予約をする",
    titleZhCN: "预约",
    titleZhTW: "預約",
    titlePt: "Agendar uma consulta",
    titleEs: "Hacer una cita",
    descEn: "Book an appointment at the Hi Korea website (hikorea.go.kr) or call 1345 for the nearest immigration office. Walk-ins are possible but wait times can be 2-4 hours.",
    descKo: "하이코리아 (hikorea.go.kr) 에서 예약하거나 1345로 전화해 가까운 출입국 사무소 예약을 하세요. 현장 접수도 가능하지만 대기 2-4시간 예상.",
    descJa: "Hi Koreaウェブサイト（hikorea.go.kr）で予約するか、1345に電話して最寄りの出入国管理局を確認してください。当日受付も可能ですが、待ち時間は2〜4時間になる場合があります。",
    descZhCN: "在Hi Korea网站（hikorea.go.kr）预约，或拨打1345了解最近的出入境管理局。可以现场办理，但等待时间可能为2-4小时。",
    descZhTW: "在Hi Korea網站（hikorea.go.kr）預約，或撥打1345了解最近的出入境管理局。可以現場辦理，但等待時間可能為2-4小時。",
    descPt: "Agende uma consulta no site Hi Korea (hikorea.go.kr) ou ligue para 1345 para o escritório de imigração mais próximo. Entrada sem agendamento é possível, mas os tempos de espera podem ser de 2 a 4 horas.",
    descEs: "Reserva una cita en el sitio web Hi Korea (hikorea.go.kr) o llama al 1345 para la oficina de inmigración más cercana. Es posible ir sin cita, pero los tiempos de espera pueden ser de 2 a 4 horas.",
  },
  {
    step: 3,
    titleEn: "Documents to bring",
    titleKo: "준비 서류",
    titleJa: "持参書類",
    titleZhCN: "需携带的文件",
    titleZhTW: "需攜帶的文件",
    titlePt: "Documentos a trazer",
    titleEs: "Documentos a llevar",
    descEn: "Passport + visa, 2 passport photos (3.5cm x 4.5cm), completed application form, proof of address, fee (30,000 KRW), and any employer/school documents.",
    descKo: "여권+비자, 여권 사진 2매(3.5x4.5cm), 작성된 신청서, 주소 증명서류, 수수료 3만원, 직장/학교 서류 등.",
    descJa: "パスポート＋ビザ、パスポート写真2枚（3.5cm×4.5cm）、記入済み申請書、住所証明、手数料（30,000ウォン）、雇用主・学校書類など。",
    descZhCN: "护照+签证、2张护照照片（3.5cm×4.5cm）、填写完整的申请表、地址证明、费用（30,000韩元）以及雇主/学校相关文件。",
    descZhTW: "護照+簽證、2張護照照片（3.5cm×4.5cm）、填寫完整的申請表、地址證明、費用（30,000韓元）以及雇主/學校相關文件。",
    descPt: "Passaporte + visto, 2 fotos de passaporte (3,5cm x 4,5cm), formulário de inscrição preenchido, comprovante de endereço, taxa (30.000 KRW) e documentos do empregador/escola.",
    descEs: "Pasaporte + visa, 2 fotos de pasaporte (3,5cm x 4,5cm), formulario de solicitud completado, comprobante de domicilio, tarifa (30,000 KRW) y documentos del empleador/escuela.",
  },
  {
    step: 4,
    titleEn: "At the immigration office",
    titleKo: "출입국 사무소에서",
    titleJa: "出入国管理局にて",
    titleZhCN: "在出入境管理局",
    titleZhTW: "在出入境管理局",
    titlePt: "No escritório de imigração",
    titleEs: "En la oficina de inmigración",
    descEn: "Take a number, wait, submit your documents, get fingerprinted. The officer will keep your passport temporarily and give you a receipt.",
    descKo: "번호표 뽑고 대기 후 서류 제출, 지문 등록. 담당자가 여권을 임시 보관하고 영수증을 줍니다.",
    descJa: "番号票を取り、待機後に書類を提出し、指紋登録を行います。担当官がパスポートを一時預かりし、受領証を渡します。",
    descZhCN: "取号等候，提交文件，进行指纹采集。工作人员将临时保管您的护照并给您一张收据。",
    descZhTW: "取號等候，提交文件，進行指紋採集。工作人員將臨時保管您的護照並給您一張收據。",
    descPt: "Pegue uma senha, aguarde, entregue seus documentos, faça o registro de impressão digital. O agente guardará seu passaporte temporariamente e lhe dará um recibo.",
    descEs: "Toma un número, espera, entrega tus documentos, registra tus huellas dactilares. El agente guardará tu pasaporte temporalmente y te dará un recibo.",
  },
  {
    step: 5,
    titleEn: "Processing time",
    titleKo: "처리 기간",
    titleJa: "処理期間",
    titleZhCN: "处理时间",
    titleZhTW: "處理時間",
    titlePt: "Prazo de processamento",
    titleEs: "Tiempo de procesamiento",
    descEn: "About 2-3 weeks. You'll receive a text when ready. You can track status on Hi Korea. Pick up in person at the same office.",
    descKo: "약 2-3주. 완료 시 문자 알림. 하이코리아에서 상태 확인 가능. 동일 사무소에서 직접 수령.",
    descJa: "約2〜3週間。完了時にSMSが届きます。Hi Koreaでステータスを確認できます。同じ事務所で直接受け取ります。",
    descZhCN: "约2-3周。完成后将收到短信通知。可在Hi Korea上追踪状态。在同一办公室亲自领取。",
    descZhTW: "約2-3週。完成後將收到簡訊通知。可在Hi Korea上追蹤狀態。在同一辦公室親自領取。",
    descPt: "Cerca de 2-3 semanas. Você receberá uma mensagem de texto quando estiver pronto. Pode acompanhar o status no Hi Korea. Retirada pessoal no mesmo escritório.",
    descEs: "Aproximadamente 2-3 semanas. Recibirás un mensaje de texto cuando esté listo. Puedes rastrear el estado en Hi Korea. Recoge en persona en la misma oficina.",
  },
];

export const COMMON_PITFALLS = [
  {
    visa: "E-2",
    issueEn: "Working at a second school without permission",
    issueKo: "허가 없이 다른 학원에서 추가 강의",
    issueJa: "許可なく別の学校で追加授業",
    issueZhCN: "未经许可在其他学校兼职任教",
    issueZhTW: "未經許可在其他學校兼職任教",
    issuePt: "Trabalhar em uma segunda escola sem permissão",
    issueEs: "Trabajar en una segunda escuela sin permiso",
    solutionEn: "E-2 holders can only work at their sponsoring employer. Any additional teaching requires a separate work authorization from immigration. Violation can result in deportation.",
    solutionKo: "E-2 비자 소지자는 초청 고용주에서만 일할 수 있습니다. 추가 강의 시 출입국 허가 필요. 위반 시 강제 출국 가능.",
    solutionJa: "E-2保持者は招聘雇用主でのみ就労できます。追加授業には出入国管理局の別途許可が必要です。違反すると強制退去になる場合があります。",
    solutionZhCN: "E-2签证持有人只能在担保雇主处工作。任何额外授课需要向出入境管理局申请单独的工作授权。违规可能导致驱逐出境。",
    solutionZhTW: "E-2簽證持有人只能在擔保雇主處工作。任何額外授課需要向出入境管理局申請單獨的工作授權。違規可能導致驅逐出境。",
    solutionPt: "Detentores do E-2 só podem trabalhar no empregador patrocinador. Qualquer ensino adicional requer uma autorização de trabalho separada da imigração. A violação pode resultar em deportação.",
    solutionEs: "Los titulares de E-2 solo pueden trabajar en su empleador patrocinador. Cualquier enseñanza adicional requiere una autorización de trabajo separada de inmigración. La violación puede resultar en deportación.",
  },
  {
    visa: "D-2/D-4",
    issueEn: "Overstaying during school breaks",
    issueKo: "방학 중 체류 기간 초과",
    issueJa: "学校の休暇中のオーバーステイ",
    issueZhCN: "学校假期期间超期居留",
    issueZhTW: "學校假期期間超期居留",
    issuePt: "Ultrapassar o prazo durante as férias escolares",
    issueEs: "Exceder el tiempo permitido durante las vacaciones escolares",
    solutionEn: "Your visa must be valid even during breaks. Check your visa expiry date — not just your school calendar. Apply for extension at least 2 weeks before expiry.",
    solutionKo: "방학 중에도 비자 유효 기간이 적용됩니다. 학교 일정이 아닌 비자 만료일을 확인하세요. 만료 최소 2주 전에 연장 신청하세요.",
    solutionJa: "休暇中もビザは有効でなければなりません。学校のカレンダーではなくビザの有効期限を確認してください。期限の少なくとも2週間前に更新申請をしてください。",
    solutionZhCN: "即使在假期期间，签证也必须有效。请检查签证到期日，而非学校日历。请在到期前至少2周申请延期。",
    solutionZhTW: "即使在假期期間，簽證也必須有效。請檢查簽證到期日，而非學校日曆。請在到期前至少2週申請延期。",
    solutionPt: "Seu visto deve ser válido mesmo durante as férias. Verifique a data de validade do visto — não apenas o calendário escolar. Solicite a extensão pelo menos 2 semanas antes do vencimento.",
    solutionEs: "Tu visa debe ser válida incluso durante las vacaciones. Verifica la fecha de vencimiento de tu visa, no solo el calendario escolar. Solicita la extensión al menos 2 semanas antes del vencimiento.",
  },
  {
    visa: "All",
    issueEn: "Changing employers/schools without updating ARC",
    issueKo: "직장/학교 변경 후 ARC 미갱신",
    issueJa: "雇用主・学校変更後にARCを更新しない",
    issueZhCN: "更换雇主/学校后未更新外国人登录证",
    issueZhTW: "更換雇主/學校後未更新外國人登錄證",
    issuePt: "Mudar de empregador/escola sem atualizar o ARC",
    issueEs: "Cambiar de empleador/escuela sin actualizar el ARC",
    solutionEn: "You must notify immigration within 15 days of changing employers. Failure to report is technically a violation. Visit your local immigration office or use Hi Korea online.",
    solutionKo: "직장 변경 후 15일 이내에 출입국에 신고해야 합니다. 미신고는 위반 사항입니다. 출입국 사무소 방문 또는 하이코리아 온라인으로 신고하세요.",
    solutionJa: "雇用主変更後15日以内に出入国管理局に届け出る必要があります。未届出は技術的に違反です。最寄りの出入国管理局を訪問するかHi Koreaオンラインを利用してください。",
    solutionZhCN: "更换雇主后必须在15天内通知出入境管理局。未上报在技术上属于违规。请前往当地出入境管理局或使用Hi Korea在线报告。",
    solutionZhTW: "更換雇主後必須在15天內通知出入境管理局。未上報在技術上屬於違規。請前往當地出入境管理局或使用Hi Korea在線報告。",
    solutionPt: "Você deve notificar a imigração dentro de 15 dias após mudar de empregador. Deixar de reportar é tecnicamente uma violação. Visite seu escritório de imigração local ou use o Hi Korea online.",
    solutionEs: "Debes notificar a inmigración dentro de los 15 días posteriores al cambio de empleador. No reportarlo es técnicamente una infracción. Visita tu oficina de inmigración local o usa Hi Korea en línea.",
  },
  {
    visa: "C-3",
    issueEn: "Working on a tourist visa",
    issueKo: "관광 비자로 취업",
    issueJa: "観光ビザでの就労",
    issueZhCN: "持旅游签证工作",
    issueZhTW: "持旅遊簽證工作",
    issuePt: "Trabalhar com visto de turista",
    issueEs: "Trabajar con visa de turista",
    solutionEn: "Any paid work on a C-3 visa is illegal. This includes English tutoring, content creation for Korean companies, and remote work paid by Korean entities. The consequences can be severe.",
    solutionKo: "C-3 비자로의 어떤 유급 활동도 불법입니다. 영어 개인 교습, 한국 회사 콘텐츠 제작, 한국 회사 대상 재택근무 포함. 적발 시 심각한 결과.",
    solutionJa: "C-3ビザでのいかなる有給労働も違法です。英語個人指導、韓国企業向けコンテンツ制作、韓国企業が支払うリモートワークを含みます。結果は深刻になり得ます。",
    solutionZhCN: "持C-3签证从事任何有偿工作均属违法，包括英语家教、为韩国公司创作内容以及韩国公司支付报酬的远程工作。后果可能十分严重。",
    solutionZhTW: "持C-3簽證從事任何有償工作均屬違法，包括英語家教、為韓國公司創作內容以及韓國公司支付報酬的遠程工作。後果可能十分嚴重。",
    solutionPt: "Qualquer trabalho remunerado com visto C-3 é ilegal. Isso inclui tutoria de inglês, criação de conteúdo para empresas coreanas e trabalho remoto pago por entidades coreanas. As consequências podem ser graves.",
    solutionEs: "Cualquier trabajo remunerado con visa C-3 es ilegal. Esto incluye tutorías de inglés, creación de contenido para empresas coreanas y trabajo remoto pagado por entidades coreanas. Las consecuencias pueden ser severas.",
  },
  {
    visa: "E-6-1",
    issueEn: "Agency not registered as 대중문화예술기획업",
    issueKo: "에이전시가 대중문화예술기획업으로 미등록",
    issueJa: "エージェンシーが대중문화예술기획업として未登録",
    issueZhCN: "经纪公司未登记为대중문화예술기획업",
    issueZhTW: "經紀公司未登記為대중문화예술기획업",
    issuePt: "Agência não registrada como 대중문화예술기획업",
    issueEs: "Agencia no registrada como 대중문화예술기획업",
    solutionEn: "Since 2024, immigration officers verify that your sponsoring agency holds an active 대중문화예술기획업 (mass culture arts planning business) license with entertainment-only scope. If the agency lacks this registration, your E-6-1 application will be rejected regardless of your experience. Always confirm the license before signing a contract.",
    solutionKo: "2024년부터 출입국 심사관은 초청 에이전시가 오락 전용 범위로 활성화된 대중문화예술기획업 등록을 보유하고 있는지 확인합니다. 등록이 없으면 경력과 무관하게 E-6-1 신청이 거부됩니다. 계약 전 반드시 등록 여부를 확인하세요.",
    solutionJa: "2024年以降、出入国管理官は招聘エージェンシーがエンターテインメント専用範囲で有効な대중문화예술기획업登録を持っているか確認します。登録がなければ経験に関わらずE-6-1申請は却下されます。契約前に必ず確認してください。",
    solutionZhCN: "自2024年起，出入境官员会核实您的担保经纪公司是否持有以娱乐为唯一范围的有效대중문화예술기획업登记。若无此登记，无论您的经验如何，E-6-1申请都将被拒绝。签合同前务必确认登记状态。",
    solutionZhTW: "自2024年起，出入境官員會核實您的擔保經紀公司是否持有以娛樂為唯一範圍的有效대중문화예술기획업登記。若無此登記，無論您的經驗如何，E-6-1申請都將被拒絕。簽合約前務必確認登記狀態。",
    solutionPt: "Desde 2024, os agentes de imigração verificam se a agência patrocinadora possui uma licença ativa de 대중문화예술기획업 (empresa de planejamento de artes da cultura de massa) com escopo exclusivo de entretenimento. Se a agência não tiver esse registro, sua solicitação E-6-1 será rejeitada independentemente de sua experiência. Sempre confirme a licença antes de assinar um contrato.",
    solutionEs: "Desde 2024, los agentes de inmigración verifican que tu agencia patrocinadora tenga una licencia activa de 대중문화예술기획업 (empresa de planificación de artes de cultura de masas) con alcance exclusivo de entretenimiento. Si la agencia carece de este registro, tu solicitud E-6-1 será rechazada independientemente de tu experiencia. Siempre confirma la licencia antes de firmar un contrato.",
  },
  {
    visa: "F-1-D",
    issueEn: "Doing any work for Korean clients on the Digital Nomad visa",
    issueKo: "디지털노마드 비자로 한국 고객사 업무 수행",
    issueJa: "デジタルノマドビザで韓国クライアントへの業務",
    issueZhCN: "持数字游民签证为韩国客户工作",
    issueZhTW: "持數位遊牧簽證為韓國客戶工作",
    issuePt: "Fazer qualquer trabalho para clientes coreanos com a visa Digital Nomad",
    issueEs: "Hacer cualquier trabajo para clientes coreanos con la visa Nómada Digital",
    solutionEn: "The F-1-D visa is strictly for income earned from a non-Korean employer. Doing paid or even unpaid consulting, freelance work, or services for any Korean individual or company violates the visa conditions and can result in deportation and a multi-year entry ban. This includes informal arrangements and online gig work delivered to Korean clients.",
    solutionKo: "F-1-D 비자는 한국 외 고용주로부터의 소득에 대해서만 허용됩니다. 한국 개인 또는 기업에 대한 유무급 컨설팅, 프리랜서 업무, 서비스 제공은 비자 조건을 위반하며 강제출국 및 수년간 입국 금지로 이어질 수 있습니다. 한국 고객을 대상으로 한 비공식 업무 및 온라인 긱 업무도 포함됩니다.",
    solutionJa: "F-1-Dビザは韓国以外の雇用主からの収入にのみ適用されます。韓国の個人や企業への有給または無給のコンサルティング、フリーランス業務、サービス提供はビザ条件に違反し、強制退去と数年間の入国禁止につながる可能性があります。韓国クライアントへの非公式な業務やオンラインギグワークも含まれます。",
    solutionZhCN: "F-1-D签证仅允许从非韩国雇主处获取收入。向任何韩国个人或公司提供有偿甚至无偿的咨询、自由职业工作或服务均违反签证条件，可能导致驱逐出境及数年入境禁令。这包括非正式安排和面向韩国客户的线上零工工作。",
    solutionZhTW: "F-1-D簽證僅允許從非韓國雇主處獲取收入。向任何韓國個人或公司提供有償甚至無償的諮詢、自由職業工作或服務均違反簽證條件，可能導致驅逐出境及數年入境禁令。這包括非正式安排和面向韓國客戶的線上零工工作。",
    solutionPt: "O visto F-1-D é estritamente para renda obtida de um empregador não coreano. Fazer consultoria, trabalho freelance ou serviços pagos ou até não remunerados para qualquer indivíduo ou empresa coreana viola as condições do visto e pode resultar em deportação e proibição de entrada por vários anos. Isso inclui arranjos informais e trabalho gig online entregue a clientes coreanos.",
    solutionEs: "La visa F-1-D es estrictamente para ingresos obtenidos de un empleador no coreano. Hacer consultoría, trabajo freelance o servicios pagados o incluso no remunerados para cualquier individuo o empresa coreana viola las condiciones de la visa y puede resultar en deportación y prohibición de entrada por varios años. Esto incluye arreglos informales y trabajo gig en línea entregado a clientes coreanos.",
  },
  {
    visa: "E-9",
    issueEn: "Leaving an EPS employer without Ministry approval",
    issueKo: "고용노동부 승인 없이 EPS 고용주 이탈",
    issueJa: "雇用労働省承認なしでEPS雇用主を離職",
    issueZhCN: "未经雇佣劳动部批准擅自离开EPS雇主",
    issueZhTW: "未經雇傭勞動部批准擅自離開EPS雇主",
    issuePt: "Deixar um empregador EPS sem aprovação do Ministério",
    issueEs: "Dejar un empleador EPS sin aprobación del Ministerio",
    solutionEn: "E-9 holders are tied to their registered employer. Leaving without Ministry of Employment and Labor approval is treated as an unauthorized absence and can immediately invalidate your visa status. If you are experiencing mistreatment or unsafe conditions, contact the EPS center (1350) before leaving — there is a formal process to change employers in documented hardship cases.",
    solutionKo: "E-9 소지자는 등록된 고용주에 구속됩니다. 고용노동부 승인 없이 이탈하면 무단 이탈로 처리되어 비자 지위가 즉시 상실될 수 있습니다. 부당 대우나 안전 위험을 겪고 있다면 이탈 전 EPS 센터(1350)에 연락하세요. 공식 절차를 통해 어려운 경우 고용주 변경이 가능합니다.",
    solutionJa: "E-9保持者は登録雇用主に拘束されます。雇用労働省の承認なしに離職すると無断離職として扱われ、ビザ身分が即時無効になる可能性があります。不当待遇や安全上の危険がある場合は、離職前にEPSセンター（1350）に連絡してください。文書化された困難な場合には正式な雇用主変更手続きがあります。",
    solutionZhCN: "E-9持有人与其登记雇主绑定。未经雇佣劳动部批准擅自离职将被视为擅自缺勤，可能立即使签证身份失效。如果遭受虐待或安全隐患，请在离职前联系EPS中心（1350），有正式程序可在有记录的困难情况下更换雇主。",
    solutionZhTW: "E-9持有人與其登記雇主綁定。未經雇傭勞動部批准擅自離職將被視為擅自缺勤，可能立即使簽證身份失效。如果遭受虐待或安全隱患，請在離職前聯繫EPS中心（1350），有正式程序可在有記錄的困難情況下更換雇主。",
    solutionPt: "Detentores de E-9 estão vinculados ao seu empregador registrado. Sair sem aprovação do Ministério do Emprego e Trabalho é tratado como ausência não autorizada e pode invalidar imediatamente seu status de visto. Se você está sofrendo maus-tratos ou condições inseguras, entre em contato com o centro EPS (1350) antes de sair — há um processo formal para mudar de empregador em casos de dificuldade documentada.",
    solutionEs: "Los titulares de E-9 están vinculados a su empleador registrado. Irse sin aprobación del Ministerio de Empleo y Trabajo se trata como ausencia no autorizada y puede invalidar inmediatamente tu estado de visa. Si estás experimentando maltrato o condiciones inseguras, contacta al centro EPS (1350) antes de irte — hay un proceso formal para cambiar de empleador en casos de dificultad documentada.",
  },
  {
    visa: "ARC",
    issueEn: "Not booking your ARC appointment on day 1 or 2 of arrival",
    issueKo: "도착 첫날 또는 둘째 날에 ARC 예약 안 하기",
    issueJa: "到着1〜2日目にARCの予約をしないこと",
    issueZhCN: "未在抵达第1或第2天预约ARC",
    issueZhTW: "未在抵達第1或第2天預約ARC",
    issuePt: "Não reservar seu agendamento do ARC no dia 1 ou 2 de chegada",
    issueEs: "No reservar tu cita del ARC el día 1 o 2 de llegada",
    solutionEn: "ARC appointments at busy offices fill up fast — sometimes 4-6 weeks out. Book the moment you arrive at hikorea.go.kr or call 1345. You must register within 90 days of entry. Bring two passport photos; there is a photo booth inside most immigration offices (cash only, around KRW 6,000-8,000). Mobile ARC (launched January 2025) is now accepted at banks and many government services, but you still need to complete the registration in person first.",
    solutionKo: "바쁜 출입국 사무소의 ARC 예약은 4-6주까지 밀릴 수 있습니다. 입국 즉시 hikorea.go.kr 또는 1345로 예약하세요. 입국 후 90일 이내에 등록해야 합니다. 여권 사진 2장을 지참하세요. 대부분의 출입국 사무소 내 포토 부스가 있습니다 (현금만 가능, 약 6,000-8,000원). 2025년 1월 출시된 모바일 ARC는 이제 은행 및 많은 행정 서비스에서 사용 가능하지만, 먼저 대면 등록이 필요합니다.",
    solutionJa: "混雑している出入国管理局のARC予約は4〜6週間先まで埋まることがあります。到着したらすぐにhikorea.go.krまたは1345で予約してください。入国後90日以内に登録が必要です。パスポート写真2枚を持参してください。ほとんどの出入国管理局内にフォトブースがあります（現金のみ、約6,000〜8,000ウォン）。2025年1月に開始したモバイルARCは銀行や多くの行政サービスで受け付けられますが、まず対面登録が必要です。",
    solutionZhCN: "繁忙的出入境事务所ARC预约可能排到4-6周后。入境后立即在hikorea.go.kr或致电1345预约。必须在入境后90天内完成登记。请携带两张护照照片；大多数出入境事务所内有自助拍照机（仅现金，约6,000-8,000韩元）。2025年1月推出的移动ARC现可在银行和许多政府服务中使用，但仍需先完成现场登记。",
    solutionZhTW: "繁忙的出入境事務所ARC預約可能排到4-6週後。入境後立即在hikorea.go.kr或致電1345預約。必須在入境後90天內完成登記。請攜帶兩張護照照片；大多數出入境事務所內有自助拍照機（僅現金，約6,000-8,000韓元）。2025年1月推出的行動ARC現可在銀行和許多政府服務中使用，但仍需先完成現場登記。",
    solutionPt: "As vagas para ARC em escritórios movimentados podem esgotar 4-6 semanas antes. Reserve no momento em que chegar em hikorea.go.kr ou ligue para 1345. Você deve se registrar dentro de 90 dias da entrada. Traga duas fotos de passaporte; há uma cabine de fotos na maioria dos escritórios de imigração (apenas dinheiro, cerca de KRW 6.000-8.000). O ARC Móvel (lançado em janeiro de 2025) agora é aceito em bancos e muitos serviços governamentais, mas você ainda precisa concluir o registro presencialmente primeiro.",
    solutionEs: "Las citas para el ARC en oficinas concurridas pueden llenarse 4-6 semanas antes. Reserva en el momento en que llegues en hikorea.go.kr o llama al 1345. Debes registrarte dentro de los 90 días de entrada. Trae dos fotos de pasaporte; hay una cabina de fotos dentro de la mayoría de las oficinas de inmigración (solo efectivo, alrededor de KRW 6.000-8.000). El ARC Móvil (lanzado en enero de 2025) ahora es aceptado en bancos y muchos servicios gubernamentales, pero primero debes completar el registro en persona.",
  },
  {
    visa: "F-1-D",
    issueEn: "Assuming the income threshold stays fixed — it changes every year with Korea's GNI",
    issueKo: "소득 기준이 고정된 것으로 착각 — 매년 한국 GNI에 연동하여 변경",
    issueJa: "所得基準が固定と思い込む — 毎年韓国GNIに連動して変化",
    issueZhCN: "误以为收入门槛固定不变 — 每年随韩国GNI调整",
    issueZhTW: "誤以為收入門檻固定不變 — 每年隨韓國GNI調整",
    issuePt: "Assumir que o limite de renda é fixo — ele muda todo ano com o GNI da Coreia",
    issueEs: "Asumir que el umbral de ingresos es fijo — cambia cada año con el GNI de Corea",
    solutionEn: "The F-1-D income requirement is set at approximately twice Korea's per-capita GNI, which is recalculated every year. The threshold for 2025 is around KRW 88M, but verify the current figure before applying. Spousal or household income cannot be combined to meet the threshold — only your own individual income counts. All supporting documents (payslips, bank statements, employment contract) must be dated within 3 months of your application.",
    solutionKo: "F-1-D 소득 요건은 한국 1인당 GNI의 약 2배로, 매년 재산정됩니다. 2025년 기준은 약 8,800만 원이지만, 신청 전 현재 기준을 반드시 확인하세요. 배우자 또는 가구 소득은 합산 불가 — 본인 개인 소득만 인정됩니다. 모든 증빙 서류 (급여 명세서, 잔고증명서, 근로계약서)는 신청일 기준 3개월 이내 서류여야 합니다.",
    solutionJa: "F-1-D所得要件は韓国の一人当たりGNIの約2倍に設定されており、毎年再計算されます。2025年の基準は約8,800万ウォンですが、申請前に最新の数値を必ず確認してください。配偶者や世帯収入は合算不可 — 個人の収入のみが認められます。全ての証明書類（給与明細、残高証明、雇用契約書）は申請日から3ヶ月以内のものが必要です。",
    solutionZhCN: "F-1-D收入要求约为韩国人均GNI的两倍，每年重新计算。2025年门槛约为8,800万韩元，但申请前请务必确认当前数值。配偶或家庭收入不能合并计算 — 仅您个人收入有效。所有证明文件（工资单、银行对账单、劳动合同）必须在申请日期3个月内出具。",
    solutionZhTW: "F-1-D收入要求約為韓國人均GNI的兩倍，每年重新計算。2025年門檻約為8,800萬韓元，但申請前請務必確認當前數值。配偶或家庭收入不能合併計算 — 僅您個人收入有效。所有證明文件（工資單、銀行對帳單、勞動合約）必須在申請日期3個月內出具。",
    solutionPt: "O requisito de renda do F-1-D é definido em aproximadamente o dobro do GNI per capita da Coreia, recalculado anualmente. O limite para 2025 é de cerca de KRW 88M, mas verifique o valor atual antes de aplicar. A renda conjugal ou domiciliar não pode ser combinada para atingir o limite — apenas sua própria renda individual conta. Todos os documentos de suporte (contracheques, extratos bancários, contrato de trabalho) devem ter data dentro de 3 meses da sua solicitação.",
    solutionEs: "El requisito de ingresos de F-1-D se establece en aproximadamente el doble del GNI per cápita de Corea, que se recalcula cada año. El umbral para 2025 es de alrededor de KRW 88M, pero verifica la cifra actual antes de aplicar. Los ingresos del cónyuge o del hogar no pueden combinarse para cumplir el umbral — solo cuentan tus propios ingresos individuales. Todos los documentos de respaldo (recibos de sueldo, estados de cuenta bancarios, contrato de trabajo) deben tener fecha dentro de los 3 meses de tu solicitud.",
  },
  {
    visa: "F-6",
    issueEn: "Divorce affecting visa status",
    issueKo: "이혼이 비자 자격에 미치는 영향",
    issueJa: "離婚がビザ状況に与える影響",
    issueZhCN: "离婚对签证状态的影响",
    issueZhTW: "離婚對簽證狀態的影響",
    issuePt: "Divórcio afetando o status de visto",
    issueEs: "El divorcio que afecta el estado de la visa",
    solutionEn: "F-6 is tied to your Korean spouse. Divorce doesn't automatically end your visa, but you'll need to notify immigration and may need to transition to another visa type, especially if you have children.",
    solutionKo: "F-6는 한국인 배우자와 연결되어 있습니다. 이혼 시 즉시 비자가 취소되지는 않지만 출입국 신고가 필요하고, 특히 자녀가 있는 경우 다른 비자로 전환이 필요할 수 있습니다.",
    solutionJa: "F-6は韓国人配偶者に紐づいています。離婚しても自動的にビザが失効するわけではありませんが、出入国管理局への届け出が必要で、特に子供がいる場合は別のビザへの切り替えが必要になる場合があります。",
    solutionZhCN: "F-6与您的韩国配偶绑定。离婚不会自动使签证失效，但您需要通知出入境管理局，特别是有子女的情况下，可能需要转为其他签证类型。",
    solutionZhTW: "F-6與您的韓國配偶綁定。離婚不會自動使簽證失效，但您需要通知出入境管理局，特別是有子女的情況下，可能需要轉為其他簽證類型。",
    solutionPt: "F-6 está vinculado ao seu cônjuge coreano. O divórcio não encerra automaticamente seu visto, mas você precisará notificar a imigração e pode precisar fazer a transição para outro tipo de visto, especialmente se tiver filhos.",
    solutionEs: "F-6 está vinculada a tu cónyuge coreano. El divorcio no termina automáticamente tu visa, pero deberás notificar a inmigración y puede que necesites transicionar a otro tipo de visa, especialmente si tienes hijos.",
  },
];

export const IMMIGRATION_OFFICES = [
  { name: "Seoul Immigration Office", nameKo: "서울출입국·외국인청", address: "18 Yangjaecheon-ro, Seocho-gu, Seoul", addressKo: "서울 서초구 양재천로 18", station: "Yangjae (3, Bundang)", phone: "1345" },
  { name: "Seoul Foreign Population Office (Mapo)", nameKo: "마포출장소", address: "27 Eoulmadag-ro, Mapo-gu, Seoul", addressKo: "서울 마포구 어울마당로 27", station: "Hongik University Station", phone: "02-6309-8999" },
  { name: "Seoul Foreign Population Office (Nowon)", nameKo: "노원출장소", address: "8 Harang-ro, Nowon-gu, Seoul", addressKo: "서울 노원구 하랑로 8", station: "Suraksan (7)", phone: "02-6309-8988" },
  { name: "Incheon Immigration Office", nameKo: "인천출입국·외국인청", address: "8 Jajeong-ro, Namdong-gu, Incheon", addressKo: "인천 남동구 자정로 8", station: "Seo-Incheon (1)", phone: "032-890-6100" },
];
