export const VISA_TYPES = [
  {
    code: "D-2",
    nameEn: "Student Visa",
    nameKo: "학생비자",
    purposeEn: "Enrolled in a Korean university or language institute",
    purposeKo: "국내 대학교 또는 어학원 재학",
    durationEn: "Duration of study program, typically 1-2 years",
    durationKo: "수학 기간 (보통 1-2년)",
    canWork: true,
    workNoteEn: "Part-time work allowed (up to 20 hrs/week with permission)",
    workNoteKo: "허가 시 주 20시간 이내 아르바이트 가능",
    requirementsEn: ["University acceptance letter", "Proof of tuition payment", "Bank statement (min $10,000)", "Passport photos"],
    requirementsKo: ["대학 입학허가서", "등록금 납부 증명", "잔고증명서 (최소 1000만원)", "여권 사진"],
    category: "study",
  },
  {
    code: "D-4",
    nameEn: "General Training Visa",
    nameKo: "일반연수비자",
    purposeEn: "Korean language studies, short-term training programs",
    purposeKo: "한국어 연수, 단기 교육 프로그램",
    durationEn: "Up to 1 year, extendable",
    durationKo: "최대 1년, 연장 가능",
    canWork: false,
    workNoteEn: "Work not permitted without additional permission",
    workNoteKo: "별도 허가 없이 취업 불가",
    requirementsEn: ["Enrollment letter from language school", "Financial proof", "Passport"],
    requirementsKo: ["어학원 등록 확인서", "재정 증명", "여권"],
    category: "study",
  },
  {
    code: "E-1",
    nameEn: "Professor Visa",
    nameKo: "교수비자",
    purposeEn: "Professors and lecturers at Korean universities",
    purposeKo: "국내 대학교 교수 및 강사",
    durationEn: "1-2 years, renewable",
    durationKo: "1-2년, 갱신 가능",
    canWork: true,
    workNoteEn: "Work permitted at sponsoring institution",
    workNoteKo: "초청 기관에서 취업 가능",
    requirementsEn: ["Employment contract", "PhD certificate", "University sponsor letter"],
    requirementsKo: ["고용 계약서", "박사학위증", "대학 초청장"],
    category: "work",
  },
  {
    code: "E-2",
    nameEn: "English Teacher Visa",
    nameKo: "원어민 영어교사 비자",
    purposeEn: "Native English speakers teaching at schools, hagwons, or universities",
    purposeKo: "학교, 학원, 대학교 원어민 영어교사",
    durationEn: "1 year (contract-based), renewable",
    durationKo: "1년 (계약 기준), 갱신 가능",
    canWork: true,
    workNoteEn: "Work permitted at sponsoring employer only",
    workNoteKo: "초청 고용주 기관에서만 취업 가능",
    requirementsEn: ["Bachelor's degree (any field)", "Criminal background check (apostilled)", "Health certificate", "Employer sponsorship"],
    requirementsKo: ["학사학위 (전공 무관)", "범죄 경력 확인서 (아포스티유)", "건강진단서", "고용주 스폰서십"],
    category: "work",
  },
  {
    code: "E-6",
    nameEn: "Arts & Entertainment Visa",
    nameKo: "예술흥행비자",
    purposeEn: "Performing artists, entertainers working in Korea",
    purposeKo: "공연 예술가, 연예인",
    durationEn: "Up to 1 year, renewable",
    durationKo: "최대 1년, 갱신 가능",
    canWork: true,
    workNoteEn: "Work permitted in the arts/entertainment sector",
    workNoteKo: "예술/공연 분야 취업 가능",
    requirementsEn: ["Employment contract", "Portfolio or performance credentials"],
    requirementsKo: ["고용 계약서", "포트폴리오 또는 실적"],
    category: "work",
  },
  {
    code: "E-7",
    nameEn: "Specialized Work Visa",
    nameKo: "특정활동비자",
    purposeEn: "Skilled professionals in designated fields (IT, engineering, design, etc.)",
    purposeKo: "IT, 엔지니어링, 디자인 등 전문직",
    durationEn: "1-3 years, renewable",
    durationKo: "1-3년, 갱신 가능",
    canWork: true,
    workNoteEn: "Work permitted in the specific designated occupation",
    workNoteKo: "지정된 직종에서 취업 가능",
    requirementsEn: ["Job offer from Korean employer", "Relevant degree + experience", "Employer sponsorship"],
    requirementsKo: ["한국 고용주 채용 확정", "관련 학위 + 경력", "고용주 스폰서십"],
    category: "work",
  },
  {
    code: "F-2",
    nameEn: "Resident Visa",
    nameKo: "거주비자",
    purposeEn: "Long-term residents: spouse of Korean citizen, points-based, skilled immigrants",
    purposeKo: "한국인 배우자, 점수제, 숙련 이민자",
    durationEn: "1-3 years, renewable toward F-5",
    durationKo: "1-3년, F-5 영주권으로 갱신 가능",
    canWork: true,
    workNoteEn: "Most employment restrictions removed",
    workNoteKo: "대부분의 취업 제한 해제",
    requirementsEn: ["Marriage certificate (for F-2-1)", "TOPIK score or points system", "Income verification"],
    requirementsKo: ["혼인관계증명서 (F-2-1의 경우)", "TOPIK 점수 또는 점수제", "소득 증명"],
    category: "resident",
  },
  {
    code: "F-4",
    nameEn: "Overseas Korean Visa",
    nameKo: "재외동포비자",
    purposeEn: "Ethnic Koreans with foreign nationality (gyopo)",
    purposeKo: "외국 국적 재외동포 (교포)",
    durationEn: "2 years, renewable indefinitely",
    durationKo: "2년, 무기한 갱신 가능",
    canWork: true,
    workNoteEn: "Work permitted in most sectors (some restrictions apply)",
    workNoteKo: "대부분의 분야 취업 가능 (일부 제한 있음)",
    requirementsEn: ["Proof of Korean ancestry", "Foreign passport", "Family registry documents"],
    requirementsKo: ["한국 혈통 증명", "외국 여권", "가족관계증명서"],
    category: "resident",
  },
  {
    code: "F-6",
    nameEn: "Marriage Visa",
    nameKo: "결혼이민비자",
    purposeEn: "Spouse of a Korean national",
    purposeKo: "한국 국민의 배우자",
    durationEn: "1 year (initial), then 2 years, then F-2 path",
    durationKo: "최초 1년, 이후 2년, F-2 취득 경로",
    canWork: true,
    workNoteEn: "Work permitted without employer sponsorship",
    workNoteKo: "고용주 스폰서십 없이 취업 가능",
    requirementsEn: ["Marriage certificate", "Korean spouse's ID and family registration", "Proof of meeting in person"],
    requirementsKo: ["혼인관계증명서", "한국인 배우자 신분증 및 가족관계증명서", "대면 만남 증명"],
    category: "resident",
  },
  {
    code: "C-3",
    nameEn: "Short-term Visitor (Tourist)",
    nameKo: "단기방문비자",
    purposeEn: "Tourism, visiting family, short business trips. Many nationalities get 90 days visa-free.",
    purposeKo: "관광, 가족 방문, 단기 출장. 많은 국적자 90일 무비자 입국 가능.",
    durationEn: "Up to 90 days (visa-free for many nationalities)",
    durationKo: "최대 90일 (많은 국적 무비자)",
    canWork: false,
    workNoteEn: "Work strictly prohibited",
    workNoteKo: "취업 엄격히 금지",
    requirementsEn: ["Valid passport", "Return ticket", "Proof of accommodation"],
    requirementsKo: ["유효한 여권", "귀국 항공권", "숙소 증명"],
    category: "tourist",
  },
];

export const VISA_WIZARD_STEPS = [
  {
    id: "purpose",
    questionEn: "Why are you coming to Korea?",
    questionKo: "한국 방문 목적이 무엇인가요?",
    options: [
      { id: "study", labelEn: "Study / Language school", labelKo: "학업 / 어학 연수", emoji: "📚" },
      { id: "teach", labelEn: "Teaching English", labelKo: "영어 강사", emoji: "🍎" },
      { id: "work", labelEn: "Work (skilled professional)", labelKo: "취업 (전문직)", emoji: "💼" },
      { id: "family", labelEn: "Family / Marriage", labelKo: "가족 / 결혼", emoji: "❤️" },
      { id: "gyopo", labelEn: "I have Korean heritage", labelKo: "재외동포", emoji: "🇰🇷" },
      { id: "tourist", labelEn: "Tourism / Short visit", labelKo: "관광 / 단기 방문", emoji: "✈️" },
    ],
  },
  {
    id: "duration",
    questionEn: "How long do you plan to stay?",
    questionKo: "얼마나 체류할 예정인가요?",
    options: [
      { id: "short", labelEn: "Under 3 months", labelKo: "3개월 미만", emoji: "📅" },
      { id: "medium", labelEn: "3 months to 1 year", labelKo: "3개월~1년", emoji: "🗓️" },
      { id: "long", labelEn: "1-3 years", labelKo: "1~3년", emoji: "📆" },
      { id: "permanent", labelEn: "Long-term / permanent", labelKo: "장기 / 영구 거주", emoji: "🏡" },
    ],
  },
];

// Purpose + duration → visa recommendation
export const VISA_RECOMMENDATIONS: Record<string, { code: string; noteEn: string; noteKo: string }[]> = {
  "study-short": [{ code: "D-4", noteEn: "Language school visa for short-term Korean study", noteKo: "단기 한국어 연수용 비자" }],
  "study-medium": [{ code: "D-4", noteEn: "Language school visa", noteKo: "어학원 비자" }, { code: "D-2", noteEn: "If enrolled in a degree program", noteKo: "학위 과정 재학 시" }],
  "study-long": [{ code: "D-2", noteEn: "University student visa for degree programs", noteKo: "대학교 학위 과정 비자" }],
  "study-permanent": [{ code: "D-2", noteEn: "Start with student visa, build toward F-2", noteKo: "학생 비자로 시작해 F-2로 전환" }],
  "teach-medium": [{ code: "E-2", noteEn: "English teacher visa — most common for native speakers", noteKo: "원어민 영어교사 비자" }],
  "teach-long": [{ code: "E-2", noteEn: "English teacher visa, renewable annually", noteKo: "원어민 영어교사 비자, 매년 갱신" }],
  "teach-short": [{ code: "E-2", noteEn: "E-2 requires employer sponsorship, minimum ~1 year contracts", noteKo: "E-2는 고용주 스폰서십 필요, 최소 1년 계약" }],
  "teach-permanent": [{ code: "E-2", noteEn: "E-2 is renewed annually — build toward F-2 after 5+ years", noteKo: "E-2는 매년 갱신 — 5년 이상 후 F-2 취득 가능" }],
  "work-medium": [{ code: "E-7", noteEn: "Specialized work visa for skilled professionals", noteKo: "전문직 특정활동비자" }],
  "work-long": [{ code: "E-7", noteEn: "Specialized work visa, path to F-2 long-term", noteKo: "E-7 후 F-2 거주비자 취득 가능" }],
  "work-permanent": [{ code: "E-7", noteEn: "Work visa → F-2 (resident) → F-5 (permanent)", noteKo: "E-7 → F-2 (거주) → F-5 (영주권)" }],
  "work-short": [{ code: "E-7", noteEn: "Most work visas require at least 1-year contracts", noteKo: "대부분의 취업 비자는 최소 1년 계약 필요" }],
  "family-medium": [{ code: "F-6", noteEn: "Marriage visa for spouses of Korean nationals", noteKo: "한국인 배우자 결혼이민비자" }],
  "family-long": [{ code: "F-6", noteEn: "Marriage visa, leads to F-2 and eventually F-5", noteKo: "결혼이민비자, F-2 → F-5 경로" }],
  "family-permanent": [{ code: "F-6", noteEn: "Marriage visa path: F-6 → F-2 → F-5 permanent", noteKo: "F-6 → F-2 → F-5 영주권" }],
  "family-short": [{ code: "C-3", noteEn: "Short visit to see family — tourist visa or visa-free entry", noteKo: "가족 방문 — 관광 비자 또는 무비자 입국" }],
  "gyopo-medium": [{ code: "F-4", noteEn: "Overseas Korean visa — minimal restrictions, renewable every 2 years", noteKo: "재외동포비자 — 제한 적고 2년마다 갱신" }],
  "gyopo-long": [{ code: "F-4", noteEn: "F-4 is renewable indefinitely and gives most work rights", noteKo: "F-4는 무기한 갱신 가능, 취업 권리 폭넓음" }],
  "gyopo-permanent": [{ code: "F-4", noteEn: "F-4 → F-5 (permanent residency) after 2 years", noteKo: "F-4 → F-5 영주권 취득 가능" }],
  "gyopo-short": [{ code: "F-4", noteEn: "Even for short stays, F-4 gives you more flexibility than a tourist visa", noteKo: "단기 체류라도 F-4는 관광비자보다 유연함" }],
  "tourist-short": [{ code: "C-3", noteEn: "Many nationalities get 90 days visa-free. Check your country.", noteKo: "많은 국적자 90일 무비자. 국가 확인 필요." }],
  "tourist-medium": [{ code: "C-3", noteEn: "Tourist visa cannot be extended beyond 90 days. You'll need a different visa for longer stays.", noteKo: "관광 비자는 90일 초과 연장 불가. 장기 체류는 다른 비자 필요." }],
  "tourist-long": [{ code: "C-3", noteEn: "A tourist visa won't work for 1+ year stays. Consider switching to a long-term visa type.", noteKo: "1년 이상 체류는 관광비자로 불가. 장기 체류 비자 전환 필요." }],
  "tourist-permanent": [{ code: "C-3", noteEn: "Permanent residence is not possible on a tourist visa. Explore F-2 or F-5 options.", noteKo: "관광비자로 영구 거주 불가. F-2 또는 F-5 비자를 알아보세요." }],
};

export const ARC_STEPS = [
  {
    step: 1,
    titleEn: "Within 90 days of arrival",
    titleKo: "입국 후 90일 이내",
    descEn: "You must register for an ARC (Alien Registration Card) within 90 days of arriving in Korea on a long-stay visa. Failing to register is a violation and can result in fines.",
    descKo: "장기 체류 비자로 입국한 경우 90일 이내에 외국인등록증(ARC)을 신청해야 합니다. 미등록 시 과태료 부과 대상입니다.",
  },
  {
    step: 2,
    titleEn: "Make an appointment",
    titleKo: "예약하기",
    descEn: "Book an appointment at the Hi Korea website (hikorea.go.kr) or call 1345 for the nearest immigration office. Walk-ins are possible but wait times can be 2-4 hours.",
    descKo: "하이코리아 (hikorea.go.kr) 에서 예약하거나 1345로 전화해 가까운 출입국 사무소 예약을 하세요. 현장 접수도 가능하지만 대기 2-4시간 예상.",
  },
  {
    step: 3,
    titleEn: "Documents to bring",
    titleKo: "준비 서류",
    descEn: "Passport + visa, 2 passport photos (3.5cm x 4.5cm), completed application form, proof of address, fee (30,000 KRW), and any employer/school documents.",
    descKo: "여권+비자, 여권 사진 2매(3.5x4.5cm), 작성된 신청서, 주소 증명서류, 수수료 3만원, 직장/학교 서류 등.",
  },
  {
    step: 4,
    titleEn: "At the immigration office",
    titleKo: "출입국 사무소에서",
    descEn: "Take a number, wait, submit your documents, get fingerprinted. The officer will keep your passport temporarily and give you a receipt.",
    descKo: "번호표 뽑고 대기 후 서류 제출, 지문 등록. 담당자가 여권을 임시 보관하고 영수증을 줍니다.",
  },
  {
    step: 5,
    titleEn: "Processing time",
    titleKo: "처리 기간",
    descEn: "About 2-3 weeks. You'll receive a text when ready. You can track status on Hi Korea. Pick up in person at the same office.",
    descKo: "약 2-3주. 완료 시 문자 알림. 하이코리아에서 상태 확인 가능. 동일 사무소에서 직접 수령.",
  },
];

export const COMMON_PITFALLS = [
  {
    visa: "E-2",
    issueEn: "Working at a second school without permission",
    issueKo: "허가 없이 다른 학원에서 추가 강의",
    solutionEn: "E-2 holders can only work at their sponsoring employer. Any additional teaching requires a separate work authorization from immigration. Violation can result in deportation.",
    solutionKo: "E-2 비자 소지자는 초청 고용주에서만 일할 수 있습니다. 추가 강의 시 출입국 허가 필요. 위반 시 강제 출국 가능.",
  },
  {
    visa: "D-2/D-4",
    issueEn: "Overstaying during school breaks",
    issueKo: "방학 중 체류 기간 초과",
    solutionEn: "Your visa must be valid even during breaks. Check your visa expiry date — not just your school calendar. Apply for extension at least 2 weeks before expiry.",
    solutionKo: "방학 중에도 비자 유효 기간이 적용됩니다. 학교 일정이 아닌 비자 만료일을 확인하세요. 만료 최소 2주 전에 연장 신청하세요.",
  },
  {
    visa: "All",
    issueEn: "Changing employers/schools without updating ARC",
    issueKo: "직장/학교 변경 후 ARC 미갱신",
    solutionEn: "You must notify immigration within 15 days of changing employers. Failure to report is technically a violation. Visit your local immigration office or use Hi Korea online.",
    solutionKo: "직장 변경 후 15일 이내에 출입국에 신고해야 합니다. 미신고는 위반 사항입니다. 출입국 사무소 방문 또는 하이코리아 온라인으로 신고하세요.",
  },
  {
    visa: "C-3",
    issueEn: "Working on a tourist visa",
    issueKo: "관광 비자로 취업",
    solutionEn: "Any paid work on a C-3 visa is illegal. This includes English tutoring, content creation for Korean companies, and remote work paid by Korean entities. The consequences can be severe.",
    solutionKo: "C-3 비자로의 어떤 유급 활동도 불법입니다. 영어 개인 교습, 한국 회사 콘텐츠 제작, 한국 회사 대상 재택근무 포함. 적발 시 심각한 결과.",
  },
  {
    visa: "F-6",
    issueEn: "Divorce affecting visa status",
    issueKo: "이혼이 비자 자격에 미치는 영향",
    solutionEn: "F-6 is tied to your Korean spouse. Divorce doesn't automatically end your visa, but you'll need to notify immigration and may need to transition to another visa type, especially if you have children.",
    solutionKo: "F-6는 한국인 배우자와 연결되어 있습니다. 이혼 시 즉시 비자가 취소되지는 않지만 출입국 신고가 필요하고, 특히 자녀가 있는 경우 다른 비자로 전환이 필요할 수 있습니다.",
  },
];

export const IMMIGRATION_OFFICES = [
  { name: "Seoul Immigration Office", nameKo: "서울출입국·외국인청", address: "18 Yangjaecheon-ro, Seocho-gu, Seoul", addressKo: "서울 서초구 양재천로 18", station: "Yangjae (3, Bundang)", phone: "1345" },
  { name: "Seoul Foreign Population Office (Mapo)", nameKo: "마포출장소", address: "27 Eoulmadag-ro, Mapo-gu, Seoul", addressKo: "서울 마포구 어울마당로 27", station: "Hongik University Station", phone: "02-6309-8999" },
  { name: "Seoul Foreign Population Office (Nowon)", nameKo: "노원출장소", address: "8 Harang-ro, Nowon-gu, Seoul", addressKo: "서울 노원구 하랑로 8", station: "Suraksan (7)", phone: "02-6309-8988" },
  { name: "Incheon Immigration Office", nameKo: "인천출입국·외국인청", address: "8 Jajeong-ro, Namdong-gu, Incheon", addressKo: "인천 남동구 자정로 8", station: "Seo-Incheon (1)", phone: "032-890-6100" },
];
